<?php
$order = $this->getVariable('order');
$invoice = $this->getVariable('model');
$currency = $order->getCurrency();
?>
<div id="Product-details" class="tab-content font-12">
    <div class="search col-xs-12 col-sm-12">
        <form class="form-inline" action="" method="get" novalidate = "novalidate">
            <span class="fa fa-search" aria-hidden="true"></span>
            <input type="search" name="increment_id" value="" class="col-xs-10 col-sm-10" />
            <button type="submit" class="btn btn-default"><?php echo $this->translate('Search'); ?></button>
        </form>
    </div>
    <div class="tab-pane fade in active" id="all">
        <ul  class="col-xs-12 col-sm-12 title-nav name  padding-5">
            <li class="col-xs-5 col-sm-5 text-left font-14"><?php echo $order->getStore()->offsetGet('name') ?></li>
            <li class="col-xs-7 col-sm-7 text-right font-14">
                <?php echo $order->getCurrency()->format($order->offsetGet('total')) ?>
                <span><?php echo $this->translate('(Including Shipping Fee: %s)', [$order->getCurrency()->format($order->offsetGet('shipping'))]) ?></span>
            </li>	
        </ul>
        <table class="table inline bt padding-5">
            <?php
            foreach ($order->getItems() as $item):
                $product = $item['product'];
                $thumbnail = $product->getThumbnail();
                ?>
                <tr<?php if (isset($item['id'])): ?> data-id="<?php echo $item['id'] ?>"<?php endif ?>>
                    <td class="col-xs-2 col-sm-2">
                        <a href="<?php echo $product->getUrl() ?>">
                            <img src="<?php echo strpos($thumbnail, '//') === false ? $this->getResourceUrl('image/resized/100x/' . $thumbnail) : $thumbnail ?>" width="50" height="50" alt="<?php echo $product->offsetGet('name') ?>" />
                        </a>
                    </td>
                    <td class="col-xs-6 col-sm-6 text-left" title="<?php echo $product->offsetGet('name') ?>">
                        <h4 class="font-12"><a href="<?php echo $product->getUrl() ?>">
                                <?php echo $item['product_name'] ?>
                            </a></h4>
                        <?php
                        $options = json_decode($item['options'], true);
                        if ($item['product_id'] && count($options)):
                            ?>
                            <dl class="options">
                                <?php
                                foreach ($product->getOptions() as $option):
                                    if (isset($options[$option->getId()])):
                                        ?>
                                        <dt><?php echo $option['title'] ?></dt>
                                        <dd><?php echo in_array($option['input'], ['select', 'radio', 'checkbox', 'multiselect']) ? $option->getValue($options[$option->getId()]) : $options[$option->getId()] ?></dd><br />
                                        <?php
                                    endif;
                                endforeach;
                                ?>
                            </dl>
                        <?php endif ?>
                    </td>
                    <td class="col-xs-1 col-sm-1 text-right">
                        <span class="price"><?php echo $currency->format($item['price']) ?></span>
                        <span><?php echo (float) $item['qty'] ?></span>                        
                    </td>
                    <td rowspan="<?php echo count($items) ?>" class="col-xs-3 col-sm-3 border-left action text-center">
                        <span class="color-blue"><?php echo $this->translate($order->getStatus()->offsetGet('name'), [], 'sales') ?></span>
                    </td>
                </tr>
            <?php endforeach; ?>
        </table>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading">
            <h4 class="panel-title font-14"><?php echo $this->translate('Invoice Infomation', [], 'sales') ?></h4>
        </div>
        <div class="panel-body">
            <?php echo $this->translate('ID'), ': ', $invoice['increment_id'] ?><br />
            <?php echo $this->translate('Order ID'), ': ', $order['increment_id'] ?><br />
            <?php
            if ($store = $order->getStore()) {
                echo $this->translate('Store'), ': ', $store->offsetGet('name');
            }
            ?><br />
            <?php
            if ($language = $order->getLanguage()) {
                echo $this->translate('Language'), ': ', $language->offsetGet('name');
            }
            ?>
        </div>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading">
            <h4 class="panel-title font-14"><?php echo $this->translate('Payment Method', [], 'sales') ?></h4>
        </div>
        <div class="panel-body">
            <?php
            echo $this->translate($order->getPaymentMethod()->getLabel()), '<br />',
            $this->translate('Order was placed using %s', [$order->offsetGet('currency')], 'sales'), '<br />',
            $invoice['comment']
            ?>
        </div>
    </div>
</div>
