<?php
$order = $this->getVariable('order');
$invoice = $this->getVariable('model');
$currency = $order->getCurrency();
?>
<div class="clearfix">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h4 class="panel-title"><?php echo $this->translate('Invoice Information', [], 'sales') ?></h4>
        </div>
        <div class="panel-body">
            <?php echo $this->translate('ID'), ': ', $invoice['increment_id'] ?><br />
            <?php echo $this->translate('Order ID'), ': ', $order['increment_id'] ?><br />
            <?php
            if ($store = $order->getStore()) {
                echo $this->translate('Store'), ': ', $store->offsetGet('name');
            }
            ?><br />
            <?php
            if ($language = $order->getLanguage()) {
                echo $this->translate('Language'), ': ', $language->offsetGet('name');
            }
            ?>
        </div>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading">
            <h4 class="panel-title"><?php echo $this->translate('Payment Method', [], 'sales') ?></h4>
        </div>
        <div class="panel-body">
            <?php
            echo $this->translate($order->getPaymentMethod()->getLabel()), '<br />',
            $this->translate('Order was placed using %s', [$order->offsetGet('currency')], 'sales'), '<br />',
            $invoice['comment']
            ?>
        </div>
    </div>
    <div class="panel panel-default wide">
        <div class="panel-heading">
            <h4 class="panel-title"><?php echo $this->translate('Product(s)') ?></h4>
        </div>
        <div class="panel-body grid table-responsive">
            <table class="table table-hover table-striped table-no-border">
                <thead class="sort-by">
                    <tr>
                        <th colspan="2"><?php echo $this->translate('Product') ?></th>
                        <th><?php echo $this->translate('SKU', [], 'sales') ?></th>
                        <th><?php echo $this->translate('Price', [], 'sales') ?></th>
                        <th><?php echo $this->translate('Qty', [], 'sales') ?></th>
                        <th><?php echo $this->translate('Total', [], 'sales') ?></th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    foreach ($invoice->getItems() as $item):
                        $product = $item['product'];
                        $thumbnail = $product->getThumbnail();
                        ?>
                        <tr<?php if (isset($item['id'])): ?> data-id="<?php echo $item['id'] ?>"<?php endif ?>>
                            <td>
                                <a href="<?php echo $product->getUrl() ?>">
                                    <img src="<?php echo $thumbnail ? $this->getResourceUrl('image/resized/100x/' . $thumbnail) : $this->getPubUrl('images/placeholder.png') ?>" width="100" alt="<?php echo $item['product_name'] ?>" />
                                </a>
                            </td>
                            <td>
                                <a href="<?php echo $product->getUrl() ?>">
                                    <?php echo $item['product_name'] ?>
                                </a>
                                <?php
                                $options = json_decode($item['options'], true);
                                if ($item['product_id'] && count($options)):
                                    ?>
                                    <dl class="options">
                                        <?php
                                        foreach ($item['product']->getOptions() as $option):
                                            if (isset($options[$option->getId()])):
                                                ?>
                                                <dt><?php echo $option['title'] ?></dt>
                                                <dd><?php echo in_array($option['input'], ['select', 'radio', 'checkbox', 'multiselect']) ? $option->getValue($options[$option->getId()]) : $options[$option->getId()] ?></dd>
                                                <?php
                                            endif;
                                        endforeach;
                                        ?>
                                    </dl>
                                <?php endif ?>
                            </td>
                            <td><?php echo $item['sku'] ?></td>
                            <td><?php echo $currency->format($item['price']) ?></td>
                            <td><?php echo (float) $item['qty'] ?></td>
                            <td><?php echo $currency->format($item['total']) ?></td>
                        </tr>
                    <?php endforeach ?>
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="6">
                            <dl class="dl-horizontal pull-right">
                                <dt><?php echo $this->translate('Subtotal', [], 'sales') ?></dt>
                                <dd><?php echo $currency->format($invoice->offsetGet('subtotal')) ?></dd>
                                <dt><?php echo $this->translate('Shipping &amp; Handling', [], 'sales') ?></dt>
                                <dd><?php echo $currency->format($invoice->offsetGet('shipping')) ?></dd>
                                <?php if ((float) $invoice->offsetGet('tax')): ?>
                                    <dt><?php echo $this->translate('Tax', [], 'sales') ?></dt>
                                    <dd><?php echo $currency->format($invoice->offsetGet('tax')) ?></dd>
                                <?php endif ?>
                                <?php
                                if ((float) $invoice->offsetGet('discount')):
                                    $discount = json_decode($invoice->offsetGet('discount_detail'), true);
                                    foreach ($discount as $type => $price):
                                        ?>
                                        <dt><?php echo $this->translate('Discount(' . $type . ')', [], 'sales') ?></dt>
                                        <dd><?php echo $currency->convert($price, true) ?></dd>
                                        <?php
                                    endforeach;
                                endif;
                                ?>
                                <dt><?php echo $this->translate('Grand Total', [], 'sales') ?></dt>
                                <dd><?php echo $currency->format($invoice->offsetGet('total')) ?></dd>
                            </dl>
                        </td>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
</div>
