<?php
$root = $this->getRootCategory();
?>
<div class="slide-mask"></div>
<aside class="slide-wrapper">
    <div>
        <ul>
            <?php
            foreach ($root->getChildrenCategories(1) as $category):
                $children = $category->getChildrenCategories(1);
                $count = $children->count();
                ?>
            <li class="clearfix"><a href="<?php echo $category->getUrl() ?>"><?php echo $category['name'] ?></a>
                    <?php if ($count): ?>
                <dl>
                            <?php
                            foreach ($children as $child):
                                $grandChildren = $child->getChildrenCategories(1);
                                ?>
                                <dt><a href="<?php echo $child->getUrl() ?>"><?php echo $child['name'] ?></a></dt>
                                <?php if ($grandChildren->count()): ?>
                                    <dd>
                                        <ul>
                                            <?php foreach ($grandChildren as $grandChild): ?>
                                                <li><a href="<?php echo $grandChild->getUrl() ?>"><?php echo $grandChild['name'] ?></a></li>
                                            <?php endforeach; ?>
                                        </ul>
                                    </dd>
                                    <?php
                                endif;
                            endforeach;
                            ?>
                        </dl>
                    <?php endif; ?>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
</aside>