<?php ?>
<div class="condition">
    <span class="title"><?php echo $this->translate('If %s of these conditions are %s.', [
                    '<span class="param form-inline"><select class="form-control"><option value="and">' .
                    $this->translate('All', [], 'promotion') .
                    '</option><option value="or">' .
                    $this->translate('Any', [], 'promotion') .
                    '</option></select></span>', '<span class="param form-inline"><select class="form-control"><option value="1">' .
                    $this->translate('Eligible', [], 'promotion') .
                    '</option><option value="0">' .
                    $this->translate('Not Eligible', [], 'promotion') .
                    '</option></select></span>'], 'promotion') ?></span>
    <ul class="children" data-tmpl="#tmpl-condition-parent">
        <li class="last">
            <a href="javascript:void(0);" class="add">
                <span class="fa fa-plus-circle" aria-hidden="true"></span>
                <span class="sr-only"><?php echo $this->translate('Add') ?></span>
            </a>
        </li>
    </ul>
    <template id="tmpl-condition-children">
        <li>
            <span class="title"></span>
            <select class="form-control">
                <option value=""><?php echo $this->translate('Please Select') ?></option>
                <option value="conbination" data-title='<?php
                echo $this->translate('If %s of these conditions are %s.', [
                    '<span class="param form-inline"><select class="form-control"><option value="all">' .
                    $this->translate('All', [], 'promotion') .
                    '</option><option value="any"></option></select></span>', '<span class="param form-inline">' .
                    $this->translate('Any', [], 'promotion') .
                    '</span>'], 'promotion')
                ?>' data-tmpl="#tmpl-condition-parent"><?php echo $this->translate('Conbination', [], 'promotion') ?></option>
                <optgroup label="<?php echo $this->translate('Product') ?>">
                    <option value="product_id" data-type="select" data-source="Seahinet\Catalog\Source\Product">ID</option>
                    <option value="attribute_set" data-type="select" data-source="Seahinet\Catalog\Source\Set"><?php echo $this->translate('Attribute Set') ?></option>
                    <option value="category" data-type="select" data-source="Seahinet\Catalog\Source\Category"><?php echo $this->translate('Category') ?></option>
                    <option value="product_type" data-type="select" data-source="Seahinet\Catalog\Source\Type"><?php echo $this->translate('Product Type') ?></option>
                    <option value="price" data-type="numeric"><?php echo $this->translate('Price') ?></option>
                    <option value="qty" data-type="numeric"><?php echo $this->translate('Quentity') ?></option>
                    <option value="row_total" data-type="numeric"><?php echo $this->translate('Subtotal') ?></option>
                </optgroup>
            </select>
        </li>
    </template>
    <template id="tmpl-condition-parent">
        <li>
            <span class="title"></span>
            <select class="form-control">
                <option value=""><?php echo $this->translate('Please Select') ?></option>
                <option value="conbination" data-title='<?php echo $this->translate('If %s of these conditions are %s.', [
                    '<span class="param form-inline"><select class="form-control"><option value="and">' .
                    $this->translate('All', [], 'promotion') .
                    '</option><option value="or">' .
                    $this->translate('Any', [], 'promotion') .
                    '</option></select></span>', '<span class="param form-inline"><select class="form-control"><option value="1">' .
                    $this->translate('Eligible', [], 'promotion') .
                    '</option><option value="0">' .
                    $this->translate('Not Eligible', [], 'promotion') .
                    '</option></select></span>'], 'promotion') ?>' data-tmpl="#tmpl-condition-parent"><?php echo $this->translate('Conbination', [], 'promotion') ?></option>
                <option value="options_conbination" data-title='<?php echo $this->translate('If an item is %s in the cart with %s of these conditions true.', ['<span class="param form-inline"><select class="form-control"><option value="found">' .
                    $this->translate('Found', [], 'promotion') .
                    '</option><option value="notfound">' .
                    $this->translate('Not Found', [], 'promotion') .
                    '</option></select></span>', '<span class="param form-inline"><select class="form-control"><option value="and">' .
                    $this->translate('All', [], 'promotion') .
                    '</option><option value="or">' .
                    $this->translate('Any', [], 'promotion') .
                    '</option></select></span>'], 'promotion') ?>' data-tmpl="#tmpl-condition-children"><?php echo $this->translate('Product Options Conbination', [], 'promotion') ?></option>
                <optgroup label="<?php echo $this->translate('Customer') ?>">
                    <option value="customer_id" data-type="select" data-source="Seahinet\Customer\Source\Customer">ID</option>
                    <option value="group" data-type="select" data-source="Seahinet\Customer\Source\Group"><?php echo $this->translate('Customer Group') ?></option>
                    <option value="level" data-type="string"><?php echo $this->translate('Customer Level') ?></option>
                </optgroup>
                <optgroup label="<?php echo $this->translate('Shopping Cart') ?>">
                    <option value="subtotal" data-type="numeric"><?php echo $this->translate('Subtotal') ?></option>
                    <option value="total_qty" data-type="numeric"><?php echo $this->translate('Total Qty') ?></option>
                    <option value="total_weight" data-type="numeric"><?php echo $this->translate('Total Weight') ?></option>
                    <option value="payment_method" data-type="select" data-source="Seahinet\Payment\Source\Method"><?php echo $this->translate('Payment Method') ?></option>
                    <option value="shipping_method" data-type="select" data-source="Seahinet\Shipping\Source\Method"><?php echo $this->translate('Shipping Method') ?></option>
                    <option value="postcode" data-type="string"><?php echo $this->translate('Postcode') ?></option>
                    <option value="county" data-type="string"><?php echo $this->translate('County') ?></option>
                    <option value="city" data-type="string"><?php echo $this->translate('City') ?></option>
                    <option value="region" data-type="string"><?php echo $this->translate('Region') ?></option>
                    <option value="country" data-type="select" data-source="Seahinet\I18n\Source\Country"><?php echo $this->translate('Country') ?></option>
                </optgroup>
            </select>
        </li>
    </template>
</div>