<?php
$elements = $this->getVariable('elements');
$scope = $this->getStore() ? 'store' : $this->getQuery('scope', 'merchant');
$scopeId = $this->getStore() ? $this->getStore()->getId() : $this->getQuery('scope_id');
uasort($elements, function($a, $b) {
    if (!isset($a['type']) && isset($b['type'])) {
        return 1;
    } elseif (!isset($b['type']) && isset($a['type'])) {
        return -1;
    }
    if (!isset($a['priority'])) {
        $a['priority'] = 0;
    }
    if (!isset($b['priority'])) {
        $b['priority'] = 0;
    }
    return $a['priority'] == $b['priority'] ? 0 : ($a['priority'] > $b['priority'] ? 1 : -1);
});
?>
<div class="edit">
    <form action="<?php echo $this->getSaveUrl() ?>" method="post">
        <?php echo $this->getStore() ? '' : $this->getChild('scope'), $this->getChild('tabs') ?>
        <input type="hidden" name="csrf" value="<?php echo $this->getCsrfKey() ?>" />
        <input type="hidden" name="key" value="<?php echo $this->getKey() ?>" />
        <input type="hidden" name="scope" value="<?php echo substr($scope, 0, 1), $scopeId ?>" />
        <?php
        $count = 0;
        foreach ($elements as $key => $item):
            if (!isset($item['type'])):
                ?>
                <div class="table tab-pane fade<?php
                if ($count++ === 0) {
                    echo' active in';
                }
                ?>" id="<?php echo $key ?>">
                         <?php
                         foreach ($item as $k => $v) {
                             if (!isset($v['scope']) || in_array($scope, (array) $v['scope'])) {
                                 echo $this->getInputBox($key . '/' . $k, $v);
                             }
                         }
                         ?>
                </div>
                <?php
            else:
                if ($count++ === 0) {
                    echo '<div class="table tab-pane fade active in" id="main-tab">';
                }
                if (!isset($item['scope']) || in_array($scope, (array) $item['scope'])) {
                    echo $this->getInputBox($key, $item);
                }
                if ($count >= count($elements)) {
                    echo '</div>';
                }
            endif;
        endforeach;
        ?>
        <div class="buttons-set">
            <button type="submit" class="btn btn-submit"><span><?php echo $this->translate('Save') ?></span></button>
            <button type="reset" class="btn btn-reset"><span><?php echo $this->translate('Reset') ?></span></button>
        </div>
    </form>
</div>
