<form action="<?php echo $this->getAdminUrl('index/forgotpost/') ?>" method="post">
    <input type="hidden" name="csrf" value="<?php echo $this->getCsrfKey() ?>" />
    <div class="input-box">
        <label for="login:username"><?php echo $this->translate('Username') ?>: </label>
        <input type="text" name="username" id="login:username" />
    </div>
    <div class="input-box">
        <label for="login:captcha"><?php echo $this->translate('Captcha') ?>: </label>
        <input type="text" name="captcha" id="login:captcha" />
        <img src="<?php echo $this->getAdminUrl('index/captcha/') ?>" alt="" />
    </div>
    <div class="buttons-set">
        <a href="<?php echo $this->getAdminUrl() ?>"><?php echo $this->translate('Back to'), ' ', $this->translate('Login') ?></a>
        <button type="submit"><span><?php echo $this->translate('Submit') ?></span></button>
    </div>
</form>