<?php
$attributes = $this->getVariable('attributes');
$count = count($attributes) / 2;
$query = $this->getQuery();
?>
<table class="table">
    <caption>
        <h2><?php echo $this->getVariable('title') ?></h2>
    </caption>
    <thead>
        <tr>
            <th colspan="<?php echo $count + 1 ?>">
                <?php echo $this->translate('Show') ?>
                <input type="number" name="limit" value="<?php echo isset($query['asc']) ? $query['asc'] : 20 ?>" onchange="location.href = '<?php echo $this->getLimitUrl() ?>limit=' + this.value" min="1" />
                <?php echo $this->translate('Per Page') ?>
            </th>
            <th colspan="<?php echo $count + 1 ?>">
                <a href="<?php echo $this->getDeleteUrl() ?>">
                    <span><?php echo $this->translate('Delete') ?></span>
                </a>
                <a href="<?php echo $this->getEditUrl() ?>">
                    <span><?php echo $this->translate('New') ?></span>
                </a>
            </th>
        </tr>
        <tr>
            <th><input type="checkbox" /></th>
            <?php foreach ($attributes as $attr => $name): ?>
                <th>
                    <a href="<?php echo $this->getOrderByUrl($attr) ?>"
                       <?php if (isset($query['asc']) && $query['asc'] === $attr): ?>
                       class="asc"
                       <?php elseif (isset($query['desc']) && $query['desc'] === $attr): ?>
                       class="desc"
                       <?php endif ?>>
                       <?php echo $this->translate($name) ?>
                    </a>
                </th>
            <?php endforeach ?>
            <th><?php echo $this->translate('Action') ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->getVariable('collection') as $item) : ?>
            <tr>
                <td><input type="checkbox" name="id[]" value="<?php echo $item['id'] ?>" /></td>
                <?php foreach ($attributes as $attr => $name): ?>
                    <td><?php echo is_array($item[$attr]) ? implode(',', $item[$attr]) : $item[$attr] ?></td>
                <?php endforeach ?>
                <td>
                    <a href="<?php echo $this->getEditUrl($item['id']) ?>"><?php echo $this->translate('Edit') ?></a>
                    <a href="<?php echo $this->getDeleteUrl() ?>"><?php echo $this->translate('Delete') ?></a>
                </td>
            </tr>
        <?php endforeach ?>
    </tbody>
</table>