<div class="grid">
    <table class="table table-hover table-striped table-no-border">
        <thead class="sort-by">
            <tr>
                <th><?php echo $this->translate('Merchant') ?></th>
                <th><?php echo $this->translate('Store') ?></th>
                <th><?php echo $this->translate('Language') ?></th>
            </tr>
        </thead>
        <tbody>
            <?php
            $merchants = [];
            $stores = [];
            $languages = [];
            foreach ($this->getVariable('collection') as $item) {
                $merchants[$item['merchant']] = $item['merchant_id'];
                $stores[$item['store']] = $item['store_id'];
                $languages[$item['language']] = $item['language_id'];
            }
            $countS = count($stores);
            $countL = count($language);
            foreach ($merchants as $name => $id):
                for ($i = 0; $i < max($countS, $countL); $i++):
                    ?>
                    <tr>
                        <?php if ($i === 0): ?>
                            <td class="text-vmiddle" rowspan="<?php echo max($countS, $countL) ?>">
                                <a href="<?php echo $this->getAdminUrl('language/merchant/?id=' . $id) ?>">
                                    <?php echo $this->translate($name, [], 'language') ?>
                                </a>
                            </td>
                            <?php
                        endif;
                        if ($countS[$item['store']]):
                            ?>
                            <td<?php if ($countS[$item['store']] > $countL[$item['language']]): ?> rowspan="<?php echo $countS[$item['store']] ?>"<?php endif ?>>
                                <a href="<?php echo $this->getAdminUrl('language/store/?id=' . $item['store_id']) ?>">
                                    <?php echo $this->translate($item['store'], [], 'language') ?>
                                </a>
                            </td>
                            <?php
                            $countS[$item['store']] = 0;
                        endif;
                        ?>
                        <td<?php if ($countS[$item['store']] < $countL[$item['language']]): ?> rowspan="<?php echo $countL[$item['language']] ?>"<?php endif ?>>
                            <a href="<?php echo $this->getAdminUrl('language/edit/?id=' . $item['language_id']) ?>">
                                <?php echo $this->translate($item['language'], [], 'language') ?>
                            </a>
                        </td>
                    </tr>
                    <?php
                endfor;
            endforeach;
            ?>
        </tbody>
    </table>
</div>
