<nav class="nav-container">
    <ul class="nav" role="menu">
        <?php
        foreach ($this->getMenuItems() as $item):
            $hasChildren = isset($item['children']);
            ?>
            <li role="presentation" class="item<?php if ($hasChildren): ?> dropdown<?php endif ?>">
                <a href="<?php if (!empty($item['children']) || !isset($item['link'])): ?>javascript:void(0);<?php
                else: echo $this->getUrl($item['link']);
                endif;
                ?>"<?php if ($hasChildren): ?> class="dropdown-toggle" data-toggle="dropdown"<?php endif ?> role="menuitem">
                    <span class="fa fa-<?php echo $item['icon'] ?>" aria-hidden="true"></span>
                    <span class="title"><?php echo $this->translate($item['title']) ?></span>
                </a>
                <?php if ($hasChildren): ?>
                    <ul class="dropdown-menu" role="menu">
                        <?php foreach ($item['children'] as $child): ?>
                        <li role="presentation" class="item">
                            <a href="<?php echo $this->getUrl($child['link']) ?>" role="menuitem"><?php echo $this->translate($child['title']) ?></a>
                        </li>
                        <?php endforeach ?>
                    </ul>
                <?php endif ?>
            </li>
        <?php endforeach ?>
    </ul>
</nav>