<label><?php echo $this->translate('Scope') ?>: </label>
<select class="scope">
    <?php
    $cm = false;
    $cs = false;
    foreach ($this->getVariable('collection') as $item):
        if ($item['merchant_id'] !== $cm):
            ?>
            <option value="m<?php echo $item['merchant_id'] ?>"><?php echo $item['merchant'] ?></option>
            <?php
            $cm = $item['merchant_id'];
        endif;
        if ($item['store_id'] !== $cs):
            ?>
            <option value="s<?php echo $item['store_id'] ?>"><?php echo $item['store'] ?></option>
            <?php
            $cs = $item['store_id'];
        endif;
        ?>
        <option value="l<?php echo $item['language_id'] ?>"><?php echo $item['language'] ?></option>
    <?php endforeach ?>
</select>