<?php
$tabs = $this->getTabs();
if (count($tabs)):
    ?>
    <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active">
            <a href="#main-tab" aria-controls="main-tab" role="tab" data-toggle="tab">
                <?php echo $this->translate($this->getMainTabLabel()) ?>
            </a>
        </li>
        <?php foreach ($this->getTabs() as $id => $tab): ?>
            <li role="presentation">
                <a href="#<?php echo $id ?>" aria-controls="profile" role="tab" data-toggle="tab">
                    <?php echo $this->translate($tab) ?>
                </a>
            </li>
        <?php endforeach ?>
    </ul>
    <?php foreach ($this->getTabs() as $id => $tab): ?>
        <div role="tabpanel" class="tab-pane fade" id="<?php echo $id ?>">
            <?php echo $this->$id ?>
        </div>
        <?php
    endforeach;
endif;
?>
