<form action="<?php echo $this->getBaseUrl('sales/order/reviewPost/') ?>" method="post">
    <input type="hidden" name="csrf" value="<?php echo $this->getCsrfKey() ?>" />
    <input type="hidden" name="order_id" value="<?php echo $this->getVariable('model')->getId() ?>" />
    <div class="fieldset">
        <?php if (count($this->getOrderRating())): ?>
            <?php foreach ($this->getOrderRating() as $rating): ?>
                <div class="input-box">
                    <label class="control-label"><?php echo $this->translate($rating['title']) ?></label>
                    <div class="cell">
                        <?php for ($i = 5; $i > 0; $i--): ?>
                            <input type="radio" name="rating[0][<?php echo $rating['id'] ?>]" hidden id="rating-0-<?php echo $rating['id'], '-', $i ?>" value="<?php echo $i ?>" />
                            <label for="rating-0-<?php echo $rating['id'], '-', $i ?>"><span class="sr-only"><?php echo $i ?></span></label>
                        <?php endfor ?>
                    </div>
                </div>
            <?php endforeach ?>
        <?php endif ?>
        <?php
        foreach ($this->getVariable('model')->getItems() as $item):
            $product = $item['product'];
            $thumbnail = $product->getThumbnail();
            ?>
            <div class="input-box">
                <div class="cell">
                    <img src="<?php echo strpos($thumbnail, '://') ? $thumbnail : $this->getResourceUrl('image/resized/100x/' . $thumbnail) ?>" alt="<?php echo $product['name'] ?>" />
                </div>
                <div class="cell">
                    <div class="col-xs-12 col-sm-4">
                        <?php
                        echo $product['name'];
                        $options = json_decode($item['options'], true);
                        if ($item['product_id'] && count($options)):
                            ?>
                            <dl class="options">
                                <?php
                                foreach ($product->getOptions() as $option):
                                    if (isset($options[$option->getId()])):
                                        ?>
                                        <dt><?php echo $option['title'] ?></dt>
                                        <dd>
                                            <?php
                                            echo (in_array($option['input'], ['select', 'radio', 'checkbox', 'multiselect']) ?
                                                    $option->getValue($options[$option->getId()]) : $options[$option->getId()])
                                            ?>
                                        </dd>
                                        <?php
                                    endif;
                                endforeach;
                                ?>
                            </dl>
                        <?php endif; ?>
                    </div>
                    <div class="col-xs-12 col-sm-4">
                        <label for="review-<?php echo $product->getId() ?>"></label>
                        <textarea name="review[<?php echo $product->getId() ?>]" class="form-control required" id="review-<?php echo $product->getId() ?>"></textarea>
                    </div>
                    <div class="col-xs-12 col-sm-4">
                        <div class="fieldset">
                            <?php foreach ($this->getProductRating() as $rating): ?>
                                <div class="input-box">
                                    <label class="control-label"><?php echo $this->translate($rating['title']) ?></label>
                                    <div class="cell">
                                        <?php for ($i = 5; $i > 0; $i--): ?>
                                            <input type="radio" name="rating[<?php echo $product->getId() ?>][<?php echo $rating['id'] ?>]" hidden id="rating-<?php echo $product->getId(), '-', $rating['id'], '-', $i ?>" value="<?php echo $i ?>" />
                                            <label for="rating-<?php echo $product->getId(), '-', $rating['id'], '-', $i ?>"><span class="sr-only"><?php echo $i ?></span></label>
                                            <?php endfor ?>
                                    </div>
                                </div>
                            <?php endforeach ?>
                        </div>
                    </div>
                </div>
            </div>
        <?php endforeach ?>
    </div>
    <div class="buttons-set">
        <button type="submit" class="btn btn-theme"><?php echo $this->translate('Submit') ?></button>
    </div>
</form>
