<div class="input-box">
    <label class="control-label" aria-required="true"><?php echo $this->translate('Account Balance') ?></label>
    <div class="cell"><?php echo $this->getCurrentBalances(); ?></div>
</div>
<div class="input-box">
    <div class="cell"></div>
    <div class="cell">
        <?php echo $this->getChild('balancedetail')->setVariable('customer', $this->getCustomer()) ?>
    </div>
</div>