---
promotion.calc:
    -
        listener: [\Seahinet\Promotion\Listeners\Regular, calc]
        priority: 10
order.place.after:
    -
        listener: [\Seahinet\Promotion\Listeners\Coupon, log]
        priority: 10