---
admin_promotion_list:
    - Are you sure to delete this record?
    - Are you sure to delete these records?
admin_promotion_edit:
    - Are you sure to delete this record?
    - Are you sure to delete these records?    
