---
promotion:
    icon: gift
    title: Promotion
    priority: 40
    children: 
        -
            link: promotion/
            operation: 'Admin\Promotion::index'
            title: Preferential Promotion
            priority: 0
