<div class="input-box">
    <label class="control-label" aria-required="true"><?php echo $this->translate('Reward Points') ?></label>
    <div class="cell"><?php echo $this->getCurrentPoints() ?></div>
</div>
<div class="input-box">
    <label for="adjust-rewardpoints" class="control-label" aria-required="true"><?php echo $this->translate('Adjustment') ?></label>
    <div class="cell">
        <input type="tel" name="adjust_rewardpoints" id="adjust-rewardpoints" class="form-control digits" value="0" />
    </div>
</div>