---
cart.add.before:
    -
        listener: [\Seahinet\Retailer\Listeners\Farm, check]
        priority: 5
customer.login.after:
    -
        listener: [\Seahinet\Retailer\Listeners\Farm, beforeCombine]
        priority: 9
Seahinet\Customer\Model\Customer.model.remove.after:
    -
        listener: [\Seahinet\Retailer\Listeners\Customer, afterRemove]
        priority: 10
Seahinet\Catalog\Model\Product.model.save.after:
    -
        listener: [\Seahinet\Retailer\Listeners\Category, afterSave]
        priority: 10
Seahinet\Catalog\Model\Product.model.load.after:
    -
        listener: [\Seahinet\Retailer\Listeners\Category, afterLoad]
        priority: 10