---
retailer_sales_products:
    - are you sure you want pull these products off shelves?
retailer_category: 
    - Are you sure to delete this record?
    - Are you sure to delete these records?
retailer_sales_products: 
    - Are you sure you want pull these products off shelves?
    - Are you sure you want recover these products?
retailer_stock_products: 
    - Are you sure you want put these products on shelves?