---
retailer:
    method: [GET,POST,DELETE]
    route: /retailer/{controller}/[{action}[/]]
    namespace: Seahinet\Retailer\Controller
store:
    route: Seahinet\Retailer\Route\Router
    priority: 50