---
order.place.after:
    -
        listener: [\Seahinet\Balance\Listeners\Recalc, afterOrderPlace]
        priority: 30
    -
        listener: [\Seahinet\Balance\Listeners\Using, afterOrderPlace]
        priority: 30
Seahinet\Sales\Model\Order.model.save.after:
    -
        listener: [\Seahinet\Balance\Listeners\Recalc, afterOrderComplete]
        priority: 30
promotion.calc:
    -
        listener: [\Seahinet\Balance\Listeners\Using, calc]
        priority: 1000
balances.apply:
    -
         listener: [\Seahinet\Balance\Listeners\Using, apply]
         priority: 1000