---
balance:
    label: Account Balance
    children:
        general:
            label: General
            scope: merchant
            children:
                enable:
                    type: select
                    label: Enable
                    required: required
                    priority: 0
                    options:
                        - Disabled
                        - Enabled
                    default: 1
                product_for_recharge:
                    type: tel
                    label: Product for Recharge 
                    priority: 1
                refunded:
                    type: select
                    label: Restore Spent Balances After Order Refunding
                    required: required
                    priority: 10
                    default: 1
                    options:
                        1: Yes
                        0: No
