SET FOREIGN_KEY_CHECKS=0;

CREATE TABLE IF NOT EXISTS `sales_order_phase` (
    `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `code` VARCHAR(20) NOT NULL,
    `name` VARCHAR(20) DEFAULT '',
    PRIMARY KEY (`id`),
    CONSTRAINT UNQ_SALES_ORDER_PHASE_CODE UNIQUE (`code`)
);

CREATE TABLE IF NOT EXISTS `sales_order_status` (
    `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `phase_id` INTEGER UNSIGNED NOT NULL,
    `name` VARCHAR(20) DEFAULT '',
    `is_default` BOOLEAN DEFAULT 1,
    PRIMARY KEY (`id`),
    INDEX IDX_SALES_ORDER_STATUS_PHASE_ID (`phase_id`),
    CONSTRAINT FK_SALES_ORDER_STATUS_PHASE_ID_SALES_ORDER_PHASE_ID FOREIGN KEY (`phase_id`) REFERENCES `sales_order_phase`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
);

INSERT INTO `sales_order_phase` VALUES 
(1,'pending','Pending'),
(2,'pending_payment','Pending Payment'),
(3,'processing','Processing'),
(4,'complete','Complete'),
(5,'canceled','Canceled'),
(6,'closed','Close'),
(7,'holded','On Hold');

INSERT INTO `sales_order_status` VALUES 
(1,1,'Pending',1),
(2,2,'Pending Payment',1),
(3,3,'Processing',1),
(4,4,'Complete',1),
(5,5,'Canceled',1),
(6,6,'Close',1),
(7,7,'On Hold',1);

CREATE TABLE IF NOT EXISTS `sales_cart` (
    `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `customer_id` INTEGER UNSIGNED DEFAULT NULL,
    `billing_address_id` INTEGER UNSIGNED DEFAULT NULL,
    `shipping_address_id` INTEGER UNSIGNED DEFAULT NULL,
    `billing_address` TEXT,
    `shipping_address` TEXT,
    `is_virtual` BOOLEAN DEFAULT 0,
    `free_shipping` BOOLEAN DEFAULT 0,
    `coupon` VARCHAR(255) DEFAULT NULL,
    `base_currency` CHAR(3) NOT NULL,
    `currency` CHAR(3) NOT NULL,
    `shipping_method` VARCHAR(255) DEFAULT NULL,
    `payment_method` VARCHAR(255) DEFAULT NULL,
    `base_subtotal` DECIMAL(12,4) DEFAULT 0,
    `subtotal` DECIMAL(12,4) DEFAULT 0,
    `base_shipping` DECIMAL(12,4) DEFAULT 0,
    `shipping` DECIMAL(12,4) DEFAULT 0,
    `base_discount` DECIMAL(12,4) DEFAULT 0,
    `discount` DECIMAL(12,4) DEFAULT 0,
    `discount_detail` TEXT DEFAULT NULL,
    `base_tax` DECIMAL(12,4) DEFAULT 0,
    `tax` DECIMAL(12,4) DEFAULT 0,
    `base_total` DECIMAL(12,4) DEFAULT 0,
    `total` DECIMAL(12,4) DEFAULT 0,
    `additional` TEXT,
    `customer_note` TEXT,
    `status` BOOLEAN DEFAULT 1,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    INDEX IDX_SALES_CART_STATUS (`status`),
    INDEX IDX_SALES_CART_CUSTOMER_ID (`customer_id`),
    INDEX IDX_SALES_CART_BILLING_ADDRESS_ID (`billing_address_id`),
    INDEX IDX_SALES_CART_SHIPPING_ADDRESS_ID (`shipping_address_id`),
    CONSTRAINT FK_SALES_CART_CUSTOMER_ID_CUSTOMER_ENTITY_ID FOREIGN KEY (`customer_id`) REFERENCES `customer_entity`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT FK_SALES_CART_BILLING_ADDR_ID_ADDR_ENTITY_ID FOREIGN KEY (`billing_address_id`) REFERENCES `address_entity`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT FK_SALES_CART_SHIPPING_ADDR_ID_ADDR_ENTITY_ID FOREIGN KEY (`shipping_address_id`) REFERENCES `address_entity`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `sales_cart_item` (
    `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `cart_id` INTEGER UNSIGNED NOT NULL,
    `store_id` INTEGER UNSIGNED DEFAULT NULL,
    `warehouse_id` INTEGER UNSIGNED DEFAULT NULL,
    `product_id` INTEGER UNSIGNED,
    `product_name` VARCHAR(255),
    `options` VARCHAR(255) NULL,
    `qty` DECIMAL(12,4) NOT NULL,
    `sku` VARCHAR(255) NOT NULL,
    `is_virtual` BOOLEAN DEFAULT 0,
    `free_shipping` BOOLEAN DEFAULT 0,
    `base_price` DECIMAL(12,4) NOT NULL,
    `price` DECIMAL(12,4) NOT NULL,
    `base_discount` DECIMAL(12,4) DEFAULT 0,
    `discount` DECIMAL(12,4) DEFAULT 0,
    `base_tax` DECIMAL(12,4) DEFAULT 0,
    `tax` DECIMAL(12,4) DEFAULT 0,
    `base_total` DECIMAL(12,4) NOT NULL,
    `total` DECIMAL(12,4) NOT NULL,
    `weight` DECIMAL(12,4) NOT NULL,
    `status` BOOLEAN NOT NULL DEFAULT 1,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    INDEX IDX_SALES_CART_ITEM_WAREHOUSE_ID (`warehouse_id`),
    INDEX IDX_SALES_CART_ITEM_STORE_ID (`store_id`),
    INDEX IDX_SALES_CART_ITEM_CART_ID (`cart_id`),
    INDEX IDX_SALES_CART_ITEM_PRODUCT_ID (`product_id`),
    INDEX IDX_SALES_CART_ITEM_STATUS (`status`),
    CONSTRAINT FK_SALES_CART_ITEM_STORE_ID_CORE_STORE_ID FOREIGN KEY (`store_id`) REFERENCES `core_store`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT FK_SALES_CART_ITEM_WAREHOUSE_ID_WAREHOUSE_ID FOREIGN KEY (`warehouse_id`) REFERENCES `warehouse`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_SALES_CART_ITEM_ORDER_ID_SALES_CART_ID FOREIGN KEY (`cart_id`) REFERENCES `sales_cart`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_SALES_CART_ITEM_PRODUCT_ID_PRODUCT_ENTITY_ID FOREIGN KEY (`product_id`) REFERENCES `product_entity`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `sales_order` (
    `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `status_id` INTEGER UNSIGNED NOT NULL,
    `increment_id` VARCHAR(255) NOT NULL,
    `customer_id` INTEGER UNSIGNED DEFAULT NULL,
    `billing_address_id` INTEGER UNSIGNED DEFAULT NULL,
    `shipping_address_id` INTEGER UNSIGNED DEFAULT NULL,
    `warehouse_id` INTEGER UNSIGNED DEFAULT NULL,
    `store_id` INTEGER UNSIGNED DEFAULT NULL,
    `language_id` INTEGER UNSIGNED DEFAULT NULL,
    `billing_address` TEXT,
    `shipping_address` TEXT,
    `is_virtual` BOOLEAN DEFAULT 0,
    `free_shipping` BOOLEAN DEFAULT 0,
    `coupon` VARCHAR(50) DEFAULT NULL,
    `base_currency` CHAR(3) NOT NULL,
    `currency` CHAR(3) NOT NULL,
    `shipping_method` VARCHAR(255) DEFAULT NULL,
    `payment_method` VARCHAR(255) DEFAULT NULL,
    `base_subtotal` DECIMAL(12,4) DEFAULT 0,
    `subtotal` DECIMAL(12,4) DEFAULT 0,
    `base_shipping` DECIMAL(12,4) DEFAULT 0,
    `shipping` DECIMAL(12,4) DEFAULT 0,
    `base_discount` DECIMAL(12,4) DEFAULT 0,
    `discount` DECIMAL(12,4) DEFAULT 0,
    `discount_detail` TEXT DEFAULT NULL,
    `base_tax` DECIMAL(12,4) DEFAULT 0,
    `tax` DECIMAL(12,4) DEFAULT 0,
    `base_total` DECIMAL(12,4) NOT NULL,
    `total` DECIMAL(12,4) NOT NULL,
    `base_total_paid` DECIMAL(12,4) DEFAULT 0,
    `total_paid` DECIMAL(12,4) DEFAULT 0,
    `base_total_refunded` DECIMAL(12,4) DEFAULT 0,
    `total_refunded` DECIMAL(12,4) DEFAULT 0,
    `additional` TEXT,
    `customer_note` TEXT,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    INDEX IDX_SALES_ORDER_STATUS_ID (`status_id`),
    INDEX IDX_SALES_ORDER_INCREMENT_ID (`increment_id`),
    INDEX IDX_SALES_ORDER_CUSTOMER_ID (`customer_id`),
    INDEX IDX_SALES_ORDER_STORE_ID (`store_id`),
    INDEX IDX_SALES_ORDER_LANGUAGE_ID (`language_id`),
    INDEX IDX_SALES_ORDER_WAREHOUSE_ID (`warehouse_id`),
    INDEX IDX_SALES_ORDER_BILLING_ADDRESS_ID (`billing_address_id`),
    INDEX IDX_SALES_ORDER_SHIPPING_ADDRESS_ID (`shipping_address_id`),
    CONSTRAINT FK_SALES_ORDER_STATUS_ID_SALES_ORDER_STATUS_ID FOREIGN KEY (`status_id`) REFERENCES `sales_order_status`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT FK_SALES_ORDER_WAREHOUSE_ID_WAREHOUSE_ID FOREIGN KEY (`warehouse_id`) REFERENCES `warehouse`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT FK_SALES_ORDER_CUSTOMER_ID_CUSTOMER_ENTITY_ID FOREIGN KEY (`customer_id`) REFERENCES `customer_entity`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT FK_SALES_ORDER_STORE_ID_CORE_STORE_ID FOREIGN KEY (`store_id`) REFERENCES `core_store`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT FK_SALES_ORDER_STORE_ID_CORE_LANGUAGE_ID FOREIGN KEY (`language_id`) REFERENCES `core_language`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT FK_SALES_ORDER_BILLING_ADDR_ID_ADDR_ENTITY_ID FOREIGN KEY (`billing_address_id`) REFERENCES `address_entity`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT FK_SALES_ORDER_SHIPPING_ADDR_ID_ADDR_ENTITY_ID FOREIGN KEY (`shipping_address_id`) REFERENCES `address_entity`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `sales_order_item` (
    `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `order_id` INTEGER UNSIGNED NOT NULL,
    `product_id` INTEGER UNSIGNED,
    `product_name` VARCHAR(255),
    `options` VARCHAR(255) NULL,
    `qty` DECIMAL(12,4) NOT NULL,
    `sku` VARCHAR(255) NOT NULL,
    `is_virtual` BOOLEAN DEFAULT 0,
    `free_shipping` BOOLEAN DEFAULT 0,
    `base_price` DECIMAL(12,4) NOT NULL,
    `price` DECIMAL(12,4) NOT NULL,
    `base_discount` DECIMAL(12,4) DEFAULT 0,
    `discount` DECIMAL(12,4) DEFAULT 0,
    `base_tax` DECIMAL(12,4) DEFAULT 0,
    `tax` DECIMAL(12,4) DEFAULT 0,
    `base_total` DECIMAL(12,4) NOT NULL,
    `total` DECIMAL(12,4) NOT NULL,
    `weight` DECIMAL(12,4) NOT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    INDEX IDX_SALES_ORDER_ITEM_ORDER_ID (`order_id`),
    INDEX IDX_SALES_ORDER_ITEM_PRODUCT_ID (`product_id`),
    CONSTRAINT FK_SALES_ORDER_ITEM_ORDER_ID_SALES_ORDER_ID FOREIGN KEY (`order_id`) REFERENCES `sales_order`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_SALES_ORDER_ITEM_PRODUCT_ID_PRODUCT_ENTITY_ID FOREIGN KEY (`product_id`) REFERENCES `product_entity`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `sales_order_invoice` (
    `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `order_id` INTEGER UNSIGNED NOT NULL,
    `increment_id` VARCHAR(255) NOT NULL,
    `store_id` INTEGER UNSIGNED DEFAULT NULL,
    `coupon` VARCHAR(50) DEFAULT NULL,
    `base_currency` CHAR(3) NOT NULL,
    `currency` CHAR(3) NOT NULL,
    `base_subtotal` DECIMAL(12,4) DEFAULT 0,
    `subtotal` DECIMAL(12,4) DEFAULT 0,
    `base_shipping` DECIMAL(12,4) DEFAULT 0,
    `shipping` DECIMAL(12,4) DEFAULT 0,
    `base_discount` DECIMAL(12,4) DEFAULT 0,
    `discount` DECIMAL(12,4) DEFAULT 0,
    `discount_detail` TEXT DEFAULT NULL,
    `base_tax` DECIMAL(12,4) DEFAULT 0,
    `tax` DECIMAL(12,4) DEFAULT 0,
    `base_total` DECIMAL(12,4) NOT NULL,
    `total` DECIMAL(12,4) NOT NULL,
    `comment` TEXT,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    INDEX IDX_SALES_ORDER_INVOICE_INCREMENT_ID (`increment_id`),
    INDEX IDX_SALES_ORDER_INVOICE_STORE_ID (`store_id`),
    INDEX IDX_SALES_ORDER_INVOICE_ORDER_ID (`order_id`),
    CONSTRAINT FK_SALES_ORDER_INVOICE_ORDER_ID_SALES_ORDER_ID FOREIGN KEY (`order_id`) REFERENCES `sales_order`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_SALES_ORDER_INVOICE_STORE_ID_CORE_STORE_ID FOREIGN KEY (`store_id`) REFERENCES `core_store`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `sales_order_invoice_item` (
    `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `item_id` INTEGER UNSIGNED,
    `invoice_id` INTEGER UNSIGNED NOT NULL,
    `product_id` INTEGER UNSIGNED,
    `product_name` VARCHAR(255),
    `options` VARCHAR(255) NULL,
    `qty` DECIMAL(12,4) NOT NULL,
    `sku` VARCHAR(255) NOT NULL,
    `base_price` DECIMAL(12,4) NOT NULL,
    `price` DECIMAL(12,4) NOT NULL,
    `base_discount` DECIMAL(12,4) DEFAULT 0,
    `discount` DECIMAL(12,4) DEFAULT 0,
    `base_tax` DECIMAL(12,4) DEFAULT 0,
    `tax` DECIMAL(12,4) DEFAULT 0,
    `base_total` DECIMAL(12,4) NOT NULL,
    `total` DECIMAL(12,4) NOT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    INDEX IDX_SALES_ORDER_INVOICE_ITEM_ITEM_ID (`item_id`),
    INDEX IDX_SALES_ORDER_INVOICE_ITEM_INVOICE_ID (`invoice_id`),
    INDEX IDX_SALES_ORDER_INVOICE_ITEM_PRODUCT_ID (`product_id`),
    CONSTRAINT FK_SALES_ORDER_INVOICE_ITEM_ITEM_ID_SALES_ORDER_ITEM_ID FOREIGN KEY (`item_id`) REFERENCES `sales_order_item`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT FK_SALES_ORDER_INVOICE_ITEM_INVOICE_ID_SALES_ORDER_INVOICE_ID FOREIGN KEY (`invoice_id`) REFERENCES `sales_order_invoice`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_SALES_ORDER_INVOICE_ITEM_PRODUCT_ID_PRODUCT_ENTITY_ID FOREIGN KEY (`product_id`) REFERENCES `product_entity`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `sales_order_shipment` (
    `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `order_id` INTEGER UNSIGNED NOT NULL,
    `increment_id` VARCHAR(255) NOT NULL,
    `customer_id` INTEGER UNSIGNED DEFAULT NULL,
    `shipping_method` VARCHAR(255) DEFAULT NULL,
    `billing_address_id` INTEGER UNSIGNED DEFAULT NULL,
    `shipping_address_id` INTEGER UNSIGNED DEFAULT NULL,
    `warehouse_id` INTEGER UNSIGNED DEFAULT NULL,
    `store_id` INTEGER UNSIGNED DEFAULT NULL,
    `billing_address` TEXT,
    `shipping_address` TEXT,
    `comment` TEXT,
    `status` BOOLEAN DEFAULT 0,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    INDEX IDX_SALES_ORDER_SHIPMENT_INCREMENT_ID (`increment_id`),
    INDEX IDX_SALES_ORDER_SHIPMENT_STORE_ID (`store_id`),
    INDEX IDX_SALES_ORDER_SHIPMENT_ORDER_ID (`order_id`),
    INDEX IDX_SALES_ORDER_SHIPMENT_CUSTOMER_ID (`customer_id`),
    INDEX IDX_SALES_ORDER_SHIPMENT_WAREHOUSE_ID (`warehouse_id`),
    INDEX IDX_SALES_ORDER_SHIPMENT_BILLING_ADDRESS_ID (`billing_address_id`),
    INDEX IDX_SALES_ORDER_SHIPMENT_SHIPPING_ADDRESS_ID (`shipping_address_id`),
    CONSTRAINT FK_SALES_ORDER_SHIPMENT_WAREHOUSE_ID_WAREHOUSE_ID FOREIGN KEY (`warehouse_id`) REFERENCES `warehouse`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT FK_SALES_ORDER_SHIPMENT_ORDER_ID_SALES_ORDER_ID FOREIGN KEY (`order_id`) REFERENCES `sales_order`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_SALES_ORDER_SHIPMENT_CUSTOMER_ID_CUSTOMER_ENTITY_ID FOREIGN KEY (`customer_id`) REFERENCES `customer_entity`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT FK_SALES_ORDER_SHIPMENT_STORE_ID_CORE_STORE_ID FOREIGN KEY (`store_id`) REFERENCES `core_store`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT FK_SALES_ORDER_SHIPMENT_BILLING_ADDR_ID_ADDR_ENTITY_ID FOREIGN KEY (`billing_address_id`) REFERENCES `address_entity`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT FK_SALES_ORDER_SHIPMENT_SHIPPING_ADDR_ID_ADDR_ENTITY_ID FOREIGN KEY (`shipping_address_id`) REFERENCES `address_entity`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `sales_order_shipment_item` (
    `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `item_id` INTEGER UNSIGNED,
    `shipment_id` INTEGER UNSIGNED NOT NULL,
    `product_id` INTEGER UNSIGNED,
    `product_name` VARCHAR(255),
    `options` VARCHAR(255) NULL,
    `qty` DECIMAL(12,4) NOT NULL,
    `sku` VARCHAR(255) NOT NULL,
    `weight` DECIMAL(12,4) NOT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    INDEX IDX_SALES_ORDER_SHIPMENT_ITEM_ITEM_ID (`item_id`),
    INDEX IDX_SALES_ORDER_SHIPMENT_ITEM_SHIPMENT_ID (`shipment_id`),
    INDEX IDX_SALES_ORDER_SHIPMENT_ITEM_PRODUCT_ID (`product_id`),
    CONSTRAINT FK_SALES_ORDER_SHIPMENT_ITEM_ITEM_ID_SALES_ORDER_ITEM_ID FOREIGN KEY (`item_id`) REFERENCES `sales_order_item`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT FK_SALES_ORDER_SHIPMENT_ITEM_SHIPMENT_ID_SALES_ORDER_SHIPMENT_ID FOREIGN KEY (`shipment_id`) REFERENCES `sales_order_shipment`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_SALES_ORDER_SHIPMENT_ITEM_PRODUCT_ID_PRODUCT_ENTITY_ID FOREIGN KEY (`product_id`) REFERENCES `product_entity`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `sales_order_shipment_track` (
    `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `shipment_id` INTEGER UNSIGNED NOT NULL,
    `order_id` INTEGER UNSIGNED NOT NULL,
    `carrier` VARCHAR(255) NOT NULL,
    `carrier_code` VARCHAR(32) DEFAULT '',
    `track_number` VARCHAR(255) NOT NULL,
    `description` TEXT,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    INDEX IDX_SALES_ORDER_TRACK_ORDER_ID (`order_id`),
    INDEX IDX_SALES_ORDER_TRACK_SHIPMENT_ID (`shipment_id`),
    CONSTRAINT FK_SALES_ORDER_TRACK_ORDER_ID_SALES_ORDER_ID FOREIGN KEY (`order_id`) REFERENCES `sales_order`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_SALES_ORDER_TRACK_SHIPMENT_ID_SALES_ORDER_SHIPMENT_ID FOREIGN KEY (`shipment_id`) REFERENCES `sales_order_shipment`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `sales_order_creditmemo` (
    `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `order_id` INTEGER UNSIGNED NOT NULL,
    `increment_id` VARCHAR(255) NOT NULL,
    `warehouse_id` INTEGER UNSIGNED DEFAULT NULL,
    `store_id` INTEGER UNSIGNED DEFAULT NULL,
    `base_currency` CHAR(3) NOT NULL,
    `currency` CHAR(3) NOT NULL,
    `base_subtotal` DECIMAL(12,4) DEFAULT 0,
    `subtotal` DECIMAL(12,4) DEFAULT 0,
    `base_shipping` DECIMAL(12,4) DEFAULT 0,
    `shipping` DECIMAL(12,4) DEFAULT 0,
    `base_discount` DECIMAL(12,4) DEFAULT 0,
    `discount` DECIMAL(12,4) DEFAULT 0,
    `base_tax` DECIMAL(12,4) DEFAULT 0,
    `tax` DECIMAL(12,4) DEFAULT 0,
    `base_total` DECIMAL(12,4) NOT NULL,
    `total` DECIMAL(12,4) NOT NULL,
    `comment` TEXT,
    `status` BOOLEAN DEFAULT 0,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    INDEX IDX_SALES_ORDER_MEMO_INCREMENT_ID (`increment_id`),
    INDEX IDX_SALES_ORDER_MEMO_STORE_ID (`store_id`),
    INDEX IDX_SALES_ORDER_MEMO_ORDER_ID (`order_id`),
    INDEX IDX_SALES_ORDER_MEMO_WAREHOUSE_ID (`warehouse_id`),
    CONSTRAINT FK_SALES_ORDER_MEMO_WAREHOUSE_ID_WAREHOUSE_ID FOREIGN KEY (`warehouse_id`) REFERENCES `warehouse`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT FK_SALES_ORDER_MEMO_ORDER_ID_SALES_ORDER_ID FOREIGN KEY (`order_id`) REFERENCES `sales_order`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_SALES_ORDER_MEMO_STORE_ID_CORE_STORE_ID FOREIGN KEY (`store_id`) REFERENCES `core_store`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `sales_order_creditmemo_item` (
    `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `item_id` INTEGER UNSIGNED,
    `creditmemo_id` INTEGER UNSIGNED NOT NULL,
    `product_id` INTEGER UNSIGNED,
    `product_name` VARCHAR(255),
    `options` VARCHAR(255) NULL,
    `qty` DECIMAL(12,4) NOT NULL,
    `sku` VARCHAR(255) NOT NULL,
    `base_price` DECIMAL(12,4) NOT NULL,
    `price` DECIMAL(12,4) NOT NULL,
    `base_discount` DECIMAL(12,4) DEFAULT 0,
    `discount` DECIMAL(12,4) DEFAULT 0,
    `base_tax` DECIMAL(12,4) DEFAULT 0,
    `tax` DECIMAL(12,4) DEFAULT 0,
    `base_total` DECIMAL(12,4) NOT NULL,
    `total` DECIMAL(12,4) NOT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    INDEX IDX_SALES_ORDER_MEMO_ITEM_ITEM_ID (`item_id`),
    INDEX IDX_SALES_ORDER_MEMO_ITEM_MEMO_ID (`creditmemo_id`),
    INDEX IDX_SALES_ORDER_MEMO_ITEM_PRODUCT_ID (`product_id`),
    CONSTRAINT FK_SALES_ORDER_MEMO_ITEM_ITEM_ID_SALES_ORDER_ITEM_ID FOREIGN KEY (`item_id`) REFERENCES `sales_order_item`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT FK_SALES_ORDER_MEMO_ITEM_MEMO_ID_SALES_ORDER_MEMO_ID FOREIGN KEY (`creditmemo_id`) REFERENCES `sales_order_creditmemo`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_SALES_ORDER_MEMO_ITEM_PRODUCT_ID_PRODUCT_ENTITY_ID FOREIGN KEY (`product_id`) REFERENCES `product_entity`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `sales_order_status_history` (
    `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `admin_id` INTEGER UNSIGNED,
    `order_id` INTEGER UNSIGNED NOT NULL,
    `status_id` INTEGER UNSIGNED,
    `status` VARCHAR(255),
    `is_customer_notified` BOOLEAN DEFAULT 0,
    `is_visible_on_front` BOOLEAN  DEFAULT 0,
    `comment` TEXT,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    INDEX IDX_SALES_ORDER_STATUS_HISTORY_ADMIN_ID (`admin_id`),
    INDEX IDX_SALES_ORDER_STATUS_HISTORY_ORDER_ID (`order_id`),
    INDEX IDX_SALES_ORDER_STATUS_HISTORY_STATUS_ID (`status_id`),
    INDEX IDX_SALES_ORDER_STATUS_HISTORY_CREATED_AT (`created_at`),
    CONSTRAINT FK_SALES_ORDER_STATUS_ADMIN_ID_ADMIN_USER_ID FOREIGN KEY (`admin_id`) REFERENCES `admin_user`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT FK_SALES_ORDER_STATUS_ORDER_ID_SALES_ORDER_ID FOREIGN KEY (`order_id`) REFERENCES `sales_order`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_SALES_ORDER_STATUS_STATUS_ID_SALES_ORDER_STATUS_ID FOREIGN KEY (`status_id`) REFERENCES `sales_order_status`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `wishlist` (
    `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `customer_id` INTEGER UNSIGNED NOT NULL,
    PRIMARY KEY (`id`),
    CONSTRAINT UNQ_WISHLIST_CUSTOMER_ID UNIQUE (`customer_id`),
    CONSTRAINT FK_WISHLIST_CUSTOMER_ID_CUSTOMER_ENTITY_ID FOREIGN KEY (`customer_id`) REFERENCES `customer_entity`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `wishlist_item` (
    `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `wishlist_id` INTEGER UNSIGNED NOT NULL,
    `product_id` INTEGER UNSIGNED,
    `warehouse_id` INTEGER UNSIGNED,
    `product_name` VARCHAR(255),
    `store_id` INTEGER UNSIGNED DEFAULT NULL,
    `description` TEXT,
    `qty` DECIMAL(12,4) NOT NULL,
    `options` VARCHAR(255) NULL,
    `price` DECIMAL(12,4) DEFAULT 0,
    `added_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    INDEX IDX_WISHLIST_ITEM_STORE_ID (`store_id`),
    INDEX IDX_WISHLIST_ITEM_PRODUCT_ID (`product_id`),
    INDEX IDX_WISHLIST_ITEM_WAREHOUSE_ID (`warehouse_id`),
    CONSTRAINT FK_WISHLIST_ITEM_PRODUCT_ID_PRODUCT_ENTITY_ID FOREIGN KEY (`product_id`) REFERENCES `product_entity`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT FK_WISHLIST_ITEM_PRODUCT_ID_WAREHOUSE_ID FOREIGN KEY (`warehouse_id`) REFERENCES `warehouse`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT FK_WISHLIST_ITEM_STORE_ID_CORE_STORE_ID FOREIGN KEY (`store_id`) REFERENCES `core_store`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `social_media` (
    `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `label` VARCHAR(255) NOT NULL,
    `link` VARCHAR(255) NOT NULL,
    `icon` VARCHAR(20) NOT NULL,
    PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `social_media_share` (
    `media_id` INTEGER UNSIGNED NOT NULL,
    `customer_id` INTEGER UNSIGNED NOT NULL,
    `product_id` INTEGER UNSIGNED NOT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`media_id`,`customer_id`,`product_id`),
    INDEX IDX_SOCIAL_MEDIA_SHARE_CUSTOMER_ID (`customer_id`),
    INDEX IDX_SOCIAL_MEDIA_SHARE_PRODUCT_ID (`product_id`),
    CONSTRAINT FK_SOCIAL_MEDIA_SHARE_MEDIA_ID_SOCIAL_MEDIA_ID FOREIGN KEY (`media_id`) REFERENCES `social_media` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_SOCIAL_MEDIA_SHARE_CUSTOMER_ID_CUSTOMER_ENTITY_ID FOREIGN KEY (`customer_id`) REFERENCES `customer_entity` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_SOCIAL_MEDIA_SHARE_PRODUCT_ID_PRODUCT_ENTITY_ID FOREIGN KEY (`product_id`) REFERENCES `product_entity` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `log_visitor` (
    `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `customer_id` INTEGER UNSIGNED NULL DEFAULT NULL,
    `store_id` INTEGER UNSIGNED NULL DEFAULT NULL,
    `product_id` INTEGER UNSIGNED NULL DEFAULT NULL,
    `session_id` CHAR(32) NOT NULL,
    `http_referer` VARCHAR(255) NULL DEFAULT NULL,
    `http_user_agent` VARCHAR(255) NULL DEFAULT NULL,
    `http_accept_charset` VARCHAR(255) NULL DEFAULT NULL,
    `http_accept_language` VARCHAR(255) NULL DEFAULT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    INDEX IDX_LOG_VISITOR_CUSTOMER_ID (`customer_id`),
    INDEX IDX_LOG_VISITOR_STORE_ID (`store_id`),
    INDEX IDX_LOG_VISITOR_PRODUCT_ID (`product_id`),
    INDEX IDX_LOG_VISITOR_SESSION_ID (`session_id`),
    CONSTRAINT UNQ_LOG_VISITOR_SESSION_ID_PRODUCT_ID UNIQUE (`session_id`,`product_id`),
    CONSTRAINT FK_LOG_VISITOR_CUSTOMER_ID_CUSTOMER_ENTITY_ID FOREIGN KEY (`customer_id`) REFERENCES `customer_entity` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_LOG_VISITOR_STORE_ID_CORE_STORE_ID FOREIGN KEY (`store_id`) REFERENCES `core_store` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_LOG_VISITOR_PRODUCT_ID_PRODUCT_ENTITY_ID FOREIGN KEY (`product_id`) REFERENCES `product_entity` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `retailer`(
    `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `store_id` INTEGER UNSIGNED NULL DEFAULT NULL,
    `address` TEXT,
    `tel` VARCHAR(20) DEFAULT NULL,
    `uri_key` VARCHAR(50) NOT NULL,
    `contact` TEXT,
    `description` TEXT,
    `keywords` TEXT,
    `profile` MEDIUMBLOB NULL DEFAULT NULL,
    `watermark` MEDIUMBLOB NULL DEFAULT NULL,
    `banner` INTEGER UNSIGNED NULL DEFAULT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    INDEX IDX_RETAILER_BANNER (`banner`),
    CONSTRAINT UNQ_RETAILER_URI_KEY UNIQUE (`uri_key`),
    CONSTRAINT UNQ_RETAILER_STORE_ID UNIQUE (`store_id`),
    CONSTRAINT FK_RETAILER_STORE_ID_CORE_STORE_ID FOREIGN KEY (`store_id`) REFERENCES `core_store` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_RETAILER_BANNER_RESOURCE_ID FOREIGN KEY (`banner`) REFERENCES `resource` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `retailer_manager`(
    `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `customer_id` INTEGER UNSIGNED NOT NULL,
    `retailer_id` INTEGER UNSIGNED NOT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    INDEX IDX_RETAILER_MANAGER_RETAILER_ID (`retailer_id`),
    CONSTRAINT UNQ_RETAILER_MANAGER_CUSTOMER_ID UNIQUE (`customer_id`),
    CONSTRAINT FK_RETAILER_MANAGER_CUSTOMER_ID_CUSTOMER_ENTITY_ID FOREIGN KEY (`customer_id`) REFERENCES `customer_entity` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_RETAILER_MANAGER_RETAILER_RETAILER_ID FOREIGN KEY (`retailer_id`) REFERENCES `retailer` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `retailer_application`(
    `customer_id` INTEGER UNSIGNED NOT NULL,
    `lisence_1` MEDIUMBLOB,
    `lisence_2` MEDIUMBLOB,
    `phone` VARCHAR(20) NOT NULL,
    `brand_type` BOOLEAN NOT NULL,
    `product_type` VARCHAR(255) NOT NULL,
    `status` BOOLEAN DEFAULT 0,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`customer_id`),
    CONSTRAINT FK_RETAILER_APPLICATION_CUSTOMER_ID_CUSTOMER_ENTITY_ID FOREIGN KEY (`customer_id`) REFERENCES `customer_entity` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `persistent`(
    `customer_id` INTEGER UNSIGNED NOT NULL,
    `key` CHAR(32) NOT NULL,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`customer_id`),
    INDEX IDX_PERSISTENT_CUSTOMER_ID (`customer_id`),
    CONSTRAINT UNQ_PERSISTENT_KEY UNIQUE (`key`),
    CONSTRAINT FK_PERSISTENT_CUSTOMER_ID_CUSTOMER_ENTITY_ID FOREIGN KEY (`customer_id`) REFERENCES `customer_entity` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `sales_rma` (
    `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `order_id` INTEGER UNSIGNED NOT NULL,
    `customer_id` INTEGER UNSIGNED NULL DEFAULT NULL,
    `service` INTEGER NOT NULL DEFAULT 0,
    `currency` CHAR(3) NULL DEFAULT NULL,
    `amount` DECIMAL(12,4) NULL DEFAULT NULL,
    `reason` INTEGER UNSIGNED NOT NULL,
    `status` INTEGER NULL DEFAULT 0,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    INDEX IDX_SALES_RMA_ORDER_ID (`order_id`),
    INDEX IDX_SALES_RMA_CUSTOMER_ID (`customer_id`),
    INDEX IDX_SALES_RMA_STATUS (`status`),
    CONSTRAINT FK_SALES_RMA_ORDER_ID_SALES_ORDER_ID FOREIGN KEY (`order_id`) REFERENCES `sales_order` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_SALES_RMA_CUSTOMER_ID_CUSTOMER_ENTITY_ID FOREIGN KEY (`customer_id`) REFERENCES `customer_entity` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `sales_rma_item`(
    `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `rma_id` INTEGER UNSIGNED NOT NULL,
    `item_id` INTEGER UNSIGNED NOT NULL,
    `qty` DECIMAL(12,4) NOT NULL,
    PRIMARY KEY (`id`),
    INDEX IDX_SALES_RMA_ITEM_RMA_ID (`rma_id`),
    INDEX IDX_SALES_RMA_ITEM_ITEM_ID (`item_id`),
    CONSTRAINT FK_SALES_RMA_ITEM_ITEM_ID_SALES_ORDER_ITEM_ID FOREIGN KEY (`item_id`) REFERENCES `sales_order_item` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_SALES_RMA_ITEM_RMA_ID_SALES_RMA_ID FOREIGN KEY (`rma_id`) REFERENCES `sales_rma` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `promotion`(
    `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(255) NOT NULL,
    `description` TEXT,
    `use_coupon` BOOLEAN NOT NULL DEFAULT 0,
    `uses_per_coupon` INTEGER UNSIGNED NOT NULL DEFAULT 0,
    `uses_per_customer` INTEGER UNSIGNED NOT NULL DEFAULT 0,
    `from_date` TIMESTAMP NULL DEFAULT NULL,
    `to_date` TIMESTAMP NULL DEFAULT NULL,
    `qty` DECIMAL(12,4) DEFAULT 0,
    `price` DECIMAL(12,4) NOT NULL DEFAULT 0,
    `is_fixed` BOOLEAN NOT NULL DEFAULT 1,
    `per_item` BOOLEAN NOT NULL DEFAULT 1,
    `free_shipping` BOOLEAN NOT NULL DEFAULT 0,
    `apply_to` BOOLEAN NOT NULL DEFAULT 0,
    `stop_processing` BOOLEAN DEFAULT 0,
    `status` BOOLEAN NOT NULL DEFAULT 1,
    `sort_order` INTEGER NOT NULL DEFAULT 0,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    INDEX IDX_PROMOTION_SORT_ORDER (`sort_order`)
);

CREATE TABLE IF NOT EXISTS `promotion_in_store`(
    `promotion_id` INTEGER UNSIGNED NOT NULL,
    `store_id` INTEGER UNSIGNED NOT NULL,
    PRIMARY KEY (`promotion_id`,`store_id`),
    INDEX IDX_PROMOTION_STORE_ID (`store_id`),
    CONSTRAINT FK_PROMOTION_IN_STORE_PROMOTION_ID_PROMOTION_ID FOREIGN KEY (`promotion_id`) REFERENCES `promotion` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_PROMOTION_IN_STORE_STORE_ID_CORE_STORE_ID FOREIGN KEY (`store_id`) REFERENCES `core_store` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `promotion_condition`(
    `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `promotion_id` INTEGER UNSIGNED NOT NULL,
    `parent_id` INTEGER UNSIGNED NULL DEFAULT NULL,
    `identifier` VARCHAR(50) NOT NULL,
    `operator` VARCHAR(20) NOT NULL,
    `value` VARCHAR(255) NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    INDEX IDX_PROMOTION_CONDITION_PROMOTION_ID (`promotion_id`),
    INDEX IDX_PROMOTION_CONDITION_PARENT_ID (`parent_id`),
    CONSTRAINT FK_PROMOTION_CONDITION_PROMOTION_ID_PROMOTION_ID FOREIGN KEY (`promotion_id`) REFERENCES `promotion` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_PROMOTION_CONDITION_PARENT_ID_PROMOTION_CONDITION_ID FOREIGN KEY (`parent_id`) REFERENCES `promotion_condition` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `promotion_handler`(
    `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `promotion_id` INTEGER UNSIGNED NOT NULL,
    `parent_id` INTEGER UNSIGNED NULL DEFAULT NULL,
    `identifier` VARCHAR(50) NOT NULL,
    `operator` VARCHAR(20) NOT NULL,
    `value` VARCHAR(255) NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    INDEX IDX_HANDLER_CONDITION_PROMOTION_ID (`promotion_id`),
    INDEX IDX_HANDLER_CONDITION_PARENT_ID (`parent_id`),
    CONSTRAINT FK_HANDLER_CONDITION_PROMOTION_ID_PROMOTION_ID FOREIGN KEY (`promotion_id`) REFERENCES `promotion` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_HANDLER_CONDITION_PARENT_ID_PROMOTION_HANDLER_ID FOREIGN KEY (`parent_id`) REFERENCES `promotion_handler` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `promotion_coupon`(
    `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `code` VARCHAR(50) NOT NULL,
    `promotion_id` INTEGER UNSIGNED NOT NULL,
    `status` BOOLEAN NOT NULL DEFAULT 1,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `expired_at` TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    INDEX IDX_PROMOTION_COUPON_PROMOTION_ID (`promotion_id`),
    INDEX IDX_PROMOTION_COUPON_STATUS (`status`),
    CONSTRAINT UNQ_PROMOTION_COUPON_CODE UNIQUE (`code`),
    CONSTRAINT FK_PROMOTION_COUPON_PROMOTION_ID FOREIGN KEY (`promotion_id`) REFERENCES `promotion` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `promotion_coupon_apply`(
    `coupon_id` INTEGER UNSIGNED NOT NULL,
    `customer_id` INTEGER UNSIGNED NOT NULL,
    PRIMARY KEY (`coupon_id`,`customer_id`),
    INDEX IDX_PROMOTION_COUPON_APPLY_CUSTOMER_ID (`customer_id`),
    CONSTRAINT FK_PROMOTION_COUPON_APPLY_COUPON_ID_PROMOTION_COUPON_ID FOREIGN KEY (`coupon_id`) REFERENCES `promotion_coupon` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_PROMOTION_COUPON_APPLY_CUSTOMER_ID_CUSTOMER_ENTITY_ID FOREIGN KEY (`customer_id`) REFERENCES `customer_entity` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `promotion_coupon_log`(
    `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `coupon_id` INTEGER UNSIGNED NOT NULL,
    `order_id` INTEGER UNSIGNED NOT NULL,
    `customer_id` INTEGER UNSIGNED NULL DEFAULT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    INDEX IDX_PROMOTION_COUPON_LOG_COUPON_ID (`coupon_id`),
    INDEX IDX_PROMOTION_COUPON_LOG_ORDER_ID (`order_id`),
    INDEX IDX_PROMOTION_COUPON_LOG_CUSTOMER_ID (`customer_id`),
    CONSTRAINT FK_PROMOTION_COUPON_LOG_COUPON_ID_PROMOTION_COUPON_ID FOREIGN KEY (`coupon_id`) REFERENCES `promotion_coupon` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_PROMOTION_COUPON_LOG_ORDER_ID_SALES_ORDER_ID FOREIGN KEY (`order_id`) REFERENCES `sales_order` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_PROMOTION_COUPON_LOG_CUSTOMER_ID_CUSTOMER_ENTITY_ID FOREIGN KEY (`customer_id`) REFERENCES `customer_entity` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `reward_points`(
    `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `customer_id` INTEGER UNSIGNED NOT NULL,
    `order_id` INTEGER UNSIGNED NULL DEFAULT NULL,
    `count` DECIMAL(12,4) NOT NULL,
    `comment` TEXT,
    `status` DECIMAL(1,0) DEFAULT 1 NOT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    INDEX IDX_REWARD_POINTS_CUSTOMER_ID (`customer_id`),
    INDEX IDX_REWARD_POINTS_ORDER_ID (`order_id`),
    INDEX IDX_REWARD_POINTS_STATUS (`status`),
    CONSTRAINT FK_REWARD_POINTS_CUSTOMER_ID_CUSTOMER_ENTITY_ID FOREIGN KEY (`customer_id`) REFERENCES `customer_entity` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_REWARD_POINTS_ORDER_ID_SALES_ORDER_ID FOREIGN KEY (`order_id`) REFERENCES `sales_order` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
);

INSERT INTO `eav_attribute` VALUES 
(46,1,'rewardpoints','int','hidden','',0,'0',0,NULL,NULL,0,0,0,0,NULL,NULL),
(47,4,'can_use_reward_points','varchar','bool','',0,'1',0,NULL,NULL,0,0,0,0,NULL,NULL),
(48,4,'reward_points','int','tel','',0,NULL,0,NULL,NULL,0,0,0,0,NULL,NULL);
INSERT INTO `eav_entity_attribute` VALUES 
(1, 1, 46, 0),
(4, 6, 47, 0),
(4, 6, 48, 0);
INSERT INTO `eav_attribute_label` VALUES
(46, 1, 'Reward Points'),
(47, 1, 'Can Use Reward Points'),
(48, 1, 'Reward Points');

CREATE TABLE IF NOT EXISTS `customer_balance`(
    `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `customer_id` INTEGER UNSIGNED NOT NULL,
    `amount` DECIMAL(12,4) NOT NULL,
    `comment` TEXT,
    `status` BOOLEAN DEFAULT 1 NOT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    INDEX IDX_CUSTOMER_ACCOUNT_CUSTOMER_ID (`customer_id`),
    CONSTRAINT FK_CUSTOMER_ACCOUNT_CUSTOMER_ID_CUSTOMER_ENTITY_ID FOREIGN KEY (`customer_id`) REFERENCES `customer_entity` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `store_decoration_template` (
    `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `store_id` INTEGER UNSIGNED NOT NULL,
    `stable_params` TEXT,
    `template_name` VARCHAR(255) NOT NULL DEFAULT '',
    `code_model` TEXT,
    `src_model` TEXT,
    `parent_id` INTEGER DEFAULT 0,
    `page_type` INTEGER DEFAULT 0,
    `status` BOOLEAN DEFAULT 0,
    PRIMARY KEY (`id`),
    INDEX IDX_STORE_DECORATION_TEMPLATE_STORE_ID (`store_id`),
    CONSTRAINT FK_STORE_DECORATION_TEMPLATE_STORE_ID FOREIGN KEY (`store_id`) REFERENCES `core_store` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `store_decoration_picinfo` (
    `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `store_id` INTEGER UNSIGNED NOT NULL,
    `resource_id` INTEGER UNSIGNED NULL DEFAULT NULL,
    `pic_title` VARCHAR(255) DEFAULT NULL,
    `url` VARCHAR(255) DEFAULT NULL,
    `resource_category_code` VARCHAR(255) NOT NULL,
    `template_id` INTEGER DEFAULT NULL,
    `part_id` VARCHAR(200) DEFAULT NULL,
    `sort_order` INTEGER DEFAULT NULL,
    PRIMARY KEY (`id`),
    INDEX IDX_STORE_DECORATION_PICINFO_STORE_ID (`store_id`),
    INDEX IDX_STORE_DECORATION_PICINFO_RESOURCE_ID (`resource_id`),
    INDEX IDX_STORE_DECORATION_PICINFO_SORT_ORDER (`sort_order`),
    CONSTRAINT FK_STORE_DECORATION_PICINFO_STORE_ID_CORE_STORE_ID FOREIGN KEY (`store_id`) REFERENCES `core_store` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_STORE_DECORATION_PICINFO_RESOURCE_ID_RESOURCE_ID FOREIGN KEY (`resource_id`) REFERENCES `resource` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `retailer_category` (
    `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `parent_id` INTEGER UNSIGNED DEFAULT NULL,
    `store_id` INTEGER UNSIGNED NOT NULL,
    `uri_key` VARCHAR(50) NOT NULL,
    `default_name` VARCHAR(255) DEFAULT '',
    `sort_order` INTEGER DEFAULT 0,
    PRIMARY KEY (`id`),
    INDEX IDX_RETAILER_CATEGORY_PARENT_ID (`parent_id`),
    INDEX IDX_RETAILER_CATEGORY_SORT_ORDER (`sort_order`),
    CONSTRAINT UNQ_RETAILER_CATEGORY_STORE_ID_URI_KEY UNIQUE (`store_id`,`uri_key`),
    CONSTRAINT FK_RETAILER_CATEGORY_PARENT_ID_RETAILER_CATEGORY_ID FOREIGN KEY (`parent_id`) REFERENCES `retailer_category` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_RETAILER_CATEGORY_STORE_ID_CORE_STORE_ID FOREIGN KEY (`store_id`) REFERENCES `core_store` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `retailer_category_name` (
    `category_id` INTEGER UNSIGNED NOT NULL,
    `language_id` INTEGER UNSIGNED NOT NULL,
    `name` VARCHAR(255) DEFAULT '',
    PRIMARY KEY (`category_id`,`language_id`),
    INDEX IDX_RETAILER_CATEGORY_NAME_CATEGORY_ID (`category_id`),
    CONSTRAINT FK_RETAILER_CATEGORY_NAME_CATEGORY_ID_RETAILER_CATEGORY_ID FOREIGN KEY (`category_id`) REFERENCES `retailer_category` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_RETAILER_CATEGORY_NAME_LANGUAGE_ID_CORE_LANGUAGE_ID FOREIGN KEY (`language_id`) REFERENCES `core_language` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `retailer_category_with_product` (
    `category_id` INTEGER UNSIGNED NOT NULL,
    `product_id` INTEGER UNSIGNED NOT NULL,
    PRIMARY KEY (`category_id`,`product_id`),
    INDEX IDX_RETAILER_CAT_WITH_PRO_PRODUCT_ID (`product_id`),
    CONSTRAINT FK_RETAILER_CAT_PRO_CATEGORY_ID_RETAILER_CATEGORY_ID FOREIGN KEY (`category_id`) REFERENCES `retailer_category` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_RETAILER_CAT_PRO_PRODUCT_ID_PRODUCT_ENTITY_ID FOREIGN KEY (`product_id`) REFERENCES `product_entity` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `customer_credit_card` (
    `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `customer_id` INTEGER UNSIGNED NULL DEFAULT NULL,
    `name` VARCHAR(255) NOT NULL,
    `type` VARCHAR(255) NOT NULL,
    `number` VARCHAR(255) NOT NULL,
    `exp_month` SMALLINT NOT NULL,
    `exp_year` SMALLINT NOT NULL,
    `verification` VARCHAR(10) NOT NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    INDEX IDX_CUSTOMER_CREDIT_CARD_CUSTOMER_ID (`customer_id`),
    CONSTRAINT CHK_CUSTOMER_CREDIT_CARD_EXP_MONTH CHECK (`exp_month` > 0 AND `exp_month` < 13),
    CONSTRAINT FK_CUSTOMER_CREDIT_CARD_CUSTOMER_ID_CUSTOMER_ENTITY_ID FOREIGN KEY (`customer_id`) REFERENCES `customer_entity` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `log_payment` (
    `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `order_id` INTEGER UNSIGNED NOT NULL,
    `trade_id` VARCHAR(255) NOT NULL,
    `method` VARCHAR(255) NOT NULL,
    `params` TEXT,
    `comment` TEXT,
    `is_request` BOOLEAN DEFAULT 0,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    INDEX IDX_LOG_PAYMENT_ORDER_ID (`order_id`),
    INDEX IDX_LOG_PAYMENT_TRADE_ID (`trade_id`),
    CONSTRAINT FK_LOG_PAYMENT_ORDER_ID_SALES_ORDER_ID FOREIGN KEY (`order_id`) REFERENCES `sales_order` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `log_rma` (
    `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `rma_id` INTEGER UNSIGNED NOT NULL,
    `is_customer` BOOLEAN NOT NULL DEFAULT 0,
    `comment` BLOB,
    `image` TEXT,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    INDEX IDX_LOG_RMA_RMA_ID (`rma_id`),
    CONSTRAINT FK_LOG_RMA_RMA_ID_SALES_RMA_ID FOREIGN KEY (`rma_id`) REFERENCES `sales_rma` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `livechat_session` (
    `id` VARCHAR(255) NOT NULL,
    `name` VARCHAR(255) NOT NULL,
    `info` TEXT,
    `status` BOOLEAN,
    PRIMARY KEY(`id`)
);

CREATE TABLE IF NOT EXISTS `livechat_record` (
    `from` VARCHAR(255) NOT NULL,
    `to` VARCHAR(255) NOT NULL,
    `type` VARCHAR(50) NOT NULL,
    `message` BLOB,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

SET FOREIGN_KEY_CHECKS=1;
