CREATE TABLE IF NOT EXISTS `art_category_entity` (
    `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `type_id` INTEGER UNSIGNED NOT NULL DEFAULT 3,
    `parent_id` INTEGER UNSIGNED NULL DEFAULT NULL,
    `attribute_set_id` INTEGER UNSIGNED NOT NULL,
    `sort_order` INTEGER DEFAULT 0,
    `status` BOOLEAN DEFAULT 1,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    INDEX IDX_ART_CATEGORY_ENTITY_PARENT_ID (`parent_id`),
    INDEX IDX_ART_CATEGORY_ENTITY_TYPE_ID (`type_id`),
    INDEX IDX_ART_CATEGORY_ENTITY_ATTRIBUTE_SET_ID (`attribute_set_id`),
    CONSTRAINT FK_ART_CATEGORY_ENTITY_PARENT_ID_ART_CATEGORY_ENTITY_ID FOREIGN KEY (`parent_id`) REFERENCES `art_category_entity`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_ART_CATEGORY_ENTITY_TYPE_ID_EAV_ENTITY_TYPE_ID FOREIGN KEY (`type_id`) REFERENCES `eav_entity_type`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_ART_CATEGORY_ENTITY_ATTR_SET_ID_EAV_ATTR_SET_ID FOREIGN KEY (`attribute_set_id`) REFERENCES `eav_attribute_set`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `art_category_value_int` (
    `attribute_id` INTEGER UNSIGNED NOT NULL,
    `language_id` INTEGER UNSIGNED NOT NULL,
    `entity_id` INTEGER UNSIGNED NOT NULL,
    `value` INTEGER NOT NULL,
    `updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`attribute_id`,`language_id`,`entity_id`),
    INDEX IDX_ART_CATEGORY_VALUE_INT_LANGUAGE_ID (`language_id`),
    INDEX IDX_ART_CATEGORY_VALUE_INT_ENTITY_ID (`entity_id`),
    INDEX IDX_ART_CATEGORY_VALUE_INT_ATTR_ID_VALUE (`attribute_id`,`value`),
    INDEX IDX_ART_CATEGORY_VALUE_INT_ENTITY_ID_VALUE (`entity_id`,`value`),
    CONSTRAINT FK_ART_CATEGORY_VALUE_INT_ATTR_ID_EAV_ATTR_ID FOREIGN KEY (`attribute_id`) REFERENCES `eav_attribute`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_ART_CATEGORY_VALUE_INT_LANGUAGE_ID_CORE_LANGUAGE_ID FOREIGN KEY (`language_id`) REFERENCES `core_language`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_ART_CATEGORY_VALUE_INT_ENTITY_ID_ART_CATEGORY_ENTITY_ID FOREIGN KEY (`entity_id`) REFERENCES `art_category_entity`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `art_category_value_datetime` (
    `attribute_id` INTEGER UNSIGNED NOT NULL,
    `language_id` INTEGER UNSIGNED NOT NULL,
    `entity_id` INTEGER UNSIGNED NOT NULL,
    `value` TIMESTAMP NOT NULL,
    `updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`attribute_id`,`language_id`,`entity_id`),
    INDEX IDX_ART_CATEGORY_VALUE_DATETIME_LANGUAGE_ID (`language_id`),
    INDEX IDX_ART_CATEGORY_VALUE_DATETIME_ENTITY_ID (`entity_id`),
    INDEX IDX_ART_CATEGORY_VALUE_DATETIME_ATTR_ID_VALUE (`attribute_id`,`value`),
    INDEX IDX_ART_CATEGORY_VALUE_DATETIME_ENTITY_ID_VALUE (`entity_id`,`value`),
    CONSTRAINT FK_ART_CATEGORY_VALUE_DATETIME_ATTR_ID_EAV_ATTR_ID FOREIGN KEY (`attribute_id`) REFERENCES `eav_attribute`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_ART_CATEGORY_VALUE_DATETIME_LANGUAGE_ID_CORE_LANGUAGE_ID FOREIGN KEY (`language_id`) REFERENCES `core_language`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_ART_CATEGORY_VALUE_DATETIME_ENTITY_ID_ARTICLE_ENTITY_ID FOREIGN KEY (`entity_id`) REFERENCES `art_category_entity`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `art_category_value_decimal` (
    `attribute_id` INTEGER UNSIGNED NOT NULL,
    `language_id` INTEGER UNSIGNED NOT NULL,
    `entity_id` INTEGER UNSIGNED NOT NULL,
    `value` DECIMAL(12,4) NOT NULL,
    `updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`attribute_id`,`language_id`,`entity_id`),
    INDEX IDX_ART_CATEGORY_VALUE_DECIMAL_LANGUAGE_ID (`language_id`),
    INDEX IDX_ART_CATEGORY_VALUE_DECIMAL_ENTITY_ID (`entity_id`),
    INDEX IDX_ART_CATEGORY_VALUE_DECIMAL_ATTR_ID_VALUE (`attribute_id`,`value`),
    INDEX IDX_ART_CATEGORY_VALUE_DECIMAL_ENTITY_ID_VALUE (`entity_id`,`value`),
    CONSTRAINT FK_ART_CATEGORY_VALUE_DECIMAL_ATTR_ID_EAV_ATTR_ID FOREIGN KEY (`attribute_id`) REFERENCES `eav_attribute`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_ART_CATEGORY_VALUE_DECIMAL_LANGUAGE_ID_CORE_LANGUAGE_ID FOREIGN KEY (`language_id`) REFERENCES `core_language`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_ART_CATEGORY_VALUE_DECIMAL_ENTITY_ID_ARTICLE_ENTITY_ID FOREIGN KEY (`entity_id`) REFERENCES `art_category_entity`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `art_category_value_varchar` (
    `attribute_id` INTEGER UNSIGNED NOT NULL,
    `language_id` INTEGER UNSIGNED NOT NULL,
    `entity_id` INTEGER UNSIGNED NOT NULL,
    `value` VARCHAR(255) NOT NULL,
    `updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`attribute_id`,`language_id`,`entity_id`),
    INDEX IDX_ART_CATEGORY_VALUE_VARCHAR_LANGUAGE_ID (`language_id`),
    INDEX IDX_ART_CATEGORY_VALUE_VARCHAR_ENTITY_ID (`entity_id`),
    INDEX IDX_ART_CATEGORY_VALUE_VARCHAR_ATTR_ID_VALUE (`attribute_id`,`value`),
    INDEX IDX_ART_CATEGORY_VALUE_VARCHAR_ENTITY_ID_VALUE (`entity_id`,`value`),
    CONSTRAINT FK_ART_CATEGORY_VALUE_VARCHAR_ATTR_ID_EAV_ATTR_ID FOREIGN KEY (`attribute_id`) REFERENCES `eav_attribute`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_ART_CATEGORY_VALUE_VARCHAR_LANGUAGE_ID_CORE_LANGUAGE_ID FOREIGN KEY (`language_id`) REFERENCES `core_language`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_ART_CATEGORY_VALUE_VARCHAR_ENTITY_ID_ARTICLE_ENTITY_ID FOREIGN KEY (`entity_id`) REFERENCES `art_category_entity`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `art_category_value_text` (
    `attribute_id` INTEGER UNSIGNED NOT NULL,
    `language_id` INTEGER UNSIGNED NOT NULL,
    `entity_id` INTEGER UNSIGNED NOT NULL,
    `value` MEDIUMTEXT NOT NULL,
    `updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`attribute_id`,`language_id`,`entity_id`),
    INDEX IDX_ART_CATEGORY_VALUE_TEXT_LANGUAGE_ID (`language_id`),
    INDEX IDX_ART_CATEGORY_VALUE_TEXT_ENTITY_ID (`entity_id`),
    CONSTRAINT FK_ART_CATEGORY_VALUE_TEXT_ATTR_ID_EAV_ATTR_ID FOREIGN KEY (`attribute_id`) REFERENCES `eav_attribute`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_ART_CATEGORY_VALUE_TEXT_LANGUAGE_ID_CORE_LANGUAGE_ID FOREIGN KEY (`language_id`) REFERENCES `core_language`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_ART_CATEGORY_VALUE_TEXT_ENTITY_ID_ARTICLE_ENTITY_ID FOREIGN KEY (`entity_id`) REFERENCES `art_category_entity`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE IF NOT EXISTS `article_entity` (
    `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `type_id` INTEGER UNSIGNED NOT NULL DEFAULT 3,
    `attribute_set_id` INTEGER UNSIGNED NOT NULL,
    `status` BOOLEAN DEFAULT 1,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    INDEX IDX_ARTICLE_ENTITY_TYPE_ID (`type_id`),
    INDEX IDX_ARTICLE_ENTITY_ATTRIBUTE_SET_ID (`attribute_set_id`),
    CONSTRAINT FK_ARTICLE_ENTITY_TYPE_ID_EAV_ENTITY_TYPE_ID FOREIGN KEY (`type_id`) REFERENCES `eav_entity_type`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_ARTICLE_ENTITY_ATTR_SET_ID_EAV_ATTR_SET_ID FOREIGN KEY (`attribute_set_id`) REFERENCES `eav_attribute_set`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `article_value_int` (
    `attribute_id` INTEGER UNSIGNED NOT NULL,
    `language_id` INTEGER UNSIGNED NOT NULL,
    `entity_id` INTEGER UNSIGNED NOT NULL,
    `value` INTEGER NOT NULL,
    `updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`attribute_id`,`language_id`,`entity_id`),
    INDEX IDX_ARTICLE_VALUE_INT_LANGUAGE_ID (`language_id`),
    INDEX IDX_ARTICLE_VALUE_INT_ENTITY_ID (`entity_id`),
    INDEX IDX_ARTICLE_VALUE_INT_ATTR_ID_VALUE (`attribute_id`,`value`),
    INDEX IDX_ARTICLE_VALUE_INT_ENTITY_ID_VALUE (`entity_id`,`value`),
    CONSTRAINT FK_ARTICLE_VALUE_INT_ATTR_ID_EAV_ATTR_ID FOREIGN KEY (`attribute_id`) REFERENCES `eav_attribute`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_ARTICLE_VALUE_INT_LANGUAGE_ID_CORE_LANGUAGE_ID FOREIGN KEY (`language_id`) REFERENCES `core_language`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_ARTICLE_VALUE_INT_ENTITY_ID_ARTICLE_ENTITY_ID FOREIGN KEY (`entity_id`) REFERENCES `article_entity`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `article_value_datetime` (
    `attribute_id` INTEGER UNSIGNED NOT NULL,
    `language_id` INTEGER UNSIGNED NOT NULL,
    `entity_id` INTEGER UNSIGNED NOT NULL,
    `value` TIMESTAMP NOT NULL,
    `updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`attribute_id`,`language_id`,`entity_id`),
    INDEX IDX_ARTICLE_VALUE_DATETIME_LANGUAGE_ID (`language_id`),
    INDEX IDX_ARTICLE_VALUE_DATETIME_ENTITY_ID (`entity_id`),
    INDEX IDX_ARTICLE_VALUE_DATETIME_ATTR_ID_VALUE (`attribute_id`,`value`),
    INDEX IDX_ARTICLE_VALUE_DATETIME_ENTITY_ID_VALUE (`entity_id`,`value`),
    CONSTRAINT FK_ARTICLE_VALUE_DATETIME_ATTR_ID_EAV_ATTR_ID FOREIGN KEY (`attribute_id`) REFERENCES `eav_attribute`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_ARTICLE_VALUE_DATETIME_LANGUAGE_ID_CORE_LANGUAGE_ID FOREIGN KEY (`language_id`) REFERENCES `core_language`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_ARTICLE_VALUE_DATETIME_ENTITY_ID_ARTICLE_ENTITY_ID FOREIGN KEY (`entity_id`) REFERENCES `article_entity`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `article_value_decimal` (
    `attribute_id` INTEGER UNSIGNED NOT NULL,
    `language_id` INTEGER UNSIGNED NOT NULL,
    `entity_id` INTEGER UNSIGNED NOT NULL,
    `value` DECIMAL(12,4) NOT NULL,
    `updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`attribute_id`,`language_id`,`entity_id`),
    INDEX IDX_ARTICLE_VALUE_DECIMAL_LANGUAGE_ID (`language_id`),
    INDEX IDX_ARTICLE_VALUE_DECIMAL_ENTITY_ID (`entity_id`),
    INDEX IDX_ARTICLE_VALUE_DECIMAL_ATTR_ID_VALUE (`attribute_id`,`value`),
    INDEX IDX_ARTICLE_VALUE_DECIMAL_ENTITY_ID_VALUE (`entity_id`,`value`),
    CONSTRAINT FK_ARTICLE_VALUE_DECIMAL_ATTR_ID_EAV_ATTR_ID FOREIGN KEY (`attribute_id`) REFERENCES `eav_attribute`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_ARTICLE_VALUE_DECIMAL_LANGUAGE_ID_CORE_LANGUAGE_ID FOREIGN KEY (`language_id`) REFERENCES `core_language`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_ARTICLE_VALUE_DECIMAL_ENTITY_ID_ARTICLE_ENTITY_ID FOREIGN KEY (`entity_id`) REFERENCES `article_entity`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `article_value_varchar` (
    `attribute_id` INTEGER UNSIGNED NOT NULL,
    `language_id` INTEGER UNSIGNED NOT NULL,
    `entity_id` INTEGER UNSIGNED NOT NULL,
    `value` VARCHAR(255) NOT NULL,
    `updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`attribute_id`,`language_id`,`entity_id`),
    INDEX IDX_ARTICLE_VALUE_VARCHAR_LANGUAGE_ID (`language_id`),
    INDEX IDX_ARTICLE_VALUE_VARCHAR_ENTITY_ID (`entity_id`),
    INDEX IDX_ARTICLE_VALUE_VARCHAR_ATTR_ID_VALUE (`attribute_id`,`value`),
    INDEX IDX_ARTICLE_VALUE_VARCHAR_ENTITY_ID_VALUE (`entity_id`,`value`),
    CONSTRAINT FK_ARTICLE_VALUE_VARCHAR_ATTR_ID_EAV_ATTR_ID FOREIGN KEY (`attribute_id`) REFERENCES `eav_attribute`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_ARTICLE_VALUE_VARCHAR_LANGUAGE_ID_CORE_LANGUAGE_ID FOREIGN KEY (`language_id`) REFERENCES `core_language`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_ARTICLE_VALUE_VARCHAR_ENTITY_ID_ARTICLE_ENTITY_ID FOREIGN KEY (`entity_id`) REFERENCES `article_entity`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `article_value_text` (
    `attribute_id` INTEGER UNSIGNED NOT NULL,
    `language_id` INTEGER UNSIGNED NOT NULL,
    `entity_id` INTEGER UNSIGNED NOT NULL,
    `value` MEDIUMTEXT NOT NULL,
    `updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`attribute_id`,`language_id`,`entity_id`),
    INDEX IDX_ARTICLE_VALUE_TEXT_LANGUAGE_ID (`language_id`),
    INDEX IDX_ARTICLE_VALUE_TEXT_ENTITY_ID (`entity_id`),
    CONSTRAINT FK_ARTICLE_VALUE_TEXT_ATTR_ID_EAV_ATTR_ID FOREIGN KEY (`attribute_id`) REFERENCES `eav_attribute`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_ARTICLE_VALUE_TEXT_LANGUAGE_ID_CORE_LANGUAGE_ID FOREIGN KEY (`language_id`) REFERENCES `core_language`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_ARTICLE_VALUE_TEXT_ENTITY_ID_ARTICLE_ENTITY_ID FOREIGN KEY (`entity_id`) REFERENCES `article_entity`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `article_option` (
    `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `article_id` INTEGER UNSIGNED NOT NULL,
    `input` VARCHAR(11) NOT NULL,
    `is_required` BOOLEAN DEFAULT 0,
    `sku` VARCHAR(255) DEFAULT '',
    `price` DECIMAL(12,4) DEFAULT 0,
    `is_fixed` BOOLEAN DEFAULT 1,
    `sort_order` INTEGER DEFAULT 0,
    PRIMARY KEY (`id`),
    INDEX IDX_ARTICLE_OPTION_ARTICLE_ID (`article_id`),
    INDEX IDX_ARTICLE_OPTION_SORT_ORDER (`sort_order`),
    CONSTRAINT FK_ARTICLE_OPTION_ARTICLE_ID_ARTICLE_ENTITY_ID FOREIGN KEY (`article_id`) REFERENCES `article_entity`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `article_option_title` (
    `option_id` INTEGER UNSIGNED NOT NULL,
    `language_id` INTEGER UNSIGNED NOT NULL,
    `title` VARCHAR(255) DEFAULT '',
    PRIMARY KEY (`option_id`,`language_id`),
    INDEX IDX_ARTICLE_OPTION_TITLE_LANGUAGE_ID (`language_id`),
    CONSTRAINT FK_ARTICLE_OPTION_TITLE_OPTION_ID_ARTICLE_OPTION_ID FOREIGN KEY (`option_id`) REFERENCES `article_option`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_ARTICLE_OPTION_TITLE_OPTION_ID_CORE_LANGUAGE_ID FOREIGN KEY (`language_id`) REFERENCES `core_language`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `article_option_value` (
    `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `option_id` INTEGER UNSIGNED NOT NULL,
    `sku` VARCHAR(255) DEFAULT '',
    `price` DECIMAL(12,4) DEFAULT 0,
    `is_fixed` BOOLEAN DEFAULT 1,
    `sort_order` INTEGER DEFAULT 0,
    PRIMARY KEY (`id`),
    INDEX IDX_ARTICLE_OPTION_VALUE_OPTION_ID (`option_id`),
    INDEX IDX_ARTICLE_OPTION_VALUE_SORT_ORDER (`sort_order`),
    CONSTRAINT FK_ARTICLE_OPTION_VALUE_OPTION_ID_ARTICLE_OPTION_ID FOREIGN KEY (`option_id`) REFERENCES `article_option`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `article_option_value_title` (
    `value_id` INTEGER UNSIGNED NOT NULL,
    `language_id` INTEGER UNSIGNED NOT NULL,
    `title` VARCHAR(255) DEFAULT '',
    PRIMARY KEY (`value_id`,`language_id`),
    INDEX IDX_ARTICLE_OPTION_VALUE_TITLE_LANGUAGE_ID (`language_id`),
    CONSTRAINT FK_ARTICLE_OPTION_VALUE_TITLE_OPTION_ID_ARTICLE_VALUE_ID FOREIGN KEY (`value_id`) REFERENCES `article_option_value`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_ARTICLE_OPTION_VALUE_TITLE_OPTION_ID_CORE_LANGUAGE_ID FOREIGN KEY (`language_id`) REFERENCES `core_language`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `article_link` (
    `article_id` INTEGER UNSIGNED NOT NULL,
    `linked_article_id` INTEGER UNSIGNED NOT NULL,
    `type` CHAR(1) NOT NULL,
    `sort_order` INTEGER DEFAULT 0,
    PRIMARY KEY (`article_id`,`linked_article_id`,`type`),
    INDEX IDX_ARTICLE_LINK_LINKED_ARTICLE_ID (`linked_article_id`),
    INDEX IDX_ARTICLE_LINK_SORT_ORDER (`sort_order`),
    CONSTRAINT FK_ARTICLE_LINK_ARTICLE_ID_ARTICLE_ENTITY_ID FOREIGN KEY (`article_id`) REFERENCES `article_entity`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_ARTICLE_LINK_LINKED_ARTICLE_ID_ARTICLE_ENTITY_ID FOREIGN KEY (`linked_article_id`) REFERENCES `article_entity`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS `article_in_category` (
    `article_id` INTEGER UNSIGNED NOT NULL,
    `category_id` INTEGER UNSIGNED NOT NULL,
    `sort_order` INTEGER DEFAULT 0,
    PRIMARY KEY (`article_id`,`category_id`),
    INDEX IDX_ARTICLE_IN_CATEGORY_CATEGORY_ID (`category_id`),
    INDEX IDX_ARTICLE_IN_CATEGORY_SORT_ORDER (`sort_order`),
    CONSTRAINT FK_ARTICLE_IN_CATEGORY_ARTICLE_ID_ARTICLE_ENTITY_ID FOREIGN KEY (`article_id`) REFERENCES `article_entity`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_ARTICLE_IN_CATEGORY_ARTICLE_ID_ART_CATEGORY_ENTITY_ID FOREIGN KEY (`category_id`) REFERENCES `art_category_entity`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `article_review` (
    `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `article_id` INTEGER UNSIGNED NOT NULL,
    `customer_id` INTEGER UNSIGNED NULL DEFAULT NULL,
    `language_id` INTEGER UNSIGNED NULL DEFAULT NULL,
    `subject` VARCHAR(255) NULL DEFAULT NULL,
    `content` BLOB,
    `reply` BLOB,
    `images` TEXT,
    `anonymous` BOOLEAN DEFAULT 0,
    `status` BOOLEAN DEFAULT 0,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    INDEX IDX_ARTICLE_REVIEW_ARTICLE_ID (`article_id`),
    INDEX IDX_ARTICLE_REVIEW_CUSTOMER_ID (`customer_id`),
    INDEX IDX_ARTICLE_REVIEW_LANGUAGE_ID (`language_id`),
    INDEX IDX_ARTICLE_REVIEW_STATUS (`status`),
    CONSTRAINT FK_ARTICLE_REVIEW_ARTICLE_ID_ARTICLE_ENTITY_ID FOREIGN KEY (`article_id`) REFERENCES `article_entity`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_ARTICLE_REVIEW_CUSTOMER_ID_CUSTOMER_ENTITY_ID FOREIGN KEY (`customer_id`) REFERENCES `customer_entity`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_ARTICLE_REVIEW_LANGUAGE_ID_CORE_LANGUAGE_ID FOREIGN KEY (`language_id`) REFERENCES `core_language`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
);