<?php
$root = $this->getRootCategory();
?>
<!--=== Slider ===-->
<div class="slider-inner">
    <div class="da-slider" id="da-slider">
        <div class="da-slide">
            <h2><i>CLEAN &amp; FRESH</i><br />
                <i>FULLY RESPONSIVE</i><br />
                <i>DESIGN</i>
            </h2>
            <p><i>Lorem ipsum dolor amet</i><br />
                <i>tempor incididunt ut</i><br />
                <i>veniam omnis </i></p>
            <div class="da-img"><img alt="" src="<?php echo $this->getPubUrl('frontend/plugins/parallax-slider/img/1.png'); ?>" /></div>
        </div>
        <div class="da-slide">
            <h2><i>RESPONSIVE VIDEO</i><br />
                <i>SUPPORT AND</i><br />
                <i>MANY MORE</i></h2>
            <p><i>Lorem ipsum dolor amet</i><br />
                <i>tempor incididunt ut</i>
            </p>
        </div>
        <div class="da-slide">
            <h2><i>USING BEST WEB</i><br />
                <i>SOLUTIONS WITH</i><br />
                <i>HTML5/CSS3</i></h2>
            <p><i>Lorem ipsum dolor amet</i><br />
                <i>tempor incididunt ut</i><br />
                <i>veniam omnis </i></p>
            <div class="da-img"><img alt="image01" src="<?php echo $this->getPubUrl('frontend/plugins/parallax-slider/img/html5andcss3.png') ?>" /></div>
        </div>
        <nav class="da-arrows">
            <span class="da-arrows-prev"></span>
            <span class="da-arrows-next"></span>		
        </nav>
    </div>
    <!--/da-slider-->
</div>
<!--/slider-->
<!--=== End Slider ===-->
<!--=== Notice Block ===-->
<div class="row-fluid purchase margin-bottom-30">
    <div class="container">
        <div class="span10">
            <?php
            $categories = $this->getCategoryPage(8);
            if ($categories):
                $categories->limit(1)->order('created_at DESC');
                foreach ($categories as $category):
                    $url = $category->getUrl();
                    ?>
                    <h3><?php echo $category['title'] ?></h3>
                    <p><?php echo mb_substr(trim(strip_tags($category['content'])), 0, 100, 'utf-8') . '……' ?></p>
                </div>
                <a class="btn-buy hover-effect" href="<?php echo $this->getBaseUrl($url . '.html') ?>" target="_blank"><?php echo $this->translate('Entry notice'); ?></a>
                <?php
            endforeach;
        endif;
        ?>
    </div>
</div>
<!--/row-fluid-->
<!-- End Notice Block -->
<!--big Carousel-->
<div class="container">
    <div class="span7" style="margin-left:0">
        <div id="myCarousel" class="carousel slide">
            <div class="carousel-inner">
                <!-- Indicators -->
                <?php
                foreach ($root->getChildrenCategories() as $category):
                    $children = $category->getProducts();
                    if (count($children)):
                        $children->limit(3)
                                ->order('created_at DESC');
                        foreach ($children as $item):
                            $thumbnail = $item->getThumbnail();
                            ?>
                            <div class="item" style="max-height: 348px;overflow: hidden">
                                <a href="<?php echo $item->getUrl($category); ?>">
                                    <?php if (strpos($thumbnail, '//') === false): ?>
                                        <img class="bttrlazyloading" src="<?php echo $this->getResourceUrl('image/resized/540x/' . $thumbnail) ?>" alt="<?php echo $item['name'] ?>" />
                                    <?php else: ?>
                                        <img src="<?php echo $thumbnail ?>" alt="<?php echo $item['name'] ?>" width="100%" />
                                    <?php endif; ?>
                                </a>
                                <div class="carousel-caption">
                                    <p class="text-center"><?php echo $item['name'] ?></p>
                                </div>
                            </div>
                            <?php
                        endforeach;
                        break;
                    endif;
                endforeach;
                ?>
            </div>   
            <div class="carousel-arrow">
                <a class="left carousel-control" href="#myCarousel" data-slide="prev"><i class="icon-angle-left"></i></a>
                <a class="right carousel-control" href="#myCarousel" data-slide="next"><i class="icon-angle-right"></i></a>
            </div>
        </div>
    </div>
    <div class="span5">
        <ol class="list-group"> 
            <?php
            foreach ($root->getChildrenCategories() as $category):
                $children = $category->getProducts();
                if (count($children)):
                    $children->limit(10)
                            ->order('created_at DESC');
                    foreach ($children as $id => $child):
                        $thumbnail = $child->getThumbnail();
                        ?>
                        <li class="list-group-item">
                            <a href="<?php echo $child->getUrl($category); ?>"><?php echo $child['name'] ?></a>
                        </li>
                        <?php
                    endforeach;
                    break;
                endif;
            endforeach;
            ?>
        </ol>
    </div>
</div>
<!--big Carousel end-->
<!--=== Content Part ===-->

<div class="container">	
    <!-- Recent Works -->
    <?php
    foreach ($root->getChildrenCategories() as $category):
        if ($category['id'] == 3):
            ?>
            <div class="headline"><h3><?php echo $category['name'] ?></h3><a href="<?php echo $category->getUrl(); ?>" style="float:right;line-height:54px"><?php echo $this->translate('More'); ?> &gt;&gt;</a></div>
            <ul class="thumbnails">
                <?php
                $children = $category->getProducts();
                if (count($children)):
                    $children->limit(3)
                            ->order('created_at DESC');
                    foreach ($children as $id => $child):
                        $thumbnail = $child->getThumbnail();
                        ?>
                        <li class="span4">
                            <div class="thumbnail-style thumbnail-kenburn">
                                <div class="thumbnail-img">
                                    <div class="overflow-hidden">
                                        <a href="<?php echo $child->getUrl($category); ?>">
                                            <?php if (strpos($thumbnail, '//') === false): ?>
                                                <img class="bttrlazyloading" src="<?php echo $this->getResourceUrl('image/resized/540x/' . $thumbnail) ?>" alt="<?php echo $child['name'] ?>" />
                                            <?php else: ?>
                                                <img src="<?php echo $thumbnail ?>" alt="<?php echo $child['name'] ?>" width="100%" />
                                            <?php endif; ?>
                                        </a>
                                    </div>
                                    <a class="btn-more hover-effect" href="<?php echo $child->getUrl($category); ?>">reading +</a>					
                                </div>
                                <h4 class="text-center"><a class="hover-effect" href="<?php echo $child->getUrl($category); ?>"><?php echo mb_substr($child['name'], 0, 20, 'utf-8'); ?></a></h4>
                                <p><?php echo mb_substr(trim(strip_tags($child['short_description'])), 0, 50, 'utf-8') . '……' ?></p>
                            </div>
                        </li>
                        <?php
                    endforeach;
                endif;
                ?>
            </ul><!--/thumbnails-->
            <!-- //End Recent Works -->
            <?php
        endif;
    endforeach;
    foreach ($root->getChildrenCategories() as $category):
        if ($category['id'] == 8):
            ?>
            <!-- Service Blocks -->
            <div class="headline"><h3><?php echo $category['name'] ?></h3><a href="<?php echo $category->getUrl(); ?>" style="float:right;line-height:54px"><?php echo $this->translate('More'); ?> &gt;&gt;</a></div>
            <div class="row-fluid">
                <?php
                $children = $category->getProducts();
                if (count($children)):
                    $children->limit(3)
                            ->order('created_at DESC');
                    foreach ($children as $id => $child):
                        $thumbnail = $child->getThumbnail();
                        ?>
                        <div class="span4">
                            <div class="service clearfix">
                                <i class="icon-asterisk"></i>
                                <div class="desc">
                                    <h4><?php echo mb_substr($child['name'], 0, 28, 'utf-8'); ?></h4>
                                    <span class="badge" style="float:right"><?php echo $child['source'] ?></span>
                                </div>
                            </div>	
                        </div>
                        <?php
                    endforeach;
                endif;
                ?>
            </div><!--/row-fluid-->
            <!-- //End Service Blokcs -->
            <?php
        endif;
    endforeach;
    foreach ($root->getChildrenCategories() as $category):
        if ($category['id'] == 12):
            $children = $category->getChildrenCategories();
            if (count($children)):
                ?>
                <!-- Recent Works -->
                <div class="headline"><h3><?php echo $category['name'] ?></h3><a href="<?php echo $category->getUrl(); ?>" style="float:right;line-height:54px"><?php echo $this->translate('More'); ?> &gt;&gt;</a></div>
                <ul class="thumbnails">
                    <?php
                    foreach ($children as $child):
                        $thumbnail = $child->getThumbnail();
                        ?>
                        <li class="span3">
                            <div class="thumbnail-style thumbnail-kenburn">
                                <div class="thumbnail-img">
                                    <div class="overflow-hidden">
                                        <?php if (strpos($thumbnail, '//') === false): ?>
                                            <img class="bttrlazyloading" src="<?php echo $this->getResourceUrl('image/resized/260x/' . $thumbnail) ?>" alt="<?php echo $child['name'] ?>" />
                                        <?php else: ?>
                                            <img src="<?php echo $thumbnail ?>" alt="<?php echo $child['name'] ?>" width="100%" />
                                        <?php endif; ?>
                                    </div>
                                    <a class="btn-more hover-effect" href="<?php echo $child->getUrl(); ?>">reading +</a>					
                                </div>
                                <h3><a class="hover-effect" href="<?php echo $child->getUrl(); ?>"><?php echo $child['name']; ?></a></h3>
                                <p><?php echo mb_substr(trim(strip_tags($child['description'])), 0, 100, 'utf-8') . '……' ?>
                                    Donec id elit non mi porta gravida at eget metus. Fusce dapibus, justo sit amet risus etiam porta sem.</p>                
                                <!-- 星星等级 -->
                                <div class="star-vote pull-right">
                                    <ul class="list-inline">
                                        <li><i class="color-green fa fa-star"></i></li>
                                        <li><i class="color-green fa fa-star"></i></li>
                                        <li><i class="color-green fa fa-star"></i></li>
                                        <li><i class="color-green fa fa-star-half-o"></i></li>
                                        <li><i class="color-green fa fa-star-o"></i></li>
                                    </ul>
                                </div>
                            </div>
                        </li>
                        <?php
                    endforeach;
                    ?>
                </ul><!--/thumbnails-->
                <!-- //End Recent Works -->
                <?php
            endif;
        endif;
    endforeach;
    foreach ($root->getChildrenCategories() as $category):
        if ($category['id'] == 11):
            ?>
            <!-- Service Blocks -->
            <div class="headline"><h3><?php echo $category['name'] ?></h3><a href="<?php echo $category->getUrl(); ?>" style="float:right;line-height:54px"><?php echo $this->translate('More'); ?> &gt;&gt;</a></div>
            <div class="row-fluid">
                <?php
                $children = $category->getProducts();
                if (count($children)):
                    $children->limit(3)
                            ->order('created_at DESC');
                    foreach ($children as $id => $child):
                        $thumbnail = $child->getThumbnail();
                        ?>
                        <div class="span4">
                            <div class="service clearfix">
                                <i class="icon-pencil"></i>
                                <div class="desc">
                                    <h4><a href="<?php echo $child->getUrl() ?>"><?php echo $child['name'] ?></a></h4>
                                    <span class="badge" style="float:right"><?php echo $this->translate('Author') ?>：<?php echo $child['author'] ?? ''; ?></span>
                                </div>
                            </div>	
                        </div>
                        <?php
                    endforeach;
                endif;
                ?>    
            </div><!--/row-fluid-->
            <!-- //End Service Blokcs -->
            <?php
        endif;
    endforeach;
    ?>
    <!-- Information Blokcs -->
    <div class="row-fluid margin-bottom-20">
        <?php
        foreach ($root->getChildrenCategories() as $category):
            if ($category['id'] == 10):
                ?>
                <!-- Who We Are -->
                <div class="span8">
                    <div class="headline"><h3><?php echo $category['name'] ?></h3><a href="<?php echo $category->getUrl(); ?>" style="float:right;line-height:54px"><?php echo $this->translate('More'); ?> &gt;&gt;</a></div>
                    <p><img class="pull-left lft-img-margin img-width-200" src="<?php echo $this->getPubUrl('frontend/img/carousel/language.jpg'); ?>" alt="" width="100%" />
                        偶然结识了韩国『친구』，一起玩耍或聚会的时候，大写加粗的尴尬。为了便于沟通，于是开始学习韩语,『대박』！
                    </p>	
                    <ul class="unstyled">
                        <?php
                        $children = $category->getProducts();
                        if (count($children)):
                            $children->limit(4)
                                    ->order('created_at DESC');
                            foreach ($children as $id => $child):
                                $thumbnail = $child->getThumbnail();
                                ?>
                                <li><i class="icon-ok color-green"></i><?php echo $child['name'] ?></li>
                                <?php
                            endforeach;
                        endif;
                        ?>
                        <br />
                        <blockquote class="hero-unify">
                            <p>学习语言真的是一件有趣的事儿，但是有时候也很让人抓狂，对于发音，真心觉得好难！也因为发音，闹过很多乌龙事件，将钱『돈』发成大便『똥』的音，只是其中的一小件儿！</p>
                            <small>CEO, Peach Yang</small>
                        </blockquote>
                </div><!--/span8-->        
                <?php
            endif;
        endforeach;
        foreach ($root->getChildrenCategories() as $category):
            if ($category['id'] == 7):
                ?>
                <!-- Latest Shots -->
                <div class="span4">
                    <div class="headline"><h3><?php echo $this->translate('Latest') . $category['name'] ?></h3><a href="<?php echo $category->getUrl(); ?>" style="float:right;line-height:54px"><?php echo $this->translate('More'); ?> &gt;&gt;</a></div>
                    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                        <!-- Indicators -->
                        <ol class="carousel-indicators">
                            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                            <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                            <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                        </ol>
                        <!-- Wrapper for slides -->
                        <div class="carousel-inner" role="listbox">
                            <?php
                            $children = $category->getProducts();
                            if (count($children)):
                                $children->limit(3)
                                        ->order('created_at DESC');
                                foreach ($children as $id => $child):
                                    $thumbnail = $child->getThumbnail();
                                    ?>
                                    <div class="item active">
                                        <?php if (strpos($thumbnail, '//') === false): ?>
                                            <img class="bttrlazyloading" src="<?php echo $this->getResourceUrl('image/resized/370x/' . $thumbnail) ?>" alt="<?php echo $child['name'] ?>" />
                                        <?php else: ?>
                                            <img src="<?php echo $thumbnail ?>" alt="<?php echo $child['name'] ?>" width="100%" />
                                        <?php endif; ?>
                                        <div class="carousel-caption text-center">
                                            <p><?php echo $child['name'] ?? ''; ?></p>
                                        </div>
                                    </div>
                                    <?php
                                endforeach;
                            endif;
                            ?>
                        </div>

                        <!-- Controls -->
                        <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
                            <span class="glyphicon icon-angle-left"></span>
                        </a>
                        <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
                            <span class="glyphicon icon-angle-right"></span>
                        </a>
                    </div>
                    <!--<article class="jq22-container">
                        <div class = "caroursel poster-main" data-setting = '{
                             "width":335,
                             "height":200,
                             "posterWidth":260,
                             "posterHeight":190,
                             "scale":0.8,
                             "dealy":"2000",
                             "algin":"middle"
                             }'>
                            <ul class = "poster-list">
                                <li class = "poster-item"><img src="<?php echo $this->getPubUrl('frontend/img/carousel/1.jpg') ?>" width = "100%"></li>
                                <li class = "poster-item"><img src="<?php echo $this->getPubUrl('frontend/img/carousel/2.jpg') ?>" width = "100%"></li>
                                <li class = "poster-item"><img src="<?php echo $this->getPubUrl('frontend/img/carousel/3.jpg') ?>" width = "100%"></li>
                                <li class = "poster-item"><img src="<?php echo $this->getPubUrl('frontend/img/carousel/4.jpg') ?>" width = "100%"></li>
                                <li class = "poster-item"><img src="<?php echo $this->getPubUrl('frontend/img/carousel/5.jpg') ?>" width = "100%"></li>
                            </ul>
                            <div class = "poster-btn poster-prev-btn"></div>
                            <div class = "poster-btn poster-next-btn"></div>
                        </div>
                    </article>-->
                </div><!--/span4-->
                <?php
            endif;
        endforeach;
        ?>
    </div><!--/row-fluid-->	
    <!-- //End Information Blokcs -->
    <!-- Our Clients -->
    <div id="clients-flexslider" class="flexslider home clients hidden-phone">
        <div class="headline"><h3>our client</h3></div>	
        <ul class="slides">
            <li>
                <a href="#">
                    <img src="<?php echo $this->getPubUrl('frontend/img/clients/hp_grey.png') ?>" alt="<?php echo $this->translate('WeChat Public Signal'); ?>" /> 
                    <img src="<?php echo $this->getPubUrl('frontend/img/clients/hp.png') ?>" class="color-img" alt="" />
                </a>
            </li>
            <li>
                <a href="#">
                    <img src="<?php echo $this->getPubUrl('frontend/img/clients/igneus_grey.png') ?>" alt="<?php echo $this->translate('Weibo') ?>" /> 
                    <img src="<?php echo $this->getPubUrl('frontend/img/clients/igneus.png') ?>" class="color-img" alt="" />
                </a>
            </li>
            <li>
                <a href="#">
                    <img src="<?php echo $this->getPubUrl('frontend/img/clients/vadafone_grey.png') ?>" alt="" /> 
                    <img src="<?php echo $this->getPubUrl('frontend/img/clients/vadafone.png') ?>" class="color-img" alt="" />
                </a>
            </li>
            <li>
                <a href="#">
                    <img src="<?php echo $this->getPubUrl('frontend/img/clients/walmart_grey.png') ?>" alt="" /> 
                    <img src="<?php echo $this->getPubUrl('frontend/img/clients/walmart.png') ?>" class="color-img" alt="" />
                </a>
            </li>
            <li>
                <a href="#">
                    <img src="<?php echo $this->getPubUrl('frontend/img/clients/shell_grey.png') ?>" alt="" /> 
                    <img src="<?php echo $this->getPubUrl('frontend/img/clients/shell.png') ?>" class="color-img" alt="" />
                </a>
            </li>
            <li>
                <a href="#">
                    <img src="<?php echo $this->getPubUrl('frontend/img/clients/natural_grey.png') ?>" alt="" /> 
                    <img src="<?php echo $this->getPubUrl('frontend/img/clients/natural.png') ?>" class="color-img" alt="" />
                </a>
            </li>
            <li>
                <a href="#">
                    <img src="<?php echo $this->getPubUrl('frontend/img/clients/aztec_grey.png') ?>" alt="" /> 
                    <img src="<?php echo $this->getPubUrl('frontend/img/clients/aztec.png') ?>" class="color-img" alt="" />
                </a>
            </li>
            <li>
                <a href="#">
                    <img src="<?php echo $this->getPubUrl('frontend/img/clients/gamescast_grey.png') ?>" alt="" /> 
                    <img src="<?php echo $this->getPubUrl('frontend/img/clients/gamescast.png') ?>" class="color-img" alt="" />
                </a>
            </li>
            <li>
                <a href="#">
                    <img src="<?php echo $this->getPubUrl('frontend/img/clients/cisco_grey.png') ?>" alt="" /> 
                    <img src="<?php echo $this->getPubUrl('frontend/img/clients/cisco.png') ?>" class="color-img" alt="" />
                </a>
            </li>
            <li>
                <a href="#">
                    <img src="<?php echo $this->getPubUrl('frontend/img/clients/everyday_grey.png') ?>" alt="" /> 
                    <img src="<?php echo $this->getPubUrl('frontend/img/clients/everyday.png') ?>" class="color-img" alt="" />
                </a>
            </li>
            <li>
                <a href="#">
                    <img src="<?php echo $this->getPubUrl('frontend/img/clients/cocacola_grey.png') ?>" alt="" /> 
                    <img src="<?php echo $this->getPubUrl('frontend/img/clients/cocacola.png') ?>" class="color-img" alt="" />
                </a>
            </li>
            <li>
                <a href="#">
                    <img src="<?php echo $this->getPubUrl('frontend/img/clients/spinworkx_grey.png') ?>" alt="" /> 
                    <img src="<?php echo $this->getPubUrl('frontend/img/clients/spinworkx.png') ?>" class="color-img" alt="" />
                </a>
            </li>
            <li>
                <a href="#">
                    <img src="<?php echo $this->getPubUrl('frontend/img/clients/shell_grey.png') ?>" alt="" /> 
                    <img src="<?php echo $this->getPubUrl('frontend/img/clients/shell.png') ?>" class="color-img" alt="" />
                </a>
            </li>
            <li>
                <a href="#">
                    <img src="<?php echo $this->getPubUrl('frontend/img/clients/natural_grey.png') ?>" alt="" /> 
                    <img src="<?php echo $this->getPubUrl('frontend/img/clients/natural.png') ?>" class="color-img" alt="" />
                </a>
            </li>
            <li>
                <a href="#">
                    <img src="<?php echo $this->getPubUrl('frontend/img/clients/gamescast_grey.png') ?>" alt="" /> 
                    <img src="<?php echo $this->getPubUrl('frontend/img/clients/gamescast.png') ?>" class="color-img" alt="" />
                </a>
            </li>
            <li>
                <a href="#">
                    <img src="<?php echo $this->getPubUrl('frontend/img/clients/everyday_grey.png') ?>" alt="" /> 
                    <img src="<?php echo $this->getPubUrl('frontend/img/clients/everyday.png') ?>" class="color-img" alt="" />
                </a>
            </li>
            <li>
                <a href="#">
                    <img src="<?php echo $this->getPubUrl('frontend/img/clients/spinworkx_grey.png') ?>" alt="" /> 
                    <img src="<?php echo $this->getPubUrl('frontend/img/clients/spinworkx.png') ?>" class="color-img" alt="" />
                </a>
            </li>
        </ul>
    </div><!--/flexslider-->
    <!-- //End Our Clients -->
</div><!--/container-->
<!-- End Content Part -->
