<?php
$parent = $this->getVariable('category')->getParentCategory();
?>    
<nav class="nav" id="layered-nav">
    <h4><?php echo $parent['name'][$this->getLanguageId()]; ?></h4>
    <dl id="myTabs" class="nav nav-tabs" role="tablist">
        <?php
        foreach ($parent->getChildrenCategories() as $category):
            $children = $category->getPages();
            $count = $children->count();
            ?>
        <dt role="presentation" class="active">
            <a data-toggle="collapse" href="#nav-<?php echo $category['id'] ?>"><?php echo $category['name'][$this->getLanguageId()]; ?></a>
        </dt>
            <dd>
                <ul id="nav-<?php echo $category['id'] ?>" class="collapse in">
                    <?php
                    foreach ($children as $child):
                        $url = $child->getUrl();
                        ?>
                        <li role="tabpanel" class="tab-pane fade active in" id="home" aria-labelledby="home-tab">
                            <a href="<?php echo $url ? $this->getBaseUrl($url . '.html') : 'javascript:void(0);' ?>"><?php echo $child['title']; ?></a>
                        </li>
                        <?php
                    endforeach;
                    ?>
                </ul>
            </dd>
        <?php endforeach; ?>
    </dl>
</nav>
