<?php
$parent = $this->getVariable('category')->getParentCategory();
?>    
<nav class="col-sm-8" id="cms-layered-nav">
    <h2 class="title"><?php echo $parent['name'][$this->getLanguageId()]; ?></h2>
    <dl class="nav">
        <?php
        foreach ($parent->getChildrenCategories() as $category):
            $children = $category->getPages();
            $count = $children->count();
            ?>
            <dt>
                <a data-toggle="collapse" href="#nav-<?php echo $category['id'] ?>">
                    <?php echo $category['name'][$this->getLanguageId()]; ?>
                </a>
            </dt>
            <dd>
                <ul id="nav-<?php echo $category['id'] ?>" class="collapse in" role="menu">
                    <?php
                    foreach ($children as $child):
                        $url = $child->getUrl();
                        ?>
                        <li role="presentation">
                            <a href="<?php echo $url ? $this->getBaseUrl($url . '.html') : 'javascript:void(0);' ?>" role="menuitem">
                                <?php echo $child['title']; ?>
                            </a>
                        </li>
                    <?php endforeach ?>
                </ul>
            </dd>
        <?php endforeach ?>
    </dl>
</nav>
