<?php 
$navigation = $this->getVariable('category');
?>    
<nav class="nav" id="layered-nav">
    <dl class="level-0" role="menu">   
        <dt>help-center</dt>
            <dd>
                <dl class="level-1">
                    <dt>Beginner's Guide</dt>
                    <dd>
                        <ul class="level-2">
                            <li class="active" role="presentation"><a href="" role="menuitem"><span>Register Help</span></a></li>
                            <li role="presentation"><a href="" role="menuitem"><span>Shopping Help</span></a></li>
                            <li role="presentation"><a href="" role="menuitem"><span>Help pay</span></a></li>
                        </ul>
                    </dd>
                </dl>
            </dd>
            <dd>
                <dl class="level-1">
                    <dt>About payment</dt>
                    <dd>
                        <ul class="level-2">
                            <li role="presentation"><a href="" role="menuitem"><span>About payment</span></a></li>
                            <li role="presentation"><a href="" role="menuitem"><span>Invoice Policy</span></a></li>
                        </ul>
                    </dd>
                </dl>
            </dd>
        </dl>
    </nav>
