<?php
$page = $this->getPageModel();
?>
<!--=== Content Part ===-->
<div class="container">		
    <div class="row-fluid blog-page blog-item">
        <div class="notice margin-bottom-30">
            <h3 class="text-center"><?php echo $page['title']; ?></h3>
            <p>&nbsp;</p>
            <ul class="unstyled inline blog-info text-center">
                <li><i class="icon-calendar"></i><?php echo date('F, j, Y', strtotime($page['created_at'])); ?></li>
                <li><i class="icon-pencil"></i><?php echo $page['author']; ?></li>
            </ul>
            <p>&nbsp;</p>
            <div class="section-cotent">
                <?php echo $page['content']; ?>
            </div>
        </div><!--/blog-->
    </div><!--/row-fluid-->        
</div><!--/container-->		
<!--=== End Content Part ===-->
