<div id="modal-reply" class="modal fade" tabindex="-1">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form action="<?php echo $this->getBaseUrl('retailer/transaction/reply/') ?>" method="post">
                <input type="hidden" name="id" />
                <input type="hidden" name="csrf" value="<?php echo $this->getCsrfKey() ?>" />
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title"><?php echo $this->translate('Reply a Review') ?></h4>
                </div>
                <div class="modal-body">
                    <ul>
                        <li>
                            <label class="control-label"><?php echo $this->translate('Content') ?></label>
                            <textarea readonly="readonly" disabled="disabled" name="content" class="form-control"></textarea>
                        </li>
                        <li>
                            <label class="control-label"><?php echo $this->translate('Reply') ?></label>
                            <textarea name="reply" class="form-control"></textarea>
                        </li>
                    </ul>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary"><?php echo $this->translate('Submit') ?></button>
                </div>
            </form>
        </div>
    </div>
</div>