<section class="section review">
    <div class="order">
        <?php
        $stores = [];
        $subtotal = [];
        foreach ($this->getItems() as $item) {
            if (!isset($subtotal[$item['store_id']])) {
                $subtotal[$item['store_id']] = 0;
            }
            $stores[$item['store_id']] = !isset($stores[$item['store_id']]) ? 1 : $stores[$item['store_id']] + 1;
            $subtotal[$item['store_id']] += $item['total'];
        }
        $current = 0;
        foreach ($this->getItems() as $item) {
            if ($current !== $item['store_id']):
                ?>
                <?php if ($current): ?>
                    <tr>
                        <th colspan="7" class="text-right text-nowrap subtotal">
                            <?php echo $this->translate('Subtotal') . ': ' . $this->getCurrency()->format($subtotal[$current]) ?>
                        </th>
                    </tr>
                <?php endif ?>
                <ul class="store">
                    <li class="col-xs-12 col-sm-12">
                        <?php echo $item['store']['name'] ?>
                    </li>
                </ul>
                <?php
                $current = $item['store_id'];
                echo $this->getRow($item, $stores[$item['store_id']]);
            else:
                echo $this->getRow($item);
            endif;
        }
        ?>
        <ul class="shipping">
            <li class="col-xs-2 col-sm-2 text-nowrap text-right">
                <?php echo $this->translate('Shipping Method', [], 'checkout') ?>
            </li>
            <li class="col-xs-9 col-sm-9">
                <?php echo $this->getChild('shipping')->setVariable('store_id', $current) ?>
            </li>
        </ul>
        <ul class="subtotal">
            <li class="text-right total">
                <?php echo $this->getChild('total') ?>
            </li>
        </ul>
        <ul  class="grand-total">
            <li class="col-xs-10 col-sm-10 text-right">
                <?php echo $this->translate('Grand Total') ?>:<?php echo $this->getCurrency()->format($this->getCart()['total']) ?>
            </li>
            <li class="col-xs-2 col-sm-2 buttons-set">
                <button type="button" class="btn btn-checkout">
                    <span><?php echo $this->translate('Place Order') ?></span>
                </button>
            </li>
        </ul>
    </div>
</section>