<section class="section review">
    <div class="table order">
        <?php
        $stores = [];
        $subtotal = [];
        foreach ($this->getItems() as $item) {
            if (!isset($subtotal[$item['store_id']])) {
                $subtotal[$item['store_id']] = 0;
            }
            $stores[$item['store_id']] = !isset($stores[$item['store_id']]) ? 1 : $stores[$item['store_id']] + 1;
            $subtotal[$item['store_id']] += $item['total'];
        }
        $current = 0;
        foreach ($this->getItems() as $item) {
            if ($current !== $item['store_id']):
                ?>
                <?php if ($current): ?>
                    <ul class="col-xs-12 col-sm-12">
                        <li class="col-xs-12 col-sm-12 text-right text-nowrap subtotal">
                            <?php echo $this->translate('Subtotal') . ': ' . $this->getCurrency()->format($subtotal[$current]) ?>
                        </li>
                    </ul>
                <?php endif ?>

                <ul class="col-xs-12 col-sm-12 store">
                    <li class="col-xs-6 col-sm-6 text-left">
                        <?php echo $item['store']['name'] ?>
                    </li>
                    <li class="col-xs-6 col-sm-6 text-right">
                        <div class="dropdown coupon" data-store="<?php echo $item['store_id'] ?>"><?php echo $this->getChild('coupon')->setVariable('store', $item['store_id']) ?></div>
                    </li>
                </ul>
                <?php
                $current = $item['store_id'];
                echo $this->getRow($item, $stores[$item['store_id']]);
            else:
                echo $this->getRow($item);
            endif;
        }
        ?>
        <ul class="col-xs-12 col-sm-12 shipping">
            <li class="col-xs-6 col-sm-6 text-nowrap text-left">
                <?php echo $this->translate('Shipping Method', [], 'checkout') ?>
                <?php echo $this->getChild('shipping')->setVariable('store_id', $current) ?>
            </li>
            <li class="col-xs-6 col-sm-6 text-nowrap text-right">
                <?php echo $this->translate('Subtotal') . ': ' . $this->getCurrency()->format($subtotal[$current]) ?>
            </li>         
        </ul>
    </div>
    <div class="tfoot">
        <ul class="col-xs-12 col-sm-12 subtotal">
            <li class="col-xs-12 col-sm-12 text-right total">
                <?php echo $this->getChild('total') ?>
            </li>
            <li class="col-xs-12 col-sm-12 text-right buttons-set">
                <p><?php echo $this->translate('Grand Total') ?>:<span><?php echo $this->getCurrency()->format($this->getCart()['total']) ?><span></p>
                <button type="button" class="btn btn-checkout"><?php echo $this->translate('Place Order') ?></button>
            </li>
        </ul>
    </div>
</section>
