<div class="table">
    <ul class="col-xs-12 col-sm-12">
        <li class="col-xs-8 col-sm-8 text-right"><?php echo $this->translate('%d item(s)', [$this->getCart()->getQty()]) ?></li>
        <li class="col-xs-4 col-sm-4"><?php echo $this->translate('Subtotal') ?>:<span><?php echo $this->getCurrency()->format($this->getCart()['subtotal']) ?></span></li>
    </ul>

    <?php
    if ((float) $this->getCart()['tax']):
        ?>
        <ul class="col-xs-12 col-sm-12">
            <li class="col-xs-8 col-sm-8 text-right text-nowrap"><?php echo $this->translate('Tax') ?></li>
            <li class="col-xs-4 col-sm-4"><span><?php echo $this->getCurrency()->format($this->getCart()['tax']) ?></span></li>
        </ul>
        <?php
    endif;
    ?>
    <?php
    if ((float) $this->getCart()['shipping']):
        ?>
        <ul class="col-xs-12 col-sm-12">
            <li class="col-xs-8 col-sm-8 text-right text-nowrap"><?php echo $this->translate('Shipping') ?>:</li>
            <li class="col-xs-4 col-sm-4 text-right"><?php echo $this->getCurrency()->format($this->getCart()['shipping']) ?></li>
        </ul>
        <?php
    endif;
    ?>
    <?php
    if ((float) $this->getCart()['discount']):
        foreach (json_decode($this->getCart()['discount_detail'], true) as $type => $discount):
            ?>
            <ul class="col-xs-12 col-sm-12">
                <li class="col-xs-8 col-sm-8 text-right text-nowrap"><?php echo $this->translate('Discount(' . $type . ')') ?>:</li>
                <li class="col-xs-4 col-sm-4 text-right"><?php echo $this->getCurrency()->convert($discount, true) ?></li>
            </ul>
            <?php
        endforeach;
    endif;
    ?>
        <ul class="col-xs-12 col-sm-12 text-right">
            <li class="col-xs-8 col-sm-8 text-right text-nowrap"><?php echo $this->translate('Grand Total') ?>:</li>
            <li class="col-xs-4 col-sm-4 text-right"><?php echo $this->getCurrency()->format($this->getCart()['total']) ?></li>
        </ul>
</div>
