<div class="table">
    <ul class="col-xs-12 col-sm-12">
        <li class="col-xs-8 col-sm-8 text-right"><?php echo $this->translate('%d item(s)', [$this->getCart()->getQty()]) ?></li>
        <li class="col-xs-4 col-sm-4"><?php echo $this->translate('Subtotal') ?>:<span><?php echo $this->getCurrency()->format($this->getCart()['subtotal']) ?></span></li>
    </ul>
    <div class="grand-total">
        <ul class="col-xs-9 col-sm-9 text-right">
            <li >
                <?php echo $this->translate('Grand Total') ?>:<span><?php echo $this->getCurrency()->format($this->getCart()['total']) ?></span>
            </li>
        </ul>
        <ul class="col-xs-3 col-sm-3 buttons-set">
            <li><button type="button" class="btn btn-checkout"><?php echo $this->translate('Place Order') ?></button></li>
        </ul>
    </div>
    <?php
    if ((float) $this->getCart()['tax']):
        ?>
        <ul class="col-xs-12 col-sm-12">
            <li class="col-xs-2 col-sm-2 text-right text-nowrap"><?php echo $this->translate('Tax') ?></li>
            <li class="col-xs-10 col-sm-10"><span><?php echo $this->getCurrency()->format($this->getCart()['tax']) ?></span></li>
        </ul>
        <?php
    endif;
    ?>
    <?php
    if ((float) $this->getCart()['shipping']):
        ?>
        <ul class="col-xs-12 col-sm-12">
            <li class="col-xs-12 col-sm-12 text-right text-nowrap"><?php echo $this->translate('Shipping') ?>:
                <span><?php echo $this->getCurrency()->format($this->getCart()['shipping']) ?></span></li>
        </ul>
        <?php
    endif;
    ?>
    <?php
    if ((float) $this->getCart()['discount']):
        foreach (json_decode($this->getCart()['discount_detail'], true) as $type => $discount):
            ?>
            <ul class="col-xs-12 col-sm-12">
                <li class="col-xs-12 col-sm-12 text-right text-nowrap">
                    <?php echo $this->translate('Discount(' . $type . ')') ?>:
                    <span><?php echo $this->getCurrency()->convert($discount, true) ?></span>
                </li>
            </ul>
            <?php
        endforeach;
    endif;
    ?>
</div>
