<?php
$tree = $this->getCategoryTree();
$cid = $this->getQuery('category_id', 0);
if (isset($tree[$cid])):
    foreach ($tree[$cid] as $category):
        ?>
        <li class="item" data-folder="#resource-category-<?php echo $category->getId() ?>">
            <span class="fa fa-folder" aria-hidden="true"></span>
            <span><?php echo $category['name'][$this->getLanguageId()] ?? $category['name'][0] ?? current($category['name']) ?></span>
        </li>
        <?php
    endforeach;
endif;
foreach ($this->getResources() as $resource):
    ?>
    <li class="item" data-href="<?php echo $this->getResourceUrl($resource) ?>">
        <?php if (substr($resource['file_type'], 0, 5) === 'image'): ?>
            <img src="<?php echo $this->getResourceUrl('image/resized/100x/'.$resource['real_name']) ?>" alt="" />
        <?php else: ?>
            <span class="fa fa-file-<?php echo $this->getResourceType($resource['file_type']) ?>-o" aria-hidden="true"></span>
        <?php endif ?>
        <span class="filename"><?php echo $resource['uploaded_name'] ?></span>
    </li>
<?php endforeach; ?>
