<?php
$categories = $this->getCategorySource();
$stores = $this->getStore();
?>
<div class="modal fade" id="resource-modal" tabindex="-1" role="dialog" aria-labelledby="resource-modal-label" data-keyboard="false">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="btn close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="resource-modal-label"><?php echo $this->translate('Resource Management') ?></h4>
            </div>
            <div class="modal-body">
                <ul class="nav nav-tabs clearfix" role="tablist">
                    <li role="presentation" class="active">
                        <a href="#select-resource" aria-controls="select-resource" role="tab" data-toggle="tab">
                            <?php echo $this->translate('Select Resource') ?>
                        </a>
                    </li>
                    <li role="presentation">
                        <a href="#upload-resource" aria-controls="upload-resource" role="tab" data-toggle="tab">
                            <?php echo $this->translate('Upload Resource') ?>
                        </a>
                    </li>
                </ul>
                <div role="tabpanel" class="tab-pane active" id="select-resource">
                    <div id="resource-list"></div>
                </div>
                <div class="tab-pane" id="upload-resource">
                    <div class="grid">
                        <form id="upload-form" class="form-inline" action="<?php echo $this->getBaseUrl('retailer/resource/upload/') ?>" method="post" enctype="multipart/form-data">
                            <input type="hidden" name="csrf" value="<?php echo $this->getCsrfKey() ?>" />
                            <div class="filters">
                                <?php if (is_array($stores)): ?>
                                    <div class="input-box">
                                        <label class="control-label" for="store_id"><?php echo $this->translate('Store') ?></label>
                                        <div class="cell">
                                            <select class="form-control" id="store_id" name="store_id">
                                                <?php foreach ($stores as $group => $store): ?>
                                                    <optgroup label="<?php echo $group ?>">
                                                        <?php foreach ($store as $id => $name): ?>
                                                            <option value="<?php echo $id ?>"><?php echo $name ?></option>
                                                        <?php endforeach ?>
                                                    </optgroup>
                                                <?php endforeach ?>
                                            </select>
                                        </div>
                                    </div>
                                <?php else: ?>
                                    <input type="hidden" name="store_id" value="<?php echo $stores ?>" />
                                <?php endif ?>
                                <div class="input-box">
                                    <label class="control-label" for="category_id"><?php echo $this->translate('Category') ?></label>
                                    <div class="cell">
                                        <select class="form-control " id="category_id" name="category_id">
                                            <option value=""><?php echo $this->translate('(NULL)') ?></option>
                                            <?php foreach ($categories as $id => $name): ?>
                                                <option value="<?php echo $id ?>"><?php echo $name ?></option>
                                            <?php endforeach ?>
                                        </select>
                                    </div>
                                </div>
                                <div class="input-box">
                                    <label class="control-label" for="file-upload"><?php echo $this->translate('Select Resource') ?></label>
                                    <div class="cell">
                                        <input id="upload-element" type="file" name="files[]" class="form-control" data-url="<?php echo $this->getBaseUrl('retailer/resource/upload/') ?>" multiple />
                                    </div>
                                </div>
                            </div>
                            <div id="upload-list"></div>
                            <div class="buttons-set">
                                <button type="submit" class="btn btn-theme"><?php echo $this->translate('Upload') ?></button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>