<header class="header-m">
    <a href="javascript:void(0);" onClick="javascript:history.back(-1);" class="fa fa-angle-left fa-2x col-xs-1 col-sm-1 text-right"></a>
    <div class="container col-xs-10 col-md-10 text-center">
        <?php echo $this->translate('Personal Center') ?>
    </div>
    <a href="javascript:viod(0);" class="fa fa-bars col-xs-1 col-sm-1 text-left" data-toggle="dropdown" style="font-size: 20px"></a>
    <ul class="filters clearfix dropdown-menu col-xs-12" role="menu"> 
        <li class="col-xs-4">
            <a href="<?php echo $this->getBaseUrl('') ?>"><?php echo $this->translate('Home') ?><span class="fa  fa-bank font-color-orange font-14"></span></a>
        </li>
        <li class="col-xs-4">
            <a href="<?php echo $this->getBaseUrl('checkout/cart/') ?>"><?php echo $this->translate('Cart') ?><span class="fa fa-shopping-cart font-color-orange font-14"></span></a>
        </li>
        <li class="col-xs-4">
            <a href="<?php echo $this->getBaseUrl('customer/account/') ?>"><?php echo $this->translate('Personal Center') ?><span class="fa   fa-user font-color-orange font-14"></span></a>
        </li>
    </ul>
</header>
<div class="container">
    <?php if ($this->getSegment('customer')->get('hasLoggedIn')): ?>
        <div class="col-left col-md-2 hidden-xs">
            <?php echo $this->getChild('nav') ?>
        </div> 
        <main class="col-main col-xs-12 col-sm-12 col-md-12">
        <?php else: ?>
            <main class="col-main col-xs-12 col-sm-12">
            <?php endif ?>
            <?php echo $this->getChild('messages'), $this->getChild('main') ?>
        </main>
    </main>
</div>
