<header class="header-m">
    <a href="javascript:void(0);" onClick="javascript:history.back(-1);" class="fa fa-angle-left headimg-left"></a>
    <div class="container">
        <?php echo $this->translate('Welcome - Register') ?>
    </div>
</header>
<div class="main-container">
    <div class="col-main container">
        <div class="col-xs-12 col-sm-12">
            <form action="<?php echo $this->getBaseUrl('customer/account/createpost/') ?>" method="post">
                <input type="hidden" name="csrf" value="<?php echo $this->getCsrfKey() ?>" />
                <div class="fieldset logon"> 
                    <div class="table">
                        <div class="input-box">
                            <div class="cell">
                                <input type="text" name="username" placeholder="<?php echo $this->translate('Username') ?>" id="reg:username" class="form-control required" spellcheck="false" />  
                            </div>
                        </div>
                        <div class="input-box">
                            <div class="cell">
                                <input type="password" name="password" placeholder="<?php echo $this->translate('Password') ?>" id="reg:password" class="form-control required" minlength="6" />
                            </div>
                        </div>
                        <div class="input-box">
                            <div class="cell">
                                <input type="password" name="cpassword" placeholder="<?php echo $this->translate('Confirm Password') ?>" id="reg:cpassword" class="form-control required" data-rule-equalto="#reg\:password" />
                            </div>
                        </div>
                        <div class="input-box">
                            <div class="cell">
                                <input type="email" name="email" placeholder="<?php echo $this->translate('Email') ?>" id="reg:email" class="form-control required email" />
                            </div>
                        </div>
                        <?php if (in_array('register', $this->getConfig()['customer/captcha/form'])): ?>
                            <div class="input-box">
                                <label for="reg:captcha" class="control-label required"><?php echo $this->translate('Captcha') ?>: </label>
                                <div class="cell">
                                    <input type="text" name="captcha" class="form-control required captcha" maxlength="5" autocomplete="off" spellcheck="false" id="reg:captcha" />
                                    <img src="<?php echo $this->getBaseUrl('customer/account/captcha/') ?>" alt="" class="captcha" height="26" width="70" />
                                </div>
                            </div>
                        <?php endif ?>
                    </div>
                    <div class="additional">
                        <div class="input-box">
                            <input type="checkbox" id="reg:agreement" name="agreement" class="required" value="1">
                            <label for="reg:agreement" class="color_red">
                                <?php echo $this->translate('I have read and agreed to the') ?>
                                <a href="" class="color_blue "><?php echo $this->translate('Blue ocean user registration agreement') ?></a>
                            </label>
                        </div>
                        <div class="input-box">
                            <input type="checkbox" id="reg:subscribe" name="subscribe" value="1">
                            <label for="reg:subscribe">
                                <?php echo $this->translate('Sign up for Newsletter') ?>
                            </label>
                        </div>
                    </div>
                    <div class="buttons-set">
                        <button type="submit" class="btn btn-submit"><span><?php echo $this->translate('Sign up Now') ?></span></button>
                    </div>
                </div>
            </form>		
        </div>
        <div class="col-xs-12 col-sm-12 login text-center margin_10">
            <div class="text-left">
                <p>
                    <?php echo $this->translate('Already Registered,') ?>
                    <a href="<?php echo $this->getBaseUrl('customer/account/login/') ?>"><?php echo $this->translate('Login Now') ?></a>
                </p>
            </div>
        </div>
    </div>
</div>
