<?php
$customer = $this->getCustomer();
?>
<form action="<?php echo $this->getBaseUrl('customer/account/save/') ?>" method="post" class="form-inline">
    <input type="hidden" name="csrf" value="<?php echo $this->getCsrfKey() ?>" />
    <input type="hidden" name="id" value="<?php echo $customer->getId() ?>">
    <div class="fieldset">
        <div class="input-box">
            <label class="control-label text-right"><?php echo $this->translate('Username') ?>:</label>
            <div class="">
                <span><strong><?php echo $customer->offsetGet('username') ?></strong></span>
            </div>
        </div>
        <?php
        foreach ($this->getAttribute() as $attr) {
            echo $this->getInputBox($attr);
        }
        ?>
        <div class="input-box">
            <label class="control-label required text-right" for="crpassword"><?php echo $this->translate('Current Password') ?>:</label>
            <div class="cell col-xs-8 col-sm-8 col-md-11 text-left">
                <input type="password" name="crpassword" id="crpassword" class="form-control required" class="form-control required" minlength="6"/>
            </div>
        </div>
        
        <input type="checkbox" class="edit-password" id="edit-password" style="float:left" />
        <label class="col-xs-11 col-sm-11" for="edit-password"><?php echo $this->translate('Edit Password') ?></label>

        <div class="input-box">
            <label class="control-label text-right" for="password"><?php echo $this->translate('New Password') ?>:</label>
            <div class="cell text-left">
                <input type="password" name="password" id="password" class="form-control" minlength="6" />
            </div>
        </div>
        <div class="input-box">
            <label class="control-label text-right" for="cpassword"><?php echo $this->translate('Confirm Password') ?>:</label>
            <div class="cell text-left">
                <input type="password" name="cpassword" id="cpassword" class="form-control" data-rule-equalTo="#password" minlength="6" />
            </div>
        </div>
    </div>
    <div class="buttons-set">
        <div class="cell">&nbsp;</div>
        <div class="cell text-center">
            <button type="submit" class="btn btn-theme">
                <span><?php echo $this->translate('Submit') ?></span>
            </button>
        </div>
    </div>
</form>
