<header class="header-m">
	<a href="javascript:void(0);" onclick="javascript:history.back(-1);" class="fa fa-angle-left headimg-left"></a>
    <div class="container"><?php echo $this->translate('Forgot Your Password') ?>?</div>
</header>
<form action="<?php echo $this->getBaseUrl('customer/account/forgotpwdpost/') ?>" method="post">
    <input type="hidden" name="csrf" value="<?php echo $this->getCsrfKey() ?>" />
    <fieldset>
        <div class="input-box">
            <label class="control-label required col-xs-2 col-sm-2 col-md-1 text-right" for="login:username"><?php echo $this->translate('Username') ?>:</label>
            <div class="cell col-xs-10 col-sm-10 col-md-11">
                <input type="text" name="username" id="login:username" class="form-control required" spellcheck="false" />
            </div>
        </div>
        <?php if (in_array('forgotpwd', $this->getConfig()['customer/captcha/form'])): ?>
            <div class="input-box">
                <label for="login:captcha" class="control-label required col-xs-2 col-sm-2 col-md-1 text-right"><?php echo $this->translate('Captcha') ?>: </label>
                <div class="cell col-xs-10 col-sm-10 col-md-11">
                    <input type="text" name="captcha" class="form-control required captcha" maxlength="5" autocomplete="off" spellcheck="false" id="login:captcha" />
                    <img src="<?php echo $this->getBaseUrl('customer/account/captcha/') ?>" alt="" class="captcha" height="26" width="70" />
                </div>
            </div>
        <?php endif ?>
        <div class="buttons-set col-xs-12 col-sm-12">
            <button type="submit" class="btn btn-submit"><span><?php echo $this->translate('Submit') ?></span></button>
        </div>
    </fieldset>
</form>