<?php
$products = $this->getProducts();
?>
<div class="container">
    <ul class="products-grid clearfix">
        <?php foreach ($products as $product): ?>
            <li class="item col-xs-6 col-sm-4 col-md-3 col-lg-2">
                <a href="<?php echo $product->getUrl($this->getCategory()) ?>" title="<?php echo $product['name'] ?>" class="product-image">
                    <img src="<?php echo $product->getThumbnail() ?>" alt="<?php echo $product['name'] ?>" />
                </a>
                <h3 class="product-name">
                    <a href="<?php echo $product->getUrl($this->getCategory()) ?>">
                        <?php echo $product['name'] ?>
                    </a>
                </h3>
                <div class="price-box">
                    <?php echo $this->getPriceBox($product) ?>
                </div>
            </li>
        <?php endforeach ?>
    </ul>
</div>