<?php
$products = $this->getProducts();
?>
<div class="container">
    <?php if (count($products)): ?>
        <ul class="products-list clearfix">
            <?php foreach ($products as $product): ?>
                <li class="item col-xs-12 col-sm-6 col-md-4">
                    <a href="<?php echo $product->getUrl($this->getCategory()) ?>" title="<?php echo $product['name'] ?>" class="product-image col-xs-4">
                        <img src="<?php echo $product->getThumbnail() ?>" alt="<?php echo $product['name'] ?>" />
                    </a>
                    <h3 class="product-name pull-right col-xs-8">
                        <a href="<?php echo $product->getUrl($this->getCategory()) ?>">
                            <?php echo $product['name'] ?>
                        </a>
                    </h3>
                    <div class="price-box pull-right col-xs-8">
                        <?php echo $this->getPriceBox($product) ?>
                    </div>
                </li>
            <?php endforeach ?>
        </ul>
    <?php else: ?>
        <p class="no-product"><?php echo $this->translate('There are no products matching the selection.') ?></p>
    <?php endif ?>
</div>