<?php
$order = $this->getVariable('order');
$currency = $order->getCurrency();
?>
<div class="clearfix">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h4 class="panel-title"><?php echo $this->translate('Order Infomation', [], 'sales') ?></h4>
        </div>
        <div class="panel-body">
            <?php echo $this->translate('ID'), ': ', $order['increment_id'] ?><br />
            <?php echo $this->translate('Status'), ': ', $this->translate($order->getStatus()->offsetGet('name'), [], 'sales') ?><br />
            <?php
            if ($store = $order->getStore()) {
                echo $this->translate('Store'), ': ', $store->offsetGet('name');
            }
            ?><br />
            <?php
            if ($language = $order->getLanguage()) {
                echo $this->translate('Language'), ': ', $language->offsetGet('name');
            }
            ?><br />
            <?php echo $this->translate('Placed at'),': ', $order['created_at'] ?>
        </div>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading clearfix">
            <h4 class="panel-title pull-left"><?php echo $this->translate('Shipping Address', [], 'sales') ?></h4>
        </div>
        <div class="panel-body">
            <?php echo nl2br($order->offsetGet('shipping_address')) ?>
        </div>
    </div>
    <?php if ($method = $order->getShippingMethod()): ?>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title"><?php echo $this->translate('Shipping Method', [], 'sales') ?></h4>
            </div>
            <div class="panel-body">
                <?php echo $this->translate($method->getLabel()) ?>
            </div>
        </div>
    <?php endif ?>
    <div class="panel panel-default">
        <div class="panel-heading">
            <h4 class="panel-title"><?php echo $this->translate('Payment Method', [], 'sales') ?></h4>
        </div>
        <div class="panel-body">
            <?php echo $this->translate($order->getPaymentMethod()->getLabel()), '<br />', $this->translate('The order was placed using %s', [$order->offsetGet('currency')], 'sales') ?>
        </div>
    </div>
    <div class="panel panel-default wide">
        <div class="panel-heading">
            <h4 class="panel-title"><?php echo $this->translate('Product(s)') ?></h4>
        </div>
        <div class="panel-body grid table-responsive">
            <table class="table table-hover table-striped table-no-border">
                <thead class="text-nowrap">
                    <tr>
                        <th colspan="2"><?php echo $this->translate('Product') ?></th>
                        <th class="text-center"></th> 
                <!-- <th class="text-center"><?php echo $this->translate('SKU', [], 'sales') ?></th> -->
                        <th class="text-center"><?php echo $this->translate('Price', [], 'sales') ?></th>
                        <th class="text-center"><?php echo $this->translate('Qty', [], 'sales') ?></th>
                        <th class="text-center"><?php echo $this->translate('Total', [], 'sales') ?></th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    foreach ($order->getItems() as $item):
                        $product = $item['product'];
                        $thumbnail = $product->getThumbnail();
                        ?>
                        <tr<?php if (isset($item['id'])): ?> data-id="<?php echo $item['id'] ?>"<?php endif ?>>
                            <td>
                                <a href="<?php echo $product->getUrl() ?>">
                                    <img src="<?php echo strpos($thumbnail, '//') === false ? $this->getResourceUrl('image/resized/100x/' . $thumbnail) : $thumbnail ?>" width="100" alt="<?php echo $item['product_name'] ?>" />
                                </a>
                            </td>
                            <td>
                                <a href="<?php echo $product->getUrl() ?>">
                                    <?php echo $item['product_name'] ?>
                                </a>
                                <?php
                                $options = json_decode($item['options'], true);
                                if ($item['product_id'] && count($options)):
                                    ?>
                                    <dl class="options">
                                        <?php
                                        foreach ($product->getOptions() as $option):
                                            if (isset($options[$option->getId()])):
                                                ?>
                                                <dt><?php echo $option['title'] ?></dt>
                                                <dd><?php echo in_array($option['input'], ['select', 'radio', 'checkbox', 'multiselect']) ? $option->getValue($options[$option->getId()]) : $options[$option->getId()] ?></dd>
                                                <?php
                                            endif;
                                        endforeach;
                                        ?>
                                    </dl>
                                <?php endif ?>
                            </td>
                            <td class="text-center"></td>
                            <!--  <td class="text-center"><?php echo $item['sku'] ?></td>-->
                            <td class="text-center"><?php echo $currency->format($item['price']) ?></td>
                            <td class="text-center"><?php echo (float) $item['qty'] ?></td>
                            <td class="text-center"><?php echo $currency->format($item['total']) ?></td>
                        </tr>
                    <?php endforeach ?>
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="6">
                            <dl class="dl-horizontal pull-right">
                                <dt><?php echo $this->translate('Subtotal', [], 'sales') ?></dt>
                                <dd><?php echo $currency->format($order->offsetGet('subtotal')) ?></dd>
                                <dt><?php echo $this->translate('Shipping &amp; Handling', [], 'sales') ?></dt>
                                <dd><?php echo $currency->format($order->offsetGet('shipping')) ?></dd>
                                <?php if ((float) $order->offsetGet('tax')): ?>
                                    <dt><?php echo $this->translate('Tax', [], 'sales') ?></dt>
                                    <dd><?php echo $currency->format($order->offsetGet('tax')) ?></dd>
                                <?php endif ?>
                                <?php
                                if ((float) $order->offsetGet('discount')):
                                    $discount = json_decode($order->offsetGet('discount_detail'), true);
                                    foreach ($discount as $type => $price):
                                        ?>
                                        <dt><?php echo $this->translate('Discount(' . $type . ')', [], 'sales') ?></dt>
                                        <dd><?php echo $currency->convert($price, true) ?></dd>
                                        <?php
                                    endforeach;
                                endif;
                                ?>
                                <dt><?php echo $this->translate('Grand Total', [], 'sales') ?></dt>
                                <dd><?php echo $currency->format($order->offsetGet('total')) ?></dd>
                                <?php if ((float) $order->offsetGet('total_refunded')): ?>
                                    <dt><?php echo $this->translate('Total Refunded', [], 'sales') ?></dt>
                                    <dd><?php echo $currency->format($order->offsetGet('total_refunded')) ?></dd>
                                <?php endif ?>
                            </dl>
                        </td>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
</div>
