<form action="<?php echo $this->getBaseUrl('/sales/refund/save/') ?>" method="post" class="form-inline">
    <input type="hidden" name="csrf" value="<?php echo $this->getCsrfKey() ?>" />
    <input type="hidden" name="order_id" value="" />
    <div class="fieldset">
        <div class="input-box">
            <label for="reason" class="control-label"><?php echo $this->translate('Reason') ?></label>
            <div class="cell">
                <textarea class="form-control required" name="comment" id="reason"></textarea>
            </div>
        </div>
        <div class="input-box">
            <label for="carrier" class="control-label"><?php echo $this->translate('Carrier') ?></label>
            <div class="cell">
                <input type="text" name="carrier" class="form-control" id="carrier" />
            </div>
        </div>
        <div class="input-box">
            <label for="track-number" class="control-label"><?php echo $this->translate('Track Number') ?></label>
            <div class="cell">
                <input type="text" name="track_number" id="track-number" class="form-control" />
            </div>
        </div>
        <div class="buttons-set">
            <div class="cell">&nbsp;</div>
            <div class="cell">
                <button type="submit" class="btn btn-theme">
                    <?php echo $this->translate('Submit') ?>
                </button>
            </div>
        </div>
    </div>
</form>
