<?php
$application = $this->getVariable('model');
$order = $application->getOrder();
$status = $application['status'];
$currency = $this->getCurrency();
?>
<div class="refund-detail">
    <ul class="nav nav-tabs">
        <li role="presentation" class="active"><a href="#products" data-toggle="tab"><?php echo $this->translate('Product Infomation') ?></a></li>
        <li role="presentation"><a href="#address" data-toggle="tab"><?php echo $this->translate('Shipping Address') ?></a></li>
    </ul>
    <div class="tab-content">
        <div role="tabpanel" class="tab-pane fade in active" id="products">
            <table class="table table-no-border">
                <thead>
                    <tr class="text-nowrap">
                        <th class="text-left" colspan="2"><?php echo $this->translate('Product Infomation') ?></th>
                        <th class="text-center"><?php echo $this->translate('Price') ?></th>
                        <th class="text-center"><?php echo $this->translate('Refund Qty') ?></th>
                        <th class="text-center"><?php echo $this->translate('Detail') ?></th>
                        <th class="text-center"><?php echo $this->translate('Total') ?></th>
                    </tr>
                </thead>
                <tbody>
                    <tr class="refund-store">
                        <td colspan="2"><?php echo $order->getStore()['name'] ?></td>
                        <td class="text-right" colspan="4"><?php echo $this->translate('Order ID'), ':', $order->offsetGet('increment_id') ?></td>
                    </tr>
                    <?php
                    $items = $application->getItems();
                    $flag = true;
                    foreach ($items as $item):
                        $product = $item['product'];
                        $thumbnail = $product->getThumbnail();
                        ?>
                        <tr class="refund-list">
                            <td>
                                <img src="<?php echo strpos($thumbnail, '//') ? $thumbnail : $this->getResourceUrl('image/resized/100x/' . $thumbnail) ?>" alt="<?php echo $product['name'] ?>" width="100" height="100" />
                            </td>
                            <td>
                                <h4 class="product-name"><?php echo $product['name'] ?></h4>
                                <?php
                                $options = json_decode($item['options'], true);
                                if ($item['product_id'] && count($options)):
                                    ?>
                                    <dl class="options">
                                        <?php
                                        foreach ($product->getOptions() as $option):
                                            if (isset($options[$option->getId()])):
                                                ?>
                                                <dt><?php echo $option['title'] ?></dt>
                                                <dd>
                                                    <?php
                                                    echo (in_array($option['input'], ['select', 'radio', 'checkbox', 'multiselect']) ?
                                                            $option->getValue($options[$option->getId()]) : $options[$option->getId()])
                                                    ?>
                                                </dd>
                                                <?php
                                            endif;
                                        endforeach;
                                        ?>
                                    </dl>
                                <?php endif ?>
                            </td>
                            <td class="text-center"><?php echo $currency->convert($item['base_price'], true) ?></td>
                            <td class="text-center"><?php echo (float) $item['refunded_qty'] ?></td>
                            <?php if ($flag): ?>
                                <td class="text-center detail" rowspan="<?php echo count($items) ?>">
                                    <span><?php echo $this->translate($this->getService($application['service'])) ?></span>
                                    <span><?php echo $this->translate($this->getStatus($application['status'])) ?></span>
                                    <span><?php echo date('Y-m-d<\b\r />H:i:s', strtotime($application['created_at'])) ?></span>
                                </td>
                                <td class="text-center amount" rowspan="<?php echo count($items) ?>"><?php echo $currency->convert($application['amount'], true) ?></td>
                                <?php
                                $flag = false;
                            endif;
                            ?>
                        </tr>
                    <?php endforeach ?>
                </tbody>
            </table>
        </div>
        <div role="tabpanel" class="tab-pane fade" id="address">
            <?php echo nl2br($order['shipping_address']) ?>
        </div>
    </div>
    <div class="handler text-right"><?php echo $this->getHandler($application['service'], $status) ?></div>
    <div class="flow">
        <div class="step active"><?php echo $this->translate('Applied') ?></div>
        <?php if ($status == -1): ?>
            <div class="step<?php if ($status > 4): ?> active<?php endif ?>"><?php echo $this->translate('Refused') ?></div>
        <?php else: ?>
            <div class="step<?php if ($status): ?> active<?php endif ?>"><?php echo $this->translate('Approved') ?></div>
            <?php if ($application['service'] > 1): ?>
                <div class="step<?php if ($status > 1): ?> active<?php endif ?>"><?php echo $this->translate('Delivering') ?></div>
                <div class="step<?php if ($status > 2): ?> active<?php endif ?>"><?php echo $this->translate('Repairing') ?></div>
                <div class="step<?php if ($status > 3): ?> active<?php endif ?>"><?php echo $this->translate('Delivering') ?></div>
            <?php elseif ($application['service']): ?>
                <div class="step<?php if ($status > 1): ?> active<?php endif ?>"><?php echo $this->translate('Delivering') ?></div>
                <div class="step<?php if ($status > 2): ?> active<?php endif ?>"><?php echo $this->translate('Refunding') ?></div>
            <?php endif ?>
            <div class="step<?php if ($status > 4): ?> active<?php endif ?>"><?php echo $this->translate('Complete') ?></div>
        <?php endif ?>
    </div>
    <div class="log">
        <?php foreach ($application->getComments() as $key => $comment): ?>
            <div class="item clearfix">
                <div class="user col-xs-2 col-md-1"><?php echo $this->translate($comment['is_customer'] ? 'Buyer' : 'Seller') ?></div>
                <div class="content col-xs-10 col-md-11">
                    <p class="comment"><?php echo $comment['comment'] ?></p>
                    <p class="date">[<?php echo $comment['created_at'] ?>]</p>
                    <?php if ($images = @json_decode($comment['image'], true)): ?>
                        <ul class="images list-inline">
                            <?php foreach ($images as $i => $image): ?>
                                <li>
                                    <img src="<?php echo $this->getBaseUrl('pub/upload/refund/' . $image) ?>" class="thumbnail" alt="" />
                                </li>
                            <?php endforeach ?>
                        </ul>
                    <?php endif ?>
                </div>
            </div>
        <?php endforeach; ?>
        <form action="<?php echo $this->getBaseUrl('sales/refund/addcomment/') ?>" method="post" enctype="multipart/form-data">
            <input type="hidden" name="csrf" value="<?php echo $this->getCsrfKey() ?>" />
            <input type="hidden" name="rma_id" value="<?php echo $this->getQuery('id') ?>" />
            <div class="input-box">
                <textarea name="comment" class="form-control"></textarea>
            </div>
            <div class="input-box images">
                <input type="file" name="voucher[]" id="voucher" hidden="hidden" accept="image/*" />
                <label for="voucher" class="add-image"><span class="fa fa-camera"></span></label>
                <span>(<?php echo $this->translate('%d images allowed at most.', [5]) ?>)</span>
            </div>
            <div class="buttons-set">
                <button type="submit" name="success_url" value="<?php echo $this->getUri() ?>" class="btn btn-submit"><?php echo $this->translate('Submit') ?></button>
            </div>
        </form>
    </div>
</div>
