<?php
$application = $this->getVariable('model');
$order = $application->getOrder();
$currency = $this->getCurrency();
?>
<div class="refund-detail">
    <ul class="nav nav-tabs">
        <li role="presentation" class="active"><a href="#products" data-toggle="tab"><?php echo $this->translate('Product Infomation') ?></a></li>
        <li role="presentation"><a href="#address" data-toggle="tab"><?php echo $this->translate('Shipping Address') ?></a></li>
    </ul>
    <div class="tab-content">
        <div role="tabpanel" class="tab-pane fade in active" id="products">
            <table>
                <thead>
                    <tr class="text-nowrap">
                        <th class="text-left" colspan="2"><?php echo $this->translate('Product Infomation') ?></th>
                        <th class="text-center"><?php echo $this->translate('Price') ?></th>
                        <th class="text-center"><?php echo $this->translate('Refund Qty') ?></th>
                        <th class="text-center"><?php echo $this->translate('Applied at') ?></th>
                        <th class="text-center"><?php echo $this->translate('Total') ?></th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <th><?php echo $order->getStore()['name'] ?></th>
                        <th><?php echo $this->translate('Order ID'), ':', $order->offsetGet('increment_id') ?></th>
                    </tr>
                    <?php
                    $items = $application->getItems();
                    $flag = true;
                    foreach ($items as $item):
                        $product = $item['product'];
                        $thumbnail = $product->getThumbnail();
                        ?>
                        <tr>
                            <td>
                                <img src="<?php echo strpos($thumbnail, '//') ? $thumbnail : $this->getResourceUrl('image/resized/100x/' . $thumbnail) ?>" alt="<?php echo $product['name'] ?>" width="100" height="100" />
                            </td>
                            <td>
                                <h4 class="product-name"><?php echo $product['name'] ?></h4>
                                <?php
                                $options = json_decode($item['options'], true);
                                if ($item['product_id'] && count($options)):
                                    ?>
                                    <dl class="options">
                                        <?php
                                        foreach ($product->getOptions() as $option):
                                            if (isset($options[$option->getId()])):
                                                ?>
                                                <dt><?php echo $option['title'] ?></dt>
                                                <dd>
                                                    <?php
                                                    echo (in_array($option['input'], ['select', 'radio', 'checkbox', 'multiselect']) ?
                                                            $option->getValue($options[$option->getId()]) : $options[$option->getId()])
                                                    ?>
                                                </dd>
                                                <?php
                                            endif;
                                        endforeach;
                                        ?>
                                    </dl>
                                <?php endif ?>
                            </td>
                            <td class="text-center"><?php echo $currency->convert($item['base_price'], true) ?></td>
                            <td class="text-center"><?php echo (float) $item['qty'] ?></td>
                            <?php if ($flag): ?>
                                <td class="text-center" rowspan="<?php echo count($items) ?>"><?php echo $application['created_at'] ?></td>
                                <td class="text-center" rowspan="<?php echo count($items) ?>"><?php echo $currency->convert($application['amount'], true) ?></td>
                                <?php
                                $flag = false;
                            endif;
                            ?>
                        </tr>
                    <?php endforeach ?>
                </tbody>
            </table>
        </div>
        <div role="tabpanel" class="tab-pane fade" id="address">

        </div>
    </div>
</div>