<?php
$query = $this->getQuery();
$consumer = $this->getConsumer();
?>
<form action="<?php echo $this->getBaseUrl('oauth/auth/login/') ?>" method="post">
    <input type="hidden" name="csrf" value="<?php echo $this->getCsrfKey() ?>" />
    <?php foreach ($query as $name => $value): ?>
        <input type="hidden" name="<?php echo $name ?>" value="<?php echo $value ?>" />
    <?php endforeach ?>
    <fieldset>
        <legend><?php echo $this->translate('Login') ?></legend>
        <p><?php echo $this->translate('<strong>%s</strong> may get your basic infomation.', [$consumer['name']], 'api') ?></p>
        <div class="input-box">
            <label class="control-label required" for="login:username"><?php echo $this->translate('Username') ?></label>
            <div class="cell">
                <input type="text" name="username" id="login:username" class="form-control required" spellcheck="false" />
            </div>
        </div>
        <div class="input-box">
            <label class="control-label required" for="login:password"><?php echo $this->translate('Password') ?></label>
            <div class="cell">
                <input type="password" name="password" id="login:password" class="form-control required" minlength="6" />
            </div>
        </div>
        <div class="input-box">
            <input type="checkbox" class="required" id="login:agreement" />
            <label class="control-label" for="login:agreement">
                <?php echo $this->translate('I have already known the risks and agreed <strong>%s</strong> to get my basic infomation.', [$consumer['name']], 'api') ?>
            </label>
        </div>
        <div class="buttons-set">
            <button type="submit" class="btn btn-submit"><span><?php echo $this->translate('Login') ?></span></button>
            <?php if ($consumer['rejected_callback_url']): ?>
                <a href="<?php echo $consumer['rejected_callback_url'] ?>" class="btn btn-cancel">
                    <span><?php echo $this->translate('Reject') ?></span>
                </a>
            <?php else: ?>
                <button type="button" class="btn btn-cancel" onclick="javascript:window.close();">
                    <span><?php echo $this->translate('Reject') ?></span>
                </button>
            <?php endif ?>
        </div>
    </fieldset>
</form>