<?php
$products = $this->getProducts();
?>
<div class="container">
    <?php if (count($products)): ?>
        <ul class="thumbnails grid">
            <?php
            foreach ($products as $product):
                $thumbnail = $product->getThumbnail();
                ?>
                <li class="span3">
                    <div class="thumbnail-style thumbnail-kenburn">
                        <div class="thumbnail-img">
                            <div class="overflow-hidden">
                                <a href="<?php echo $product->getUrl($this->getCategory()); ?>">
                                    <?php if (strpos($thumbnail, '//') === false): ?>
                                        <img class="bttrlazyloading" src="<?php echo $this->getResourceUrl('image/resized/260x/' . $thumbnail) ?>" alt="<?php echo $product['name'] ?>" />
                                    <?php else: ?>
                                        <img src="<?php echo $thumbnail ?>" alt="<?php echo $product['name'] ?>" width="100%" />
                                    <?php endif; ?>
                                </a>	
                            </div>				
                        </div>
                        <h3><a class="hover-effect" href="<?php echo $product->getUrl($this->getCategory()); ?>"><?php echo mb_substr($product['name'], 0, 13, 'utf-8'); ?></a></h3>
                        <p><?php echo mb_substr(trim(strip_tags($product['description'])), 0, 38, 'utf-8') ?></p>                
                    </div>
                </li>
                <?php
            endforeach;
            ?>
        </ul><!--/thumbnails-->
    <?php else: ?>
        <p class="no-product text-center"><?php echo $this->translate('There are no products matching the selection.') ?></p>
    <?php endif ?>
</div>