<?php
$collection = $this->getStatement();
$customer = $this->getCustomer();
?>
<div class="statement">
    <table class="table">
        <thead>
            <tr>
                <td>&nbsp;&nbsp;&nbsp;&nbsp;<?php echo $this->translate('Available Balance'); ?>:
                    <span class="count">
                        <?php echo $this->getCurrency()->convert($customer->getBalance(), TRUE); ?>
                    </span>
                    <a href="<?php echo $this->getBaseUrl('balance/statement/recharge/'); ?>" type="submit" class="btn btn-theme"><?php echo $this->translate('Recharge'); ?></a>
                </td>
            </tr>
        </thead>
    </table>
    <p>&nbsp;</p>
    <table class="table table-hover">
        <thead>
            <tr>
                <th class="text-center"><?php echo $this->translate('Balance') ?></th>
                <th class="text-center"><?php echo $this->translate('Comment') ?></th>
                <th class="text-center"><?php echo $this->translate('Status') ?></th>
                <th class="text-center"><?php echo $this->translate('Date') ?></th>
                <th class="text-center"><?php echo $this->translate('Operating'); ?></th>
            </tr>
        </thead>
        <?php if (count($collection)): ?>
            <tbody>
                <?php foreach ($collection as $balance): ?>
                    <tr class="text-center"<?php if ($balance['order_id']): ?> onclick="javascript:window.open('<?php echo $this->getBaseUrl('sales/order/view/?id=' . $balance['order_id']); ?>')" <?php endif; ?>>
                        <td><?php echo (new \Seahinet\Sales\Model\Order)->getCurrency()->convert($balance['amount'], TRUE) ?></td>
                        <td><?php echo $this->translate($balance['comment']) ?></td>
                        <td>
                            <?php
                            if (!$balance['status']):
                                if ((float) $balance['amount'] < 0):
                                    echo $this->translate('Refunded');
                                else:
                                    echo $this->translate('Pending Payment');
                                endif;
                            else:
                                echo $this->translate('Successful Trade');
                            endif;
                            ?>
                        </td>
                        <td><?php echo $balance['created_at'] ?></td>
                        <td>
                            <?php
                            if (!$balance['status']):
                                if ((float) $balance['amount'] > 0):
                                    ?>
                                    <span><?php echo $this->translate('Pending Payment'); ?></span>&nbsp;&nbsp;|&nbsp;&nbsp;
                                    <a href="<?php echo $this->getBaseUrl('balance/statement/cancel/'); ?>" data-method="delete" data-params="id=<?php echo $balance->getId() ?>&csrf=<?php echo $this->getCsrfKey() ?>">
                                        <?php echo $this->translate('Cancel Recharge'); ?>
                                    </a>
                                    <?php
                                else:
                                    ?>
                                    <span><?php echo $this->translate('Successful Trade'); ?></span>
                                <?php
                                endif;
                            else:
                                ?>
                                <span><?php echo $this->translate('Successful Trade'); ?></span>
                            <?php endif; ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="5" class="text-center">
                        <?php echo $this->getChild('pager')->setCollection($collection); ?>
                    </td>
                </tr>
            </tfoot>
        <?php else: ?>
            <tfoot>
                <tr>
                    <td colspan="5" class="text-center"><?php echo $this->translate('No data to display') ?></td>
                </tr>
            </tfoot>
        <?php endif; ?>
    </table>
</div>
