<section class="section balance" data-change-after="coupon" data-url="<?php echo $this->getBaseUrl('balance/index/load/'); ?>">
    <h4 class="title"><?php echo $this->translate('Balance'); ?></h4>
    <div class="available">
        <?php
        if ($this->hasLoggedIn() && $this->getConfig()['balance/general/enable'] && $this->getConfig()['balance/general/product_for_recharge']):
            $cart = new Seahinet\Checkout\ViewModel\Cart;
            $balances = $this->getCurrentBalances();
            ?>
            <?php
            if ($balances):
                ?>
                <p>
                    <input type="checkbox" name="include_balance" id="include_balance" value="<?php echo $cart->getCurrency()->convert($balances, TRUE); ?>" <?php if ($balances): ?> checked="checked" <?php endif; ?> />
                    <label for="include_balance" class="label" title="<?php echo $this->translate('Available Balance'); ?>"><?php echo $this->translate('Available Balance'); ?></label>
                    <span class="price balance" data-price="<?php echo $cart->getCurrency()->convert($balances, TRUE) ?>">：<?php echo $cart->getCurrency()->convert($balances, TRUE) ?></span>
                    <a href="<?php echo $this->getBaseUrl('balance/index/apply/'); ?>" class="btn<?php if ($this->hasApplied()): ?> clicked<?php endif ?>" data-method="get" data-load='shipping'><?php echo $this->translate('Apply'); ?></a>
                    <a href="<?php echo $this->getBaseUrl('balance/index/cancel/'); ?>" class="btn" data-method="get" data-load='shipping'><?php echo $this->translate('Cancel') ?></a>
                </p>
                <?php
            else:
                ?>
                <p><?php echo $this->translate('Current available balance.'); ?></p>
            <?php
            endif;
        endif;
        ?>
    </div>
</section>
