<?php
$collection = $this->getStatement();
?>
<div class="statement">
    <table class="table">
        <thead>
            <tr>
                <td class="col-lg-8 col-md-8"><?php echo $this->translate('Available Balance'); ?>:<?php //echo $collection[][''] ?></td>
                <td class="col-lg-4 col-md-4 text-right">
                    <p class="text-right"><a href="<?php echo $this->getBaseUrl('balance/statement/recharge/'); ?>" type="submit" class="btn btn-theme"><?php echo $this->translate('Recharge'); ?></a></p>
                </td>
            </tr>
        </thead>
    </table>
    <p>&nbsp;</p>
    <table class="table table-hover">
        <thead>
            <tr>
                <th class="text-center"><?php echo $this->translate('Balance') ?></th>
                <th class="text-center"><?php echo $this->translate('Comment') ?></th>
                <th class="text-center"><?php echo $this->translate('Status') ?></th>
                <th class="text-center"><?php echo $this->translate('Date') ?></th>
                <th class="text-center"><?php echo $this->translate('Operating'); ?></th>
            </tr>
        </thead>
        <?php if (count($collection)): ?>
            <tbody>
                <?php foreach ($collection as $balance): ?>
                    <tr class="text-center">
                        <td><?php echo (new \Seahinet\Sales\Model\Order)->getCurrency()->convert($balance['amount'], TRUE) ?></td>
                        <td><?php echo $this->translate($balance['comment']) ?></td>
                        <td><?php echo $this->translate($balance['status'] ? 'Successful Trade' : 'Pending Payment') ?></td>
                        <td><?php echo $balance['created_at'] ?></td>
                        <td>
                            <?php
                            if ($balance['status'] != 0):
                                ?>
                                <span><?php echo $this->translate('Payment Success'); ?></span>
                                <?php
                            else:
                                ?>
                                <span><?php echo $this->translate('Pending Payment'); ?></span>&nbsp;&nbsp;|&nbsp;&nbsp;
                                <a href="<?php echo $this->getBaseUrl('balance/statement/cancel/'); ?>" data-method="delete" data-params="id=<?php echo $balance->getId() ?>&csrf=<?php echo $this->getCsrfKey() ?>"><?php echo $this->translate('Cancel Recharge'); ?></a>
                            <?php endif; ?>
                        </td>
                    </tr>
                <?php endforeach ?>
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="5" class="text-center">
                        <?php echo $this->getChild('pager')->setCollection($collection); ?>
                    </td>
                </tr>
            </tfoot>
        <?php else: ?>
            <tfoot>
                <tr>
                    <td colspan="5" class="text-center"><?php echo $this->translate('No data to display') ?></td>
                </tr>
            </tfoot>
        <?php endif; ?>
    </table>
</div>
