<?php
$collection = $this->getStatement();
?>
<div class="statement">
    <table class="table table-hover">
        <thead>
            <tr>
                <th class="text-center"><?php echo $this->translate('Balance') ?></th>
                <th class="text-center"><?php echo $this->translate('Comment') ?></th>
                <th class="text-center"><?php echo $this->translate('Status') ?></th>
                <th class="text-center"><?php echo $this->translate('Date') ?></th>
                <th class="text-center"><?php echo $this->translate('Operating'); ?></th>
            </tr>
        </thead>
        <?php if (count($collection)): ?>
            <tbody>
                <?php foreach ($collection as $balance): ?>
                    <tr class="text-center">
                        <td><?php echo (int) $balance['amount'] ?></td>
                        <td><?php echo $this->translate($balance['comment']) ?></td>
                        <td><?php echo $this->translate($balance['status'] ? 'Payment Success' : 'Pending Payment') ?></td>
                        <td><?php echo $balance['created_at'] ?></td>
                        <td>
                            <?php
                            if ($balance['status'] != 0):
                                ?>
                                <span><?php echo $this->translate('Payment Success'); ?></span>
                                <?php
                            else:
                                ?>
                                <a href="<?php echo $this->getBaseUrl('balance/statement/?id=' . $balance['id']); ?>"><?php echo $this->translate('To Pay'); ?></a>&nbsp;&nbsp;|&nbsp;&nbsp;
                                <a href="<?php echo $this->getBaseUrl('balance/statement/cancel/?id=' . $balance['id']); ?>" data-method="delete" data-params="id=<?php echo $balance->getId() ?>"><?php echo $this->translate('Cancel Recharge'); ?></a>
                            <?php endif; ?>
                        </td>
                    </tr>
                <?php endforeach ?>
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="5" class="text-center">
                        <?php echo $this->getChild('pager')->setCollection($collection); ?>
                    </td>
                </tr>
            </tfoot>
        <?php else: ?>
            <tfoot>
                <tr>
                    <td colspan="5" class="text-center"><?php echo $this->translate('No data to display') ?></td>
                </tr>
            </tfoot>
        <?php endif; ?>
    </table>
</div>
<p class="text-right"><a href="<?php echo $this->getBaseUrl('balance/statement/recharge/'); ?>" type="submit" class="btn btn-theme"><?php echo $this->translate('Recharge'); ?></a></p>
