<div class="recharge">
    <form action="<?php echo $this->getBaseUrl('balance/statement/save/') ?>" method="post" class="form-inline" enctype="multipart/form-data">
        <input type="hidden" name="csrf" value="<?php echo $this->getCsrfKey() ?>" />
        <input type="hidden" name="id" />
        <div class="fieldset">
            <div class="input-box">
                <label class="control-label" for=""><?php echo $this->translate('Amount Charge'); ?>:</label>
                <div class="cell">
                    <input type="text" class="form-control required invalid" name="integral" /><span><?php echo $this->translate(''); ?></span>
                </div>
            </div>
            <div class="input-box">
                <label class="control-label" for=""><?php echo $this->translate('Comment'); ?>:</label>
                <div class="cell"><textarea cols="40" name="integral" class="form-control"></textarea></div>
            </div>
            <div class="input-box">
                <label class="control-label"><?php echo $this->translate('Status'); ?>:</label>
                <div class="cell">
                    <select name="status">
                        <option value="0"><?php echo $this->translate('No');  ?></option>
                        <option value="1"><?php echo $this->translate('Yes'); ?></option>
                    </select>
                </div>
            </div>
            <div class="buttons-set">
                <div class="cell">&nbsp;</div>
                <div class="cell">
                    <button type="submit" class="btn btn-theme"><?php echo $this->translate('To Pay'); ?></button>
                </div>
            </div>
    </form>
</div>