<?php
$customer = $this->getCustomer();
?>
<div class="recharge">
    <form action="<?php echo $this->getBaseUrl('balance/statement/save/') ?>" method="post" class="form-inline" enctype="multipart/form-data">
        <input type="hidden" name="csrf" value="<?php echo $this->getCsrfKey() ?>" />
        <input type="hidden" name="id" />
        <input type="hidden" name="customer_id" value="<?php echo $customer->getId(); ?>" />
        <div class="fieldset">
            <div class="input-box">
                <label class="control-label" for="balance"><?php echo $this->translate('Amount Charge'); ?>:</label>
                <div class="cell">
                    <input type="text" class="form-control required invalid" name="balance" id="balance" /><span><?php echo $this->translate(''); ?></span>
                </div>
            </div>
            <div class="input-box">
                <label class="control-label" for=""><?php echo $this->translate('Comment'); ?>:</label>
                <div class="cell">
                    <textarea cols="40" name="comment" id="comment" class="form-control"></textarea>
                </div>
            </div>
            <div class="buttons-set">
                <div class="cell">&nbsp;</div>
                <div class="cell">
                    <button type="submit" class="btn btn-theme"><?php echo $this->translate('To Pay'); ?></button>
                </div>
            </div>
        </div>
    </form>
</div>