<?php
$crumbs = $this->getCrumbs();
if (count($crumbs)):
    $last = array_pop($crumbs);
    ?>
    <div class="container">
        <div class="breadcrumb-m hidden-lg">
            <a href="javascript:viod(0);" onclick="javascript:history.back(-1);" class="fa fa-angle-left headimg-left col-xs-1 col-sm-1"></a>
            <div class="content-list col-xs-10 col-sm-10">
                <a href="" class="col-xs-4 col-sm-4"><?php echo $this->translate('Product');?></a>
                <a class="col-xs-4 col-sm-4" href="#description" aria-controls="description" role="tab" data-toggle="tab"><?php echo $this->translate('Description') ?></a>
                <a href="" class="col-xs-4 col-sm-4"><?php echo $this->translate('Review');?></a>
            </div>
            <a href="javascript:viod(0);" class="fa fa-bars headimg-right col-xs-1 col-sm-1"></a>
        </div>
    </div>
<?php endif; ?>
