<?php
$crumbs = $this->getCrumbs();
if (count($crumbs)):
    $last = array_pop($crumbs);
    ?>
    <div class="container">
        <div class="breadcrumb-m hidden-lg">
            <a href="javascript:viod(0);" onclick="javascript:history.back(-1);" class="fa fa-bars fa-2x breadcrumb-right col-xs-1 col-sm-1"></a>
            <div class="content-list col-xs-10 col-sm-10">
                <a href="<?php echo $this->getBaseUrl(); ?>"><img src="<?php echo $this->getBaseUrl('/pub/theme/mobile/frontend/images/breadcrumb-logo.png') ?>" width="40" /></a>
            </div>
            <a href="javascript:viod(0);" class="fa fa-filter fa-2x col-xs-1 col-sm-1" role="button" data-toggle="collapse" href="#collapseExample" aria-expanded="false" aria-controls="collapseExample"></a>
        </div>
    </div>
<?php endif; ?>
