---
product:
    icon: sitemap
    title: Product Management
    priority: 15
    children:
        -
            link: product_manage/
            title: Product Management
            priority: 0
        -
            link: category_manage/
            title: Category Management
            priority: 10
system:
    children:
        -
            link: config/product/
            title: Product Configuration
            priority: 45
