<div id="modal-edit-category" class="modal fade" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <form action="<?php echo $this->getBaseUrl('retailer/category/save/') ?>" method="post">
                <input type="hidden" name="csrf" value="<?php echo $this->getCsrfKey() ?>" />
                <input type="hidden" name="id" />
                <input type="hidden" name="parent_id" />
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="newcatModalLabel"><?php echo $this->translate('New Category') ?></h4>
                </div>
                <div class="modal-body">
                    <div class="input-box">
                        <label class="control-label"><?php echo $this->translate('Name') ?></label>
                        <input type="text" name="name" class="form-control required" />
                    </div>
                    <div class="input-box">
                        <label class="control-label"><?php echo $this->translate('Uri Key') ?></label>
                        <input type="text" name="uri_key" class="form-control required" />
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary"><?php echo $this->translate('Save') ?></button>
                    <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo $this->translate('Cancel') ?></button>
                </div>
            </form>
        </div>
    </div>
</div>