<?php
$categories = $this->getCategories();
?>
<div class="category-edit">
    <input type="checkbox" class="selectall" id="checkall" name="checkall[]" data-cbtype="all" />
    <label for="checkall"><?php echo $this->translate('Select All'); ?></label>
    <a href="<?php echo $this->getBaseUrl('retailer/category/remove/'); ?>" class="batch-delete" data-method="delete"><?php echo $this->translate('Batch Delete'); ?></a>
    <div class="buttons-set text-right">
        <button data-toggle="modal" data-target="#modal-edit-category" class="btn btn-theme"><span class="fa fa-plus" aria-hidden="true"></span><?php echo $this->translate('Add New Category') ?></button>
    </div>
</div>
<div class="category-content">
    <ul class="table categories-title col-lg-12 col-md-12">
        <li class="col-lg-1 col-md-1"></li>
        <li class="col-lg-9 col-md-9"><?php echo $this->translate('Category Name'); ?></li>
        <li class="col-lg-2 col-md-2 text-center"><?php echo $this->translate('Operation'); ?></li>
    </ul>
    <ul class="table categories-list">
        <?php
        if (count($categories)):
            foreach ($categories[0] as $category):
                ?>
                <li class="clearfix" data-id="<?php echo $category->getId() ?>">
                    <input type="hidden" name="order[]" value="<?php echo $category->getId() ?>" />
                    <div class="select-category"><input type="checkbox" name="category_store" data-id="<?php echo $category->getId() ?>" /></div>
                    <h4 class="category-name active text-left font-14">
                        <?php echo $category->getName() ?>
                    </h4>
                    <div class="action font-12">
                        <a href="#modal-edit-category" data-toggle="modal" data-info='{parent_id:<?php echo $category->getId() ?>}'><?php echo $this->translate('Append') ?></a>
                        <a href="#modal-edit-category" data-toggle="modal" data-info='{name:"<?php echo $category->getName() ?>",id:<?php echo $category->getId() ?>,parent_id:<?php echo (int) $category['parent_id'] ?>,uri_key:"<?php echo $category['uri_key'] ?>"}'><?php echo $this->translate('Edit') ?></a>
                        <a href="<?php echo $this->getBaseUrl('retailer/category/delete/') ?>" data-method="delete" data-params="id=<?php echo $category->getId() ?>&csrf=<?php echo $this->getCsrfKey() ?>"><?php echo $this->translate('Delete') ?></a>
                        <a href="javascript:void(0);" class="move"><span class="fa fa-arrows" aria-hidden="true"></span><span class="sr-only"><?php echo $this->translate('Move') ?></span></a>
                    </div>
                    <?php if (!empty($categories[$category->getId()])): ?>
                        <ul class="children">
                            <?php foreach ($categories[$category->getId()] as $child): ?>
                                <li class="child clearfix" data-id="<?php echo $child->getId() ?>">
                                    <input type="hidden" name="order[]" value="<?php echo $child->getId() ?>" />
                                    <h4 class="category-name font-12 text-left">
                                        <?php echo $child->getName() ?>
                                    </h4>
                                    <div class="action font-12">
                                        <a href="#modal-edit-category" data-toggle="modal" data-info='{name:"<?php echo $child->getName() ?>",id:<?php echo $child->getId() ?>,parent_id:<?php echo (int) $child['parent_id'] ?>,uri_key:"<?php echo $child['uri_key'] ?>"}'><?php echo $this->translate('Edit') ?></a>
                                        <a href="<?php echo $this->getBaseUrl('retailer/category/delete/') ?>" data-method="delete" data-params="id=<?php echo $child->getId() ?>&csrf=<?php echo $this->getCsrfKey() ?>"><?php echo $this->translate('Delete') ?></a>
                                        <a href="javascript:void(0);" class="move"><span class="fa fa-arrows" aria-hidden="true"></span><span class="sr-only"><?php echo $this->translate('Move') ?></span></a>
                                    </div>
                                </li>
                            <?php endforeach ?>
                        </ul>
                    <?php endif ?>
                </li>
                <?php
            endforeach;
        else:
            ?>
            <li class="text-center"><?php echo $this->translate('There is no category available.') ?></li>
            <?php endif ?>
    </ul>
</div>