---
admin_resource_category_list:
    - Are you sure to delete this record?
    - Are you sure to delete these records?
admin_resource_category_edit:
    - Are you sure to delete this record?
    - Are you sure to delete these records?
admin_resource_list:
    - Are you sure to delete this record?
    - Are you sure to delete these records?