---
admin_resource:
    update: grid
    root:
        children:
            head:
                action:
                    -
                        method: addScript
                        params: [{src:'backend/js/modal.js',defer:'defer',async:'async'}]
                    -
                        method: addScript
                        params: [{src:'backend/js/tab.js',defer:'defer',async:'async'}]
                    -
                        method: addScript
                        params: backend/js/collapse.js
                    -
                        method: addLink
                        params: backend/css/resource.css
                    -
                        method: addScript
                        params: backend/js/jquery.ui/core.js
                    -
                        method: addScript
                        params: backend/js/jquery.ui/widget.js
                    -
                        method: addScript
                        params: backend/js/jquery.ui/mouse.js
                    -
                        method: addScript
                        params: backend/js/jquery.ui/draggable.js
                    -
                        method: addScript
                        params: backend/js/jquery.ui/droppable.js
                    -
                        method: addScript
                        params: backend/js/jquery.fileupload/core.js
                    -
                        method: addScript
                        params: backend/js/resource.js
                    -
                        method: setTitle
                        params: Resource Management / CMS
            content:
                children:
                    grid:
                        type: Seahinet\Admin\ViewModel\Resource\Explorer
                        template: resource/explorer
            extra:
                children:
                    modal:
                        type: Seahinet\Admin\ViewModel\Resource\Modal
                        template: resource/upload
admin_resource_nav:
    update: frontend
    root:
        template: page/ajax
        unset: [head]
        children:
            content:
                unset: [breadcrumb,messages]
                children:
                    main:
                        type: Seahinet\Admin\ViewModel\Resource\Explorer
                        template: resource/navigation
admin_resource_list:
    update: frontend
    root:
        template: page/ajax
        unset: [head]
        children:
            content:
                unset: [breadcrumb,messages]
                children:
                    main:
                        type: Seahinet\Admin\ViewModel\Resource\Explorer
                        template: resource/list
                        children:
                            pager:
                                type: Seahinet\Lib\ViewModel\Pager
                                action:
                                    -
                                        method: setVariable
                                        params: 
                                            - canJump
                                            - 0
admin_popup_images_list:
    update: grid
    root:
        template: page/ajax
        unset: [head]
        children:
            content:
                unset: [breadcrumb,messages]
                children:
                    grid:
                        type: Seahinet\Admin\ViewModel\Resource\Grid\Resource
                        template: resource/gridpopup
                                        
