---
resource:
    update: default
    root:
        children:
            content:
                children:
                    page:
                        type: Seahinet\resource\ViewModel\resource
admin_resource_category_list:
    update: grid
    root:
        children:
            head:
                action:
                    -
                        method: setTitle
                        params: resource category Management / Resouces
            content:
                children:
                    breadcrumb:
                        action:
                            -
                                method: addCrumb
                                params: [{link:':ADMIN/resource_Category/',label:'resource category Management'}]
                            -
                                method: addAdditional
                                params: [{link:':ADMIN/resource_Category/edit/',label:'Add New category'}]
                    grid:
                        type: Seahinet\Admin\ViewModel\Resource\Category
admin_resource_category_edit:
    update: edit
    root:
        children:
            head:
                action:
                    -
                        method: addScript
                        params: [{src:'backend/js/resource/resource.js',defer:'defer',async:'async'}]
            content:
                children:
                    breadcrumb:
                        action:
                            -
                                method: addCrumb
                                params: [{link:':ADMIN/resource_Category/',label:'resource category Management'}]
                            -
                                method: addCrumb
                                params: [{label:'Edit'}]
                    edit:
                        type: Seahinet\Admin\ViewModel\Resource\CategoryEdit
                        children:
                            category_language:
                                type: Seahinet\Lib\ViewModel\Template
                                template: Resource/category_language
admin_resource_list:
    update: grid
    root:
        children:
            head:
                action:
                    -
                        method: setTitle
                        params: resource Management / Resouces
            content:
                children:
                    breadcrumb:
                        action:
                            -
                                method: addCrumb
                                params: [{link:':ADMIN/resource_resource/',label:'Resource Management'}]
                    grid:
                        type: Seahinet\Admin\ViewModel\Resource\Resource
                        children:
                            list_image_v:
                                type: Seahinet\Lib\ViewModel\Template
                                template: Resource/list_image_v