---
admin_resource_category_list:
    update: grid
    root:
        children:
            head:
                action:
                    -
                        method: setTitle
                        params: Resource Category / Resource Management / CMS
            content:
                children:
                    breadcrumb:
                        action:
                            -
                                method: addCrumb
                                params: [{link:':ADMIN/resource_category/',label:'Resource Category'}]
                            -
                                method: addAdditional
                                params: [{link:':ADMIN/resource_category/edit/',label:'Add New Category'}]
                    grid:
                        type: Seahinet\Admin\ViewModel\Resource\Grid\Category
admin_resource_category_edit:
    update: edit
    root:
        children:
            content:
                children:
                    breadcrumb:
                        action:
                            -
                                method: addCrumb
                                params: [{link:':ADMIN/resource_category/',label:'Resource Category'}]
                            -
                                method: addCrumb
                                params: [{label:'Edit'}]
                    edit:
                        type: Seahinet\Admin\ViewModel\Resource\Edit\Category
admin_resource_list:
    update: grid
    root:
        children:
            head:
                action:
                    -
                        method: addScript
                        params: [{src:'backend/js/modal.js',defer:'defer',async:'async'}]
                    -
                        method: addScript
                        params: [{src:'backend/js/tab.js',defer:'defer',async:'async'}]
                    -
                        method: addScript
                        params: backend/js/jquery.ui/widget.js
                    -
                        method: addScript
                        params: backend/js/jquery.fileupload/core.js
                    -
                        method: addScript
                        params: backend/js/jquery.fileupload/config.js
                    -
                        method: setTitle
                        params: Resource Management / CMS
            content:
                children:
                    breadcrumb:
                        action:
                            -
                                method: addCrumb
                                params: [{link:':ADMIN/resource_resource/',label:'Resource Management'}]
                            -
                                method: addAdditional
                                params: [{'label':'Upload','data':{'toggle':'modal','target':'#resource-modal','upload':'upload','reload':'reload'}}]
                    grid:
                        type: Seahinet\Admin\ViewModel\Resource\Grid\Resource
                        template: resource/grid
            extra:
                children:
                    modal:
                        type: Seahinet\Admin\ViewModel\Resource\Modal
                        template: resource/modal
admin_popup_images_list:
    update: grid
    root:
        template: page/ajax
        unset: [head]
        children:
            content:
                children:
                    grid:
                        type: Seahinet\Admin\ViewModel\Resource\Grid\Resource
                        template: resource/gridpopup
                                        
