---
admin:
    Resource:
        icon: file-image-o
        title: Resource
        priority: 30
        children:
            -
                link: 'Resource_Category/'
                title: 'Category'
                priority: 0
            -
                link: 'Resource_Resource/'
                title: 'Resource'
                priority: 10
