<?php
$currency = $this->getCart()->getCurrency();
?>
<div class="view clearfix">
    <?php if ($customer = $this->getCustomer()): ?>
        <div class="panel">
            <div class="panel-heading">
                <h4 class="panel-title"><?php echo $this->translate('Customer Information', [], 'sales') ?></h4>
            </div>
            <div class="panel-body">
                ID: <?php echo $customer->getId() ?><br />
                <?php echo $this->translate('Username'), ': ', $customer['username'] ?>
            </div>
        </div>
    <?php endif ?>
    <?php if ($billing = $this->getCart()->offsetGet('billing_address')): ?>
        <div class="panel">
            <div class="panel-heading">
                <h4 class="panel-title"><?php echo $this->translate('Billing Address', [], 'sales') ?></h4>
            </div>
            <div class="panel-body">
                <?php echo nl2br($billing) ?>
            </div>
        </div>
    <?php endif ?>
    <?php if ($shipping = $this->getCart()->offsetGet('shipping_address')): ?>
        <div class="panel">
            <div class="panel-heading">
                <h4 class="panel-title"><?php echo $this->translate('Shipping Address', [], 'sales') ?></h4>
            </div>
            <div class="panel-body">
                <?php echo nl2br($shipping) ?>
            </div>
        </div>
    <?php endif ?>
    <?php if ($shippingMethod = $this->getCart()->offsetGet('shipping_method')): ?>
        <div class="panel">
            <div class="panel-heading">
                <h4 class="panel-title"><?php echo $this->translate('Shipping Method', [], 'sales') ?></h4>
            </div>
            <div class="panel-body">
                <?php echo $shippingMethod ?>
            </div>
        </div>
    <?php endif ?>
    <?php if ($paymentMethod = $this->getCart()->offsetGet('payment_method')): ?>
        <div class="panel">
            <div class="panel-heading">
                <h4 class="panel-title"><?php echo $this->translate('Payment Method', [], 'sales') ?></h4>
            </div>
            <div class="panel-body">
                <?php echo $paymentMethod ?>
            </div>
        </div>
    <?php endif ?>
    <div class="panel wide">
        <div class="panel-heading">
            <h4 class="panel-title"><?php echo $this->translate('Product(s)', [], 'sales') ?></h4>
        </div>
        <div class="panel-body grid table-responsive">
            <table class="table table-hover table-striped table-no-border">
                <thead class="sort-by">
                    <tr>
                        <th><?php echo $this->translate('Store', [], 'sales') ?></th>
                        <th><?php echo $this->translate('Warehouse', [], 'sales') ?></th>
                        <th><?php echo $this->translate('Product Name', [], 'sales') ?></th>
                        <th><?php echo $this->translate('SKU', [], 'sales') ?></th>
                        <th><?php echo $this->translate('Options', [], 'sales') ?></th>
                        <th><?php echo $this->translate('Price', [], 'sales') ?></th>
                        <th><?php echo $this->translate('Qty', [], 'sales') ?></th>
                        <th><?php echo $this->translate('Total', [], 'sales') ?></th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->getCollection() as $item): ?>
                        <tr<?php if (isset($item['id'])): ?> data-id="<?php echo $item['id'] ?>"<?php endif ?>>
                            <td><?php echo $item['store'] ?></td>
                            <td><?php echo $item['warehouse'] ?></td>
                            <td><?php echo $item['product_name'] ?></td>
                            <td><?php echo $item['sku'] ?></td>
                            <td>
                                <?php
                                $options = json_decode($item['options'], true);
                                if ($item['product_id'] && count($options)) {
                                    foreach ($item['product']->getOptions() as $option) {
                                        if (isset($options[$option->getId()])) {
                                            echo $option['title'], ': ', (in_array($option['input'], ['select', 'radio', 'checkbox', 'multiselect']) ?
                                                    $option->getValue($options[$option->getId()]) : $options[$option->getId()]), '<br />';
                                        }
                                    }
                                }
                                ?>
                            </td>
                            <td><?php echo $currency->format($item['price']) ?></td>
                            <td><?php echo $item['qty'] ?></td>
                            <td><?php echo $currency->format($item['total']) ?></td>
                        </tr>
                    <?php endforeach ?>
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="8" class="text-right">

                        </td>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
</div>
