<?php
$order = $this->getOrder();
$currency = $this->getOrder()->getCurrency();
?>
<div class="view clearfix">
    <div class="buttons-set text-right">
        <?php if ($this->canCancel()): ?>
            <a href="<?php echo $this->getAdminUrl('sales_order/cancel/?id=' . $order->getId()) ?>" class="btn btn-cancel">
                <?php echo $this->translate('Cancel', [], 'sales') ?>
            </a>
        <?php endif ?>
        <?php if ($this->canHold()): ?>
            <a href="<?php echo $this->getAdminUrl('sales_order/hold/?id=' . $order->getId()) ?>" class="btn">
                <?php echo $this->translate('Hold', [], 'sales') ?>
            </a>
        <?php elseif ($this->canUnhold()): ?>
            <a href="<?php echo $this->getAdminUrl('sales_order/unhold/?id=' . $order->getId()) ?>" class="btn">
                <?php echo $this->translate('Unhold', [], 'sales') ?>
            </a>
        <?php endif ?>
        <?php if ($this->canInvoice()): ?>
            <a href="<?php echo $this->getAdminUrl('sales_order/invoice/?id=' . $order->getId()) ?>" class="btn">
                <?php echo $this->translate('Invoice', [], 'sales') ?>
            </a>
        <?php endif ?>
        <?php if ($this->canShip()): ?>
            <a href="<?php echo $this->getAdminUrl('sales_order/ship/?id=' . $order->getId()) ?>" class="btn">
                <?php echo $this->translate('Ship', [], 'sales') ?>
            </a>
        <?php endif ?>
    </div>
    <div class="panel">
        <div class="panel-heading">
            <h4 class="panel-title"><?php echo $this->translate('Order Infomation', [], 'sales') ?></h4>
        </div>
        <div class="panel-body">
            <?php echo $this->translate('ID'), ': ', $order['increment_id'] ?><br />
            <?php echo $this->translate('Status'), ': ', $this->translate($this->getStatus()->offsetGet('name'), [], 'sales') ?>
        </div>
    </div>
    <div class="panel">
        <div class="panel-heading">
            <h4 class="panel-title"><?php echo $this->translate('Customer Infomation', [], 'sales') ?></h4>
        </div>
        <div class="panel-body"><?php if ($customer = $this->getCustomer()): ?>
                ID: <?php echo $customer->getId() ?><br />
                <?php echo $this->translate('Username'), ': ', $customer['username'] ?>
            <?php endif ?></div>
    </div>
    <div class="panel">
        <div class="panel-heading">
            <h4 class="panel-title"><?php echo $this->translate('Billing Address', [], 'sales') ?></h4>
        </div>
        <div class="panel-body">
            <?php echo nl2br($order->offsetGet('billing_address')) ?>
        </div>
    </div>
    <div class="panel">
        <div class="panel-heading">
            <h4 class="panel-title"><?php echo $this->translate('Shipping Address', [], 'sales') ?></h4>
        </div>
        <div class="panel-body">
            <?php echo nl2br($order->offsetGet('shipping_address')) ?>
        </div>
    </div>
    <div class="panel">
        <div class="panel-heading">
            <h4 class="panel-title"><?php echo $this->translate('Shipping Method', [], 'sales') ?></h4>
        </div>
        <div class="panel-body">
            <?php echo $this->translate($order->getShippingMethod()->getLabel()) ?>
        </div>
    </div>
    <div class="panel">
        <div class="panel-heading">
            <h4 class="panel-title"><?php echo $this->translate('Payment Method', [], 'sales') ?></h4>
        </div>
        <div class="panel-body">
            <?php echo $this->translate($order->getPaymentMethod()->getLabel()), '<br />', $this->translate('Order was placed using %s', [$order->offsetGet('currency')], 'sales') ?>
        </div>
    </div>
    <div class="panel wide">
        <div class="panel-heading">
            <h4 class="panel-title"><?php echo $this->translate('Item(s)') ?></h4>
        </div>
        <div class="panel-body grid table-responsive">
            <table class="table table-hover table-striped table-no-border">
                <thead class="sort-by">
                    <tr>
                        <th><?php echo $this->translate('Product Name', [], 'sales') ?></th>
                        <th><?php echo $this->translate('SKU', [], 'sales') ?></th>
                        <th><?php echo $this->translate('Options', [], 'sales') ?></th>
                        <th><?php echo $this->translate('Price', [], 'sales') ?></th>
                        <th><?php echo $this->translate('Qty', [], 'sales') ?></th>
                        <th><?php echo $this->translate('Total', [], 'sales') ?></th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->getCollection() as $item): ?>
                        <tr<?php if (isset($item['id'])): ?> data-id="<?php echo $item['id'] ?>"<?php endif ?>>
                            <td><?php echo $item['product_name'] ?></td>
                            <td><?php echo $item['sku'] ?></td>
                            <td>
                                <?php
                                if ($item['product_id']) {
                                    $options = json_decode($item['options'], true);
                                    foreach ($item['product']->getOptions() as $option) {
                                        if (isset($options[$option->getId()])) {
                                            echo $option['title'], ': ', (in_array($option['input'], ['select', 'radio', 'checkbox', 'multiselect']) ?
                                                    $option->getValue($options[$option->getId()]) : $options[$option->getId()]), '<br />';
                                        }
                                    }
                                }
                                ?>
                            </td>
                            <td><?php echo $currency->format($item['price']) ?></td>
                            <td><?php echo $item['qty'] ?></td>
                            <td><?php echo $currency->format($item['total']) ?></td>
                        </tr>
                    <?php endforeach ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
