<?php
$refund = $this->getRefund();
$order = $this->getOrder();
$currency = $order->getCurrency();
?>
<div class="view clearfix">
    <div class="panel">
        <div class="panel-heading">
            <h4 class="panel-title"><?php echo $this->translate('Return &amp; Refund', [], 'sales') ?></h4>
        </div>
        <div class="panel-body">
            <?php echo $this->translate('ID'), ': ', $refund['id'] ?><br />
            <?php echo $this->translate('Order ID'), ': ', $order['increment_id'] ?><br />
            <?php
            if ($store = $order->getStore()) {
                echo $this->translate('Store'), ': ', $store->offsetGet('name');
            }
            ?><br />
            <?php
            if ($language = $order->getLanguage()) {
                echo $this->translate('Language'), ': ', $language->offsetGet('name');
            }
            ?>
        </div>
    </div>
    <div class="panel">
        <div class="panel-heading">
            <h4 class="panel-title"><?php echo $this->translate('Customer Infomation', [], 'sales') ?></h4>
        </div>
        <div class="panel-body"><?php if ($customer = $this->getCustomer()): ?>
                ID: <?php echo $customer->getId() ?><br />
                <?php echo $this->translate('Username'), ': ', $customer['username'] ?>
            <?php endif ?></div>
    </div>
    <div class="panel wide">
        <div class="panel-heading">
            <h4 class="panel-title"><?php echo $this->translate('Product(s)') ?></h4>
        </div>
        <div class="panel-body grid table-responsive">
            <table class="table table-hover table-striped table-no-border">
                <thead class="sort-by">
                    <tr>
                        <th><?php echo $this->translate('Product Name', [], 'sales') ?></th>
                        <th><?php echo $this->translate('SKU', [], 'sales') ?></th>
                        <th><?php echo $this->translate('Options', [], 'sales') ?></th>
                        <th><?php echo $this->translate('Price', [], 'sales') ?></th>
                        <th><?php echo $this->translate('Qty', [], 'sales') ?></th>
                        <th><?php echo $this->translate('Total', [], 'sales') ?></th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->getCollection() as $item): ?>
                        <tr<?php if (isset($item['id'])): ?> data-id="<?php echo $item['id'] ?>"<?php endif ?>>
                            <td><?php echo $item['product_name'] ?></td>
                            <td><?php echo $item['sku'] ?></td>
                            <td>
                                <?php
                                $options = json_decode($item['options'], true);
                                if ($item['product_id'] && count($options)) {
                                    foreach ($item['product']->getOptions() as $option) {
                                        if (isset($options[$option->getId()])) {
                                            echo $option['title'], ': ', (in_array($option['input'], ['select', 'radio', 'checkbox', 'multiselect']) ?
                                                    $option->getValue($options[$option->getId()]) : $options[$option->getId()]), '<br />';
                                        }
                                    }
                                }
                                ?>
                            </td>
                            <td><?php echo $currency->format($item['price']) ?></td>
                            <td><?php echo (float) $item['qty'] ?></td>
                            <td><?php echo $currency->format($item['total']) ?></td>
                        </tr>
                    <?php endforeach ?>
                </tbody>
            </table>
        </div>
    </div>
    <div class="panel">
        <div class="panel-heading">
            <h4 class="panel-title"><?php echo $this->translate('Action', [], 'sales') ?></h4>
        </div>
        <div class="panel-body">
            <?php echo $this->getHandler() ?>
            <div class="clearfix">
                <?php foreach ($this->getRefund()->getComments() as $comment): ?>
                    <div class="col-xs-1">
                        <?php echo $this->translate($comment['is_customer'] ? 'Buyer' : 'Seller') ?>
                    </div>
                    <div class="col-xs-11">
                        <p class="comment"><?php echo $comment['comment'] ?></p>
                        <p class="date">[<?php echo $comment['created_at'] ?>]</p>
                        <?php if ($images = @json_decode($comment['image'], true)): ?>
                            <ul class="images list-inline">
                                <?php foreach ($images as $i => $image): ?>
                                    <li>
                                        <img src="<?php echo $this->getBaseUrl('pub/upload/refund/' . $image) ?>" class="thumbnail" alt="" />
                                    </li>
                                <?php endforeach ?>
                            </ul>
                        <?php endif ?>
                    </div>
                <?php endforeach ?>
            </div>
        </div>
    </div>
    <div class="panel">
        <div class="panel-heading">
            <h4 class="panel-title"><?php echo $this->translate('Total', [], 'sales') ?></h4>
        </div>
        <div class="panel-body">
            <dl class="dl-horizontal">
                <dt><?php echo $this->translate('Subtotal', [], 'sales') ?></dt>
                <dd><?php echo $currency->format($order->offsetGet('subtotal')) ?></dd>
                <dt><?php echo $this->translate('Shipping &amp; Handling', [], 'sales') ?></dt>
                <dd><?php echo $currency->format($order->offsetGet('shipping')) ?></dd>
                <dt><?php echo $this->translate('Tax', [], 'sales') ?></dt>
                <dd><?php echo $currency->format($order->offsetGet('tax')) ?></dd>
                <dt><?php echo $this->translate('Discount', [], 'sales') ?></dt>
                <dd><?php echo $currency->format($order->offsetGet('discount')) ?></dd>
                <dt><?php echo $this->translate('Grand Total', [], 'sales') ?></dt>
                <dd><?php echo $currency->format($order->offsetGet('total')) ?></dd>
            </dl>
        </div>
    </div>
</div>
