<?php
$shipment = $this->getShipment();
$order = $this->getOrder();
$currency = $order->getCurrency();
?>
<div class="view clearfix">
    <div class="buttons-set text-right">
        <a href="<?php echo $this->getAdminUrl('sales_shipment/print/?id=' . $order->getId()) ?>" class="btn btn">
            <?php echo $this->translate('Print', [], 'sales') ?>
        </a>
    </div>
    <div class="panel">
        <div class="panel-heading">
            <h4 class="panel-title"><?php echo $this->translate('Shipment Infomation', [], 'sales') ?></h4>
        </div>
        <div class="panel-body">
            <?php echo $this->translate('ID'), ': ', $shipment['increment_id'] ?><br />
            <?php echo $this->translate('Shipping &amp; Handling', [], 'sales') ?>：<?php echo $currency->format($order->offsetGet('shipping')) ?><br />
            <?php echo $this->translate('Tax', [], 'sales') ?>：<?php echo $currency->format($order->offsetGet('tax')) ?><br />
            <?php echo $this->translate('Discount', [], 'sales') ?>：<?php echo $currency->format($order->offsetGet('discount')) ?><br />
            <?php echo $this->translate('Total Paid', [], 'sales') ?>：<?php echo $currency->format($order->offsetGet('total_paid')) ?><br />
            <?php echo $this->translate('Total Refunded', [], 'sales') ?>：<?php echo $currency->format($order->offsetGet('total_refunded')) ?><br />
            <?php echo $this->translate('Total'), ': ', $currency->format($order->offsetGet('base_total')) ?>
        </div>
    </div>
    <div class="panel">
        <div class="panel-heading">
            <h4 class="panel-title"><?php echo $this->translate('Customer Infomation', [], 'sales') ?></h4>
        </div>
        <div class="panel-body"><?php if ($customer = $this->getCustomer()): ?>
                ID: <?php echo $customer->getId() ?><br />
                <?php echo $this->translate('Username'), ': ', $customer['username'] ?>
            <?php endif ?></div>
    </div>
    <div class="panel">
        <div class="panel-heading">
            <h4 class="panel-title"><?php echo $this->translate('Order Infomation', [], 'sales') ?></h4>
        </div>
        <div class="panel-body">
            <?php echo $this->translate('ID'), ': ', $order['increment_id'] ?><br />
            <?php echo $this->translate('Status'), ': ', $this->translate($order->getStatus()->offsetGet('name'), [], 'sales') ?><br />
            <?php
            if ($store = $order->getStore()) {
                 echo $this->translate('Store'), ': ', $store->offsetGet('name');
             }
            ?><br />
            <?php
             if ($language = $order->getLanguage()) {
                 echo $this->translate('Language'), ': ', $language->offsetGet('name');
             }
             ?>
        </div>
    </div>
    <div class="panel">
        <div class="panel-heading">
            <h4 class="panel-title"><?php echo $this->translate('Shipping Method', [], 'sales') ?></h4>
        </div>
        <div class="panel-body">
            <?php echo $this->translate($order->getShippingMethod()->getLabel()) ?>
        </div>
    </div>
    <div class="panel">
        <div class="panel-heading">
            <h4 class="panel-title"><?php echo $this->translate('Billing Address', [], 'sales') ?></h4>
        </div>
        <div class="panel-body">
            <?php echo nl2br($order->offsetGet('billing_address')) ?>
        </div>
    </div>
    <div class="panel">
        <div class="panel-heading">
            <h4 class="panel-title"><?php echo $this->translate('Shipping Address', [], 'sales') ?></h4>
        </div>
        <div class="panel-body">
            <?php echo nl2br($order->offsetGet('shipping_address')) ?>
        </div>
    </div>
    <div class="panel">
        <div class="panel-heading">
            <h4 class="panel-title"><?php echo $this->translate('Comment') ?></h4>
        </div>
        <div class="panel-body">
                <div class="input-box">
                    <?php echo $shipment['comment'] ?>
                </div>
        </div>
     </div>
</div>
