<?php
$shipment = $this->getShipment();
$order = $this->getOrder();
$currency = $order->getCurrency();
?>
<div class="view clearfix">
    <div class="buttons-set text-right">
        <a href="<?php echo $this->getAdminUrl('sales_shipment/print/?id=' . $order->getId()) ?>" class="btn btn">
            <?php echo $this->translate('Print', [], 'sales') ?>
        </a>
    </div>
    <div class="panel">
        <div class="panel-heading">
            <h4 class="panel-title"><?php echo $this->translate('Shipment Infomation', [], 'sales') ?></h4>
        </div>
        <div class="panel-body">
            <?php echo $this->translate('ID'), ': ', $shipment['increment_id'] ?><br />
            <?php echo $this->translate('Order ID'), ': ', $order['increment_id'] ?><br />
            <?php
            if ($store = $order->getStore()) {
                echo $this->translate('Store'), ': ', $store->offsetGet('name');
            }
            ?><br />
            <?php
            if ($language = $order->getLanguage()) {
                echo $this->translate('Language'), ': ', $language->offsetGet('name');
            }
            ?>
        </div>
    </div>
    <div class="panel">
        <div class="panel-heading">
            <h4 class="panel-title"><?php echo $this->translate('Customer Infomation', [], 'sales') ?></h4>
        </div>
        <div class="panel-body"><?php if ($customer = $this->getCustomer()): ?>
                ID: <?php echo $customer->getId() ?><br />
                <?php echo $this->translate('Username'), ': ', $customer['username'] ?>
            <?php endif ?></div>
    </div>
    <div class="panel">
        <div class="panel-heading">
            <h4 class="panel-title"><?php echo $this->translate('Shipping Address', [], 'sales') ?></h4>
        </div>
        <div class="panel-body">
            <?php echo nl2br($order->offsetGet('shipping_address')) ?>
        </div>
    </div>
    <div class="panel">
        <div class="panel-heading">
            <h4 class="panel-title"><?php echo $this->translate('Billing Address', [], 'sales') ?></h4>
        </div>
        <div class="panel-body">
            <?php echo nl2br($order->offsetGet('billing_address')) ?>
        </div>
    </div>
    <div class="panel">
        <div class="panel-heading">
            <h4 class="panel-title"><?php echo $this->translate('Shipping Method', [], 'sales') ?></h4>
        </div>
        <div class="panel-body">
            <?php echo $this->translate($order->getShippingMethod()->getLabel()) ?>
        </div>
    </div>
    <div class="panel">
        <div class="panel-heading">
            <h4 class="panel-title"><?php echo $this->translate('Comment') ?></h4>
        </div>
        <div class="panel-body"><?php echo $shipment['comment'] ?></div>
    </div>
    <div class="panel wide">
        <div class="panel-heading">
            <h4 class="panel-title"><?php echo $this->translate('Product(s)') ?></h4>
        </div>
        <div class="panel-body grid table-responsive">
            <table class="table table-hover table-striped table-no-border">
                <thead class="sort-by">
                    <tr>
                        <th><?php echo $this->translate('Product Name', [], 'sales') ?></th>
                        <th><?php echo $this->translate('SKU', [], 'sales') ?></th>
                        <th><?php echo $this->translate('Options', [], 'sales') ?></th>
                        <th><?php echo $this->translate('Price', [], 'sales') ?></th>
                        <th><?php echo $this->translate('Qty', [], 'sales') ?></th>
                        <th><?php echo $this->translate('Total', [], 'sales') ?></th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->getCollection() as $item): ?>
                        <tr<?php if (isset($item['id'])): ?> data-id="<?php echo $item['id'] ?>"<?php endif ?>>
                            <td><?php echo $item['product_name'] ?></td>
                            <td><?php echo $item['sku'] ?></td>
                            <td>
                                <?php
                                $options = json_decode($item['options'], true);
                                if ($item['product_id'] && count($options)) {
                                    foreach ($item['product']->getOptions() as $option) {
                                        if (isset($options[$option->getId()])) {
                                            echo $option['title'], ': ', (in_array($option['input'], ['select', 'radio', 'checkbox', 'multiselect']) ?
                                                    $option->getValue($options[$option->getId()]) : $options[$option->getId()]), '<br />';
                                        }
                                    }
                                }
                                ?>
                            </td>
                            <td><?php echo $currency->format($item['price']) ?></td>
                            <td><?php echo $item['qty'] ?></td>
                            <td><?php echo $currency->format($item['total']) ?></td>
                        </tr>
                    <?php endforeach ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
