<!DOCTYPE html>
<html class="no-js" lang="<?php echo $this->getLang() ?>">
    <head>
        <!--[if lt IE 9]><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><![endif]-->
        <!--[if (gte IE 9)|(!IE)]><!-->
        <meta charset="UTF-8" />
        <!--<![endif]-->
        <?php echo $this->head ?>
    </head>
    <body class="<?php echo $this->getBodyClass() ?>">
        <?php echo $this->globalNotice ?>
        <?php echo $this->content ?>
        <?php echo $this->extra ?>
    </body>
</html>