<!--=== Footer ===-->
<div class="footer-v1">
    <div class="container">
        <div class="row-fluid">
            <!-- About -->
            <div class="span3 md-margin-bottom-40">
                <a href="home.php"><img id="logo-footer" class="footer-logo" src="<?php echo $this->getPubUrl('frontend/images/logo2-default.png') ?>" alt=""></a>
                <p>About website dolor sit amet, consectetur adipiscing elit. Maecenas eget nisl id libero tincidunt sodales.</p>
                <p>Duis eleifend fermentum ante ut aliquam. Cras mi risus, dignissim sed adipiscing ut, placerat non arcu.</p>
            </div><!--/col-md-3-->
            <!-- End About -->
            <!-- Latest -->
            <div class="span3 md-margin-bottom-40">
                <div class="posts">
                    <div class="headline"><h3>Latest Posts</h3></div>
                    <ul class="list-unstyled latest-list">
                        <li>
                            <a href="#">Incredible content</a>
                            <small>May 8, 2014</small>
                        </li>
                        <li>
                            <a href="#">Best shoots</a>
                            <small>June 23, 2014</small>
                        </li>
                        <li>
                            <a href="#">New Terms and Conditions</a>
                            <small>September 15, 2014</small>
                        </li>
                    </ul>
                </div>
            </div><!--/col-md-3-->
            <!-- End Latest -->

            <!-- Link List -->
            <div class="span3 md-margin-bottom-40">
                <div class="headline"><h3>Useful Links</h3></div>
                <ul class="list-unstyled link-list">
                    <li><a href="#">About us</a></li>
                    <li><a href="#">Portfolio</a></li>
                    <li><a href="#">Latest jobs</a></li>
                    <li><a href="#">Community</a></li>
                    <li><a href="#">Contact us</a></li>
                </ul>
            </div><!--/col-md-3-->
            <!-- End Link List -->

            <!-- Address -->
            <div class="span3 map-img md-margin-bottom-40">
                <div class="headline"><h3>Contact Us</h3></div>
                <address class="md-margin-bottom-40">
                    Hongkong Green Garden Road No. 63<br>
                    QingDao, CN <br>
                    Phone: 156-2108-3308 <br>
                    WeiBo: ITpeachBaby <br>
                    Email: <a href="mailto:ymt0519@163.com" class="">ymt0519@163.com</a>
                </address>
            </div><!--/col-md-3-->
            <!-- End Address -->
        </div>
    </div>

    <div class="copyright">
        <div class="container">
            <div class="row">
                <div class="span6">
                    <p>
                        2016 © All Rights Reserved.
                        <a href="#">Privacy Policy</a>
                    </p>
                </div>

                <!-- Social Links -->
                <div class="span6">
                    <ul class="social-icons list-inline">
                        <!--                        <li>
                                                       <a href="#" class="tooltips" data-toggle="tooltip" data-placement="top" title="" data-original-title="Weixin">
                                                           <i class="fa fa-weixin"></i>
                                                       </a>
                                                   </li>
                                                   <li>
                                                       <a href="#" class="tooltips" data-toggle="tooltip" data-placement="top" title="" data-original-title="Skype">
                                                           <i class="fa fa-skype"></i>
                                                       </a>
                                                   </li>
                                                   <li>
                                                       <a href="#" class="tooltips" data-toggle="tooltip" data-placement="top" title="" data-original-title="Google Plus">
                                                           <i class="fa fa-google-plus"></i>
                                                       </a>
                                                   </li>
                                                   <li>
                                                       <a href="#" class="tooltips" data-toggle="tooltip" data-placement="top" title="" data-original-title="Linkedin">
                                                           <i class="fa fa-linkedin"></i>
                                                       </a>
                                                   </li>
                                                   <li>
                                                       <a href="#" class="tooltips" data-toggle="tooltip" data-placement="top" title="" data-original-title="Pinterest">
                                                           <i class="fa fa-pinterest"></i>
                                                       </a>
                                                   </li>
                                                   <li>
                                                       <a href="#" class="tooltips" data-toggle="tooltip" data-placement="top" title="" data-original-title="Twitter">
                                                           <i class="fa fa-twitter"></i>
                                                       </a>
                                                   </li>
                                                   <li>
                                                       <a href="#" class="tooltips" data-toggle="tooltip" data-placement="top" title="" data-original-title="Dribbble">
                                                           <i class="fa fa-dribbble"></i>
                                                       </a>
                                                   </li>-->
                        <li><a href="#" data-original-title="Feed" class="social_rss"></a></li>
                        <li><a href="#" data-original-title="Facebook" class="social_facebook"></a></li>
                        <li><a href="#" data-original-title="Twitter" class="social_twitter"></a></li>
                        <li><a href="#" data-original-title="Goole Plus" class="social_googleplus"></a></li>
                        <li><a href="#" data-original-title="Pinterest" class="social_pintrest"></a></li>
                        <li><a href="#" data-original-title="Linkedin" class="social_linkedin"></a></li>
                        <li><a href="#" data-original-title="Vimeo" class="social_vimeo"></a></li>
                    </ul>
                </div>
                <!-- End Social Links -->
            </div>
        </div>
    </div><!--/copyright-->
</div>
<!--=== End Copyright ===-->

<!-- JS Global Compulsory -->			
<script type="text/javascript" src="<?php echo $this->getPubUrl('frontend/js/modernizr.custom.js') ?>"></script>
<!-- JS Implementing Plugins -->           
<script type="text/javascript" src="<?php echo $this->getPubUrl('frontend/plugins/flexslider/jquery.flexslider-min.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getPubUrl('frontend/plugins/parallax-slider/js/modernizr.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getPubUrl('frontend/plugins/parallax-slider/js/jquery.cslider.js') ?>"></script> 
<!-- JS Page Level -->
<script src="http://libs.baidu.com/jquery/1.11.3/jquery.min.js"></script>
<!--[if IE]>
              <script src="http://libs.useso.com/js/html5shiv/3.7/html5shiv.min.js"></script>
<![endif]-->
<!--[if lt IE 9]>
    <script src="<?php echo $this->getPubUrl('frontend/js/respond.js') ?>"></script>
<![endif]-->
