<?php
$title = $this->getTitle();
if (strpos($title, '/')) {
    $t = [];
    foreach (explode('/', $title) as $part) {
        $t[] = $this->translate(trim($part));
    }
    $title = implode(' / ', $t);
}
?>
<meta http-equiv="X-UA-Compatible" content="IE=Edge" />
<meta name="renderer" content="webkit" />
<title><?php echo $title ?></title>
<meta name="description" content="<?php echo $this->getDescription() ?>" />
<meta name="keywords" content="<?php echo $this->getKeywords() ?>" />
<meta name="robots" content="<?php echo $this->getConfig()['theme/global/robots'] ?>" />
<?php if ($base = $this->getBase()): ?>
    <base href="<?php echo is_string($base) ? $base : $base['href'] ?>"<?php if (is_array($base) && isset($base['target'])): ?> target="<?php echo $base['target'] ?>"<?php endif ?> />
<?php endif ?>
<?php echo $this->getMeta(), $this->getLink(), $this->getScript() ?>
<script>
    window.GLOBAL = {BASE_URL: '<?php echo $this->getBaseUrl() ?>', PUB_URL: '<?php echo $this->getPubUrl() ?>', LOCALE: '<?php echo $this->getLocale() ?>', FORMAT: '<?php echo $this->getFormat() ?>'};
<?php echo $this->translate ?>
</script>
