<?php
$title = $this->getTitle();
if (strpos($title, '/')) {
    $t = [];
    foreach (explode('/', $title) as $part) {
        $t[] = $this->translate(trim($part));
    }
    $title = implode(' / ', $t);
}
?>
<meta http-equiv="X-UA-Compatible" content="IE=Edge" />
<title><?php echo $title ?></title>
<?php echo $this->getMeta(), $this->getLink(), $this->getScript(); ?>
<script>
    window.GLOBAL = {BASE_URL: '<?php echo $this->getBaseUrl() ?>',PUB_URL:'<?PHP echo $this->getPubUrl() ?>'};
</script>
