<div class="message-box<?php if (!$this->getVariable('inline')): ?> container<?php endif ?>"><?php foreach ($this->getMessages() as $message): ?>
        <div class="alert alert-<?php echo $message['level'] ?? 'info' ?>">
            <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>
            <?php echo is_scalar($message) ? $message : $message['message'] ?>
        </div>
    <?php endforeach ?></div>
