<?php
if ($this->getCollection()):
    $current = $this->getCurrentPage();
    $pages = $this->getAllPages();
    $limit = $this->getLimit();
//     if ($this->showLabel()) {
//         $total = min($current * $limit, $this->getCount());
//         echo $this->translate('Display %d - %d of %d record(s).', [min($total, ($current - 1) * $limit + 1), $total, $this->getCount()], 'pager');
//     }
  ?>
    <ol class="pager">
        
<!--         <li class="first"> -->
<!--           <a href="<?php echo $this->getPagerUrl(1) ?>"><?php echo $this->translate('First', [], 'pager') ?></a> -->
<!--         </li> -->
        <li class="prev">
        	<?php if ($current > 1): ?>
            	<a href="<?php echo $this->getPagerUrl($current - 1) ?>">
            <?php endif ?>
            <span><?php echo $this->translate('Previous', [], 'pager') ?></span>
            <?php if ($current > 1): ?>
            	</a>
            <?php endif ?>
        </li>
        <?php for ($p = 1; $p <= $pages; $p++): ?>
            <li>
                <?php if ($current === $p): ?>
                    <span class="current">
                    <?php else: ?>
                        <a href="<?php echo $this->getPagerUrl($p) ?>">
                        <?php endif ?>
                        <?php echo $p ?>
                        <?php if ($current === $p): ?>
                    </span>
                <?php else: ?>
                    </a>
                <?php endif ?>
            </li>
        <?php endfor ?>
        
        
        <li class="next">
        	<?php if ($current < $pages): ?>
            	<a href="<?php echo $this->getPagerUrl($current + 1) ?>">
            <?php endif; ?>           	
            <span><?php echo $this->translate('Next', [], 'pager') ?></span>
            <?php if ($current < $pages): ?>            	
            	</a>
            <?php endif; ?>  
        </li>
<!--             <li class="last"> -->
   <!--             <a href="<?php echo $this->getPagerUrl($pages) ?>"><?php echo $this->translate('Last', [], 'pager') ?></a>-->
<!--             </li> -->

		<li class="total">
		  &nbsp;
		  <?php echo $this->translate('total '.$pages.'  pages') ?>
		</li>
		
		<li class="pageto">
		   &nbsp;
		   <?php echo $this->translate('to') ?>
		   <input type="text" name="whichpage" id="whichpage" />
		   <?php echo $this->translate('page') ?>
		   &nbsp;&nbsp;
		   <button type="button">Confirm</button>
		   
		</li>
    </ol>
<?php endif; ?>
