<!DOCTYPE html>
<html class="no-js" lang="<?php echo str_replace('_', '-', $this->getLang()) ?>">
    <head>
        <!--[if lt IE 9]>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <![endif]-->
        <!--[if (gte IE 9)|(!IE)]><!-->
        <meta charset="UTF-8" />
        <!--<![endif]-->
        <?php echo $this->head ?>
    </head>
    <body class="<?php echo $this->getBodyClass() ?>">
        <?php echo $this->globalNotice ?>
        <header class="header clearfix">
            <?php echo $this->header ?>
        </header>
        <?php echo $this->beforeContent ?>
        <div class="main-container">
            <?php echo $this->content ?>
        </div>
        <?php echo $this->afterContent ?>
        <footer class="footer clearfix">
            <?php echo $this->footer ?>
        </footer>
        <?php echo $this->extra ?>
    </body>
</html>