<?php
$order = $this->getVariable('model');
$currency = $this->getCurrency();
?>
<div class="panel-heading">
    <h4 class="panel-title"><?php echo $this->translate('Return &amp; Refund'); ?></h4>
</div>
<div class="form-rma">
    <form action="<?php echo $this->getBaseUrl('/sales/refund/save/') ?>" method="post" class="form-inline" enctype="multipart/form-data">
        <input type="hidden" name="csrf" value="<?php echo $this->getCsrfKey() ?>" />
        <input type="hidden" name="order_id" value="<?php echo $order->getId() ?>" />
        <div class="service col-xs-12 col-sm-12"> 
            <div class="input-box">
                <label for="service " class="control-label required col-xs-2 col-sm-1"><?php echo $this->translate('Service') ?></label>
                <div class="cell col-xs-10 col-sm-11">
                    <select name="service" id="service" class="form-control required ">
                        <?php foreach ($this->getServices() as $key => $service): ?>
                            <option value="<?php echo $key ?>"><?php echo $this->translate($service) ?></option>
                        <?php endforeach ?>
                    </select>
                </div>
            </div>
        </div>
        <div class="table-no-border">
            <?php
            foreach ($this->getItems() as $item):
                if ($item['qty']):
                    $product = $item['product'];
                    $thumbnail = $product->getThumbnail();
                    ?>
                    <ul class="col-xs-12 col-sm-12 product">
                        <li  class="col-xs-2 col-sm-2">
                            <img src="<?php echo strpos($thumbnail, '//') === false ? $this->getResourceUrl('image/resized/100x/' . $thumbnail) : $thumbnail ?>" width="50" height="50" alt="<?php echo $item['product_name'] ?>" />
                        </li>
                        <li  class="col-xs-7 col-sm-7 padding-5">
                            <h4 class="product-name"><?php echo $item['product_name'] ?></h4>
                            <?php
                            $options = json_decode($item['options'], true);
                            if ($item['product_id'] && count($options)):
                                ?>
                                <ul class="options">
                                    <?php
                                    foreach ($product->getOptions() as $option):
                                        if (isset($options[$option->getId()])):
                                            ?>
                                            <li><?php echo $option['title'] ?>
                                                <span>
                                                    <?php
                                                    echo (in_array($option['input'], ['select', 'radio', 'checkbox', 'multiselect']) ?
                                                            $option->getValue($options[$option->getId()]) : $options[$option->getId()])
                                                    ?>
                                                    </pan>
                                            </li>
                                            <?php
                                        endif;
                                    endforeach;
                                    ?>
                                </ul>
                            <?php endif; ?>
                        </li>
                        <li class="text-right"> x <?php echo (float) $item['qty'] ?></li>
                        <li class="font-12 text-right"><?php echo $currency->convert($item['base_total'], true) ?></li>
                        <li class=" text-right">
                            <div class="qty text-nowrap">
                                <label class="spin minus" for="qty-<?php echo $item['id'] ?>">-</label>
                                <input type="number" name="qty[<?php echo $item['id'] ?>]" id="qty-<?php echo $item['id'] ?>"
                                       min="0"
                                       max="<?php echo (float) $item['qty'] ?>"
                                       class=" required" value="<?php echo (float) $item['qty'] ?>" />
                                <label class="spin plus" for="qty-<?php echo $item['id'] ?>">+</label>
                            </div>
                        </li>
                    </ul>
                    <?php
                endif;
            endforeach;
            ?>
        </div>
        <div class="fieldset">
            <div class="input-box">
                <label for="reason" class="control-label col-xs-2 col-sm-1"><?php echo $this->translate('Reason') ?></label>
                <div class="cell col-xs-10 col-sm-11">
                    <select name="reason" id="reason" class="form-control required ">
                        <?php foreach ($this->getReasons() as $key => $reason): ?>
                            <option value="<?php echo $key ?>"><?php echo $this->translate($reason) ?></option>
                        <?php endforeach ?>
                        <option value="0"><?php echo $this->translate('Other') ?></option>
                    </select>
                </div>
            </div>
            <div class="input-box">
                <label for="comment" class="control-label col-xs-2 col-sm-1"><?php echo $this->translate('Comment') ?></label>
                <div class="cell col-xs-10 col-sm-11">
                    <textarea name="comment" class="form-control required " id="comment" placeholder="<?php echo $this->translate('Please describe the reasons for refunding in detail.') ?>"></textarea>
                </div>
            </div>
             <div class="input-box">
                <label for="voucher" class="control-label"><?php echo $this->translate('Voucher') ?></label>
                <div class="cell images">
                    <input type="file" name="voucher[]" id="voucher" hidden="hidden" accept="image/*" />
                    <label for="voucher" class="add-image"><span class="fa fa-camera"></span></label>
                    <span>(<?php echo $this->translate('%d images allowed at most.', [5]) ?>)</span>
                </div>
            </div>
            <div class="buttons-set text-center padding-5">
                <div class="cell">&nbsp;</div>
                <div class="cell">
                    <button type="submit" class="btn btn-theme">
                        <?php echo $this->translate('Submit') ?>
                    </button>
                </div>
            </div>
        </div>
    </form>
</div>
