<?php
$applications = $this->getApplication();
$currency = $this->getCurrency();
?>

<div id="Has-sold" class="seller-tab">
    <div class="tab-nav">
        <ul id="myTab" class="nav nav-tabs col-xs-12 col-sm-12">
            <li class="active col-xs-3 col-sm-3">
                <a href="#all" data-toggle="tab">
                    全部
                </a>
            </li>
            <li class="col-xs-3 col-sm-3">
                <a href="#delivery" data-toggle="tab">
                    待付款
                </a>
            </li>
            <li class="col-xs-3 col-sm-3">
                <a href="#payment" data-toggle="tab">
                    待发货
                </a>
            </li>
            <li class="col-xs-3 col-sm-3">
                <a href="#refund" data-toggle="tab">
                    待收货
                </a>
            </li>
        </ul>
    </div>	
    <div class="search col-xs-12 col-sm-12 padding-5" >
        <div class="search_center">
            <i class="fa fa-search" aria-hidden="true"></i>
            <input type="search" name="search" value="收件人姓名/电话/运单号/地址信息关键字" class="col-xs-12 col-sm-12"/>
        </div>
    </div>
    <div id="Product-details" class="tab-content">
        <div class="tab-pane fade in active" id="all">
            <div class="menu-ctn padding-5">
                <ul  class="col-xs-12 col-sm-12 title-nav  name">
                    <li class="col-xs-5 col-sm-5 text-left font-12"><a href="" target="_blank">123456's Store</a></li>
                    <li class="col-xs-7 col-sm-7 text-right font-12"><a href="">实付:￥208.00(含运费: ￥10.00)</a></li>	
                </ul>
                <ul class="col-xs-12 col-sm-12 inline bt">
                    <li class="col-xs-2 col-sm-2"><img src="http://ecomv2.seahinet.test1/pub/resource/image/resized/173x/TB1jLZiNFXXXXapXFXXXXXXXXXX_!!0-item_pic.jpg" style="display: inline;" width="50" height="50"></li>
                    <li class="col-xs-7 col-sm-7"><span class="text-ovflow">女装 打褶中裙 173805 优衣库UNIQLO</span><p class="choose col-xs-12 col-sm-12 "><span class="col-xs-4 col-sm-4">颜色:棕色</span><span  class="col-xs-4 col-sm-4">尺码:XL</span><span  class="col-xs-4 col-sm-4"></span></p></li>
                    <li class="col-xs-3  col-sm-3 text-right">
                        <span class="price ">￥198.00</span>
                        <span>x1</span>
                        <span class=" color-blue font-14">已付款</span>
                    </li>
                </ul>
            </div>
            <div class="bt-link">
                <ul class="col-xs-12 col-sm-12 inline text-center operation ">
                    <li class="col-xs-2 col-sm-6" ></li>
                    <li class="col-xs-2 col-sm-6"></li>	
                    <li class="col-xs-4 col-sm-6" data-toggle="modal" data-target="#modal-refund"><span><a href="">退换申请</a></span></li>
                    <li class="col-xs-4 col-sm-6"><a href="">查看详情</a></li>		
                </ul>	
            </div>
        </div>
        <div class="tab-pane fade " id="delivery">
            2
        </div>
        <div class="tab-pane fade" id="payment">
            3
        </div>
        <div class="tab-pane fade " id="refund">
            4
        </div>
    </div>
</div>
<!--
<p class="font-14 pad-10"><?php echo $this->translate('Return &amp; Refund') ?></p>
<div class="table-responsive">
    <table class="table table-no-border refund-list">
        <?php if (count($applications)): ?>
            <colgroup>
                <col width="116" />
                <col />
                <col width="1" />
                <col width="1" />
                <col width="1" />
                <col width="1" />
            </colgroup>
            <thead>
                <tr class="text-nowrap">
                    <th class="text-left" colspan="2"><?php echo $this->translate('Product Infomation') ?></th>
                    <th class="text-center col-lg-1 col-md-1"><?php echo $this->translate('Price') ?></th>
                    <th class="text-center col-lg-1 col-md-1"><?php echo $this->translate('Refund Qty') ?></th>
                    <th class="text-center col-lg-1 col-md-1"><?php echo $this->translate('Last Modified') ?></th>
                    <th class="text-center col-lg-2 col-md-2"><?php echo $this->translate('Action') ?></th>
                </tr>
            </thead>
            <tbody>
                <?php
                foreach ($applications as $application):
                    $order = $application->getOrder();
                    $flag = true;
                    ?>
                    <tr class="store">
                        <th colspan="2">
                            <?php echo $order->getStore()['name'] ?>
                        </th>
                        <th colspan="4" class="text-nowrap text-right">
                            <span class="label"><?php echo $this->translate('Order ID') ?>:</span>
                            <span><?php echo $order['increment_id'] ?></span>
                        </th>
                    </tr>
                    <?php
                    $items = $application->getItems();
                    foreach ($items as $item):
                        $product = $item['product'];
                        $thumbnail = $product->getThumbnail();
                        ?>
                        <tr class="list">
                            <td>
                                <img src="<?php echo strpos($thumbnail, '//') === false ? $this->getResourceUrl('image/resized/100x/' . $thumbnail) : $thumbnail ?>" alt="<?php echo $product['name'] ?>" width="100" height="100" />
                            </td>
                            <td>
                                <h4 class="product-name"><?php echo $product['name'] ?></h4>
                                <?php
                                $options = json_decode($item['options'], true);
                                if ($item['product_id'] && count($options)):
                                    ?>
                                    <dl class="options">
                                        <?php
                                        foreach ($product->getOptions() as $option):
                                            if (isset($options[$option->getId()])):
                                                ?>
                                                <dt><?php echo $option['title'] ?></dt>
                                                <dd>
                                                    <?php
                                                    echo (in_array($option['input'], ['select', 'radio', 'checkbox', 'multiselect']) ?
                                                            $option->getValue($options[$option->getId()]) : $options[$option->getId()])
                                                    ?>
                                                </dd>
                                                <?php
                                            endif;
                                        endforeach;
                                        ?>
                                    </dl>
                                <?php endif ?>
                            </td>
                            <td class="text-center"><?php echo $currency->convert($item['base_price'], true) ?></td>
                            <td class="text-center"><?php echo (float) $item['refunded_qty'] ?></td>
                            <?php if ($flag): ?>
                                <td class="text-center text-nowrap border_left" rowspan="<?php echo count($items) ?>">
                                    <?php echo date('Y-m-d<\b\r />H:i:s', strtotime($application['updated_at'])) ?>
                                </td>
                                <td class="text-center action" rowspan="<?php echo count($items) ?>">
                                    <a href="<?php echo $this->getBaseUrl($this->getOrderUrl()), '?id=', $order->getId() ?>"><?php echo $this->translate('Order Details') ?></a><br />
                                    <a href="<?php echo $this->getBaseUrl($this->getViewUrl()), '?id=', $application->getId() ?>"><?php echo $this->translate('View Details') ?></a>
                                </td>
                                <?php
                                $flag = false;
                            endif;
                            ?>
                        </tr>
                        <?php
                    endforeach;
                endforeach;
            else:
                ?>
                <tr>
                    <td colspan="6" class="text-center"><?php echo $this->translate('You have placed no refund application.') ?></td>
                </tr>
            <?php endif ?>
        </tbody>
    </table>
</div>
-->

