<?php
$applications = $this->getApplication();
$currency = $this->getCurrency();
$profile = new Seahinet\Customer\ViewModel\Dashboard\Profile;
$payment = $profile->getPendingPayment();
$shipment = $profile->getShipping();
$review = $profile->getReviewing();
$refund1 = new Seahinet\Sales\ViewModel\Refund;
$refund = $refund1->getApplication();
$refund->getSelect()->where->notEqualTo('status', 5);
?>
<div id="Has-sold" class="seller-tab">
    <ul id="myTab" class="nav nav-tabs col-xs-12 col-sm-12 font-12 text-center">
        <li class="active col-xs-3 col-sm-3">
            <a href="<?php echo $this->getBaseUrl('sales/order/list/'); ?>">
                <?php echo $this->translate('All'); ?>(<span><?php echo count($applications); ?></span>)
            </a>
        </li>
        <li class="col-xs-3 col-sm-3">
            <a href="<?php echo $this->getBaseUrl('sales/order/list/?status=1'); ?>">
                <?php echo $this->translate('Pending Payment'); ?>(<span><?php echo $profile->getPendingPayment(); ?></span>)
            </a>
        </li>
        <li class="col-xs-3 col-sm-3">
            <a href="<?php echo $this->getBaseUrl('sales/order/list/?status=2'); ?>">
                <?php echo $this->translate('Delivering', [], 'customer'); ?>(<span><?php echo $profile->getShipping(); ?></span>)
            </a>
        </li>
        <li class="col-xs-3 col-sm-3">
            <a href="<?php echo $this->getBaseUrl('sales/order/list/?status=3'); ?>">
                <?php echo $this->translate('Reviewing', [], 'customer'); ?>(<span><?php echo $profile->getReviewing(); ?></span>)
            </a>
        </li>
    </ul>
    <div class="search padding-5 col-xs-12 col-sm-12">
        <form class="form-inline" action="" method="get" novalidate = "novalidate">
            <span class="fa fa-search" aria-hidden="true"></span>
            <input type="search" name="increment_id" value="" class="col-xs-10 col-sm-10" />
            <button type="submit" class="btn btn-default"><?php echo $this->translate('Search'); ?></button>
        </form>
    </div>
    <?php if (count($applications)): ?>
        <div id="Product-details" class="tab-content">
            <div class="tab-pane fade in active" id="all">
                <?php
                foreach ($applications as $application):
                    $order = $application->getOrder();
                    $flag = true;
                    ?>
                    <div class="menu-ctn">
                        <ul  class="col-xs-12 col-sm-12 title-nav name  padding-5 font-12">
                            <li class="col-xs-5 col-sm-5 text-left"><?php echo $order->getStore()['name'] ?></li>
                            <li class="col-xs-7 col-sm-7 text-right">
                                <?php echo $currency->format($order->offsetGet('total')); ?>
                                <span class="font-12">
                                    <?php echo $this->translate('(Including Shipping Fee: %s)', [$currency->format($order->offsetGet('shipping'))]); ?>
                                </span>
                            </li>	
                        </ul>
                        <table class="table inline bt padding-5">
                            <?php
                            $items = $application->getItems();
                            foreach ($items as $item):
                                $product = $item['product'];
                                $thumbnail = $product->getThumbnail();
                                ?>
                                <tr>
                                    <td class="col-xs-2 col-sm-2">
                                        <img src="<?php echo strpos($thumbnail, '//') === false ? $this->getResourceUrl('image/resized/100x/' . $thumbnail) : $thumbnail ?>" alt="<?php echo $product['name'] ?>" width="50" height="50" />
                                    </td>
                                    <td class="col-xs-6 col-sm-6">
                                        <h4 class="font-12"><?php echo $product['name'] ?></h4>
                                        <?php
                                        $options = json_decode($item['options'], true);
                                        if ($item['product_id'] && count($options)):
                                            ?>
                                            <dl class="options">
                                                <?php
                                                foreach ($product->getOptions() as $option):
                                                    if (isset($options[$option->getId()])):
                                                        ?>
                                                        <dt><?php echo $option['title'] ?></dt>
                                                        <dd>
                                                            <?php
                                                            echo (in_array($option['input'], ['select', 'radio', 'checkbox', 'multiselect']) ?
                                                                    $option->getValue($options[$option->getId()]) : $options[$option->getId()])
                                                            ?>
                                                        </dd>
                                                        <?php
                                                    endif;
                                                endforeach;
                                                ?>
                                            </dl>
                                        <?php endif ?>
                                    </td>
                                    <td class="col-xs-1 col-sm-1 text-right">
                                        <span class="price "><?php echo $currency->convert($item['base_price'], true) ?></span>
                                        <span><?php echo (float) $item['refunded_qty'] ?></span>
                                    </td>
                                    <?php if ($flag) : ?>
                                        <td rowspan="<?php echo count($items) ?>" class="col-xs-3 col-sm-3 border-left action text-center">
                                            <span class="color-blue">
                                                <?php echo $this->translate($this->getStatus($application['service'], $application['status'])) ?>
                                            </span>
                                        </td>
                                        <?php
                                        $flag = FALSE;
                                    endif;
                                    ?>
                                </tr>
                                <?php
                            endforeach;
                            ?>
                        </table>
                        <ul class="sale_status  padding-5">
                            <li class="col-xs-12 col-sm-12 text-right">
                                <a href="<?php echo $this->getBaseUrl($this->getOrderUrl()), '?id=', $order->getId() ?>" class="btn"><?php echo $this->translate('Order Details') ?></a>
                                <a href="<?php echo $this->getBaseUrl($this->getViewUrl()), '?id=', $application->getId() ?>" class="btn"><?php echo $this->translate('View Details') ?></a>
                            </li>
                        </ul>
                    </div>
                    <?php
                endforeach;
                ?>
            </div>
            <div class="tab-pane fade " id="delivery">
                2
            </div>
            <div class="tab-pane fade" id="payment">
                3
            </div>
            <div class="tab-pane fade " id="refund">
                4
            </div>
        </div>
        <?php
    else:
        ?>
        <div class="tab-content">
            <p>
                <?php echo $this->translate('No return products.'); ?>
            </p>
        </div>
    <?php
    endif;
    ?>
</div>
