<?php
$application = $this->getVariable('model');
$order = $application->getOrder();
$status = $application['status'];
$currency = $this->getCurrency();
?>
<div class="refund-detail">
    <ul class="nav nav-tabs">
        <li role="presentation" class="active"><a href="#products" data-toggle="tab"><?php echo $this->translate('Product Infomation') ?></a></li>
        <li role="presentation"><a href="#address" data-toggle="tab"><?php echo $this->translate('Shipping Address') ?></a></li>
    </ul>
    <div class="tab-content">
        <div role="tabpanel" class="tab-pane fade in active" id="products">
            <ul class="col-xs-12 col-sm-12 title-nav name  padding-5 font-12">
                <li class="text-left col-xs-6 col-sm-6" colspan="2"><?php echo $order->getStore()['name'] ?></li>
                <li class="col-xs-6 col-sm-6 text-right" colspan="2">
                    <?php echo $currency->format($order->offsetGet('total')); ?>
                    <span class="font-12">
                        <?php echo $this->translate('(Including Shipping Fee: %s)', [$currency->format($order->offsetGet('shipping'))]); ?>
                    </span>
                </li>
            </ul>
            <table class="table table-no-border font-12">
                <tbody>
                    <?php
                    $items = $application->getItems();
                    $flag = true;
                    foreach ($items as $item):
                        $product = $item['product'];
                        $thumbnail = $product->getThumbnail();
                        ?>
                        <tr class="refund-list">
                            <td class="col-xs-2 col-sm-2">
                                <img src="<?php echo strpos($thumbnail, '//') === false ? $this->getResourceUrl('image/resized/100x/' . $thumbnail) : $thumbnail ?>" alt="<?php echo $product['name'] ?>" width="50" height="50" />
                            </td>
                            <td class="col-xs-6 col-sm-6">
                                <h4 class="product-name font-12"><?php echo $product['name'] ?></h4>
                                <?php
                                $options = json_decode($item['options'], true);
                                if ($item['product_id'] && count($options)):
                                    ?>
                                    <dl class="options">
                                        <?php
                                        foreach ($product->getOptions() as $option):
                                            if (isset($options[$option->getId()])):
                                                ?>
                                                <dt><?php echo $option['title'] ?></dt>
                                                <dd>
                                                    <?php
                                                    echo (in_array($option['input'], ['select', 'radio', 'checkbox', 'multiselect']) ?
                                                            $option->getValue($options[$option->getId()]) : $options[$option->getId()])
                                                    ?>
                                                </dd>
                                                <?php
                                            endif;
                                        endforeach;
                                        ?>
                                    </dl>
                                <?php endif ?>
                            </td>
                            <td class="col-xs-1 col-sm-1 text-right">
                                <span class="price "><?php echo $currency->convert($item['base_price'], true) ?></span>
                                <span><?php echo (float) $item['refunded_qty'] ?></span>
                            </td>
                            <?php if ($flag): ?>
                                <td class="col-xs-3 col-sm-3 border-left action text-center" rowspan="<?php echo count($items) ?>">
                                    <span><?php echo $this->translate($this->getService($application['service'])) ?></span>
                                    <span><?php echo date('Y-m-d<\b\r />H:i:s', strtotime($application['created_at'])) ?></span>
                                </td>
                                <?php
                                $flag = false;
                            endif;
                            ?>
                        </tr>
                    <?php endforeach ?>
                    <tr>
                        <td colspan="4" class="text-right text-vmiddle amount">
                            <?php echo $this->translate('Refund Amount'); ?>:<?php echo $currency->convert($application['amount'], true) ?>
                        </td> 
                    </tr>
                </tbody>
            </table>
        </div>
        <div role="tabpanel" class="tab-pane fade font-12" id="address">
            <?php echo nl2br($order['shipping_address']) ?>
        </div>
    </div>
    <div class="handler text-center"><?php echo $this->getHandler($application['service'], $status) ?></div>
    <div class="flow font-12">
        <div class="step active"><?php echo $this->translate('Applied') ?></div>
        <?php if ($status == -1): ?>
            <div class="step active"><?php echo $this->translate('Refused') ?></div>
        <?php else: ?>
            <div class="step<?php if ($status): ?> active<?php endif ?>"><?php echo $this->translate('Approved') ?></div>
            <?php if ($application['service'] > 1): ?>
                <div class="step<?php if ($status > 1): ?> active<?php endif ?>"><?php echo $this->translate('Delivering') ?></div>
                <div class="step<?php if ($status > 2): ?> active<?php endif ?>"><?php echo $this->translate('Repairing') ?></div>
                <div class="step<?php if ($status > 3): ?> active<?php endif ?>"><?php echo $this->translate('Delivering') ?></div>
            <?php elseif ($application['service']): ?>
                <div class="step<?php if ($status > 1): ?> active<?php endif ?>"><?php echo $this->translate('Delivering') ?></div>
                <div class="step<?php if ($status > 2): ?> active<?php endif ?>"><?php echo $this->translate('Refunding') ?></div>
            <?php endif ?>
            <div class="step<?php if ($status > 4): ?> active<?php endif ?>"><?php echo $this->translate('Complete') ?></div>
        <?php endif ?>
    </div>
    <div class="log font-12">
        <?php foreach ($application->getComments() as $key => $comment): ?>
            <div class="item clearfix">
                <div class="user col-xs-2 col-md-1"><?php echo $this->translate($comment['is_customer'] ? 'Buyer' : 'Seller') ?></div>
                <div class="content col-xs-10 col-md-11">
                    <p class="comment"><?php echo $comment['comment'] ?></p>
                    <p class="date">[<?php echo $comment['created_at'] ?>]</p>
                    <?php if ($images = @json_decode($comment['image'], true)): ?>
                        <ul class="images list-inline">
                            <?php foreach ($images as $i => $image): ?>
                                <li>
                                    <img src="<?php echo $this->getBaseUrl('pub/upload/refund/' . $image) ?>" class="thumbnail" alt="" />
                                </li>
                            <?php endforeach ?>
                        </ul>
                    <?php endif ?>
                </div>
            </div>
        <?php endforeach; ?>
        <?php if ($status != -1 && $status < 5): ?>
            <form action="<?php echo $this->getBaseUrl('sales/refund/addcomment/') ?>" method="post" enctype="multipart/form-data">
                <input type="hidden" name="csrf" value="<?php echo $this->getCsrfKey() ?>" />
                <input type="hidden" name="rma_id" value="<?php echo $this->getQuery('id') ?>" />
                <div class="input-box">
                    <textarea name="comment" class="form-control"></textarea>
                </div>
                <div class="input-box images">
                    <input type="file" name="voucher[]" id="voucher" hidden="hidden" accept="image/*" />
                    <label for="voucher" class="add-image"><span class="fa fa-camera"></span></label>
                    <span>(<?php echo $this->translate('%d images allowed at most.', [5]) ?>)</span>
                </div>
                <div class="buttons-set">
                    <button type="submit" name="success_url" value="<?php echo $this->getUri() ?>" class="btn btn-submit"><?php echo $this->translate('Submit') ?></button>
                </div>
            </form>
        <?php endif ?>
    </div>
</div>
