<?php
$data_tag = $this->getVariable("data_tag");
$part_id = $this->getVariable("part_id");
$picInfos = $this->getStorePicInfo("store_carousel");
$picInfo = json_encode($picInfos);

$retailer = $this->getStoreBanner();

 ?>


<ul class="nav nav-tabs" id="myTab" style="margin:11px 18px" > 
      <li class="active"><a href="#basic">基本属性</a></li> 
      <li><a href="#uploadPic">Banner图片</a></li> 
 </ul> 
       
 <div class="tab-content"> 
      <div class="tab-pane active" id="basic" >
<div style="margin:20px" >


<!--宽度设置:
<input type="radio" name="widthSetType" value="0"  > 自适应100%
&nbsp; <input type="radio" name="widthSetType" value="1" checked="checked" > 自行设置
<input type="text"  id="widthSet" class="params"  value="1128" > px

 <br><br>--> 
高度设置: <input type="text"  id="heightSet" class="params" value="200" >
 <br><br>

</div>
      	</div> 
<div class="tab-pane" id="uploadPic" >
<div style="margin:26px">
<form id=uploadForm onsubmit="return false" >
<input type="hidden" name='retailer_id' value="<?php echo $retailer['id'] ?>" >
 <div class="rows" >   
   上传图片: &nbsp;<input type="file" name="files[]" id=myuploadfile style="display:inline"> &nbsp; <button onclick="doUpload()" class="btn btn-danger btn-sm">上 传</button>
</div>
</form>
<hr width="99%" style="border-color:#e8c7b6" > 
<div class="rows">
	<ul class="picList" style="text-align: center;"  >
 <?php if(empty($retailer['banner'])){ ?>
	<img width="380" src="<?php echo $this->getBaseUrl('/pub/theme/default/frontend/dragResource/images/text1.jpg') ?>">
<?php } else{  ?>
	<img width="380" src="<?php echo $this->getBaseUrl('/pub/resource/image/'.$retailer['real_name']) ?>"><br><br>
		<button class="btn btn-warning btn-xs" onclick="deleteUpload()" >删 除</button>
<?php } ?>
	</ul> 	
</div>
</div>
</div> 
  <input type="hidden" id='focusBtn' >	     
    
    
 <script> 
      $(function () { 
      $('#myTab a:first').tab('show');
        $('#myTab a').click(function (e) {          
          e.preventDefault();//阻止a链接的跳转行为 
          $(this).tab('show');//显示当前选中的链接及关联的content
 
        }) 
      }) 
    </script>
<script>
	var data_tag = '<?php echo $data_tag; ?>';
	var part_id = '<?php echo $part_id; ?>';
	var obj = $('#'+part_id,parent.document);
	var data_param = $.trim(obj.attr('data-param'))=="" ? {} : JSON.parse(decodeURIComponent(obj.attr('data-param')));

	$(document).ready(function(){

  		for (key in data_param) {
  			$("#"+key).val(data_param[key]);
  		}
		
		if(!$.isEmptyObject(data_param))
		{   
			$("input:radio[name='widthSetType'][value='"+data_param.widthSetType+"']").attr("checked",true);
			if(data_param.widthSetType==1)
				$("#widthSet").attr('disabled',false);
			else
				$("#widthSet").attr('disabled',true);
		}
		
		$("input:radio[name='widthSetType']").click(function(){
			if($(this).val()=="1")
				$("#widthSet").attr('disabled',false);
			else
				$("#widthSet").attr('disabled',true);
		});
		
	    
	});	
	
	
	function doUpload() {
	 if($.trim($('#myuploadfile').val())=="")
	 	return;  
     var formData = new FormData($( "#uploadForm" )[0]);  
     $.ajax({  
          url: '<?php echo $this->getBaseUrl('retailer/store/decorationUploadForBanner') ?>' ,  
          type: 'POST',  
          data: formData, 
          cache: false,  
          contentType: false,  
          processData: false,
          beforeSend:function(){
            layer.load(1, {shade: [0.1,'#fff'] });	
          },  
          success: function (json) {  
        	if(json.status==0){
				var htmls = '<img width="380" src="<?php echo $this->getBaseUrl('/pub/resource/image/') ?>'+ json.picInfo +'">';
				htmls += '<br><br><button class="btn btn-warning btn-xs" onclick="deleteUpload()" >删 除</button>';
				$('.picList').html(htmls);
        	}
        	$("#uploadForm")[0].reset();
        	layer.closeAll();
          },  
          error: function (json) {  
           
          }  
     });  
}


	
	
	function deleteUpload(){
	$.ajax({  
          url: '<?php echo $this->getBaseUrl('retailer/store/decorationUploadDeleteForBanner') ?>' ,  
          type: 'POST',  
          data: {},  
          beforeSend:function(){
            layer.load(1, {shade: [0.1,'#fff'] });	
          },  
          success: function (json) {  
        	if(json.status==0){
        		var htmls = '<img width="380" src="<?php echo $this->getBaseUrl('/pub/theme/default/frontend/dragResource/images/text1.jpg') ?>">';
				$('.picList').html(htmls);
        	}
        	layer.closeAll();
          },  
          error: function (json) {  
           
          }  
    });
		
	} 

	$('#focusBtn').click(function(){
		data_param = {};
		data_param['widthSetType'] = $("input:radio[name='widthSetType']:checked").val();
		
		if(data_param['widthSetType']=="1")
		{
			if(isNaN($("#widthSet").val()))
			{
				layer.msg('宽度设置请输入数字', {shade: [0.3,'#fff'],time: 2000});
				return;
			}
			
		}
				
		$('.params').each(function(){
			var tempID = $(this).attr('id');
			var tempVal = $(this).val();
			data_param[tempID] = tempVal; 
		});
		
		data_param = encodeURIComponent(JSON.stringify(data_param));
		obj.attr('data-param',data_param);
		top.window.call_ajax_data(part_id,data_tag);
		
		
		
	});
</script>

