<?php
$data_tag = $this->getVariable("data_tag");
$part_id = $this->getVariable("part_id");
$Infos = $this->getStorePicInfo("menu");
$Info = json_encode($Infos);

 ?>


<ul class="nav nav-tabs" id="myTab" style="margin:11px 18px" > 
      <li><a href="#uploadPic">基本属性</a></li> 
 </ul> 
       
 <div class="tab-content"> 
<div class="tab-pane" id="uploadPic" >
<div style="margin:26px">

<form id=uploadForm onsubmit="return false" >
<input type="hidden" id="resource_category_code" value="menu" />
 <div class="rows">
  导航标题: &nbsp;<input type="text" id='title'  placeholder="" > &nbsp; 链 接: &nbsp;<input type="text" id='url' name="url" placeholder="http://" style="width:260px" >
 &nbsp;<button onclick="doAdd()" class="btn btn-danger btn-sm">增 加</button> 
 </div>
</form>

<hr width="99%" style="border-color:#e8c7b6" > 
<div class="rows">
	<ul class="infoList">

	
	</ul> 	
</div>
</div>
</div>

 </div> 
  <input type="hidden" id='focusBtn' >	     

<script> 
      $(function () { 
      $('#myTab a:first').tab('show');
        $('#myTab a').click(function (e) {          
          e.preventDefault();//阻止a链接的跳转行为 
          $(this).tab('show');//显示当前选中的链接及关联的content
 
        }) 
      }) 
</script>
    
<script>
	var data_tag = '<?php echo $data_tag; ?>';
	var part_id = '<?php echo $part_id; ?>';
	var obj = $('#'+part_id,parent.document);
	var data_param = $.trim(obj.attr('data-param'))=="" ? {} : JSON.parse(decodeURIComponent(obj.attr('data-param')));
	var Info = {info1:JSON.parse(<?php echo $Info ?>)};
	$(document).ready(function(){

  		for (key in data_param) {
  			$("#"+key).val(data_param[key]);
  		}
		
		
		$('.infoList').html(template('li_menu',Info));
	    
	});	
	
	
	function doAdd() {  
     var title = $('#title').val();
     var url = $('#url').val(); 
     var resource_category_code = $('#resource_category_code').val(); 
     $.ajax({  
          url: '<?php echo $this->getBaseUrl('retailer/store/decorationInfoAdd') ?>' ,  
          type: 'POST',  
          data: {title:title,url:url,resource_category_code:resource_category_code},  
          beforeSend:function(){
            layer.load(1, {shade: [0.1,'#fff'] });	
          },  
          success: function (json) {  
        	if(json.status==0){
        		console.log(111222);
        		Info.info1 = JSON.parse(json.Info);
        		$('.infoList').html(template('li_menu',Info));	
        	}
        	$("#uploadForm")[0].reset();
        	layer.closeAll();
          },  
          error: function (json) {  
           
          }  
     });  
}

	function modify(obj){
		$li = $(obj).closest("li");
		$li.find('div.adjust').find('span').hide();
		$li.find('div.adjust').find('input').show();
		$li.find('button.mod').hide();
		$li.find('button.save').show();
		
	}
	
	function save(obj,id){
		$li = $(obj).closest("li");
		var pic_title = $li.find('div.adjust').find("input[name='pic_title']").val();
		var url = $li.find('div.adjust').find("input[name='url']").val();
		$.ajax({  
          url: '<?php echo $this->getBaseUrl('retailer/store/decorationUploadSave') ?>' ,  
          type: 'POST',  
          data: {id:id,pic_title:pic_title,url:url,resource_category_code:'menu'},  
          beforeSend:function(){
            layer.load(1, {shade: [0.1,'#fff'] });	
          },  
          success: function (json) {  
        	if(json.status==0){
        		$li.find('div.adjust').find("span[name='pic_title']").html(pic_title);
        		$li.find('div.adjust').find("span[name='url']").html(url);
				$li.find('div.adjust').find('span').show();
				$li.find('div.adjust').find('input').hide();
				$li.find('button.mod').show();
				$(obj).hide();	
        	}
        	layer.closeAll();
          },  
          error: function (json) {  
           
          }  
    });
				
	}
	
	function deleteInfo(id){
	$.ajax({  
          url: '<?php echo $this->getBaseUrl('retailer/store/decorationInfoDelete') ?>' ,  
          type: 'POST',  
          data: {id:id,resource_category_code:'menu'},  
          beforeSend:function(){
            layer.load(1, {shade: [0.1,'#fff'] });	
          },  
          success: function (json) {  
        	if(json.status==0){
 
        		Info.info1 = JSON.parse(json.Info);
        		$('.infoList').html(template('li_menu',Info));	
        	}
        	layer.closeAll();
          },  
          error: function (json) {  
           
          }  
    });
		
	} 

	$('#focusBtn').click(function(){
		data_param = {};

				
		$('.params').each(function(){
			var tempID = $(this).attr('id');
			var tempVal = $(this).val();
			data_param[tempID] = tempVal; 
		});
		
		data_param = encodeURIComponent(JSON.stringify(data_param));
		obj.attr('data-param',data_param);
		top.window.call_ajax_data(part_id,data_tag);
	});
</script>

<script id="li_menu" type="text/html" >
	<li>

	<div class='title' style="text-align: center;" >标 题</div>
	<div class="url" style="text-align: center;"  >链 接</div>
	<div style="text-align: center;width:80px"  >操 作</div>
	<div style="clear:both"></div>			
	</li>
	
	{{each info1 as value i}}
	<li>
	<div class='title adjust' ><input type="text" name='pic_title' value="{{value.pic_title}}" style="display:none" ><span name='pic_title'>{{value.pic_title}}</span></div>
	<div class="url adjust"  ><input type="text" name='url' value="{{value.url}}" style="display:none" ><span name='url'>{{value.url}}</span></div>
	<div class='adjust' ><button class="btn btn-success btn-xs mod" onclick="modify(this)" >修 改</button> <button class="btn btn-primary btn-xs save" onclick="save(this,{{value.id}})" style="display:none" >保 存</button>  <button class="btn btn-warning btn-xs" onclick='deleteInfo({{value.id}})' >删 除</button></div>
	<div style="clear:both"></div>			
	</li>
	 {{/each}}
</script>
