<?php
$data_tag = $this->getVariable("data_tag");
$part_id = $this->getVariable("part_id");
 ?>
 <div style="padding:11px">
  <script id="editor" type="text/plain" style="width:1000px;height:450px;"></script>
</div>	
 <input type="hidden" id='focusBtn' >	



<script>
	var data_tag = '<?php echo $data_tag; ?>';
	var part_id = '<?php echo $part_id; ?>';
	var obj = $('#'+part_id,parent.document).find('.view').find('.content.function-tag');
	var data_param = $.trim(obj.attr('data-param'))=="" ? {} : JSON.parse(decodeURIComponent(obj.attr('data-param')));
	var ue = UE.getEditor('editor');
	//console.log(obj.html());
	var tempHtml = obj.html();
	setTimeout(function(){
		UE.getEditor('editor').setContent(tempHtml);
	},800);
  	
	$(document).ready(function(){	

  		for (key in data_param) {
  			$("#"+key).val(data_param[key]);
  		}
  		

	});	

	$('#focusBtn').click(function(){
		data_param = {};
		$('.params').each(function(){
			var tempID = $(this).attr('id');
			var tempVal = $(this).val();
			data_param[tempID] = tempVal; 
		});
		data_param = encodeURIComponent(JSON.stringify(data_param));
		obj.attr('data-param',data_param);
		obj.html(ue.getContent());
		window.parent.layer.closeAll();
		//window.parent.call_ajax_data(part_id,data_tag);
	});
</script>

<script>
UE.registerUI('dialog',function(editor,uiName){

    //创建dialog
    var dialog = new UE.ui.Dialog({
  
        iframeUrl:'<?php echo $this->getBaseUrl('/retailer/resource/?decoration=1')?>',

        editor:editor,

        name:uiName,

        title:"图片管理",


        cssRules:"width:900px;height:450px;",


        buttons:[
            {
                className:'edui-okbutton',
                label:'确定',
                onclick:function () {
                    dialog.close(true);
                }
            },
            {
                className:'edui-cancelbutton',
                label:'取消',
                onclick:function () {
                    dialog.close(false);
                }
            }
        ]
        });


    var btn = new UE.ui.Button({
        name:'dialogbutton' + uiName,
        title:'图片管理',

        cssRules :'background-position: -725px -77px;',
        onclick:function () {
            //渲染dialog
            dialog.render();
            dialog.open();
        }
    });

    return btn;
},[73]);	
	
</script>


