<?php
$data_tag = $this->getVariable("data_tag");
$part_id = $this->getVariable("part_id");
 ?>


<ul class="nav nav-tabs" id="myTab" style="margin:11px 18px" > 
      <li class="active"><a href="#basic">基本属性</a></li> 
      <li><a href="#uploadPic">上传图片</a></li> 
 </ul> 
       
 <div class="tab-content"> 
      <div class="tab-pane active" id="basic" >
      <div style="margin:20px" >
是否显示标题框：
<select id='show_column' class="params"  >
<option value=1 >显示</option>
<option value=0 >不显示</option>	
</select> <br><br>
标题文字:
<input type="text" id='title' class="params" > 
 <br><br>

高度设置:
<input type="radio" name="heightSetType" value="0" checked="checked" > 自适应
<input type="radio" name="heightSetType" value="1" > 自行设置
<input type="text"  id="heightSet" class="params" disabled="true" value="0" >

 <br><br>

</div>
      	</div> 
   <div class="tab-pane" id="uploadPic" >
   	<div style="margin:26px">
   	上传图片:
   	</div>
   	 </div> 
</div> 
  <input type="hidden" id='focusBtn' >	     
    <script> 
      $(function () { 
      $('#myTab a:first').tab('show');
        $('#myTab a').click(function (e) {          
          e.preventDefault();//阻止a链接的跳转行为 
          $(this).tab('show');//显示当前选中的链接及关联的content
 
        }) 
      }) 
    </script>
<script>
	var data_tag = '<?php echo $data_tag; ?>';
	var part_id = '<?php echo $part_id; ?>';
	var obj = $('#'+part_id,parent.document).find('.view').find('.content.function-tag');
	var data_param = $.trim(obj.attr('data-param'))=="" ? {} : JSON.parse(decodeURIComponent(obj.attr('data-param')));
	$(document).ready(function(){

  		for (key in data_param) {
  			$("#"+key).val(data_param[key]);
  		}
		
		if(!$.isEmptyObject(data_param))
		{   
			$("input:radio[name='heightSetType'][value='"+data_param.heightSetType+"']").attr("checked",true);
			if(data_param.heightSetType==1)
				$("#heightSet").attr('disabled',false);
			else
				$("#heightSet").attr('disabled',true);
		}
		
		$("input:radio[name='heightSetType']").click(function(){
			if($(this).val()=="1")
				$("#heightSet").attr('disabled',false);
			else
				$("#heightSet").attr('disabled',true);
		});
	    
	});	

	$('#focusBtn').click(function(){
		data_param = {};
		data_param['heightSetType'] = $("input:radio[name='heightSetType']:checked").val();
		
		if(data_param['heightSetType']=="1")
		{
			if(isNaN($("#heightSet").val()))
			{
				layer.msg('高度设置请输入数字', {shade: [0.3,'#fff'],time: 2000});
				return;
			}
			
		}
				
		$('.params').each(function(){
			var tempID = $(this).attr('id');
			var tempVal = $(this).val();
			data_param[tempID] = tempVal; 
		});
		
		data_param = encodeURIComponent(JSON.stringify(data_param));
		obj.attr('data-param',data_param);
		top.window.call_ajax_data(part_id,data_tag);
	});
</script>


