<?php
$data_tag = $this->getVariable("data_tag");
$part_id = $this->getVariable("part_id");
 ?>
<div style="margin:20px" >
是否显示标题框：
<select id='show_column' class="params"  >
<option value=1 >显示</option>
<option value=0 >不显示</option>	
</select> <br><br>
标题文字:
<input type="text" id='title' class="params" > 
 <br><br>

高度设置:
<input type="radio" name="heightSetType" value="0" checked="checked" > 自适应
<input type="radio" name="heightSetType" value="1" > 自行设置
<input type="text"  id="heightSet" class="params" disabled="true" value="0" >

 <br><br>
上传图片: 


<input type="hidden" id='focusBtn' >	
</div>
<script>
	var data_tag = '<?php echo $data_tag; ?>';
	var part_id = '<?php echo $part_id; ?>';
	var obj = $('#'+part_id,parent.document).find('.view').find('.content.function-tag');
	var data_param = $.trim(obj.attr('data-param'))=="" ? {} : JSON.parse(decodeURIComponent(obj.attr('data-param')));
	$(document).ready(function(){

  		for (key in data_param) {
  			$("#"+key).val(data_param[key]);
  		}
		
		if(!$.isEmptyObject(data_param))
		{   
			$("input:radio[name='heightSetType'][value='"+data_param.heightSetType+"']").attr("checked",true);
			if(data_param.heightSetType==1)
				$("#heightSet").attr('disabled',false);
			else
				$("#heightSet").attr('disabled',true);
		}
		
		$("input:radio[name='heightSetType']").click(function(){
			if($(this).val()=="1")
				$("#heightSet").attr('disabled',false);
			else
				$("#heightSet").attr('disabled',true);
		});
	    
	});	

	$('#focusBtn').click(function(){
		data_param = {};
		data_param['heightSetType'] = $("input:radio[name='heightSetType']:checked").val();
		
		if(data_param['heightSetType']=="1")
		{
			if(isNaN($("#heightSet").val()))
			{
				layer.msg('高度设置请输入数字', {shade: [0.3,'#fff'],time: 2000});
				return;
			}
			
		}
				
		$('.params').each(function(){
			var tempID = $(this).attr('id');
			var tempVal = $(this).val();
			data_param[tempID] = tempVal; 
		});
		
		data_param = encodeURIComponent(JSON.stringify(data_param));
		obj.attr('data-param',data_param);
		top.window.call_ajax_data(part_id,data_tag);
	});
</script>


