<?php
$data_tag = $this->getVariable("data_tag");
$part_id = $this->getVariable("part_id");
 ?>


<ul class="nav nav-tabs" id="myTab" style="margin:11px 18px" > 
      <li class="active"><a href="#basic">基本属性</a></li> 
      <li><a href="#uploadPic">轮播图片</a></li> 
 </ul> 
       
 <div class="tab-content"> 
      <div class="tab-pane active" id="basic" >
<div style="margin:20px" >
是否显示标题框：
<select id='show_column' class="params"  >
<option value=1 >显示</option>
<option value=0 >不显示</option>	
</select> <br><br>
标题文字:
<input type="text" id='title' class="params" > 
 <br><br>

高度设置:
<input type="radio" name="heightSetType" value="0" checked="checked" > 自适应
<input type="radio" name="heightSetType" value="1" > 自行设置
<input type="text"  id="heightSet" class="params" disabled="true" value="0" >

 <br><br>

</div>
      	</div> 
<div class="tab-pane" id="uploadPic" >
<div style="margin:26px">
<form id=uploadForm onsubmit="return false" >
<input type="hidden" name="csrf" value="<?php echo $this->getCsrfKey() ?>" />
<input type="hidden" name="resource_category_code" value="store_carousel" />
 <div class="rows">
  图片标题: &nbsp;<input type="text" id='pic_title' placeholder="" > &nbsp; 图片链接: &nbsp;<input type="text" id='url' placeholder="http://" style="width:260px" > 
 </div>
 <div class="rows" >   
   上传图片: &nbsp;<input type="file" name="files[]" style="display:inline"> &nbsp; <button onclick="doUpload()" class="btn btn-danger btn-sm">增 加</button>
</div>
</form>
<hr width="99%"> 
<div class="rows">
	<ul class="picList">

	
	</ul> 	
</div>
</div>
</div> 
  <input type="hidden" id='focusBtn' >	     
    
    
 <script> 
      $(function () { 
      $('#myTab a:first').tab('show');
        $('#myTab a').click(function (e) {          
          e.preventDefault();//阻止a链接的跳转行为 
          $(this).tab('show');//显示当前选中的链接及关联的content
 
        }) 
      }) 
    </script>
<script>
	var data_tag = '<?php echo $data_tag; ?>';
	var part_id = '<?php echo $part_id; ?>';
	var obj = $('#'+part_id,parent.document).find('.view').find('.content.function-tag');
	var data_param = $.trim(obj.attr('data-param'))=="" ? {} : JSON.parse(decodeURIComponent(obj.attr('data-param')));
	$(document).ready(function(){

  		for (key in data_param) {
  			$("#"+key).val(data_param[key]);
  		}
		
		if(!$.isEmptyObject(data_param))
		{   
			$("input:radio[name='heightSetType'][value='"+data_param.heightSetType+"']").attr("checked",true);
			if(data_param.heightSetType==1)
				$("#heightSet").attr('disabled',false);
			else
				$("#heightSet").attr('disabled',true);
		}
		
		$("input:radio[name='heightSetType']").click(function(){
			if($(this).val()=="1")
				$("#heightSet").attr('disabled',false);
			else
				$("#heightSet").attr('disabled',true);
		});
		
		$('.picList').html(template('li_carousel'));
	    
	});	
	
	
	function doUpload() {  
     var formData = new FormData($( "#uploadForm" )[0]);  
     $.ajax({  
          url: '<?php echo $this->getBaseUrl('retailer/store/decorationUpload') ?>' ,  
          type: 'POST',  
          data: formData,  
          async: false,  
          cache: false,  
          contentType: false,  
          processData: false,  
          success: function (json) {  
        	if(json.status){
        		$('.picList').html(template('li_carousel'));	
        	}
          },  
          error: function (json) {  
           
          }  
     });  
} 

	$('#focusBtn').click(function(){
		data_param = {};
		data_param['heightSetType'] = $("input:radio[name='heightSetType']:checked").val();
		
		if(data_param['heightSetType']=="1")
		{
			if(isNaN($("#heightSet").val()))
			{
				layer.msg('高度设置请输入数字', {shade: [0.3,'#fff'],time: 2000});
				return;
			}
			
		}
				
		$('.params').each(function(){
			var tempID = $(this).attr('id');
			var tempVal = $(this).val();
			data_param[tempID] = tempVal; 
		});
		
		data_param = encodeURIComponent(JSON.stringify(data_param));
		obj.attr('data-param',data_param);
		top.window.call_ajax_data(part_id,data_tag);
	});
</script>

<script id="li_carousel" type="text/html" >
	<li>
	<div><img src='<?php echo $this->getBaseUrl('/pub/theme/default/frontend/images/sample.jpg'); ?>' width=100 height=70 ></div>
	<div class='title adjust' ><input type="text" name='pic_title' ></div>
	<div class="url adjust"  ><input type="text" name='url' > http://wefefefef.coefn.efsheg dfefsdfefd ebsdf efsdthsdfnef  </div>
	<div class='adjust' ><button class="btn btn-warning btn-xs" >删 除</button></div>
	<div style="clear:both"></div>			
	</li>
</script>
