<?php
$item = $this->getVariable('item');
$key = $this->getVariable('key');
$id = preg_replace('/\W/', '-', $key);
$parent = $this->getVariable('parent');
?>
<div class="input-box">
    <?php if (isset($item['label'])): ?>
        <label for="<?php echo $id ?>" class="control-label<?php if (isset($item['required'])): ?> required<?php endif ?>">
            <?php echo $this->translate($item['label']) ?>
        </label>
    <?php endif ?>
    <div class="cell">
        <select name="<?php echo $key ?>" id="<?php echo $id ?>"<?php
        if (!isset($item['attrs']['class'])):
            ?> class="form-control<?php if (isset($item['required'])): ?> required<?php endif ?> <?php
                    if (isset($item['class'])) {
                        echo $item['class'];
                    }
                    ?>"<?php endif ?> <?php if (isset($item['attrs'])) echo $parent->getAttrs($item['attrs']) ?>>
                    <?php if ((!isset($item['required']) || !$item['required'])&&!isset($item['attrs']['multiple'])): ?>
                <option value=""><?php echo $this->translate(isset($item['empty_string']) ? $item['empty_string'] : 'Please Select') ?></option>
            <?php endif ?>
            <?php
            foreach ($item['options'] as $value => $label):
                if (is_array($label)):
                    ?>
                    <optgroup label="<?php echo $value ?>">
                        <?php foreach ($label as $v => $l): ?>
                            <option value="<?php echo $v ?>"<?php if (isset($item['value']) && (in_array($v, (array) $item['value']) || (string) $v === $item['value'])): ?> selected="selected"<?php endif ?>><?php echo $this->translate($l) ?></option>
                        <?php endforeach; ?>
                    </optgroup>
                <?php else: ?>
                    <option value="<?php echo $value ?>"<?php if (isset($item['value']) && (in_array($value, (array) $item['value']) || (string) $value === $item['value'])): ?> selected="selected"<?php endif ?>><?php echo $this->translate($label) ?></option>
                <?php endif ?>
            <?php endforeach ?>
        </select>
        <?php if (isset($item['comment'])): ?>
            <div class="comment">
                <?php echo nl2br($this->translate($item['comment'])) ?>
            </div>
        <?php endif ?>
    </div>
</div>
