<div class="container">
    <div class="col-md-4">
        <img height="230" src="<?php echo $this->getBaseUrl('/pub/theme/default/frontend/images/placeholder.png')?>" />
    </div>
    <div class="col-md-8">
        <h2>【中国质造】商家入驻通道-女装</h2>
        <P>面向产业带传统制造企业进行招商。如果你有丰富的生产经验，优秀的设计研发团队和优良的品控管理体系，如果你愿意转型在线发展自主品牌。淘宝网面向产业带企业盛大招商，扶持传统制造企业转型升级。如果你是，非你莫属！</P>
        <br />
        <p>招商范围</p>
        <p>此活动为淘宝卖家专属</p>
        <p>报名资质</p>
        <p>个人店铺</p>
        <p>活动规则</p>
        <p>当前活动审核通过后可撤销报名</p>
        <br />
        <button>立即报名</button>
    </div>
</div>
