<div class="col-xs-9 col-sm-9 col-md-10 wishlist mg-bottom-40">
    <h3><?php echo $this->translate('Activity Registration'); ?></h3>
    <div>
        <button data-toggle="modal" data-target="#modal-activity">可参加的活动</button>
    </div>
    <br />
    <div>
        <form method="get">
            <div >
                <span>活动名称:</span>
                <input type="text" value="" name="order_sn">
                <input type="submit" value="搜索" class="btn">
            </div>
        </form>
    </div>
    <br />
    
    <div class="row">
        <table class="table table-bordered">
            <tr>
                <th>活动名称</th>
                <th>报名截止</th>
                <th>已成功报名</th>
                <th>状态</th>
                <th>操作</th>
            </tr>
            <tr>
                <td>新势力周·秋冬上新·健身招商-单品区</td>
                <td>当天结束</td>
                <td>40个</td>
                <td>已报名</td>
                <td><a target="_blank" href="<?php echo $this->getBaseUrl('retailer/marketing/viewactivity')?>">查看</a>&nbsp;&nbsp;<a href="javascript:void(0);">撤销</a></td>
            </tr>
            <tr>
                <td>“828全球现场”大促（亚洲会场）</td>
                <td>当天结束</td>
                <td>120个</td>
                <td>已撤销</td>
                <td><a target="_blank" href="<?php echo $this->getBaseUrl('retailer/marketing/viewactivity')?>">查看</a></td>
            </tr>
            <tr>
                <th colspan="5">
                    <div class="text-right">
                        <a>共 2 个项目</a>
                        <a href="#">上一页</a>
                        <a href="#">1</a>
                        <span>1 / 1</span>
                        <a href="#">下一页</a>
                    </div>
                </th>
            </tr>
        </table>
    </div>
    
    <div id="modal-activity" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="activityModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="activityModalLabel">我能参加的活动</h4>
                </div>
                <div class="modal-body">
                    <div style="height: 500px;overflow-y: scroll;">
                        <table style="width: 100%;">
                            <tr>
                                <td><img width="230" height="80" src="<?php echo $this->getBaseUrl('/pub/theme/default/frontend/images/placeholder.png')?>" /></td>
                                <td>
                                    <p>【中国质造】商家入驻通道-女装</p>
                                    <p>面向产业带传统制造企业进行招商。如果你有丰富的生产经验，优秀的设计研发团队和优良的品控管理体系，如果你愿意转型在线发展自主品牌。淘宝网面向产业带企业盛大招商，扶持传统制造企业转型升级。如果你是，非你莫属！</p>
                                    <p>活动关键字：免费、中国质造准入</p>
                                    <p>已报名：0&nbsp;&nbsp;活动时间：2015.08.17-长期有效</p>
                                </td>
                                <td><button data-dismiss="modal" onclick="window.open('<?php echo $this->getBaseUrl('retailer/marketing/viewactivity')?>')">我要报名</button></td>
                            </tr>
                            <tr>
                                <td><img width="230" height="80" src="<?php echo $this->getBaseUrl('/pub/theme/default/frontend/images/placeholder.png')?>" /></td>
                                <td>
                                    <p>玩具8.23-8.28商家清单</p>
                                    <p>玩具8.23-8.28商家清单</p>
                                    <p>活动关键字：免费、母婴</p>
                                    <p>已报名：2815&nbsp;&nbsp;活动时间：2015.08.17-长期有效</p>
                                </td>
                                <td><button data-dismiss="modal" onclick="window.open('<?php echo $this->getBaseUrl('retailer/marketing/viewactivity')?>')">我要报名</button></td>
                            </tr>
                        </table>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                </div>
            </div>
        </div>
    </div>
    
</div>
