<?php 

?>
<div class="col-xs-9 col-sm-9 col-md-12 wishlist mg-bottom-40">
    <h3><?php echo $this->translate('After Service'); ?></h3>    
    <div id="scarch_order">
        <form method="get">
            <div class="sale">
                <div class="evaluation_left">
                    <label for="order_sn">订单号:</span>
                    <input type="text" value="" name="order_sn">&nbsp;&nbsp;
                    <label for="apply_time_from">申请时间:</label>
                    <input type="text" value="" id="apply_time_from" name="apply_time_from"> &ndash; <input type="text" value="" name="apply_time_to" id="apply_time_to">&nbsp;&nbsp;
                    <label for="buyer_name">买家:</label>
                    <input type="text" value="" name="buyer_name">
                    <input type="submit" value="<?php echo $this->translate('Search');?>" class="btn">
                </div>
            </div>
        </form>
    </div>
    <div class="after">
        <table class="table order-list text-center">
            <thead>
                <tr class="table_head">
                    <th class="col-lg-4 col-md-4  text-center">宝贝</th>
                    <th class="col-lg-2 col-md-2  text-center">售后编号</th>
                    <th class="col-lg-2 col-md-2  text-center">售后原因</th>
                    <th class="col-lg-1 col-md-1  text-center">状态</th>
                    <th class="col-lg-2 col-md-2  text-center">时间</th>
                    <th class="col-lg-1 col-md-1  text-center">操作</th>
                </tr>
            </thead>
            <caption>
                <div class="col-xs-6 store">雄鹰能量棒 <a href=""><span class="fa fa-qq"></span></a></div>
                <div class="col-xs-6 text-right list_right">
                    <span class="label">订单号：</span>
                    <span>20771553987443</span>
                    <span class="list_time">2016-07-15</span>
                </div>
            </caption>
                <tbody>
                <tr>
                    <td class="col-lg-4 col-md-4">
                        <img class="Thumbnail" src="http://ecomv2.seahinet.test1/pub/resource/image/resized/100x/TB12zVxHpXXXXbuaXXXXXXXXXXX_!!0-item_pic.jpg" alt="">
                        <h4>雄鹰能量棒Eagle Energy吸入式咖啡因能量棒</p> 
                    </td>
                    <td class="col-lg-2 col-md-2 text-center"> <span>1216100814216147</span></td>
                    <td class="col-lg-1 col-md-1 text-center">
                        <span class="after_color"><a href="">换货申请</a></span>
                    </td>
                    <td class="col-lg-1 col-md-1 text-center"><a href="">处理中</a></td>
                    <td class="col-lg-2 col-md-2 text-center">
                        <span class="list_time">2016-07-15&nbsp;&nbsp;16:55:34</span>
                    </td>
                    <td class="col-lg-1 col-md-1 text-center">
                        <button class="after_bt">取消</button>
                        <div><a target="_blank" href="http://127.0.0.1/ecomv2admin/retailer/transaction/afterview">查看详情</a>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
    <div id="modal-refuse" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="refusedModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="refusedModalLabel">拒绝申请</h4>
                </div>
                <div class="modal-body">
                    <div >
                        <h1>您确定要拒绝买家的售后申请吗？</h1>
                        <p>订单号&nbsp;&nbsp;&nbsp;&nbsp;:<span>88888888889</span></p>
                        <dl>
                            <dt>拒绝原因:</dt>
                            <dd><textarea name="reason"></textarea></dd>
                        </dl>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                    <button type="button" class="btn btn-primary">确认</button>
                </div>
            </div>
        </div>
    </div>

    <div id="modal-agree" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="agreedModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="agreedModalLabel">同意售后</h4>
                </div>
                <div class="modal-body">
                    <div>买家:&nbsp;&nbsp;Stone<br>订单号&nbsp;&nbsp;:<strong>88888888889</strong></div>
                    <div>
                        <ul>
                            <li>
                                <h3>处理方式</h3>
                                <p>
                                    <select name="agree_method">
                                        <option value="退款">退款</option>
                                        <option value="退货">退货</option>
                                        <option value="补发">补发</option>
                                    </select>
                                </p>
                            </li>
                            <li>
                                <h3>同意原因</h3>
                                <p><textarea name="agree"></textarea></p>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                    <button type="button" class="btn btn-primary">确认</button>
                </div>
            </div>
        </div>
    </div>
</div>
