<div class="col-lg-12 col-md-12">
    <div class="wishlist decorationlist">
        <h3>售后详情</h3>
        <div style="clear:both"></div>
        <!-- tab -->
        <div class="deccoration_topbg"></div>
        <div class="deccoration_tabs">
            <ul id="Decoration" class="nav nav-tabs">
                <li class="active">
                    <a href="#order" data-toggle="tab">
                        <div class="seperation-title"><span class="title">订单信息</span> </div>
                    </a>
                </li>
                <li>
                    <a href="#receipt" data-toggle="tab">
                        <div class="seperation-title"><span class="title">收货人信息</span> </div>
                    </a>
                </li>
            </ul>
            <!-- tabcontent -->
            <div id="myTabContent" class="tab-content">
                <div id="order" class="tab-pane fade in active">
                    <div class="after"> 
                        <table class="table table-no-border table_content"> 
                            <caption> 
                                <div class="col-xs-6 store">
                                    雄鹰能量棒 
                                    <a href=""><span class="fa fa-qq"></span></a>
                                </div> 
                                <div class="col-xs-6 text-right list_right"> 
                                    <span class="label">订单号：</span> 
                                    <span>20771553987443</span> 
                                    <span class="list_time">2016-07-15</span> 
                                </div> 
                            </caption> 
                            <tbody class="table_body"> 
                                <tr> 
                                    <td> <img class="Thumbnail" src="http://ecomv2.seahinet.test1/pub/resource/image/resized/100x/TB12zVxHpXXXXbuaXXXXXXXXXXX_!!0-item_pic.jpg" alt="" /> </td> 
                                    <td class="text-vtop "> 
                                        <div class="product-name">
                                            雄鹰能量棒Eagle Energy吸入式咖啡因能量棒
                                        </div> </td> 
                                    <td class=" text-left"> <span>20771553987443</span></td> 
                                    <td class="after_replace  text-center"> <span class="after_color"><a href="">换货申请</a></span> </td> 
                                    <td "="" class="after_replace text-right after_color"><a href="">买家提出申请</a> </td> 
                                    <td class="text-right"> <span class="list_time">2016-07-15&nbsp;&nbsp;16:55:34</span> </td> 
                                    <td class="text-center"> <button class="after_bt">取消</button>  </td> 
                                </tr> 
                            </tbody> 
                        </table> 
                    </div>

                    <div class="after—table">
                        <div class="information">
                            <table class="after_table_cont col-md-12">
                                <thead>
                                    <tr>
                                        <th>售后信息</th>
                                    </tr>

                                </thead>
                                <tbody>
                                    <tr >

                                        <td class="text-center table_td_1">
                                            <span><i class="fa fa-circle-o" aria-hidden="true"></i><span class="border_after border_after_bg" ></span><i class="fa fa-caret-right" aria-hidden="true"></i></span>
                                            <span><i class="fa fa-circle-o fa_left" aria-hidden="true"></i><span class="border_after border_after_bg" ></span><i class="fa fa-caret-right" aria-hidden="true"></i></span>
                                            <span><i class="fa fa-circle-o fa_left " aria-hidden="true"></i><span class="border_after border_after_bg_2" ></span><i class="fa fa-caret-right fa-circle-o_bg" aria-hidden="true"></i></span>
                                            <span><i class="fa fa-circle-o fa_left fa-circle-o_bg" aria-hidden="true"></i><span class="border_after border_after_bg_2" ></span><i class="fa fa-caret-right fa-circle-o_bg" aria-hidden="true"></i></span>
                                            <span><i class="fa fa-circle-o fa_left fa-circle-o_bg" aria-hidden="true"></i></span>

                                        </td>

                                    </tr>
                                    <tr class="table_tr">
                                        <td class="table_td" >
                                            <span class="col-md-2 text-center">提交申请</span>
                                            <span class="col-md-2 text-center">卖家审核</span>
                                            <span class="col-md-2 text-center text_left">卖家收货</span>
                                            <span class="col-md-2 text-center text_left">退款</span>
                                            <span class="col-md-2 text-center text_left">完成</span>
                                        </td>

                                    </tr>
                                    <tr class="padding_top">
                                        <td class="after_contact"><span>对卖家售后服务不满意，要求小二介入</span></td>

                                    </tr>
                                    <tr class="padding_bottom border_bottom" >
                                        <td class="after_contact"><button>平台小二介入</button> </td>
                                    </tr>
                                </tbody>
                            </table>

                        </div>

                        <div class="service">
                            <div class="details">
                                <div class="border_left"></div>
                                <table class="panel-body table">

                                    <tbody>

                                        <tr>
                                            <td class="title_img"> <span class="fa fa-pencil-square-o icon_comment" aria-hidden="true"></span><span class="title_img_mg"><img src="http://ecomv2.seahinet.test1/pub/resource/image/resized/45x/TB1fWOsLXXXXXXrXVXXXXXXXXXX_!!0-item_pic.jpg" alt="" data-label="" data-group="" width="45"><div class="img_left_bd"></div></span></td>

                                            <td class="col-md-2"><span>买家：</span><a href="" class="buyer">万物生dy</a></td>
                                            <td class="" colspan="3"><a href="">处理信息：</a></td>


                                        </tr>
                                        <tr>
                                            <td class=""></td>
                                            <td class=""></td>

                                            <td class="price" colspan="3"><span>您的订单235982840财务已退款，请您注意查收，具体到账周期可查询//heip.jd.com/user/liss/130-262.html</span></td>
                                        </tr>
                                        <tr class="">
                                            <td class=""></td>
                                            <td class=" "></td>
                                            <td class="" colspan="3"><span>[2016-09-19&nbsp;&nbsp;12:30:37]</span></td>
                                        </tr>
                                        <tr class="table_images ">
                                            <td></td>
                                            <td class="border_bt"></td>
                                            <td colspan="3" class="border_bt"><img class="bttrlazyloading animated bounceIn" src="http://ecomv2.seahinet.test1/pub/resource/image/resized/173x/20160930_132005_102.jpg">
                                                <img class="bttrlazyloading animated bounceIn" src="http://ecomv2.seahinet.test1/pub/resource/image/resized/173x/20160930_132005_102.jpg">
                                                <img class="bttrlazyloading animated bounceIn" src="http://ecomv2.seahinet.test1/pub/resource/image/resized/173x/20160930_132005_102.jpg"></td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                            <div class="details">
                                <div class="border_left"></div>
                                <table class="panel-body table">

                                    <tbody>

                                        <tr>
                                            <td class="title_img"> <span class="fa fa-pencil-square-o icon_comment" aria-hidden="true"></span><span class="title_img_mg"><img src="http://ecomv2.seahinet.test1/pub/resource/image/resized/45x/TB1fWOsLXXXXXXrXVXXXXXXXXXX_!!0-item_pic.jpg" alt="" data-label="" data-group="" width="45"><div class="img_left_bd"></div></span></td>
                                            <td class="col-md-2"><span>买家：</span><a href="" class="buyer">万物生dy</a></td>
                                            <td class="" colspan="3"><a href="">处理信息：</a></td>
                                        </tr>
                                        <tr>
                                            <td class=""></td>
                                            <td class=""></td>

                                            <td class="price" colspan="3"><span>您的订单235982840财务已退款，请您注意查收，具体到账周期可查询//heip.jd.com/user/liss/130-262.html</span></td>
                                        </tr>
                                        <tr class="">
                                            <td class=""></td>
                                            <td class=""></td>
                                            <td class="" colspan="3"><span>[2016-09-19&nbsp;&nbsp;12:30:37]</span></td>
                                        </tr>
                                        <tr class="table_images">
                                            <td></td>
                                            <td class="border_bt"></td>
                                            <td colspan="3" class="border_bt"><img class="bttrlazyloading animated bounceIn" src="http://ecomv2.seahinet.test1/pub/resource/image/resized/173x/20160930_132005_102.jpg">
                                                <img class="bttrlazyloading animated bounceIn" src="http://ecomv2.seahinet.test1/pub/resource/image/resized/173x/20160930_132005_102.jpg">
                                                <img class="bttrlazyloading animated bounceIn" src="http://ecomv2.seahinet.test1/pub/resource/image/resized/173x/20160930_132005_102.jpg"></td>
                                        </tr>
                                    </tbody>
                                </table>

                                <div class="submit">
                                    <div class="cell">
                                        <textarea  class="form-control textarea" rows="6" cols="5"></textarea>
                                    </div>
                                    <div class="btn_sub">
                                        <button class="img_sub">图片上传</button>

                                        <input type="submit" value="确&nbsp;认" class="submit_btn">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div id="receipt" class="tab-pane fade">
                    <button class="btn btn-primary" onclick="window.location = 'http://127.0.0.1/ecomv2admin/retailer/store/decoration?id=-1'"><i class="fa fa-plus" style="padding: 0 6px"></i>新建模版</button>
                    <div class="decoration-content">
                        <ul>

                        </ul>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>
<!--     售后详情 <button class="after_bt" data-toggle="modal" data-target="#modal-reply">售后详情</button>  -->


