<div class="container">
    <div class="col-md-12">
		<div class="wishlist decorationlist" style="width:935px">
        <h3>售后详情</h3>


        <div style="clear:both"></div>
        <!-- tab -->
        <div class="deccoration_topbg"></div>
        <div class="deccoration_tabs">
            <ul id="Decoration" class="nav nav-tabs">
                <li class="active">
                    <a href="#MyTemplates" data-toggle="tab">
                        <div class="seperation-title"><span class="title">订单信息</span> </div>
                    </a>
                </li>
                <li>
                    <a href="#TemplateSubject" data-toggle="tab">
                        <div class="seperation-title"><span class="title">收货人信息</span> </div>
                    </a>
                </li>
            </ul>
            <!-- tabcontent -->
            <div id="myTabContent" class="tab-content">
			         <div id="order" class="tab-pane fade in active">
						<div class="after"> 
						   <table class="table table-no-border table_content"> 
						    <caption> 
						     <div class="col-xs-6 store">
						      雄鹰能量棒 
						      <a href=""><span class="fa fa-qq"></span></a>
						     </div> 
						     <div class="col-xs-6 text-right list_right"> 
						      <span class="label">订单号：</span> 
						      <span>20771553987443</span> 
						      <span class="list_time">2016-07-15</span> 
						     </div> 
						    </caption> 
						    <tbody class="table_body"> 
						     <tr> 
						      <td> <img class="Thumbnail" src="http://ecomv2.seahinet.test1/pub/resource/image/resized/100x/TB12zVxHpXXXXbuaXXXXXXXXXXX_!!0-item_pic.jpg" alt="" /> </td> 
						      <td class="text-vtop "> 
						       <div class="product-name">
						        雄鹰能量棒Eagle Energy吸入式咖啡因能量棒
						       </div> </td> 
						      <td class=" text-left"> <span>20771553987443</span></td> 
						      <td class="after_replace  text-center"> <span class="after_color"><a href="">换货申请</a></span> </td> 
						      <td "="" class="after_replace text-right after_color"><a href="">买家提出申请</a> </td> 
						      <td class="text-right"> <span class="list_time">2016-07-15&nbsp;&nbsp;16:55:34</span> </td> 
						      <td class="text-center"> <button class="after_bt">取消</button>  </td> 
						     </tr> 
						    </tbody> 
						   </table> 
						  </div>
						  
						<div class="after——table">
							<table class="after_table_cont col-md-12">
								<thead>
									<tr>
										<th>售后信息</th>
									</tr>

								</thead>
								<tbody>
									<tr >
										
										<td class="text-center table_td_1">
											<span><i class="fa fa-circle-o" aria-hidden="true"></i><span class="border_after border_after_bg" ></span><i class="fa fa-caret-right" aria-hidden="true"></i></span>
											<span><i class="fa fa-circle-o fa_left" aria-hidden="true"></i><span class="border_after border_after_bg" ></span><i class="fa fa-caret-right" aria-hidden="true"></i></span>
											<span><i class="fa fa-circle-o fa_left " aria-hidden="true"></i><span class="border_after border_after_bg_2" ></span><i class="fa fa-caret-right fa-circle-o_bg" aria-hidden="true"></i></span>
											<span><i class="fa fa-circle-o fa_left fa-circle-o_bg" aria-hidden="true"></i><span class="border_after border_after_bg_2" ></span><i class="fa fa-caret-right fa-circle-o_bg" aria-hidden="true"></i></span>
											<span><i class="fa fa-circle-o fa_left fa-circle-o_bg" aria-hidden="true"></i></span>
											
										</td>
									
									</tr>
									<tr class="table_tr">
											<td class="table_td" >
											<div>	<span class="col-md-2 text-center">提交申请</span><span class="col-md-2 text-center">卖家审核</span><span class="col-md-2 text-center text_left">卖家收货</span><span class="col-md-3 text-center">退款</span><span class="col-md-1 text-center text_left">完成</span></div></td>
										
									</tr>
								</tbody>
							</table>
						
						
						
						</div>
			                  
			      </div>
			                
                 <div id="receipt" class="tab-pane fade">
                <button class="btn btn-primary" onclick="window.location = 'http://127.0.0.1/ecomv2admin/retailer/store/decoration?id=-1'"><i class="fa fa-plus" style="padding: 0 6px"></i>新建模版</button>
                <div class="decoration-content">
                    <ul>
                         
                    </ul>
                </div>
            </div>
                
            </div>


           
        </div>

    </div>
    </div>
</div>
