<div class="col-xs-9 col-sm-9 col-md-10 wishlist mg-bottom-40">
    <h3><?php echo $this->translate('Comment Management'); ?></h3>
    
    <div id="scarch_order">
        <form method="get">
            <div class="evaluation ">
            	
            	<div class="evaluation_left">
            		 <span>商品名称:</span>
                	<input type="text" value="" name="product_name" />
            	</div>
            	<div class="evaluation_left">
            		  <span>买家:</span>
               		 <input type="text" value="" name="buyer_name" />
            	</div>
            	<div class="evaluation_left">
            		  <span>评论内容:</span>
                <input type="text" value="" name="keyword" />
                <input type="submit" value="搜索" class="btn">
            	</div>
               
              
              
            </div>
        </form>
    </div>
    <br /><br />
    	<div class="evaluate">
    		<div class="down_icon"> <span class="span"><span>评价</span><i class="fa fa-caret-down text-center"></i></span><span class="span"><span>评语</span><i class="fa fa-caret-down text-center"></i></span></div>
    		<div class="details">
    			<table class="panel-body table">
			
			        <tbody>
			        <div class="border_left"></div>
			     	<tr>
			     		<td class="title_img"> <span class="fa fa-pencil-square-o icon_comment"  aria-hidden="true" ></span><span class="title_img_mg"><img src="http://ecomv2.seahinet.test1/pub/resource/image/resized/100x/135.jpg" alt=""><div class="img_left_bd"></div></span></td>
			     		
			     		<td class="col-md-2" ><span>买家：</span><a href="" class="buyer">万物生dy</a></td>
			     		<td class="title_txt"><a href="">现货Eagle Energy雄鹰能量棒吸入式咖啡因缓解疲劳</a></td>
			     		<td class="text-right"><button data-toggle="modal" data-target="#modal-reply">回复</button></td>
			     	</tr>
			     	<tr>
			     		<td class=""></td>
			     		<td class=""></td>
			     		
			     		<td class="price">￥198.00</td>
			     	</tr>
			     	<tr>
			     		<td></td>
			     		<td class="star"><i class="fa fa-star" aria-hidden="true"></i><i class="fa fa-star" aria-hidden="true"></i><i class="fa fa-star" aria-hidden="true"></i><i class="fa fa-star" aria-hidden="true"></i><i class="fa fa-star" aria-hidden="true"></i></td>
			     		<td class=""><span class="buyer">买家评价：</span><span>味道还可以</span></td>
			     		<td class=""></td>
			     	
			     	</tr>
			     	<tr class="">
			     		<td class=""></td>
			     		<td class="border_bt"></td>
			     		<td class="border_bt"><span>[2016-09-19&nbsp;&nbsp;12:30:37]</span></td>
			     		<td class="border_bt"></td>
			     		<td class="border_bt"></td>
			     	
			     	</tr>
			       </tbody>
   				 </table>
    		</div>
    		
    		<div class="details">
    			<table class="panel-body table">
			
			        <tbody>
			        <div class="border_left"></div>
			     	<tr>
			     		<td class="title_img"> <span class="fa fa-pencil-square-o icon_comment"  aria-hidden="true" ></span><span class="title_img_mg"><img src="http://ecomv2.seahinet.test1/pub/resource/image/resized/100x/135.jpg" alt=""><div class="img_left_bd"></div></span></td>
			     		
			     		<td class="col-md-2" ><span>买家：</span><a href="" class="buyer">万物生dy</a></td>
			     		<td class="title_txt"><a href="">现货Eagle Energy雄鹰能量棒吸入式咖啡因缓解疲劳</a></td>
			     		<td class="text-right"><button data-toggle="modal" data-target="#modal-reply">回复</button></td>
			     	</tr>
			     	<tr>
			     		<td class=""></td>
			     		<td class=""></td>
			     		
			     		<td class="price">￥198.00</td>
			     	</tr>
			     	<tr>
			     		<td></td>
			     		<td class="star"><i class="fa fa-star" aria-hidden="true"></i><i class="fa fa-star" aria-hidden="true"></i><i class="fa fa-star" aria-hidden="true"></i><i class="fa fa-star" aria-hidden="true"></i><i class="fa fa-star" aria-hidden="true"></i></td>
			     		<td class=""><span class="buyer">买家评价：</span><span>味道还可以</span></td>
			     		<td class=""></td>
			     	
			     	</tr>
			     	<tr>
			     		<td></td>
			     		<td class="star"></td>
			     		<td class=""><span class="buyer">卖家回复：</span><span>欢迎亲下次光临</span></td>
			     		<td class=""></td>
			     	
			     	</tr>
			     	<tr class="">
			     		<td class=""></td>
			     		<td class="border_bt"></td>
			     		<td class="border_bt"><span>[2016-09-19&nbsp;&nbsp;12:30:37]</span></td>
			     		<td class="border_bt"></td>
			     		<td class="border_bt"></td>
			     	
			     	</tr>
			       </tbody>
   				 </table>
    		</div>
    		
    		
    		
    	</div>
    
    
    
    
    
    
    
   
    <div id="modal-reply" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="replyModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="replyModalLabel">回复评论</h4>
                </div>
                <div class="modal-body">
                    <ul>
                        <li>
                            <h3>评论内容:</h3>
                            <p><label>hello3</label></p>
                        </li>
                        <li>
                            <h3>回复评论:</h3>
                            <p><textarea name="content">what3?</textarea><br></p>
                        </li>
                    </ul>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary">确认</button>
                </div>
            </div>
        </div>
    </div>
    
</div>
