<?php
$retailer = $this->getRetailer();
$store = $this->getStore();
?>
<div class="dashboard">
    <div class="myinfo">
        <div class="infodetail col-md-5 col-sm-12  col-xs-12 mg-bottom-20 auto-height">
            <div class="pull-left">
                <img alt="" src="<?php echo $retailer['profile'] ? 'data:image/png;base64, ' . base64_encode($retailer['profile']) : $this->getPubUrl('frontend/images/placeholder.png') ?>"  height="100" width="100" />
            </div>
            <div class="pad-left-100">
                <div class="mg-bottom-10">
                    <span class="wel-name">
                        <?php echo $store['name'] ?>
                    </span>
                    <span class="fa fa-star" aria-hidden="true"></span>
                    <span class="fa fa-star-o" aria-hidden="true"></span>
                    <span class="fa fa-star-o" aria-hidden="true"></span>
                    <span class="fa fa-star-o" aria-hidden="true"></span>
                    <span class="fa fa-star-o" aria-hidden="true"></span>
                    <div class="start">
                        <span class="start-v"><?php echo $this->translate('V') ?></span><span class="start-num"><?php echo $this->translate('%d', [0]) ?></span>
                    </div>
                </div>
                <div>
                    <p>
                        <a href="<?php echo $this->getBaseUrl('retailer/store/settings/') ?>"><?php echo $this->translate('Store Settings') ?></a>
                        <a href="<?php echo $this->getBaseUrl('retailer/store/view/') ?>"><?php echo $this->translate('View My Store') ?></a>
                    </p>
                </div>
                <div>
                    <span><?php echo $this->translate('Transaction') ?></span>
                    <span class="bal-text"><?php echo $this->translate('&nbsp;&nbsp;Non-payment') ?></span>
                    <span class="tran-num"><?php echo $this->translate('(') . $this->translate('%d', [0]) . $this->translate(')') ?></span>
                    <span class="bal-text"><?php echo $this->translate('&nbsp;&nbsp;Non-receiving') ?></span>
                    <span class="tran-num"><?php echo $this->translate('(') . $this->translate('%d', [0]) . $this->translate(')') ?></span>
                    <span class="bal-text"><?php echo $this->translate('&nbsp;&nbsp;Non-evaluation') ?></span>
                    <span class="tran-num"><?php echo $this->translate('(') . $this->translate('%d', [0]) . $this->translate(')') ?></span>
                </div>
            </div>
        </div>
        <div class="col-md-7 col-sm-12 col-xs-12">
            <div class="store_rating">
                <?php echo $this->translate('Store Dynamic Score') ?>
                <div class="">
                    <div class="col-sm-15 col-sm-3">
                        <div class="pad-5">
                            <p><?php echo $this->translate('Description Match') ?></p>
                            <p><?php echo $this->translate('4.27273') ?></p>
                            <p class="tran-num"><?php echo $this->translate('Less than %.2f%%', [11.69]) ?> <i class="fa fa-arrow-down" aria-hidden="true"></i></p>
                        </div>
                    </div>
                    <div class="col-sm-15 col-sm-3">
                        <div class="pad-5">
                            <p><?php echo $this->translate('Service Attitude') ?></p>
                            <p><?php echo $this->translate('4.27273') ?></p>
                            <p class="tran-num"> <?php echo $this->translate('Less than %.2f%%', [11.69]) ?> <i class="fa fa-arrow-down" aria-hidden="true"></i></p>
                        </div>
                    </div>
                    <div class="col-sm-15 col-sm-3">
                        <div class="pad-5">
                            <p><?php echo $this->translate('Logistics Service') ?></p>
                            <p><?php echo $this->translate('4.27273') ?></p>
                            <p class="tran-num"><?php echo $this->translate('Less than %.2f%%', [11.69]) ?> <i class="fa fa-arrow-down" aria-hidden="true"></i></p>
                        </div>
                    </div>
                    <div class="col-sm-15 col-sm-3">
                        <div class="pad-5">
                            <p><?php echo $this->translate('After Sales Attitude') ?></p>
                            <p><?php echo $this->translate('4.27273') ?></p>
                        </div>
                    </div>
                    <div class="col-sm-15 col-sm-3">
                        <div class="pad-5">
                            <p><?php echo $this->translate('After Sales Speed') ?></p>
                            <p><?php echo $this->translate('4.27273') ?></p>
                        </div>
                    </div>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>

    <div class="myorder">
        <div class="myorder-text display-inline-block"><?php echo $this->translate('Real Time Index') ?></div>
        <div class="myorder-info"><?php echo $this->translate('Update Time:&nbsp;%s', ['2016-07-14 14:44']) ?></div>
        <div class="view-more pull-right"><a href=""><?php echo $this->translate('More') ?></a></div>
    </div>

    <div class="order">
        <div class="real-time-index pad-20-30">
            <div class="col-md-4">
                <dl class="index-block mg-bottom-20">
                    <dt><span class="text-right"><?php echo $this->translate('Number of Visitors:&nbsp;') ?></span><span><?php echo $this->translate('%d', [123]) ?></span></dt>
                    <dd><span class="text-right"><?php echo $this->translate('Yesterday:&nbsp;') ?></span><span><?php echo $this->translate('%d', [123]) ?></span></dd>
                    <dd><span class="text-right"><?php echo $this->translate('This Week:&nbsp;') ?></span><span><?php echo $this->translate('%d', [123]) ?></span></dd>
                    <dd><span class="text-right"><?php echo $this->translate('This Month:&nbsp;') ?></span><span><?php echo $this->translate('%d', [123]) ?></span></dd>
                </dl>
            </div>
            <div class="col-md-4">
                <div class="middle-dashed-line">
                    <dl class="index-block mg-bottom-20">
                        <dt><span class="text-right"><?php echo $this->translate('Order Form:&nbsp;') ?></span><span><?php echo $this->translate('%d', [123]) ?></span></dt>
                        <dd><span class="text-right"><?php echo $this->translate('Yesterday:&nbsp;') ?></span><span><?php echo $this->translate('%d', [123]) ?></span></dd>
                        <dd><span class="text-right"><?php echo $this->translate('This Week:&nbsp;') ?></span><span><?php echo $this->translate('%d', [123]) ?></span></dd>
                        <dd><span class="text-right"><?php echo $this->translate('This Month:&nbsp;') ?></span><span><?php echo $this->translate('%d', [123]) ?></span></dd>
                    </dl>
                </div>
            </div>
            <div class="col-md-4">
                <dl class="index-block mg-bottom-20">
                    <dt><span class="text-right"><?php echo $this->translate('Sales Amount :&nbsp;') ?></span><span><?php echo $this->translate('%d', [123]) ?></span></dt>
                    <dd><span class="text-right"><?php echo $this->translate('Yesterday:&nbsp;') ?></span><span><?php echo $this->translate('%d', [123]) ?></span></dd>
                    <dd><span class="text-right"><?php echo $this->translate('This Week:&nbsp;') ?></span><span><?php echo $this->translate('%d', [123]) ?></span></dd>
                    <dd><span class="text-right"><?php echo $this->translate('This Month:&nbsp;') ?></span><span><?php echo $this->translate('%d', [123]) ?></span></dd>
                </dl>
            </div>
        </div>
    </div>

    <div class="statistics mg-bottom-40">
        <div class="col-md-6">
            <div class="col-mg-right-20">
                <div class="coupon-title">
                    <div class="myorder-text display-inline-block"><?php echo $this->translate('Sales of Product Order') ?></div>
                    <div class="view-more pull-right"><a href=""><?php echo $this->translate('More') ?></a></div>
                </div>
                <div class="statistics-list">
                    <table>
                        <tr>
                            <th colspan="2"><?php echo $this->translate('Product Name') ?></th>
                            <th class="text-right"><?php echo $this->translate('Sales Amount') ?></th>
                            <th class="text-right"><?php echo $this->translate('Compare Yesterday') ?></th>
                        </tr>
                        <tr>
                            <td><img alt="" src="<?php echo $this->getBaseUrl('/pub/theme/default/frontend/images/placeholder.png') ?>"  height="50" width="50" /></td>
                            <td><?php echo $this->translate('%s', ['Eagle Energy']) ?></td>
                            <td class="text-right"><?php echo $this->translate('%d', ['299']) ?></td>
                            <td class="text-right"><i class="fa fa-arrow-up color-orange" aria-hidden="true"></i><?php echo $this->translate('%d%%', ['299']) ?></td>
                        </tr>
                        <tr>
                            <td><img alt="" src="<?php echo $this->getBaseUrl('/pub/theme/default/frontend/images/placeholder.png') ?>"  height="50" width="50" /></td>
                            <td><?php echo $this->translate('%s', ['Eagle Energy']) ?></td>
                            <td class="text-right"><?php echo $this->translate('%d', ['299']) ?></td>
                            <td class="text-right"><i class="fa fa-arrow-up color-orange" aria-hidden="true"></i><?php echo $this->translate('%d%%', ['299']) ?></td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="col-mg-left-20">
                <div class="coupon-title">
                    <div class="myorder-text display-inline-block width-auto"><?php echo $this->translate('Store Vistors Composing') ?></div>
                    <div class="view-more pull-right"><a href=""><?php echo $this->translate('More') ?></a></div>
                </div>
                <div class="statistics-list">
                    <table>
                        <tr>
                            <td><?php echo $this->translate('PC') ?></td>
                            <td><?php echo $this->translate('%.2f%%', ['37.03']) ?></td>
                            <td><?php echo $this->translate('Wireless') ?></td>
                            <td><?php echo $this->translate('%.2f%%', ['62.96']) ?></td>
                        </tr>
                        <tr>
                            <td><?php echo $this->translate('Paid') ?></td>
                            <td><?php echo $this->translate('%.2f%%', ['4.16']) ?></td>
                            <td><?php echo $this->translate('Free') ?></td>
                            <td><?php echo $this->translate('%.2f%%', ['95.83']) ?></td>
                        </tr>
                        <tr>
                            <td><?php echo $this->translate('New Visitor') ?></td>
                            <td><?php echo $this->translate('%.2f%%', ['60.03']) ?></td>
                            <td><?php echo $this->translate('Old Visitor') ?></td>
                            <td><?php echo $this->translate('%.2f%%', ['39.97']) ?></td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>

</div>
