<?php
$retailer = $this->getRetailer();
$store = $this->getStore();
?>
<div class="dashboard">
    <div class="myinfo">
        <div class="infodetail col-lg-6 col-md-6">
            <div class="pull-left right-10">
                <img class="img-circle" src="<?php echo $retailer['profile'] ? 'data:image/png;base64, ' . base64_encode($retailer['profile']) : $this->getPubUrl('frontend/images/placeholder.png') ?>"  height="100" width="100" />
            </div>
            <div class="pad-left-120">
                <h3>
                    <?php echo $store['name'] ?>
                </h3>
                <div class="grade">
                    <span class="fa fa-star" aria-hidden="true"></span>
                    <span class="fa fa-star-o" aria-hidden="true"></span>
                    <span class="fa fa-star-o" aria-hidden="true"></span>
                    <span class="fa fa-star-o" aria-hidden="true"></span>
                    <span class="fa fa-star-o" aria-hidden="true"></span>
                    <div class="start">
                        <span class="start-v"><?php echo $this->translate('V') ?></span>
                        <span class="start-num"><?php echo $this->translate('%d', [0]) ?></span>
                    </div>
                </div>
                <ul>
                    <li>
                        <a href="<?php echo $this->getBaseUrl('retailer/store/setting/') ?>"><?php echo $this->translate('Store Settings') ?></a>
                    </li>
                    <li>
                        <a href="<?php echo $this->getBaseUrl('retailer/store/view/') ?>"><?php echo $this->translate('View My Store') ?></a>
                    </li>
                </ul>
                <dl>
                    <dt><?php echo $this->translate('Transaction') ?></dt>
                    <dd>
                        <?php echo $this->translate('Non-payment') ?>(<a href="<?php echo $this->getBaseUrl('sales/order/list/'); ?>"><?php echo $this->translate('%d', [0]) ?></a>)
                    </dd>
                    <dd>
                        <?php echo $this->translate('Non-receiving') ?>(<a href="<?php echo $this->getBaseUrl('sales/order/list/'); ?>"><?php echo $this->translate('%d', [0]) ?></a>)
                    </dd>
                    <dd><?php echo $this->translate('Non-evaluation') ?>(<a href="<?php echo $this->getBaseUrl('sales/order/list/'); ?>"><?php echo $this->translate('%d', [0]) ?></a>)
                    </dd>
                </dl>
            </div>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
            <div class="store_rating text-left">
                <h3 class="text-center"><?php echo $this->translate('Store Score') ?></h3>
                <div class="col-lg-12 col-md-12 text-center">
                    <div class="col-lg-4 col-md-4">
                        <div class="pad-5">
                            <p><?php echo $this->translate('Description Match') ?></p>
                            <p><?php echo $this->translate('4.27273') ?></p>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-4">
                        <div class="pad-5">
                            <p><?php echo $this->translate('Service Attitude') ?></p>
                            <p><?php echo $this->translate('4.27273') ?></p>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-4">
                        <div class="pad-5">
                            <p><?php echo $this->translate('Logistics Service') ?></p>
                            <p><?php echo $this->translate('4.27273') ?></p>
                        </div>
                    </div>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>

    <div class="myorder">
        <div class="myorder-text display-inline-block"><?php echo $this->translate('Real Time Index') ?></div>
        <div class="myorder-info"><?php echo $this->translate('Update Time:&nbsp;%s', ['2016-07-14 14:44']) ?></div>
        <div class="view-more pull-right"><a href=""><?php echo $this->translate('More') ?></a></div>
    </div>

    <div class="order">
        <div class="real-time-index pad-20-30">
            <div class="col-md-4">
                <dl class="index-block mg-bottom-20">
                    <dt><span class="text-right"><?php echo $this->translate('Number of Visitors:&nbsp;') ?></span><span><?php echo $this->translate('%d', [123]) ?></span></dt>
                    <dd><span class="text-right"><?php echo $this->translate('Yesterday:&nbsp;') ?></span><span><?php echo $this->translate('%d', [123]) ?></span></dd>
                    <dd><span class="text-right"><?php echo $this->translate('This Week:&nbsp;') ?></span><span><?php echo $this->translate('%d', [123]) ?></span></dd>
                    <dd><span class="text-right"><?php echo $this->translate('This Month:&nbsp;') ?></span><span><?php echo $this->translate('%d', [123]) ?></span></dd>
                </dl>
            </div>
            <div class="col-md-4">
                <div class="middle-dashed-line">
                    <dl class="index-block mg-bottom-20">
                        <dt><span class="text-right"><?php echo $this->translate('Order Form:&nbsp;') ?></span><span><?php echo $this->translate('%d', [123]) ?></span></dt>
                        <dd><span class="text-right"><?php echo $this->translate('Yesterday:&nbsp;') ?></span><span><?php echo $this->translate('%d', [123]) ?></span></dd>
                        <dd><span class="text-right"><?php echo $this->translate('This Week:&nbsp;') ?></span><span><?php echo $this->translate('%d', [123]) ?></span></dd>
                        <dd><span class="text-right"><?php echo $this->translate('This Month:&nbsp;') ?></span><span><?php echo $this->translate('%d', [123]) ?></span></dd>
                    </dl>
                </div>
            </div>
            <div class="col-md-4">
                <dl class="index-block mg-bottom-20">
                    <dt><span class="text-right"><?php echo $this->translate('Sales Amount :&nbsp;') ?></span><span><?php echo $this->translate('%d', [123]) ?></span></dt>
                    <dd><span class="text-right"><?php echo $this->translate('Yesterday:&nbsp;') ?></span><span><?php echo $this->translate('%d', [123]) ?></span></dd>
                    <dd><span class="text-right"><?php echo $this->translate('This Week:&nbsp;') ?></span><span><?php echo $this->translate('%d', [123]) ?></span></dd>
                    <dd><span class="text-right"><?php echo $this->translate('This Month:&nbsp;') ?></span><span><?php echo $this->translate('%d', [123]) ?></span></dd>
                </dl>
            </div>
        </div>
    </div>

    <div class="statistics mg-bottom-40">
        <div class="col-lg-12 col-md-12">
            <div class="coupon-title">
                <div class="myorder-text display-inline-block"><?php echo $this->translate('Sales of Product Order') ?></div>
                <div class="view-more pull-right"><a href=""><?php echo $this->translate('More') ?></a></div>
            </div>
            <table class="table">
                <tr>
                    <th><?php echo $this->translate('Product Name') ?></th>
                    <th><?php echo $this->translate('SKU'); ?></th>
                    <th class="text-right"><?php echo $this->translate('Sales Amount') ?></th>
                    <th class="text-right"><?php echo $this->translate('Compare Yesterday') ?></th>
                </tr>
                <tr>
                    <td><img src="<?php echo $this->getBaseUrl('/pub/theme/default/frontend/images/placeholder.png') ?>"  height="100" width="100" />
                        <h3><?php echo $this->translate('%s', ['Eagle Energy']) ?></h3></td>
                    <td>12</td>
                    <td class="text-right"><?php echo $this->translate('%d', ['299']) ?></td>
                    <td class="text-right"><i class="fa fa-arrow-up color-orange" aria-hidden="true"></i><?php echo $this->translate('%d%%', ['299']) ?></td>
                </tr>
            </table>
        </div>
    </div>
</div>
