<?php
  $templates = $this->getTemplateList();
?>
<main class="col-main col-xs-9 col-sm-9 col-md-10 mg-bottom-40 sales-products">
    <div class="wishlist decorationlist">
    <h3><?php echo $this->translate('Store Decoration'); ?></h3>

    <div style="clear:both"></div>

    <div class="seperation-title"><span class="title">主题模版</span> 共有  4 条记录</div>
    <hr class="seperation">
    <div class="decoration-content">
     <ul>
     	<li>
     	<div class="top">
     		<div class="position1">模版1</div>
     		<div class="position2"><button class="btn btn-danger btn-sm">使用该模版</button></div>
     	</div>
     	<div class="bottom">经典模版</div>	
     	</li>
     	
     	     	<li>
     	<div class="top">
     		<div class="position1">模版1</div>
     		<div class="position2"><button class="btn btn-danger btn-sm">使用该模版</button></div>
     	</div>
     	<div class="bottom">经典模版</div>	
     	</li>
     	
     </ul>
     
        
        <div class="page-block" style="clear:both">
        <div>

         </div>
        </div>
    </div>
    
    <div class="seperation-title"><span class="title">我的模版</span> <span>共有  4 条记录</span> &nbsp;&nbsp;&nbsp; <button class="btn btn-primary" onclick="window.location='<?php echo $this->getBaseUrl('/retailer/store/decoration') ?>'">新建模版</button></div>
    <hr class="seperation">
    <div class="decoration-content">
     <ul>
     	
     	<?php foreach ($templates as $key => $template) { ?>
     	
     	<li>
     	<div class="top">
     		<div class="position1">模版1</div>
     		<div class="position3">
     			<button class="btn btn-success btn-sm" onclick="window.location='<?php echo $this->getBaseUrl('/retailer/store/decoration?id='.$template['id']) ?>'" >修改</button>
     			<button class="btn btn-danger btn-sm">删除</button>
					<button class="btn btn-info btn-sm">设为当前模版</button>
					</div>
     	</div>
     	<div class="bottom"><?php echo $template['template_name'] ?></div>	
     	</li>
    <?php } ?> 
     
     </ul>
     
        
        <div class="page-block" style="clear:both">
        <div>

         </div>
        </div>
    </div>
    
    
    <div id="modal-receive" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="receiveModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="receiveModalLabel">收到货款</h4>
                </div>
                <div class="modal-body">
                    <div >
                        <h1>您确定已经收到买家的货款了吗？</h1>
                        <p>订单号&nbsp;&nbsp;&nbsp;&nbsp;:<span>88888888888</span></p>
                        <dl>
                            <dt>操作原因:</dt>
                            <dd><textarea name="remark"></textarea></dd>
                        </dl>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                    <button type="button" class="btn btn-primary">确认</button>
                </div>
            </div>
        </div>
    </div>
    
    <div id="modal-price" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="priceModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="priceModalLabel">费用调整</h4>
                </div>
                <div class="modal-body">
                    <div>买家:&nbsp;&nbsp;Stone<br>订单号&nbsp;&nbsp;:<strong>88888888888</strong></div>
                    <div>
                        <ul>
                            <li>
                                <h3>商品总价:<strong>¥100.00</strong></h3>
                                <p><input type="text" value="100.00" name="goods_amount"></p>
                            </li>
                            <li>
                                <h3>配送费用:<strong>¥10.00</strong></h3>
                                <p><input type="text" value="10.00" name="shipping_fee"></p>
                            </li>
                        </ul>
                    </div>
                    <div><h3>订单总价:<strong>¥110.00</strong></h3></div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                    <button type="button" class="btn btn-primary">确认</button>
                </div>
            </div>
        </div>
    </div>
    
    <div id="modal-cancel" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="cancelModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="cancelModalLabel">费用调整</h4>
                </div>
                <div class="modal-body">
                    <h1>您是否确定要取消以下订单？</h1>
                    <p>订单号&nbsp;&nbsp;&nbsp;&nbsp;:<span>88888888888</span></p>
                    <dl>
                        <dt>取消原因:</dt>
                        <dd>
                            <div class="li">
                                <input type="radio" value="无法备齐货物" id="d1" name="cancel_reason" checked=""> <label for="d1">无法备齐货物</label>
                            </div>
                            <div class="li">
                                <input type="radio" value="不是有效的订单" id="d2" name="cancel_reason"> <label for="d2">不是有效的订单</label>
                            </div>
                            <div class="li">
                                <input type="radio" value="买家主动要求" id="d3" name="cancel_reason"> <label for="d3">买家主动要求</label>
                            </div>
                            <div class="li">
                                <input type="radio" value="其他原因" id="d4" flag="other_reason" name="cancel_reason"> <label for="d4">其他原因</label>
                            </div>
                        </dd>
                        <dd id="other_reason">
                            <textarea name="remark" id="other_reason_input"></textarea>
                        </dd>
                    </dl>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary">确认</button>
                </div>
            </div>
        </div>
    </div>
    </div>
</main>
<script>
	$(function(){
		$(".decorationlist .decoration-content li div.top").mouseover(function(){
			$(this).find('.position2').show();
			$(this).find('.position3').show();
		});
		
	$(".decorationlist .decoration-content li div.top").mouseout(function(){
			$(this).find('.position2').hide();
			$(this).find('.position3').hide();
		});
		
		
	});
</script>