<?php
    $subtitle = $this->getVariable("subtitle");
    $order = $this->getVariable("order");
    $transactions = $this->getRetailerTransaction();
    $sales_status = $this->getAllSalesStatus();
    
?>
<div class="col-xs-9 col-sm-9 col-md-10 wishlist mg-bottom-40">
    <h3><?php echo $this->translate($subtitle); ?></h3>
    
    <div class="filter-bar">
        <form class="form-inline" action="<?php echo $this->getCurrentUrl() ?>" method="get" novalidate = "novalidate">
            <div >
                <span>订单号:</span>
                <input class="form-control " type="text" value="" name="id">&nbsp;&nbsp;
                <span>订单状态:</span>
                <select class="form-control " id="order_status" name="order_status">
                    <option value="0">全部</option>
                    <?php
                        foreach($sales_status as $item){
                        echo '<option value="'.$item['id'].'">'.$this->translate($item['name']).'</option>';
                        }
                    ?>
                </select>&nbsp;&nbsp;
                <span>发货状态:</span>
                <select class="form-control " id="send_status" name="send_status">
                     <option value="">全部</option>
                </select>&nbsp;&nbsp;
                <input type="hidden" value="<?php echo $order['type']; ?>" name="type">
                <button class="btn" type="submit">搜索</button><br />
                <span>运单号:</span>
                <input class="form-control " type="text" value="" id="send_id" name="send_id">&nbsp;&nbsp;
                <span>支付状态:</span>
                <select class="form-control " id="pay_status" name="pay_status">
                     <option value="">全部</option>
                </select>&nbsp;&nbsp;
                <span>售后状态:</span>
                <select class="form-control " id="sold_status" name="sold_status">
                     <option value="">全部</option>
                </select>&nbsp;&nbsp;<br />
                
                <span>用户名:</span>
                <input class="form-control " type="text" value="" name="buyer_name">&nbsp;&nbsp;
                <span>成交时间:</span>
                <input class="form-control " type="text" value="" id="add_time_from" name="add_time_from">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&ndash;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input class="form-control " type="text" value="" name="add_time_to" id="add_time_to">&nbsp;&nbsp;<br />
                <span>收件人:</span>
                <input class="form-control " type="text" value="" id="receiver" name="receiver">&nbsp;&nbsp;
            </div>
        </form>
    </div>
    <br /><br />
    
    <div class="">
        <div>
            <div class="pull-left">
                <div>
                    <label>
                    <input type="checkbox" data-cbtype="all">
                    <span>全选</span>
                    </label>
                    <button class="btn-options">批量发货</button>
                    <button class="btn-options">批量标记</button>
                    <button class="btn-options">批量免运费</button>
                    <label>
                    <input type="checkbox">
                    <span>不显示已关闭的订单</span>
                    </label>
                </div>
            </div>
            <div class="pull-right">
                <div>
                    <button class="btn-options">上一页</button>
                    <button class="btn-options">下一页</button>
                </div>
            </div>
        </div>
        <div class="clearfix mg-bottom-20"></div>
        <table class="table table-title">
            <tr>
                <td style="width: 35%;">商品</td>
                <td style="width: 8%;">单价</td>
                <td style="width: 8%;">数量</td>
                <td style="width: 8%;">售后</td>
                <td style="width: 11%;">买家</td>
                <td style="width: 11%;">交易状态</td>
                <td style="width: 11%;">实收款</td>
                <td style="width: 8%;">评价</td>
            </tr>
        </table>
        <div class="clearfix mg-bottom-10"></div>
        <?php
            foreach($transactions as $transaction){
        ?>
        <div class="transaction-list">
            <table class="table table-info">
                <tr>
                    <td colspan="7">
                        <label>
                        <input type="checkbox" value="<?php echo $transaction['id']; ?>" name="orderid">
                        <span>订单号: </span><span><?php echo $transaction['increment_id']; ?></span>&nbsp;&nbsp;&nbsp;&nbsp;<span>成交时间: </span><span> </span><span><?php echo $transaction['created_at']; ?></span>
                        </label>
                    </td>
                    <td>&nbsp;</td>
                </tr>
            </table>
            <table class="list-info">
                <?php
                    foreach($transaction['items'] as $key => $item){
                        $thumbnail =  $this->getProduct($item['product_id'])->getThumbnail();
                ?>
                <tr>
                    <td style="width: 35%;">
                        <div class="good-pic">
                            <a href="">
                                <?php if (strpos($thumbnail, 'http') === false){ ?>
                                    <img src="<?php echo $this->getBaseUrl('pub/resource/image/resized/' . $thumbnail) ?>" class="bttrlazyloading" data-bttrlazyloading-lg-src="<?php echo $this->getBaseUrl('pub/resource/image/resized/50x/' . $thumbnail) ?>" data-bttrlazyloading-md-src="<?php echo $this->getBaseUrl('pub/resource/image/resized/108x/' . $thumbnail) ?>" data-bttrlazyloading-sm-src="<?php echo $this->getBaseUrl('pub/resource/image/resized/125x/' . $thumbnail) ?>" data-bttrlazyloading-xs-src="<?php echo $this->getBaseUrl('pub/resource/image/resized/256x/' . $thumbnail) ?>" alt="<?php echo $item['product_name']; ?>" />
                                <?php }else{ ?>
                                    <img src="<?php echo $thumbnail ?>" alt="<?php echo $item['product_name']; ?>" />
                                <?php } ?>
                            </a>
                        </div>
                        <div class="good-title">
                            <p>
                                <a target="_blank" href="">
                                    <span><?php echo $item['product_name'] ?></span>
                                </a>
                            </p>
                        </div>
                    </td>
                    <td style="width: 8%;">
                        <div>
                            <p class="text-center">
                                <span><?php echo $this->getCurrency()->format($item['price']); ?></span>
                            </p>
                        </div>
                    </td>
                    <td style="width: 8%;">
                        <div>
                            <p class="text-center"><?php echo $this->translate('%d', [$item['qty']]); ?></p>
                        </div>
                    </td>
                    <td class="border-right" style="width: 8%;">&nbsp; </td>
                    <td class="border-right" style="width: 11%;">
                        <?php
                            if($key == 0){
                        ?>
                        <div>
                            <p class="text-center word-break-all">
                                <a href="" target="_blank"><?php echo $customer = $this->getCustomerByID($transaction['customer_id'])->username; ?></a><i title="查询该买家订单"></i>
                            </p>
                            <p class="text-center">
                                <a title="查询该买家订单" target="_blank" href=""></a>
                            </p>
                        </div>
                        <?php
                            }else{
                                echo '&nbsp;';
                            }
                        ?>
                    </td>
                    <td class="border-right" style="width: 11%;">
                        <?php
                            if($key == 0){
                        ?>
                        <div>
                            <p class="text-center">
                                <span ><?php echo $this->translate($transaction['status_name']); ?></span>
                            </p>
                            <p class="text-center">
                                <a target="_blank" href="">详情</a>
                            </p>
                        </div>
                        <?php
                            }else{
                                echo '&nbsp;';
                            }
                        ?>
                    </td>
                    <td class="border-right" style="width: 11%;">
                        <?php
                            if($key == 0){
                        ?>
                        <div>
                            <p class="text-center">
                                <strong><span><?php echo $this->getCurrency()->format($item['total']); ?></span></strong>
                            </p>
                            <p class="text-center">
                                <span class="font-12">(含快递:<?php echo $this->getCurrency()->format($transaction['shipping']); ?>)</span>
                            </p>
                        </div>
                        <?php
                            }else{
                                echo '&nbsp;';
                            }
                        ?>
                    </td>
                    <td style="width: 8%;">&nbsp;</td>
                </tr>
                <?php
                    }
                ?>
            </table>
        </div>
        <?php
            }
        ?>
        
        <div>
            <div class="pull-left">
                <div>
                    <label>
                    <input type="checkbox" data-cbtype="all">
                    <span>全选</span>
                    </label>
                    <button class="btn-options">批量发货</button>
                    <button class="btn-options">批量标记</button>
                    <button class="btn-options">批量免运费</button>
                </div>
            </div>
            <div class="pull-right">
                <!--div>
                    <button class="btn-options">上一页</button>
                    <button class="btn-options">下一页</button>
                </div-->
                <?php
                    if (is_object($this->getVariable('collection'))) {
                        echo $this->getChild('pager')->setCollection($this->getVariable('collection'));
                    }
                    ?>
            </div>
        </div>
    </div>
    
    <div id="modal-receive" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="receiveModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="receiveModalLabel">收到货款</h4>
                </div>
                <div class="modal-body">
                    <div >
                        <h1>您确定已经收到买家的货款了吗？</h1>
                        <p>订单号&nbsp;&nbsp;&nbsp;&nbsp;:<span>88888888888</span></p>
                        <dl>
                            <dt>操作原因:</dt>
                            <dd><textarea name="remark"></textarea></dd>
                        </dl>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                    <button type="button" class="btn btn-primary">确认</button>
                </div>
            </div>
        </div>
    </div>
    
    <div id="modal-price" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="priceModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="priceModalLabel">费用调整</h4>
                </div>
                <div class="modal-body">
                    <div>买家:&nbsp;&nbsp;Stone<br>订单号&nbsp;&nbsp;:<strong>88888888888</strong></div>
                    <div>
                        <ul>
                            <li>
                                <h3>商品总价:<strong>¥100.00</strong></h3>
                                <p><input type="text" value="100.00" name="goods_amount"></p>
                            </li>
                            <li>
                                <h3>配送费用:<strong>¥10.00</strong></h3>
                                <p><input type="text" value="10.00" name="shipping_fee"></p>
                            </li>
                        </ul>
                    </div>
                    <div><h3>订单总价:<strong>¥110.00</strong></h3></div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                    <button type="button" class="btn btn-primary">确认</button>
                </div>
            </div>
        </div>
    </div>
    
    <div id="modal-cancel" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="cancelModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="cancelModalLabel">费用调整</h4>
                </div>
                <div class="modal-body">
                    <h1>您是否确定要取消以下订单？</h1>
                    <p>订单号&nbsp;&nbsp;&nbsp;&nbsp;:<span>88888888888</span></p>
                    <dl>
                        <dt>取消原因:</dt>
                        <dd>
                            <div class="li">
                                <input type="radio" value="无法备齐货物" id="d1" name="cancel_reason" checked=""> <label for="d1">无法备齐货物</label>
                            </div>
                            <div class="li">
                                <input type="radio" value="不是有效的订单" id="d2" name="cancel_reason"> <label for="d2">不是有效的订单</label>
                            </div>
                            <div class="li">
                                <input type="radio" value="买家主动要求" id="d3" name="cancel_reason"> <label for="d3">买家主动要求</label>
                            </div>
                            <div class="li">
                                <input type="radio" value="其他原因" id="d4" flag="other_reason" name="cancel_reason"> <label for="d4">其他原因</label>
                            </div>
                        </dd>
                        <dd id="other_reason">
                            <textarea name="remark" id="other_reason_input"></textarea>
                        </dd>
                    </dl>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary">确认</button>
                </div>
            </div>
        </div>
    </div>
    
</div>
