<?php
    $subtitle = $this->getVariable("subtitle");
    $order = $this->getVariable("order");
?>
<div class="col-xs-9 col-sm-9 col-md-10 wishlist mg-bottom-40">
    <h3><?php echo $this->translate($subtitle); ?></h3>
    
    <div id="scarch_order">
        <form method="get">
            <div >
                <span>订单号:</span>
                <input type="text" value="" name="order_sn">
                <span>下单时间:</span>
                <input type="text" value="" id="add_time_from" name="add_time_from"> &ndash; <input type="text" value="" name="add_time_to" id="add_time_to">
                <span>买家:</span>
                <input type="text" value="" name="buyer_name">
                <input type="hidden" value="<?php echo $order['type']; ?>" name="type">
                <input type="submit" value="搜索" class="btn">
            </div>
        </form>
    </div>
    <br /><br />
    
    <div id="search_list">
        <table style="width: 100%;">
            <tr>
                <th><input type="checkbox"  id="all"></th>
                <th colspan="7">
                    <label for="all"><span class="all">全选</span></label>
                    <a name="order_id" uri="#" ectype="batchcancel" href="javascript:;">取消订单</a>
                </th>
            </tr>
            <tr>
                <th></th>
                <th>订单号</th>
                <th>买家</th>
                <th>收货人姓名</th>
                <th>电话号码</th>
                <th>支付方式</th>
                <th>订单总价</th>
                <th>订单状态</th>
            </tr>
            <tr>
                <td><input type="checkbox" value=""></td>
                <td><span>88888888888</span></td>
                <td>Buyer</td>
                <td>Stone</td>
                <td>13333333333<br>
                </td>
                <td>支付宝</td>
                <td><strong>¥110.00</strong></td>
                <td><span>待付款</span></td>
            </tr>
            <tr>
                <td align="right" colspan="8">
                    <div>
                        <button data-toggle="modal" data-target="#modal-receive">收到货款</button>
                        <button data-toggle="modal" data-target="#modal-price">调整费用</button>
                        <button data-toggle="modal" data-target="#modal-cancel">取消订单</button>
                        <a target="_blank" href="<?php echo $this->getBaseUrl('retailer/transaction/orderview')?>">查看订单</a>
                    </div>
                </td>
            </tr>
            <tr>
                <td><input type="checkbox" value=""></td>
                <td><span>88888888889</span></td>
                <td>Buyer</td>
                <td>Stone</td>
                <td>13333333333<br>
                </td>
                <td>支付宝</td>
                <td><strong>¥110.00</strong></td>
                <td><span>待付款</span></td>
            </tr>
            <tr>
                <td align="right" colspan="8">
                    <div>
                        <button>收到货款</button>
                        <button>调整费用</button>
                        <button>取消订单</button>
                        <a target="_blank" href="#">查看订单</a>
                    </div>
                </td>
            </tr>
            <tr>
                <th><input type="checkbox" id="all2"></th>
                <th colspan="7">
                    <p>
                        <label for="all2"><span class="all">全选</span></label>
                        <a name="order_id" uri="#" ectype="batchcancel" href="javascript:;">取消订单</a>
                    </p>
                    <div style="text-align: right;">
                        <a>共 2 个项目</a>
                        <a href="#">上一页</a>
                        <a href="#">1</a>
                        <span>1 / 1</span>
                        <a href="#">下一页</a>
                    </div>
                </th>
            </tr>
        </table>
    </div>
    
    <div id="modal-receive" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="receiveModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="receiveModalLabel">收到货款</h4>
                </div>
                <div class="modal-body">
                    <div >
                        <h1>您确定已经收到买家的货款了吗？</h1>
                        <p>订单号&nbsp;&nbsp;&nbsp;&nbsp;:<span>88888888888</span></p>
                        <dl>
                            <dt>操作原因:</dt>
                            <dd><textarea name="remark"></textarea></dd>
                        </dl>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                    <button type="button" class="btn btn-primary">确认</button>
                </div>
            </div>
        </div>
    </div>
    
    <div id="modal-price" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="priceModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="priceModalLabel">费用调整</h4>
                </div>
                <div class="modal-body">
                    <div>买家:&nbsp;&nbsp;Stone<br>订单号&nbsp;&nbsp;:<strong>88888888888</strong></div>
                    <div>
                        <ul>
                            <li>
                                <h3>商品总价:<strong>¥100.00</strong></h3>
                                <p><input type="text" value="100.00" name="goods_amount"></p>
                            </li>
                            <li>
                                <h3>配送费用:<strong>¥10.00</strong></h3>
                                <p><input type="text" value="10.00" name="shipping_fee"></p>
                            </li>
                        </ul>
                    </div>
                    <div><h3>订单总价:<strong>¥110.00</strong></h3></div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                    <button type="button" class="btn btn-primary">确认</button>
                </div>
            </div>
        </div>
    </div>
    
    <div id="modal-cancel" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="cancelModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="cancelModalLabel">费用调整</h4>
                </div>
                <div class="modal-body">
                    <h1>您是否确定要取消以下订单？</h1>
                    <p>订单号&nbsp;&nbsp;&nbsp;&nbsp;:<span>88888888888</span></p>
                    <dl>
                        <dt>取消原因:</dt>
                        <dd>
                            <div class="li">
                                <input type="radio" value="无法备齐货物" id="d1" name="cancel_reason" checked=""> <label for="d1">无法备齐货物</label>
                            </div>
                            <div class="li">
                                <input type="radio" value="不是有效的订单" id="d2" name="cancel_reason"> <label for="d2">不是有效的订单</label>
                            </div>
                            <div class="li">
                                <input type="radio" value="买家主动要求" id="d3" name="cancel_reason"> <label for="d3">买家主动要求</label>
                            </div>
                            <div class="li">
                                <input type="radio" value="其他原因" id="d4" flag="other_reason" name="cancel_reason"> <label for="d4">其他原因</label>
                            </div>
                        </dd>
                        <dd id="other_reason">
                            <textarea name="remark" id="other_reason_input"></textarea>
                        </dd>
                    </dl>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary">确认</button>
                </div>
            </div>
        </div>
    </div>
    
</div>
