<div class="container">
    <div class="col-md-12">
        <div>
            <h3>客户信息</h3>
        </div>
        <br />
        
        <div class="row">
            <table class="table table-bordered">
                <tr>
                    <td>真实姓名</td>
                    <td><span>李雪 </span></td>
                    <td><span>性别</span></td>
                    <td><span>女</span></td>
                    <td><span>手机</span></td>
                    <td><span>11111111111</span></td>
                </tr>
                  <tr>
                    <td><span>电子邮箱</span></td>
                    <td>&nbsp;</td>
                    <td><span>生日</span></td>
                    <td>&nbsp;</td>
                    <td><span>省份城市</span></td>
                    <td><span>山东省 青岛市</span></td>
                </tr>
            </table>
            <br />
            <table  class="table table-bordered">
                <tr>
                    <td>会员级别</td>
                    <td><span>普通会员</span></td>
                    <td><span>客户来源</span></td>
                    <td><span>交易成功</span></td>
                    <td><span>会员状态</span></td>
                    <td><span>享受折扣 </span></td>
                </tr>
                <tr>
                    <td>信用等级</td>
                    <td>5</td>
                    <td>交易次数</td>
                    <td><span>1次</span></td>
                    <td>交易额</td>
                    <td><span>75.80（元）</span></td>
                </tr>
                <tr>
                    <td>上次交易时间</td>
                    <td><span>2016-07-14</span></td>
                    <td>宝贝件数</td>
                    <td><span>2件</span></td>
                    <td>平均订单金额</td>
                    <td><span>75.80（元）</span></td>
                </tr>
                <tr>
                    <td>交易关闭数</td>
                    <td><span>0笔</span></td>
                    <td colspan="4"></td>
                </tr>
                <tr class="bottom">
                    <td>收货地址</td>
                    <td colspan="5"><span>******************</span></td>
                </tr>
            </table>
            <br />
            <table class="table table-bordered">
                <tr>
                    <td><span>备注</span></td>
                    <td colspan="2">内容</td>
                    <td colspan="2">时间</td>
                    <td>操作</td>
                </tr>
            </table>
            <br /><br />
        </div>
    </div>
</div>
