<div class="container">
    <div class="col-md-12">
        <div>
            <h3>订单详情</h3>
            <div>
                <div>订单状态&nbsp;:&nbsp;<strong>待付款</strong></div>
                <div>订单号&nbsp;:&nbsp;88888888888</div>
                <div>下单时间&nbsp;:&nbsp;2016-08-24 11:55:35</div>
            </div>
            <br />
            <h3>订单信息</h3>
            <dl>
                <dt>买家信息</dt>
                <dd>买家&nbsp;:&nbsp;Buyer</dd>
                <dd>电话号码&nbsp;:&nbsp;13333333333</dd>
                 <dd>所在地区&nbsp;:&nbsp;中国    山东省 青岛</dd>
                 <dd>手机号码&nbsp;:&nbsp;-</dd>
                 <dd>电子邮件&nbsp;:&nbsp;stonesun@seahinet.com</dd>
                 <dd>详细地址&nbsp;:&nbsp;不知道</dd>
             </dl>
             <div>
                <div>
                    <div>
                        <div><img width="50" height="50" src="<?php echo $this->getBaseUrl('/pub/theme/default/frontend/images/placeholder.png')?>"></div>
                        <div>
                            <div>
                                <a href="#">test</a><br>
                            </div>
                            <div>
                                <span>数量&nbsp;:&nbsp;<strong>1</strong></span>
                                <span>单价&nbsp;:&nbsp;<strong>100.00</strong></span>
                            </div>
                        </div>
                    </div>
                    <div>
                        <div><img width="50" height="50" src="<?php echo $this->getBaseUrl('/pub/theme/default/frontend/images/placeholder.png')?>"></div>
                        <div>
                            <div>
                                <a href="#">test2</a><br>
                            </div>
                            <div>
                                <span>数量&nbsp;:&nbsp;<strong>1</strong></span>
                                <span>单价&nbsp;:&nbsp;<strong>100.00</strong></span>
                            </div>
                        </div>
                    </div>
                    <div>
                        <div><img width="50" height="50" src="<?php echo $this->getBaseUrl('/pub/theme/default/frontend/images/placeholder.png')?>"></div>
                        <div>
                            <a href="#">test3</a><br>
                        </div>
                        <div>
                            <span>数量&nbsp;:&nbsp;<strong>1</strong></span>
                            <span>单价&nbsp;:&nbsp;<strong>100.00</strong></span>
                        </div>
                    </div>
                    <div class="ware_list">
                        <div><img width="50" height="50" src="<?php echo $this->getBaseUrl('/pub/theme/default/frontend/images/placeholder.png')?>"></div>
                        <div>
                            <div>
                                <a href="#">test4</a><br>
                            </div>
                            <div>
                                <span>数量&nbsp;:&nbsp;<strong>1</strong></span>
                                <span>单价&nbsp;:&nbsp;<strong>100.00</strong></span>
                            </div>
                        </div>
                    </div>
                    <div>
                        <div><img width="50" height="50" src="<?php echo $this->getBaseUrl('/pub/theme/default/frontend/images/placeholder.png')?>"></div>
                        <div>
                            <div>
                                <a href="#">test5</a><br>
                            </div>
                            <div>
                                <span>数量&nbsp;:&nbsp;<strong>1</strong></span>
                                <span>单价&nbsp;:&nbsp;<strong>100.00</strong></span>
                            </div>
                        </div>
                    </div>
                    <br />
                    <div>配送费用&nbsp;:&nbsp;<span>¥10.00<strong>(sf)</strong></span>优惠打折&nbsp;:&nbsp;<span>¥0.00</span>订单总价&nbsp;:&nbsp;<b>¥510.00</b>
                    </div>
                    <ul>
                        <li>下单时间&nbsp;:&nbsp;2016-08-24 11:55:35</li>
                    </ul>
               </div>
           </div>
           <br />
            <h3>收货人及物流信息</h3>
            <div>
               收货地址&nbsp;:&nbsp;Stone,&nbsp;13333333333 ,&nbsp;中国    山东省 青岛&nbsp;不知道                ,&nbsp;266000<br>
               配送方式&nbsp;:&nbsp;sf<br>
            </div>
        </div>
    </div>
</div>
