<?php
$subtitle = $this->getVariable("subtitle");
$filter = $this->getVariable("filter");
$transactions = $this->getRetailerTransaction();
$sales_status = $this->getAllSalesStatus();
?>
<div class="wishlist">
    <h3><?php echo $this->translate($subtitle); ?></h3>
    <div class="filter-bar col-md-12 col-xs-12 col-sm-12">
        <form class="form-inline" action="<?php echo $this->getCurrentUrl() ?>" method="get" novalidate = "novalidate">
            <div class="soldout">
                <div class=" col-md-3 col-xs-12 col-sm-6">
                    <label><?php echo $this->translate('Order Number'); ?>:</label>
                    <input class="form-control " type="text" value="<?php echo isset($filter['increment_id']) ? $filter['increment_id'] : ''; ?>" name="increment_id">
                </div>
                <div class="col-md-3 col-xs-12 col-sm-6">
                    <label><?php echo $this->translate('Trading Status'); ?>:</label>
                    <select class="form-control " id="order_status" name="order_status">
                        <option value="0"><?php echo $this->translate('All'); ?></option>
                        <?php
                        foreach ($sales_status as $item) {
                            $selected = (isset($filter['order_status']) && $filter['order_status'] == $item['id']) ? 'selected' : '';
                            echo '<option value="' . $item['id'] . '" ' . $selected . '>' . $this->translate($item['name']) . '</option>';
                        }
                        ?>
                    </select>
                </div>
                <div class=" col-md-6 col-xs-12 col-sm-6">
                    <label><?php echo $this->translate('Closing Time'); ?>:</label>
                    <input class="form-control " type="text" value="<?php echo isset($filter['add_time_from']) ? $filter['add_time_from'] : ''; ?>" readonly="readonly" id="add_time_from" name="add_time_from">-<input class="form-control" readonly="readonly" type="text" value="<?php echo isset($filter['add_time_to']) ? $filter['add_time_to'] : ''; ?>" name="add_time_to" id="add_time_to">
                </div>
                <div class=" col-md-3 col-xs-12 col-sm-6">
                    <label><?php echo $this->translate('Rcpt To'); ?>:</label>
                    <input class="form-control " type="text" value="<?php echo isset($filter['receiver']) ? $filter['receiver'] : ''; ?>" id="receiver" name="receiver" />
                </div>
                <div class=" col-md-3 col-xs-12 col-sm-6">
                    <label><?php echo $this->translate('Tracking Number'); ?>:</label>
                    <input class="form-control " type="text" value="<?php echo isset($filter['track_id']) ? $filter['track_id'] : ''; ?>" id="track_id" name="track_id">
                </div>
                <div class="col-md-6 col-xs-12 col-sm-6">
                    <label><?php echo $this->translate('Telephone / Cell phone'); ?>:</label>     
                    <input class="form-control " type="text" value="<?php echo isset($filter['receiver_phone']) ? $filter['receiver_phone'] : ''; ?>" id="receiver_phone" name="receiver_phone" />              
                </div>
                <div class="col-md-12 col-xs-12 col-sm-12">
                    <a class="btn" href="<?php echo $this->getBaseUrl('retailer/transaction/product/'); ?>"><?php echo $this->translate('Reset') ?></a>&nbsp;&nbsp;
                    <button class="btn" type="submit"><?php echo $this->translate('Search'); ?></button>
                </div>
            </div>
        </form>
    </div>
    <br />
    <div class="">
        <div style="display: none;">
            <div class="pull-left">
                <div class="batch_button" >
                    <label>
                        <input type="checkbox" data-cbtype="all">
                        <span><?php echo $this->translate('Select All'); ?></span>
                    </label>
                    <button class="btn-options">批量发货</button>
                    <button class="btn-options">批量标记</button>
                    <button class="btn-options">批量免运费</button>
                    <label>
                        <input type="checkbox">
                        <span>不显示已关闭的订单</span>
                    </label>
                </div>
            </div>
        </div>
        <div class="clearfix mg-bottom-20"></div>
        <table class="table table-title">
            <tr>
                <td style="width: 35%;"><?php echo $this->translate('Goods'); ?></td>
                <td style="width: 8%;"><?php echo $this->translate('Price'); ?></td>
                <td style="width: 8%;"><?php echo $this->translate('Qty'); ?></td>
                <td style="width: 11%;"><?php echo $this->translate('Buyer'); ?></td>
                <td style="width: 11%;"><?php echo $this->translate('Trading Status'); ?></td>
                <td style="width: 11%;"><?php echo $this->translate('True Income'); ?></td>
                <td style="width: 8%;"><?php echo $this->translate('operating'); ?></td>
            </tr>
        </table>
        <div class="clearfix mg-bottom-10"></div>
        <?php
        foreach ($transactions as $transaction) {
            ?>
            <div class="transaction-list">
                <table class="table table-info">
                    <tr>
                        <td colspan="7">
                            <label>
                                <span><?php echo $this->translate('Order ID'); ?>: </span><span><?php echo $transaction['increment_id']; ?></span>&nbsp;&nbsp;&nbsp;&nbsp;<span><?php echo $this->translate('Closing Time'); ?>: </span><span> </span><span><?php echo $transaction['created_at']; ?></span>
                            </label>
                        </td>
                        <td>&nbsp;</td>
                    </tr>
                </table>
                <?php
                if (!empty($transaction['items'])) {
                    ?>
                    <table class="table list-info">
                        <?php
                        $flag = true;
                        foreach ($transaction['items'] as $key => $item) {
                            $thumbnail = $this->getProduct($item['product_id'])->getThumbnail();
                            ?>
                            <tr>
                                <td style="width: 35%;">
                                    <div class="product-pic">
                                        <a href="<?php echo $this->getProduct($item['product_id'])->getUrl(); ?>" title="<?php echo $item['product_name']; ?>">
                                            <?php if (strpos($thumbnail, '//') === false) { ?>
                                                <img src="<?php echo $this->getBaseUrl('pub/resource/image/' . $thumbnail) ?>" class="bttrlazyloading" data-bttrlazyloading-lg-src="<?php echo $this->getBaseUrl('pub/resource/image/resized/50px/' . $thumbnail) ?>" data-bttrlazyloading-md-src="<?php echo $this->getBaseUrl('pub/resource/image/resized/108x/' . $thumbnail) ?>" data-bttrlazyloading-sm-src="<?php echo $this->getBaseUrl('pub/resource/image/resized/125x/' . $thumbnail) ?>" data-bttrlazyloading-xs-src="<?php echo $this->getBaseUrl('pub/resource/image/resized/256x/' . $thumbnail) ?>" alt="<?php echo $item['product_name']; ?>" />
                                            <?php } else { ?>
                                                <img src="<?php echo $thumbnail ?>" alt="<?php echo $item['product_name']; ?>" />
                                            <?php } ?>
                                        </a>
                                    </div>
                                    <div class="product-title">
                                        <p>
                                            <a href="<?php echo $this->getProduct($item['product_id'])->getUrl(); ?>" title="<?php echo $item['product_name']; ?>">
                                                <span><?php echo $item['product_name'] ?></span>
                                            </a>
                                        </p>
                                    </div>
                                </td>
                                <td style="width: 8%;">
                                    <div>
                                        <p class="text-center">
                                            <span><?php echo $this->getCurrency()->format($item['price']); ?></span>
                                        </p>
                                    </div>
                                </td>
                                <td style="width: 8%;">
                                    <div>
                                        <p class="text-center"><?php echo $this->translate('%d', [$item['qty']]); ?></p>
                                    </div>
                                </td>
                                <?php
                                if ($key == 0) {
                                    ?>
                                    <td class="border-right" rowspan="<?php echo count($transaction['items']); ?>" style="width: 11%;">
                                        <div>
                                            <p class="text-center word-break-all">
                                                <a href=""><?php echo $customer = $this->getCustomerByID($transaction['customer_id'])->username; ?></a><i title="查询该买家订单"></i>
                                            </p>
                                            <p class="text-center">
                                                <a title="查询该买家订单" href=""></a>
                                            </p>
                                        </div>
                                    </td>
                                    <?php
                                }
                                if ($key == 0) {
                                    ?>
                                    <td class="border-right" rowspan="<?php echo count($transaction['items']); ?>" style="width: 11%;">

                                        <div>
                                            <p class="text-center">
                                                <span ><?php echo $this->translate($transaction['status_name']); ?></span>
                                            </p>
                                            <p class="text-center">
                                                <a href="<?php echo $this->getBaseUrl('retailer/transaction/orderview?id=' . $transaction['id']) ?>"><?php echo $this->translate('Detail'); ?></a>
                                            </p>
                                        </div>
                                    </td>
                                    <?php
                                }
                                if ($key == 0) {
                                    ?>
                                    <td class="border-right" rowspan="<?php echo count($transaction['items']); ?>" style="width: 11%;">
                                        <div>
                                            <p class="text-center">
                                                <strong><span class=" color-blue"><?php echo $transaction->getCurrency()->format($transaction->offsetGet('total')); ?></span></strong>
                                            </p>
                                            <p class="text-center">
                                                <span class="font-12">(<?php echo $this->translate('Including Courier Charges'); ?>:<?php echo $this->getCurrency()->format($transaction['shipping']); ?>)</span>
                                            </p>
                                        </div>
                                    </td>
                                    <?php
                                }
                                if ($key == 0) {
                                    $order_obj = $this->getOrder($transaction['id']);
                                    ?>
                                    <td style="width: 8%;" rowspan="<?php echo count($transaction['items']); ?>"  class="text-center font-12">
                                        <?php if ($order_obj->canCancel()) { ?>
                                            <a href="<?php echo $this->getBaseUrl('retailer/sales_order/cancel/?id=' . $order_obj->getId()) ?>" onclick="if (!confirm('<?php echo $this->translate('Are you sure to cancel this order?') ?>'))
                                                                            return false;" class="btn btn-cancel font-12">
                                               <?php echo $this->translate('Cancel', [], 'sales') ?>
                                            </a><br />
                                        <?php } ?>
                                        <?php if ($order_obj->canHold()) { ?>
                                            <a href="<?php echo $this->getBaseUrl('retailer/sales_order/hold/?id=' . $order_obj->getId()) ?>"  class="btn font-12">
                                                <?php echo $this->translate('Hold', [], 'sales') ?>
                                            </a><br />
                                        <?php } ?>

                                        <?php if ($order_obj->canUnhold()) { ?>
                                            <a href="<?php echo $this->getBaseUrl('retailer/sales_order/unhold/?id=' . $order_obj->getId()) ?>"  class="btn font-12">
                                                <?php echo $this->translate('Unhold', [], 'sales') ?>
                                            </a><br />
                                        <?php } ?>

                                        <?php if ($order_obj->canInvoice()) { ?>
                                            <a href="<?php echo $this->getBaseUrl('retailer/sales_order/invoice/?id=' . $order_obj->getId()) ?>"  class="btn">
                                                <?php echo $this->translate('Invoice', [], 'sales') ?>
                                            </a><br />
                                        <?php } ?>

                                        <?php if ($order_obj->canShip()) { ?>
                                            <a href="<?php echo $this->getBaseUrl('retailer/sales_order/ship/?id=' . $order_obj->getId()) ?>"  class="btn">
                                                <?php echo $this->translate('Ship', [], 'sales') ?>
                                            </a><br />
                                        <?php } ?>

                                        <?php if ($order_obj->canRefund()) { ?>
                                            <a href="<?php echo $this->getBaseUrl('retailer/sales_order/refund/?id=' . $order_obj->getId()) ?>"  class="btn">
                                                <?php echo $this->translate('Refund', [], 'sales') ?>
                                            </a><br />
                                        <?php } ?>
                                        <a href="<?php echo $this->getBaseUrl('retailer/sales_order/print/?id=' . $order_obj->getId()) ?>"  class="btn">
                                            <?php echo $this->translate('Print', [], 'sales') ?>
                                        </a><br />

                                    </td>
                                <?php } ?>
                            </tr>
                            <?php
                        }
                        ?>
                    </table>
                    <?php
                }
                ?>
            </div>
            <?php
        }
        ?>

        <div style="display: none;">
            <div>
                <div>
                    <label>
                        <input type="checkbox" data-cbtype="all">
                        <span>全选</span>
                    </label>
                    <button class="btn-options">批量发货</button>
                    <button class="btn-options">批量标记</button>
                    <button class="btn-options">批量免运费</button>
                </div>
            </div>
        </div>
        <div class="page-block">
            <div>
                <?php
                if (is_object($transactions)) {
                    echo $this->getChild('pager')->setCollection($transactions);
                }
                ?>
            </div>
        </div>
    </div>

    <div id="modal-receive" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="receiveModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="receiveModalLabel">收到货款</h4>
                </div>
                <div class="modal-body">
                    <div >
                        <h1>您确定已经收到买家的货款了吗？</h1>
                        <p>订单号&nbsp;&nbsp;&nbsp;&nbsp;:<span>88888888888</span></p>
                        <dl>
                            <dt>操作原因:</dt>
                            <dd><textarea name="remark"></textarea></dd>
                        </dl>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                    <button type="button" class="btn btn-primary">确认</button>
                </div>
            </div>
        </div>
    </div>

    <div id="modal-price" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="priceModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="priceModalLabel">费用调整</h4>
                </div>
                <div class="modal-body">
                    <div>买家:&nbsp;&nbsp;Stone<br>订单号&nbsp;&nbsp;:<strong>88888888888</strong></div>
                    <div>
                        <ul>
                            <li>
                                <h3>商品总价:<strong>¥100.00</strong></h3>
                                <p><input type="text" value="100.00" name="products_amount"></p>
                            </li>
                            <li>
                                <h3>配送费用:<strong>¥10.00</strong></h3>
                                <p><input type="text" value="10.00" name="shipping_fee"></p>
                            </li>
                        </ul>
                    </div>
                    <div><h3>订单总价:<strong>¥110.00</strong></h3></div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                    <button type="button" class="btn btn-primary">确认</button>
                </div>
            </div>
        </div>
    </div>

    <div id="modal-cancel" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="cancelModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="cancelModalLabel">费用调整</h4>
                </div>
                <div class="modal-body">
                    <h1>您是否确定要取消以下订单？</h1>
                    <p>订单号&nbsp;&nbsp;&nbsp;&nbsp;:<span>88888888888</span></p>
                    <dl>
                        <dt>取消原因:</dt>
                        <dd>
                            <div class="li">
                                <input type="radio" value="无法备齐货物" id="d1" name="cancel_reason" checked=""> <label for="d1">无法备齐货物</label>
                            </div>
                            <div class="li">
                                <input type="radio" value="不是有效的订单" id="d2" name="cancel_reason"> <label for="d2">不是有效的订单</label>
                            </div>
                            <div class="li">
                                <input type="radio" value="买家主动要求" id="d3" name="cancel_reason"> <label for="d3">买家主动要求</label>
                            </div>
                            <div class="li">
                                <input type="radio" value="其他原因" id="d4" flag="other_reason" name="cancel_reason"> <label for="d4">其他原因</label>
                            </div>
                        </dd>
                        <dd id="other_reason">
                            <textarea name="remark" id="other_reason_input"></textarea>
                        </dd>
                    </dl>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary">确认</button>
                </div>
            </div>
        </div>
    </div>
</div>
