<?php
$elements = $this->getVariable('elements');
?>

<main class="col-main col-xs-9 col-sm-9 col-md-10 mg-bottom-40">
    <div class="wishlist">
        <div class="product-edit">
            <h3 class="page-title"><?php echo $this->translate('Select Attribute Set') ?></h3>
            <form action="<?php echo $this->getSaveUrl() ?>" method="get">
                <div class="page-content table tab-pane fade active in" id="main-tab">
                    <?php
                    foreach ($elements as $key => $item) {
                        echo $this->getInputBox($key, $item);
                    }
                    ?>
                </div>
                <div class="buttons-set">
                    <button type="submit" class="btn btn-submit"><span><?php echo $this->translate('Next', [], 'eav') ?></span></button>
                </div>
            </form>
        </div>
    </div>
</main>
