<?php
$subtitle = $this->getVariable("subtitle");
$sales_products = $this->getRetailerSalesProducts();
$filter = $this->getVariable('filter');
?>
<div class="wishlist sales-products">
    <h3><?php echo $this->translate($subtitle); ?></h3>
    <div class="filter-bar" >
        <form id="filter_form" class="form-inline" action="<?php echo $this->getCurrentUrl() ?>" method="get" novalidate = "novalidate">
            <div class="sell">
                <ul class="commodity">
                    <li ><span><?php echo $this->translate('Product Name'); ?>:</span> <input class="form-control " type="text" value="<?php echo isset($filter['name']) ? $filter['name'] : ''; ?>" name="name"></li>
                    <li ><span><?php echo $this->translate('Commodity Code'); ?>:</span> <input class="form-control " type="text" value="<?php echo isset($filter['sku']) ? $filter['sku'] : ''; ?>" name="sku"></li>
                    <li ><span><?php echo $this->translate('Price'); ?>:</span> <input class="form-control small-text " type="text" value="<?php echo isset($filter['price_from']) ? $filter['price_from'] : ''; ?>" name="price_from"> - <input class="form-control small-text nomargin" type="text" value="<?php echo isset($filter['price_to']) ? $filter['price_to'] : ''; ?>" name="price_to"> </li>
                    <li ><span><?php echo $this->translate('Product Category'); ?>:</span> 
                        <select class="form-control " id="catalog" name="catalog" value="">
                            <option value=""><?php echo $this->translate('All'); ?></option>
                            <?php echo $this->renderCategory(0, 0, $filter['catalog']); ?>
                        </select>
                    </li>
                    <li ><span><?php echo $this->translate('Commodity Classification'); ?>:</span> 
                        <select class="form-control " id="category" name="category" value="<?php echo $filter['category']; ?>">
                            <option value=""><?php echo $this->translate('All'); ?></option>
                        </select>
                    </li>
                    <li ><span><?php echo $this->translate('Gallery Featured'); ?>:</span> 
                        <select class="form-control " id="recomend_status" name="recomend_status">
                            <option value=""><?php echo $this->translate('All'); ?></option>
                            <option value="1" <?php echo (isset($filter['recommend_status']) && $filter['recommend_status'] == 1) ? 'selected' : ''; ?>><?php echo $this->translate('Yes'); ?></option>
                            <option value="0" <?php echo (isset($filter['recommend_status']) && $filter['recommend_status'] == 0) ? 'selected' : ''; ?>><?php echo $this->translate('No'); ?></option>
                        </select>
                    </li>
                    <div class="commodity_btn">
                        <a class="btn" href="<?php echo $this->getBaseUrl('retailer/product/sales/'); ?>"><?php echo $this->translate('Reset'); ?></a> 
                        &nbsp;&nbsp; <button class="btn"><?php echo $this->translate('Search'); ?></button>
                    </div>
                </ul>
            </div>
        </form>
    </div>
    <div style="clear:both"></div>

    <div class="seperation-title">共有<span style="color:#FF0000"><?php echo count($sales_products) ?></span> 条记录</div>
    <hr class="seperation">
    <div class="products-content">
        <table class="table table-title">
            <tr>
                <td style="width: 45%;"><?php echo $this->translate('Product Name'); ?></td>
                <td style="width: 14%;"><?php echo $this->translate('Price'); ?></td>
                <td style="width: 11%;"><span><a href=><?php echo $this->translate('Inventory'); ?></a></span></td>
                <td style="width: 15%;"><span><a href=><?php echo $this->translate('Release Time'); ?></a></span></td>
                <td style="width: 15%;"><?php echo $this->translate('operating'); ?></td>
            </tr>
            <tr style="border-bottom: 1px solid #EDEDED;" >
                <td colspan="6" style="text-align: left;" >
                    <input type="checkbox" class="selectall" data-cbtype="all">
                    <span><?php echo $this->translate('All'); ?></span>
                    &nbsp;&nbsp;
                    <button class="btn-options enhancement product_status" data-type=0><?php echo $this->translate('Undercarriage'); ?></button><span class="function-seperation">|</span>
                    <button class="btn-options enhancement product_recommend" data-type=1><?php echo $this->translate('Gallery Featured'); ?></button>
                    <button class="btn-options enhancement product_recommend" data-type=0><?php echo $this->translate('Cancel Recommendation'); ?></button>
                </td>
            </tr>
        </table>
        <div class="clearfix mg-bottom-10"></div>
        <?php
        foreach ($sales_products as $sales_product) {
            ?>
            <div class="transaction-list-sales" data-id="<?php echo $sales_product['id']; ?>">
                <table class="list-info">
                    <?php
                    $thumbnail = $this->getProduct($sales_product['id'])->getThumbnail();
                    ?>
                    <tr>
                        <td style="width: 45%;">
                            <div class="recommend">
                                <input type="checkbox" data-id="<?php echo $sales_product['id']; ?>">
                                <span><?php echo isset($sales_product['recommend']) ? ($sales_product['recommend'] == 1 ? '已推荐' : '') : ''; ?></span>
                            </div>

                            <div class="product-pic">
                                <a href="<?php echo $sales_product->getUrl(); ?>" title="<?php echo $sales_product['name']; ?>">
                                    <?php if (strpos($thumbnail, '//') === false) { ?>
                                        <img src="<?php echo $this->getBaseUrl('pub/resource/image/' . $thumbnail) ?>" class="bttrlazyloading" data-bttrlazyloading-lg-src="<?php echo $this->getBaseUrl('pub/resource/image/resized/50x/' . $thumbnail) ?>" data-bttrlazyloading-md-src="<?php echo $this->getBaseUrl('pub/resource/image/resized/108x/' . $thumbnail) ?>" data-bttrlazyloading-sm-src="<?php echo $this->getBaseUrl('pub/resource/image/resized/125x/' . $thumbnail) ?>" data-bttrlazyloading-xs-src="<?php echo $this->getBaseUrl('pub/resource/image/resized/256x/' . $thumbnail) ?>" alt="<?php echo $sales_product['name']; ?>" />
                                    <?php } else { ?>
                                        <img src="<?php echo $thumbnail ?>" alt="<?php echo $sales_product['name']; ?>" />
                                    <?php } ?>
                                </a>
                            </div>
                            <div class="product-title">
                                <p>
                                    <a href="<?php echo $sales_product->getUrl(); ?>" title="<?php echo $sales_product['name'] ?>">
                                        <span><?php echo $sales_product['name'] ?></span>
                                    </a>
                                </p>
                            </div>
                        </td>
                        <td style="width: 14%;">
                            <div>
                                <p class="text-center">
                                    <span class="money"><?php echo $this->getCurrency()->format($sales_product['price']); ?></span>
                                </p>
                            </div>
                        </td>
                        <td style="width: 11%;">
                            <div>
                                <p class="text-center"><?php echo $this->translate('%d', [$this->getInventory($sales_product['id'], $sales_product['sku'])]); ?></p>
                            </div>
                        </td>
                        <td class="border-right text-center" style="width: 15%;"><?php echo empty($sales_product['created_at']) ? '&nbsp;' : $sales_product['created_at']; ?></td>
                        <td class="border-right" style="width: 15%;">
                            <div>
                                <p class="text-center">
                                    <span class="control-right" ><a href="<?php echo $this->getBaseUrl('retailer/product/release?id=' . $sales_product['id']) ?>" class="control-right" ><?php echo $this->translate('Edit Commodity'); ?></a></span>
                                </p>
                            </div>
                        </td>
                    </tr>
                </table>
            </div>
            <?php
        }
        ?>
        <div>
            <table class="table table-title">
                <tr style="background-color:#F1F2F4;">
                    <td  style="text-align: left;" >
                        <input type="checkbox" class="selectall" data-cbtype="all">
                        <span><?php echo $this->translate('All'); ?></span>
                        &nbsp;&nbsp;
                        <button class="btn-options enhancement product_status" data-type=0><?php echo $this->translate('Undercarriage'); ?></button> <span class="function-seperation">|</span>
                        <button class="btn-options enhancement product_recommend" data-type=1><?php echo $this->translate('Gallery Featured'); ?></button>
                        <button class="btn-options enhancement product_recommend" data-type=0><?php echo $this->translate('Cancel Recommendation'); ?></button>
                    </td>
                </tr>
            </table>
        </div>
        <div class="page-block">
            <div>
                <?php
                if (is_object($sales_products)) {
                    echo $this->getChild('pager')->setCollection($sales_products);
                }
                ?>
            </div>
        </div>
    </div>

    <div id="modal-receive" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="receiveModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="receiveModalLabel">收到货款</h4>
                </div>
                <div class="modal-body">
                    <div >
                        <h1>您确定已经收到买家的货款了吗？</h1>
                        <p>订单号&nbsp;&nbsp;&nbsp;&nbsp;:<span>88888888888</span></p>
                        <dl>
                            <dt><?php echo $this->translate('Product Name'); ?>操作原因:</dt>
                            <dd><textarea name="remark"></textarea></dd>
                        </dl>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo $this->translate('Product Name'); ?>取消</button>
                    <button type="button" class="btn btn-primary"><?php echo $this->translate('Product Name'); ?>确认</button>
                </div>
            </div>
        </div>
    </div>

    <div id="modal-price" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="priceModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="priceModalLabel">费用调整</h4>
                </div>
                <div class="modal-body">
                    <div>买家:&nbsp;&nbsp;Stone<br>订单号&nbsp;&nbsp;:<strong>88888888888</strong></div>
                    <div>
                        <ul>
                            <li>
                                <h3>商品总价:<strong>¥100.00</strong></h3>
                                <p><input type="text" value="100.00" name="products_amount"></p>
                            </li>
                            <li>
                                <h3>配送费用:<strong>¥10.00</strong></h3>
                                <p><input type="text" value="10.00" name="shipping_fee"></p>
                            </li>
                        </ul>
                    </div>
                    <div><h3>订单总价:<strong>¥110.00</strong></h3></div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                    <button type="button" class="btn btn-primary">确认</button>
                </div>
            </div>
        </div>
    </div>

    <div id="modal-cancel" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="cancelModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="cancelModalLabel">费用调整</h4>
                </div>
                <div class="modal-body">
                    <h1>您是否确定要取消以下订单？</h1>
                    <p>订单号&nbsp;&nbsp;&nbsp;&nbsp;:<span>88888888888</span></p>
                    <dl>
                        <dt>取消原因:</dt>
                        <dd>
                            <div class="li">
                                <input type="radio" value="无法备齐货物" id="d1" name="cancel_reason" checked=""> <label for="d1">无法备齐货物</label>
                            </div>
                            <div class="li">
                                <input type="radio" value="不是有效的订单" id="d2" name="cancel_reason"> <label for="d2">不是有效的订单</label>
                            </div>
                            <div class="li">
                                <input type="radio" value="买家主动要求" id="d3" name="cancel_reason"> <label for="d3">买家主动要求</label>
                            </div>
                            <div class="li">
                                <input type="radio" value="其他原因" id="d4" flag="other_reason" name="cancel_reason"> <label for="d4">其他原因</label>
                            </div>
                        </dd>
                        <dd id="other_reason">
                            <textarea name="remark" id="other_reason_input"></textarea>
                        </dd>
                    </dl>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary"><?php echo $this->translate('Product Name'); ?>确认</button>
                </div>
            </div>
        </div>
    </div>
</div>
