<?php 
$templateView = $this->getTemplateView(); 
$menuView = $this->template_menu();
$logo_topView = $this->template_logo_top(!empty($templateView['stable_params']['logo_top']) ? $templateView['stable_params']['logo_top'] : '' );
$logo_top_outerHeight = !empty($templateView['stable_params']['logo_top']['heightSet']) ? $templateView['stable_params']['logo_top']['heightSet'] + 4 : 200;
$productsDataView = $this->getSearchProducts();
?>

<div class="decoration_logo_top stable_top" style="height:<?php echo $logo_top_outerHeight;  ?>px;background-image:url(<?php echo $logo_topView;  ?>" >

</div>
<header class="header clearfix">
<nav class="nav-main  store_menu">
<ul class="nav nav-pills container">
	<li class="dropdown"><a class="dropdown-toggle" href="javascript:void(0);">全部商品分类</a><ul class="dropdown-menu">
            <li>
            <a href="http://project.zm.com/clothes.html">服装城</a>
                    </li>
            <li>
            <a href="http://project.zm.com/digital.html">数码城</a>
                    </li>
            <li>
            <a href="http://project.zm.com/food.html">美食城</a>
                    </li>
            <li>
            <a href="http://project.zm.com/market.html">蓝海超市</a>
                    </li>
            <li>
            <a href="http://project.zm.com/group-buying.html">团购</a>
                    </li>
    </ul>
</li>
	<?php echo $menuView; ?>
</ul>
</nav>
</header>
<div class="container">
    <div class="retailer-store">    
	<div class="col-md-12" style="padding: 11px;">
                    <div class="search content function-tag" data-tag="long_search" data-name="本店搜索" data-param="" data-id="b119-ef64-8901-a6b4">
                       <form>	<label class="search-label">本店搜索 &nbsp;| &nbsp;&nbsp; </label>
                                        关键字: <input class="keyword" type="text" name="name" value="">&nbsp;&nbsp;
                价格: <input class="price-from" type="text" name="price_from" value="">
                &nbsp;-&nbsp;
                <input class="price-to" type="text" name="price_to" value="">
                <button class="search-button">搜索</button>
                </form>
                </div>
                                <div class="hot-product">
                                    <div class="title">
                                        <h2>
                                            搜索商品 : 
                                        </h2>
                                    </div>
                                    <div class="content function-tag" ><ul>
          					<?php echo $productsDataView; ?>
                        
                        </ul></div>
                                </div>
                            </div>

	</div>
</div>

<script>
 $(function(){
 	$('.header .nav-main').hide();
 	$('.header .nav-main.store_menu').show();
 });
</script>


