

<?php $templateView = $this->getTemplateView(); ?>
<div class="container">
    <div class="retailer-store">    
      <div class="row clearfix">
      <div class="col-md-12">
            <div class="banner">
                <img src="<?php echo $this->getBaseUrl('/pub/theme/default/frontend/images/home_banner.jpg')?>" style='width:1139px' />
            </div>
        </div>
        </div>
        <?php echo !empty($templateView) ? $templateView['src_model'] : ''; ?>
	</div>
</div>


