<div class="container">
    <div class="retailer-store">
        <div class="col-md-12">
            <div class="banner">
                <img src="<?php echo $this->getBaseUrl('/pub/theme/default/frontend/images/home_banner.jpg')?>"  />
            </div>
        </div>
        
        <div class="col-md-12">
            <div class="hot-product">
                <div class="title"><h2>热卖产品</h2></div>
                <div class="content">
                    <ul>
                        <li class="col-md-3">
                            <div>
                                <a href=""><img class="pic" src="<?php echo $this->getBaseUrl('/pub/theme/default/frontend/images/sample.jpg')?>"  /></a>
                                <p class="price"><span class="actural">￥119.00 </span><span class="discount">￥119.00</span></p>
                                <h3 class="product-name"><a href="">雄鹰能量棒Eagle Energy吸入式咖啡因能量棒提神醒脑的口袋咖啡</a></h3>
                                <p class="paid-count">1999人付款</p>
                            </div>
                        </li>
                        <li class="col-md-3">
                            <div>
                                <a href=""><img class="pic" src="<?php echo $this->getBaseUrl('/pub/theme/default/frontend/images/sample.jpg')?>"  /></a>
                                <p class="price"><span class="actural">￥119.00 </span><span class="discount">￥119.00</span></p>
                                <h3 class="product-name"><a href="">雄鹰能量棒Eagle Energy吸入式咖啡因能量棒提神醒脑的口袋咖啡</a></h3>
                                <p class="paid-count">1999人付款</p>
                            </div>
                        </li>
                        <li class="col-md-3">
                            <div>
                                <a href=""><img class="pic" src="<?php echo $this->getBaseUrl('/pub/theme/default/frontend/images/sample.jpg')?>"  /></a>
                                <p class="price"><span class="actural">￥119.00 </span><span class="discount">￥119.00</span></p>
                                <h3 class="product-name"><a href="">雄鹰能量棒Eagle Energy吸入式咖啡因能量棒提神醒脑的口袋咖啡</a></h3>
                                <p class="paid-count">1999人付款</p>
                            </div>
                        </li>
                        <li class="col-md-3">
                            <div>
                                <a href=""><img class="pic" src="<?php echo $this->getBaseUrl('/pub/theme/default/frontend/images/sample.jpg')?>"  /></a>
                                <p class="price"><span class="actural">￥119.00 </span><span class="discount">￥119.00</span></p>
                                <h3 class="product-name"><a href="">雄鹰能量棒Eagle Energy吸入式咖啡因能量棒提神醒脑的口袋咖啡</a></h3>
                                <p class="paid-count">1999人付款</p>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        
        <div class="col-md-12">
            <div class="search">
                <label class="search-label">本店搜索</label>
                <input class="keyword" type="text" name="keyword" value="" />&nbsp;&nbsp;
                <input class="price-from" type="text" name="price-from" value="" />
                &nbsp;-&nbsp;
                <input class="price-to" type="text" name="price-to" value="" />
                <button class="search-button">搜索</button>
            </div>
        </div>
        
        <div class="col-md-12">
            <div class="retailer-prompt">
                <div class="title"><h2>店长推荐</h2><span class="more">更多&gt;</span></div>
                <div class="content">
                <div class="col-md-4">
                    <div class="col-md-6">
                        <div class="prompt-small"><img class="pic" src="<?php echo $this->getBaseUrl('/pub/theme/default/frontend/images/sample.jpg')?>"  /></div>
                    </div>
                    <div class="col-md-6">
                        <div class="prompt-small"><img class="pic" src="<?php echo $this->getBaseUrl('/pub/theme/default/frontend/images/sample.jpg')?>"  /></div>
                    </div>
                    <div class="col-md-6">
                        <div class="prompt-small"><img class="pic" src="<?php echo $this->getBaseUrl('/pub/theme/default/frontend/images/sample.jpg')?>"  /></div>
                    </div>
                    <div class="col-md-6">
                        <div class="prompt-small"><img class="pic" src="<?php echo $this->getBaseUrl('/pub/theme/default/frontend/images/sample.jpg')?>"  /></div>
                    </div>
                </div>
                <div class="col-md-4">
                            <div class="prompt-big">
                                <a href=""><img class="pic" src="<?php echo $this->getBaseUrl('/pub/theme/default/frontend/images/sample.jpg')?>"  /></a>
                                <p class="price"><span class="actural">￥119.00 </span><span class="discount">￥119.00</span></p>
                                <h3 class="product-name"><a href="">雄鹰能量棒Eagle Energy吸入式咖啡因能量棒提神醒脑的口袋咖啡</a></h3>
                                <p class="paid-count">1999人付款</p>
                            </div>
                </div>
                <div class="col-md-4">
                    <div class="col-md-6">
                        <div class="prompt-small"><img class="pic" src="<?php echo $this->getBaseUrl('/pub/theme/default/frontend/images/sample.jpg')?>"  /></div>
                    </div>
                    <div class="col-md-6">
                        <div class="prompt-small"><img class="pic" src="<?php echo $this->getBaseUrl('/pub/theme/default/frontend/images/sample.jpg')?>"  /></div>
                    </div>
                    <div class="col-md-6">
                        <div class="prompt-small"><img class="pic" src="<?php echo $this->getBaseUrl('/pub/theme/default/frontend/images/sample.jpg')?>"  /></div>
                    </div>
                    <div class="col-md-6">
                        <div class="prompt-small"><img class="pic" src="<?php echo $this->getBaseUrl('/pub/theme/default/frontend/images/sample.jpg')?>"  /></div>
                    </div>
                </div>
            </div>
            </div>
        </div>
        
        <div class="col-md-3">
            <div class="local-search">
                <div class="title"><h2>本店搜索</h2></div>
                <div class="search-table">
                    <table>
                        <tr>
                            <td class="label">关键字:</td>
                            <td><input class="keyword" type="text" name="key" value="" /></td>
                        </tr>
                        <tr>
                            <td class="label">价格:</td>
                            <td><input class="price-from" type="text" name="pri-from" value="" />&nbsp;&nbsp;<input class="price-to" type="text" name="pri-to" value="" />
                </td>
                        </tr>
                        <tr>
                            <td class="label">&nbsp;</td>
                            <td><button class="search-button">搜索</button></td>
                        </tr>
                        <tr>
                            <td class="label">热门</td>
                            <td><a href="">雄鹰能量棒</a>&nbsp;<a href="">吸入式咖啡</a></td>
                        </tr>
                    </table>
                </div>
            </div>

            <div class="category">
                <div class="title"><h2>商品分类</h2></div>
                <div class="content">
                    <ul class="category_list">
                        <li><a href="">查看所有分类&gt;&gt;</a></li>
                        <li><a href="">按销量</a>&nbsp;<a href="">按价格</a>&nbsp;<a href="">按评价</a>&nbsp;<a href="">按新品</a></li>
                        <li class="dropdown">
                            <span>薄荷糖口香糖补充剂等</span>
                            <ul>
                                <li></li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <span>益智开脑洞</span>
                        </li>
                        <li class="dropdown">
                            <span>睡眠放松</span>
                        </li>
                        <li class="dropdown">
                            <span>改善心情</span>
                        </li>
                        <li class="dropdown">
                            <span>能量补充</span>
                        </li>
                    </ul>
                </div>
            </div>
            
            <div class="statics">
                <div class="title"><h2>销售量</h2></div>
                <div class="content">
                    <ul>
                        <li>
                            <div class="col-md-4">
                                <a href=""><img class="pic" src="<?php echo $this->getBaseUrl('/pub/theme/default/frontend/images/sample.jpg')?>"  /></a>
                                </div>
                                <div class="col-md-8">
                                    <div class="pad-5">
                                        <h3 class="product-name"><a href="">雄鹰能量棒Eagle Energy吸入式咖啡因能量棒提神醒脑的口袋咖啡</a></h3>
                                        <p class="price"><span class="actural">￥119.00 </span></p>
                                        <p class="paid-count">热销<span class="sales-num">900</span>笔</p>
                                    </div>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        
        <div class="col-md-9">
            <div class="products">
                <div class="title"><h2>商品推荐</h2></div>
                <div class="content">
                    <ul>
                        <li class="col-md-3">
                            <div>
                                <a href=""><img class="pic" src="<?php echo $this->getBaseUrl('/pub/theme/default/frontend/images/sample.jpg')?>"  /></a>
                                <p class="price"><span class="actural">￥119.00 </span><span class="paid-count">1999人付款</span></p>
                                <h3 class="product-name"><a href="">雄鹰能量棒Eagle Energy吸入式咖啡因能量棒提神醒脑的口袋咖啡</a></h3>
                            </div>
                        </li>
                        <li class="col-md-3">
                            <div>
                                <a href=""><img class="pic" src="<?php echo $this->getBaseUrl('/pub/theme/default/frontend/images/sample.jpg')?>"  /></a>
                                <p class="price"><span class="actural">￥119.00 </span><span class="paid-count">1999人付款</span></p>
                                <h3 class="product-name"><a href="">雄鹰能量棒Eagle Energy吸入式咖啡因能量棒提神醒脑的口袋咖啡</a></h3>
                            </div>
                        </li>
                        <li class="col-md-3">
                            <div>
                                <a href=""><img class="pic" src="<?php echo $this->getBaseUrl('/pub/theme/default/frontend/images/sample.jpg')?>"  /></a>
                                <p class="price"><span class="actural">￥119.00 </span><span class="paid-count">1999人付款</span></p>
                                <h3 class="product-name"><a href="">雄鹰能量棒Eagle Energy吸入式咖啡因能量棒提神醒脑的口袋咖啡</a></h3>
                            </div>
                        </li>
                        <li class="col-md-3">
                            <div>
                                <a href=""><img class="pic" src="<?php echo $this->getBaseUrl('/pub/theme/default/frontend/images/sample.jpg')?>"  /></a>
                                <p class="price"><span class="actural">￥119.00 </span><span class="paid-count">1999人付款</span></p>
                                <h3 class="product-name"><a href="">雄鹰能量棒Eagle Energy吸入式咖啡因能量棒提神醒脑的口袋咖啡</a></h3>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        
    </div>
</div>
