---
livechat:
    label: Live Chat Configuration
    children:
        enable:
            label: Enable
            required: required
            type: select
            priority: 0
            default: 1
            scope: merchant
            options:
                - No
                - Yes
        port:
            label: Port
            type: tel
            priority: 10
            scope: merchant
        online_start:
            label: Online Start Time
            required: required
            type: time
            priority: 20
            default: 00:00
            scope: merchant
        online_end:
            label: Online End Time
            required: required
            type: time
            priority: 21
            default: 23:59
            scope: merchant
