<?php
$collection = $this->getStatement();
?>
<div class="statement">
    <table class="table table-hover">
        <thead>
            <tr>
                <th class="text-center"><?php echo $this->translate('Points') ?></th>
                <th class="text-center"><?php echo $this->translate('Comment') ?></th>
                <th class="text-center"><?php echo $this->translate('Status') ?></th>
                <th class="text-center"><?php echo $this->translate('Date') ?></th>
            </tr>
        </thead>
        <?php if (count($collection)): ?>
            <tbody>
                <?php foreach ($collection as $point): ?>
                    <tr class="text-center">
                        <td><?php echo (int) $point['count'] ?></td>
                        <td><?php echo $this->translate($point['comment']) ?></td>
                        <td><?php echo $this->translate($point['status'] ? 'Available' : 'Unavailable') ?></td>
                        <td><?php echo $point['created_at'] ?></td>
                    </tr>
                <?php endforeach ?>
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="4" class="text-right">
                        <?php echo $this->getChild('pager')->setCollection($collection); ?>
                    </td>
                </tr>
            </tfoot>
        <?php else: ?>
            <tfoot>
                <tr>
                    <td colspan="4"><?php echo $this->translate('No data to display') ?></td>
                </tr>
            </tfoot>
        <?php endif; ?>
    </table>
</div>
