<?php if ($this->canReview()): ?>
    <div class="review-form">
        <form action="<?php echo $this->getBaseUrl('catalog/review/save') ?>" method="post" class="form-inline">
            <input type="hidden" name="csrf" value="<?php echo $this->getCsrfKey() ?>" />
            <input type="hidden" name="product_id" value="<?php echo $this->getVariable('id') ?>" />
            <div class="input-box">
                <label for="review-content" class="control-label"><?php echo $this->translate('Content') ?></label>
                <textarea rows="4" name="content" id="review-content" class="form-control required" style="width:90%"></textarea>
            </div>
            <button class="btn" type="submit"><?php echo $this->translate('Submit') ?></button>
        </form>
    </div>
<?php endif; ?>