<div class="col-xs-9 col-sm-9 col-md-12 wishlist mg-bottom-40">
    <h3><?php echo $this->translate('Product Category') ?></h3>
    <div class="shop_classify">
   
       <input type="checkbox" class="check"> <label>全选</label>
          <button data-toggle="" data-target="" class="batch">批量发货</button>
  
        <button data-toggle="modal" data-target="#modal-newcat" class="add_classify"><span class="fa fa-plus"></span>新增分类</button>
    </div>

   <div>
    <table class="table  category_table text-center">

	 <thead> 
	    <tr class="table_head ">
		      <th  class="text-center">分类名称</th> 
		      <th  class="text-center">创建时间</th> 
			  <th  class="text-center col-md-1">移动</th> 
			  <th  class="text-center col-md-2">操作</th>
			  <th></th>
		     
		    </tr>
  		</thead> 
  		<tbody>
  			<tr>
  				<td class="text-left class_icon">
  					<input type="checkbox" class="check ">
  					<a href="#" onclick="i_btn($(this))"><i class="fa fa-caret-down text-center"></i></a>
  					
  					<div class="class_menu">
  						<dl>
		  				<dt class="dl_border dt_border">家庭收纳用具</dt>
		  				<div  class="dd_content">
							<div  class="border_lf"></div>
		  					<div class="border_bt"></div>
		  					<dd class="dl_border dd_left">家庭收纳用具</dd>
		  				</div>
		  				<div  class="dd_content">
							<div  class="border_lf"></div>
		  					<div class="border_bt"></div>
		  					<dd class="dl_border dd_left">家庭收纳用具</dd>
		  				</div>
		  				

		  				<div  class="dd_content">
							<div  class="border_lf"></div>
		  					<div class="border_bt"></div>
		  					<dd class="dl_border dd_left">家庭收纳用具</dd>
		  				</div>

  						</dl>
  					</div>
  					
  					
  					
  				</td>
  				<td>2016-10-19 &nbsp;&nbsp;17:18:35</td>
  				<td class="icon_up"><i class="fa fa-long-arrow-up " aria-hidden="true"></i><i class="fa fa-long-arrow-down" aria-hidden="true"></i></td>
  				<td><span><a href="" data-toggle="modal" data-target="#modal-newcat">修改</a></span>丨<span><a href="">删除</a></span></td>
  				<td> <button data-toggle="modal" data-target="#modal-newcat" class="add_classify"><span class="fa fa-plus"></span>新增子分类</button></td>
  			</tr>
  			
  		
  		</tbody>
  
	</table>

    </div>
    
    
    
    
    
    
    
    
    <div id="modal-newcat" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="newcatModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="newcatModalLabel">新增分类</h4>
                </div>
                <div class="modal-body">
                    <ul>
                        <li>
                            <h3>分类名称:</h3>
                            <p><input type="text" value="" name="cate_name"><label></label></p>
                        </li>
                        <li>
                            <h3>上级分类:</h3>
                            <p>
                                <select name="parent_id">
                                <option>请选择...</option>
                                <option selected="" value="1">我的分类1</option>
                                <option value="2">我的分类2</option>
                                <option value="3">我的分类3</option>
                                </select>
                            </p>
                        </li>
                        <li>
                            <h3>排序:</h3>
                            <p><input type="text" value="255" name="sort_order"></p>
                        </li>
                    </ul>
                    <div><input type="submit" value="提交" class="btn"></div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                    <button type="button" class="btn btn-primary">确认</button>
                </div>
            </div>
        </div>
    </div>
    
</div>
<script>
	function i_btn(env){
 		env.next('.class_menu').find('.dd_content').toggle();
		var btn_i = env.find('i');
		if(btn_i.is('.fa-caret-down')){
			btn_i.removeClass();
			btn_i.addClass('fa fa-caret-up text-center btn_i');
		}else{
			btn_i.removeClass();
			btn_i.addClass('fa fa-caret-down text-center btn_i');
		}
	}
</script>
