<div class="col-xs-9 col-sm-9 col-md-10 wishlist mg-bottom-40">
    <h3><?php echo $this->translate('Goods Category') ?></h3>
    <div>
        <button data-toggle="modal" data-target="#modal-newcat">新增分类</button>
    </div>
    <div>
        <table class="table table-bordered">
            <tr>
                <th>
                    <input type="checkbox" class="checkall" id="all">
                </th>
                <th colspan="4"><label for="all"> <span>全选</span> </label>
                    <a href="javascript:void(0);">删除</a>
                </th>
            </tr>
            <tr >
                <th></th>
                <th>分类名称</th>
                <th>排序</th>
                <th>操作</th>
            </tr>
            <tr >
                <td>
                    <input type="checkbox" value="">
                </td>
                <td>
                    <span>我的分类1</span>
                </td>
                <td><span >255</span></td>
                <td>
                    <a href="javascript:void(0);" data-toggle="modal" data-target="#modal-newcat">新增下级</a>
                    <a href="javascript:void(0);" data-toggle="modal" data-target="#modal-newcat">编辑</a>
                    <a href="javascript:void(0);">删除</a>
                </td>
            </tr>
            <tr >
                <td>
                    <input type="checkbox" value="">
                </td>
                <td>
                    <span>我的分类2</span>
                </td>
                <td><span >255</span></td>
                <td>
                    <a href="javascript:void(0);" data-toggle="modal" data-target="#modal-newcat">新增下级</a>
                    <a href="javascript:void(0);" data-toggle="modal" data-target="#modal-newcat">编辑</a>
                    <a href="javascript:void(0);">删除</a>
                </td>
            </tr>
            <tr>
                <th>
                    <input type="checkbox" class="checkall" id="all2">
                </th>
                <th colspan="4">
                    <p class="position1">
                        <label for="all2"><span class="all">全选</span></label>
                        <a href="javascript:void(0);">删除</a></p>
                </th>
            </tr>
        </table>
    </div>
    
    <div id="modal-newcat" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="newcatModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="newcatModalLabel">新增分类</h4>
                </div>
                <div class="modal-body">
                    <ul>
                        <li>
                            <h3>分类名称:</h3>
                            <p><input type="text" value="" name="cate_name"><label></label></p>
                        </li>
                        <li>
                            <h3>上级分类:</h3>
                            <p>
                                <select name="parent_id">
                                <option>请选择...</option>
                                <option selected="" value="1">我的分类1</option>
                                <option value="2">我的分类2</option>
                                <option value="3">我的分类3</option>
                                </select>
                            </p>
                        </li>
                        <li>
                            <h3>排序:</h3>
                            <p><input type="text" value="255" name="sort_order"></p>
                        </li>
                    </ul>
                    <div><input type="submit" value="提交" class="btn"></div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                    <button type="button" class="btn btn-primary">确认</button>
                </div>
            </div>
        </div>
    </div>
    
</div>
