
<div class="col-xs-12 col-sm-12 col-md-12 wishlist mg-bottom-40 activity_body">
    <h4><?php echo $this->translate('Freight Setting'); ?></h4>
    <div class="border-widht"></div>
    <div class="activity">
	<ul id="activity" class="nav nav-tabs col-xs-12 col-sm-12">
		<li class="active">
			<a href="#Freeshipping" data-toggle="tab">免运费</a>
		</li>
		<li>
			<a href="#Fixedfreight" data-toggle="tab">固定运费</a>
		</li>
	</ul>
	<div id="myTabContent" class="tab-content">
		<div class="tab-pane fade in active" id="Freeshipping">
			<div>
      			<form method="get">
	           		<div class="activity_search col-xs-12 col-sm-12">
	           			<div class="padding-0-5 col-md-8 col-xs-12 col-sm-6">
		           			<lable class="col-xs-3 col-sm-2 col-md-2"><span class="color-red">*</span>免运费启用:</lable>
		               		<select class="col-md-6" id="" name="" value="">
                            <option value="">禁用</option>
                             <option value="">启用</option>
                            </select>
	           			</div>
	           			<div class="padding-0-5 col-md-8 col-xs-12 col-sm-6">
		           			<lable class="col-xs-3 col-sm-2 col-md-2"><span class="color-red">*</span>运费标签:</lable>
		               		<input type="text" value="" name="order_sn" class=" col-md-6 col-xs-6 col-sm-6" >
	           			</div>
	           			<div class="padding-0-5 col-md-8 col-xs-12 col-sm-6">
		           			<lable class="col-xs-3 col-sm-2 col-md-2" >最小订单金额:</lable>
		               		<input type="text" value="" name="order_sn" class=" col-md-6 col-xs-6 col-sm-6" >
	           			</div>
	           			<div class="padding-0-5 col-md-8 col-xs-12 col-sm-6">
		           			<lable class="col-xs-3 col-sm-2 col-md-2">最大订单金额:</lable>
		               		<input type="text" value="" name="order_sn" class="col-md-6 col-xs-6 col-sm-6" >
	           			</div>
	           			<div class="col-md-6 col-xs-12 col-sm-12 text-center">
	           			<div class="button_ctn">
	           				<button type="submit" class="btn">确认</button>
	           				<button type="button" class="btn-2">取消</button>
	           			</div>
	           				
	           				
	           			</div>
	            	</div>
       			 </form>
  		  	</div>
		</div>
		<div class="tab-pane fade" id="Fixedfreight">
			<div>
      			<form method="get">
	           		<div class="activity_search col-xs-12 col-sm-12">
	           			<div class="padding-0-5 col-md-8 col-xs-12 col-sm-6">
		           			<lable class="col-xs-3 col-sm-2 col-md-2"><span class="color-red">*</span>固定运费启用:</lable>
		               		<select class="col-md-6" id="" name="" value="">
                            <option value="">禁用</option>
                             <option value="">启用</option>
                            </select>
	           			</div>
	           			<div class="padding-0-5 col-md-8 col-xs-12 col-sm-6">
		           			<lable class="col-xs-3 col-sm-2 col-md-2"><span class="color-red">*</span>运费标签:</lable>
		               		<input type="text" value="" name="order_sn" class=" col-md-6 col-xs-6 col-sm-6" >
	           			</div>
	           			<div class="padding-0-5 col-md-8 col-xs-12 col-sm-6">
		           			<lable class="col-xs-3 col-sm-2 col-md-2" >最小订单金额:</lable>
		               		<input type="text" value="" name="order_sn" class=" col-md-6 col-xs-6 col-sm-6" >
	           			</div>
	           			<div class="padding-0-5 col-md-8 col-xs-12 col-sm-6">
		           			<lable class="col-xs-3 col-sm-2 col-md-2">最大订单金额:</lable>
		               		<input type="text" value="" name="order_sn" class="col-md-6 col-xs-6 col-sm-6" >
	           			</div>
	           			<div class="col-md-6 col-xs-12 col-sm-12 text-center">
	           			<div class="button_ctn">
	           				<button type="submit" class="btn">确认</button>
	           				<button type="button" class="btn-2">取消</button>
	           			</div>
	           				
	           				
	           			</div>
	            	</div>
       			 </form>
  		  	</div>
		
		</div>
		
	</div>
</div>
    
    
    
    
 </div>
