<div class="col-xs-12 col-sm-12 col-md-12">
    <div class="filters">
        <form action="" method="get" class="form-inline">
            <div class="input-box">
                <label for="category_id" class="control-label"><?php echo $this->translate('Category'); ?></label>
                <div class="cell">
                    <select name="category_id" id="category_id" class="form-control ">
                        <option value=""><?php echo $this->translate('(NULL)'); ?></option>
                        <option value="1">心机小物</option>
                        <option value="2">杯子</option>
                    </select>
                </div>
            </div>
            <div class="input-box">
                <label for="file_type" class="control-label"><?php echo $this->translate('File Type'); ?></label>
                <div class="cell">
                    <select name="file_type" id="file_type" class="form-control ">
                        <option value=""><?php echo $this->translate('Please Select'); ?></option>
                        <option value="image/gif">image/gif</option>
                        <option value="image/jpeg">image/jpeg</option>
                        <option value="image/png">image/png</option>
                    </select>
                </div>
            </div>
            <div class="input-box">
                <label for="uploaded_name" class="control-label"><?php echo $this->translate('Uploaded Name'); ?></label>
                <div class="cell">
                    <input type="text" name="uploaded_name" id="uploaded_name" class="form-control " value="">
                </div>
            </div>

            <div class="input-box">
                <label class="control-label" for="sortby:limit"><?php echo $this->translate('Item(s) per page'); ?></label>
                <div class="cell">
                    <input type="tel" name="limit" id="sortby:limit" class="form-control" value="20">
                </div>
            </div>
            <div class="buttons-set">
                <button type="submit" class="btn"><?php echo $this->translate('Search'); ?></button>
                <button type="reset" class="btn"><?php echo $this->translate('Reset'); ?></button>
            </div>
        </form>
    </div>
    <div class="col-lg-12 col-md-12">
        <div class="col-lg-2 col-md-2 content-left">
            <h3><?php echo $this->translate('Resource Management'); ?></h3>
            <dl>
                <dt><span class="fa fa-folder" aria-hidden="true"></span><?php echo $this->translate('My Photo'); ?></dt>
                <dd><span class="fa fa-folder" aria-hidden="true"></span><?php echo $this->translate('Photo1'); ?></dd>
                <dd><span class="fa fa-folder" aria-hidden="true"></span><?php echo $this->translate('Photo2'); ?></dd>
                <dd><span class="fa fa-folder" aria-hidden="true"></span><?php echo $this->translate('Photo3'); ?></dd>
                <dt><span class="fa fa-folder" aria-hidden="true"></span><?php echo $this->translate('My Photo1'); ?></dt>
                <dd><span class="fa fa-folder" aria-hidden="true"></span><?php echo $this->translate('Photo1'); ?></dd>
                <dd><span class="fa fa-folder" aria-hidden="true"></span><?php echo $this->translate('Photo2'); ?></dd>
                <dd><span class="fa fa-folder" aria-hidden="true"></span><?php echo $this->translate('Photo3'); ?></dd>            
            </dl>
        </div>
        <div class="col-lg-10 col-md-10 content-right">
            <div class="row height-50">
                <h4 class="col-lg-6 col-md-6 line-height-30 margin-left"><span class="fa fa-picture-o" aria-hidden="true"></span><?php echo $this->translate('Photo Space'); ?></h4>
                <p class="col-lg-6 col-md-6 line-height-30 text-right">
                    <button data-toggle="modal" data-target="#modal-upload"><span class="fa fa-cloud-upload" aria-hidden="true"></span><?php echo $this->translate('Upload'); ?></button>
                    <button data-toggle="modal" data-target="#modal-newfolder"><?php echo $this->translate('New Files'); ?></button>
                    <input type="text" placeholder="按文件夹名称/图片名称搜索" />
                    <button><?php echo $this->translate('Search'); ?></button>
                </p>
            </div>
            <div class="row background">
                <ul class="col-lg-9 col-md-9 line-height-40">
                    <li>
                        <a href=""><label for="select_all"></label><input type="checkbox" name="select_all"><?php echo $this->translate('Select All') ?></a>
                    </li>
                    <li>
                        <a href=""><span class="fa fa-pencil" aria-hidden="true"></span><?php echo $this->translate('Rename') ?></a>
                    </li>
                    <li><a href=""><span class="fa fa-times" aria-hidden="true"></span><?php echo $this->translate('Delete') ?></a></li>
                </ul>
                <ul class="col-lg-3 col-md-3">
                    <li class="sort-by" style="width: 50%"><a href=""><?php
                            echo $this->translate('Sort') . ':&nbsp;';
                            echo $this->translate('Time') . '&nbsp;'
                            ?><span class="fa fa-caret-down" aria-hidden="true"></span></a></li>
                    <li class="sort-by text-center" style="width: 40%">
                        <a href="" class="border-right"><span class="fa fa-th-large" aria-hidden="true"></span></a>
                        <a href=""><span class="fa fa-th-list" aria-hidden="true"></span></a>
                    </li>
                </ul>
            </div>
            <div class="row file-panel">
                <ul class="col-lg-12 col-md-12">
                    <li class="col-lg-3 col-md-3"><a href=""><span class="fa fa-folder-open" aria-hidden="true"></span><br /><?php echo $this->translate('Photo1'); ?></a></li>
                    <li class="col-lg-3 col-md-3"><a href=""><span class="fa fa-folder-open" aria-hidden="true"></span><br /><?php echo $this->translate('Photo2'); ?></a></li>
                    <li class="col-lg-3 col-md-3"><a href=""><span class="fa fa-folder-open" aria-hidden="true"></span><br /><?php echo $this->translate('Photo3'); ?></a></li>
                    <li class="col-lg-3 col-md-3"><a href=""><span class="fa fa-folder-open" aria-hidden="true"></span><br /><?php echo $this->translate('Photo4'); ?></a></li>
                </ul>

            </div>
        </div>
    </div>
    <div id="modal-upload" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="uploadModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="uploadModalLabel"><?php echo $this->translate('Resource Management'); ?></h4>
                </div>
                <div class="modal-body">
                    <ul class="nav nav-tabs clearfix" role="tablist">
                        <li role="presentation" class="active">
                            <a href="#select-resource" aria-controls="select-resource" role="tab" data-toggle="tab">
                                <?php echo $this->translate('Select Resource'); ?>
                            </a>
                        </li>
                        <li role="presentation">
                            <a href="#upload-resource" aria-controls="upload-resource" role="tab" data-toggle="tab">
                                <?php echo $this->translate('Upload Resource'); ?>                        
                            </a>
                        </li>
                        <li class="col-lg-8 col-md-8 text-right" style="float:right">
                            <a href="#"><?php echo $this->translate('Search'); ?></a><input type="text" name="search">
                        </li>
                    </ul>
                    <div class="col-lg-12 col-md-12 tab-content">
                        <div class="tab-pane active" role="tabpanel" id="select-resource">
                            <div class="content-left" style="width:177px;float:left">
                                <h3><?php echo $this->translate('Resource Management'); ?></h3>
                                <dl>
                                    <dt><span class="fa fa-folder" aria-hidden="true"></span><?php echo $this->translate('My Photo'); ?></dt>
                                    <dd><span class="fa fa-folder" aria-hidden="true"></span><?php echo $this->translate('Photo1'); ?></dd>
                                    <dd><span class="fa fa-folder" aria-hidden="true"></span><?php echo $this->translate('Photo2'); ?></dd>
                                    <dd><span class="fa fa-folder" aria-hidden="true"></span><?php echo $this->translate('Photo3'); ?></dd>
                                    <dt><span class="fa fa-folder" aria-hidden="true"></span><?php echo $this->translate('My Photo1'); ?></dt>
                                    <dd><span class="fa fa-folder" aria-hidden="true"></span><?php echo $this->translate('Photo1'); ?></dd>
                                    <dd><span class="fa fa-folder" aria-hidden="true"></span><?php echo $this->translate('Photo2'); ?></dd>
                                    <dd><span class="fa fa-folder" aria-hidden="true"></span><?php echo $this->translate('Photo3'); ?></dd>   
                                </dl>
                            </div>
                            <div class="content-right" style="width:788px;float:left">
                                <ul class="col-lg-12 col-md-12 heading">
                                    <li class="col-lg-2 col-md-2"><?php echo $this->translate('Images'); ?></li>
                                    <li class="col-lg-7 col-md-7"><?php echo $this->translate('File Name'); ?></li>
                                    <li class="col-lg-1 col-md-1"><?php echo $this->translate('Size'); ?></li>
                                    <li class="col-lg-1 col-md-1"><?php echo $this->translate('Status'); ?></li>
                                    <li class="col-lg-1 col-md-1"><?php echo $this->translate('Delete'); ?></li>
                                </ul>  
                            </div>                          
                        </div>
                        <div class="tab-pane" role="tabpanel" id="upload-resource">
                            <div class="content-left" style="width:177px;float:left">
                                <h3><?php echo $this->translate('Resource Management'); ?></h3>
                                <dl>
                                    <dt><span class="fa fa-folder" aria-hidden="true"></span><?php echo $this->translate('My Photo'); ?></dt>
                                    <dd><span class="fa fa-folder" aria-hidden="true"></span><?php echo $this->translate('Photo1'); ?></dd>
                                    <dd><span class="fa fa-folder" aria-hidden="true"></span><?php echo $this->translate('Photo2'); ?></dd>
                                    <dd><span class="fa fa-folder" aria-hidden="true"></span><?php echo $this->translate('Photo3'); ?></dd>
                                    <dt><span class="fa fa-folder" aria-hidden="true"></span><?php echo $this->translate('My Photo1'); ?></dt>
                                    <dd><span class="fa fa-folder" aria-hidden="true"></span><?php echo $this->translate('Photo1'); ?></dd>
                                    <dd><span class="fa fa-folder" aria-hidden="true"></span><?php echo $this->translate('Photo2'); ?></dd>
                                    <dd><span class="fa fa-folder" aria-hidden="true"></span><?php echo $this->translate('Photo3'); ?></dd>
                                </dl>
                            </div>
                            <div class="content-right" style="width:788px;float:left">
                                <ul class="col-lg-12 col-md-12 heading">
                                    <li class="col-lg-2 col-md-2"><?php echo $this->translate('Images'); ?></li>
                                    <li class="col-lg-7 col-md-7"><?php echo $this->translate('File Name'); ?></li>
                                    <li class="col-lg-1 col-md-1"><?php echo $this->translate('Size'); ?></li>
                                    <li class="col-lg-1 col-md-1"><?php echo $this->translate('Status'); ?></li>
                                    <li class="col-lg-1 col-md-1"><?php echo $this->translate('Delete'); ?></li>
                                </ul>  
                            </div>
                            <div class="cue clearfix">
                                <p><input type="checkbox" name=" watermark" />&nbsp;<label for=" watermark"><?php echo $this->translate('Add Watermark');?></label></p>
                                <p>小提示:</p>
                                <ul>
                                    <li>1. 图片单张大小支持2M以下, 超过无法上传</li>
                                    <li>2. 自动压缩和宽度调整可能会使图片失真</li>
                                    <li>3. 支持的图片格式: jpg、jpeg、png、gif</li>
                                </ul>
                            </div>
                            <div class="modal-footer">
                                <ul class="col-lg-4 col-md-4">
                                    <li><label><?php echo $this->translate('Add Categorey'); ?></label></li>
                                    <li><input type="text"></li>
                                    <li><a href=""><?php echo $this->translate('New'); ?></a></li>
                                </ul>
                                <ul class="col-lg-4 col-md-4">
                                    <li>
                                        <label><?php echo $this->translate('Select Resource'); ?></label>
                                    </li>
                                    <li>
                                        <select name="resource">
                                            <option><?php echo $this->translate('Select File'); ?></option>
                                        </select>
                                    </li>
                                </ul>
                                <div class="col-lg-4 col-md-4">
                                    <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                                    <button type="button" class="btn btn-primary"><?php echo $this->translate('Upload'); ?></button>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>

    <div id="modal-newfolder" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="newfolderModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="newfolderModalLabel">新建文件夹</h4>
                </div>
                <div class="modal-body">
                    <div>
                        文件夹名称: <input type="text" placeholder="新建文件夹" />
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                    <button type="button" class="btn btn-primary">确认</button>
                </div>
            </div>
        </div>
    </div>

    <div id="modal-move" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="moveModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="moveModalLabel">移动到</h4>
                </div>
                <div class="modal-body">
                    <select>
                        <option value="0">图片空间</option>
                        <option value="1">装修</option>
                        <option value="2">商品图片</option>
                    </select>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                    <button type="button" class="btn btn-primary">确认</button>
                </div>
            </div>
        </div>
    </div>

</div>
