
<div class="col-xs-12 col-sm-12 col-md-12 mg-bottom-40">
    <div class="breadcrumb clearfix">
        <ol class="col-lg-6 col-md-6">
            <li><?php echo $this->translate('Current Position') ?>:</li>
            <li><?php echo $this->translate('Photo Space') ?></li>
        </ol>
        <div class="buttons-set col-lg-6 col-md-6 text-right">
            <button data-toggle="modal" data-target="#modal-upload"><?php echo $this->translate('Upload'); ?></button>

        </div>

    </div>
    <div class="filters">
        <from action="" method="get" class="form-inline" novalidate="novalidate">
            <div class="input-box">
                <?php echo $this->translate('Condition query'); ?>
            </div>
        </from>
    </div>
    <div class="col-lg-12 col-md-12">
        <div class="col-lg-3 col-md-3 content-left border-right">
            <h3><?php echo $this->translate('Resource Management'); ?></h3>
            <dl>
                <dt><span class="fa fa-folder" aria-hidden="true"></span><?php echo $this->translate('My Photo'); ?></dt>
                <dd><span class="fa fa-folder" aria-hidden="true"></span><?php echo $this->translate('Photo1'); ?></dd>
                <dd><span class="fa fa-folder" aria-hidden="true"></span><?php echo $this->translate('Photo2'); ?></dd>
                <dd><span class="fa fa-folder" aria-hidden="true"></span><?php echo $this->translate('Photo3'); ?></dd>
                <dt><span class="fa fa-folder" aria-hidden="true"></span><?php echo $this->translate('My Photo1'); ?></dt>
                <dd><span class="fa fa-folder" aria-hidden="true"></span><?php echo $this->translate('Photo1'); ?></dd>
                <dd><span class="fa fa-folder" aria-hidden="true"></span><?php echo $this->translate('Photo2'); ?></dd>
                <dd><span class="fa fa-folder" aria-hidden="true"></span><?php echo $this->translate('Photo3'); ?></dd>            
            </dl>
        </div>
        <div class="col-lg-9 col-md-9 content-right">
            <div class="row height-50">
                <h4 class="col-lg-6 col-md-6 line-height-30 margin-left"><span class="fa fa-picture-o" aria-hidden="true"></span><?php echo $this->translate('Photo Space'); ?></h4>
                <p class="col-lg-6 col-md-6 line-height-30">
                    <button data-toggle="modal" data-target="#modal-upload"><span class="fa fa-cloud-upload" aria-hidden="true"></span><?php echo $this->translate('Upload'); ?></button>
                    <button data-toggle="modal" data-target="#modal-newfolder">新建文件夹</button>
                    <input type="text" placeholder="按文件夹名称/图片名称搜索" />
                    <button>搜索</button>
                </p>
            </div>
            <div class="row background">
                <ul class="col-lg-9 col-md-9 line-height-40">
                    <li>
                        <a href=""><label for="select_all"></label><input type="checkbox" name="select_all"><?php echo $this->translate('Select All') ?></a>
                    </li>
                    <li>
                        <a href=""><span class="fa fa-pencil" aria-hidden="true"></span><?php echo $this->translate('Rename') ?></a>
                    </li>
                    <li><a href=""><span class="fa fa-exchange" aria-hidden="true"></span><?php echo $this->translate('Move') ?></a></li>
                    <li><a href=""><span class="fa fa-picture-o" aria-hidden="true"></span><?php echo $this->translate('Edit') ?></a></li>
                    <li><a href=""><span class="fa fa-arrows-alt" aria-hidden="true"></span><?php echo $this->translate('Adapter cell phone') ?></a></li>
                    <li><a href=""><span class="fa fa-times" aria-hidden="true"></span><?php echo $this->translate('Delete') ?></a></li>
                </ul>
                <ul class="col-lg-3 col-md-3">
                    <li class="sort-by"><a href=""><?php echo $this->translate('sort') . ':&nbsp;';
                    echo $this->translate('Time') . '&nbsp;' ?><span class="fa fa-caret-down" aria-hidden="true"></span></a></li>
                    <li class="sort-by">
                        <a href="" class="border-right"><span class="fa fa-th-large" aria-hidden="true"></span></a>
                        <a href=""><span class="fa fa-th-list" aria-hidden="true"></span></a>
                    </li>
                </ul>
            </div>
            <div class="row file-panel">
                <ul class="col-lg-12 col-md-12">
                    <li class="col-lg-3 col-md-3"><a href=""><span class="fa fa-folder-open" aria-hidden="true"></span><br /><?php echo $this->translate('Photo1');?></a></li>
                    <li class="col-lg-3 col-md-3"><a href=""><span class="fa fa-folder-open" aria-hidden="true"></span><br /><?php echo $this->translate('Photo2');?></a></li>
                    <li class="col-lg-3 col-md-3"><a href=""><span class="fa fa-folder-open" aria-hidden="true"></span><br /><?php echo $this->translate('Photo3');?></a></li>
                    <li class="col-lg-3 col-md-3"><a href=""><span class="fa fa-folder-open" aria-hidden="true"></span><br /><?php echo $this->translate('Photo4');?></a></li>
                </ul>

            </div>
        </div>
    </div>
    <div id="modal-upload" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="uploadModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="uploadModalLabel">上传图片</h4>
                </div>
                <div class="modal-body">
                    <div >
                        <p>修改位置</p>
                        <select>
                            <option value="0">图片空间</option>
                            <option value="1">装修</option>
                            <option value="2">商品图片</option>
                        </select>
                    </div>
                    <div >
                        <button>上传</button>
                    </div>
                    <div>
                        <p>小提示:</p>
                        <ul>
                            <li>1. 图片单张大小支持2M以下, 超过无法上传</li>
                            <li>2. 自动压缩和宽度调整可能会使图片失真</li>
                            <li>3. 支持的图片格式: jpg、jpeg、png、gif</li>
                        </ul>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                    <button type="button" class="btn btn-primary">确认</button>
                </div>
            </div>
        </div>
    </div>

    <div id="modal-newfolder" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="newfolderModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="newfolderModalLabel">新建文件夹</h4>
                </div>
                <div class="modal-body">
                    <div>
                        文件夹名称: <input type="text" placeholder="新建文件夹" />
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                    <button type="button" class="btn btn-primary">确认</button>
                </div>
            </div>
        </div>
    </div>

    <div id="modal-move" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="moveModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="moveModalLabel">移动到</h4>
                </div>
                <div class="modal-body">
                    <select>
                        <option value="0">图片空间</option>
                        <option value="1">装修</option>
                        <option value="2">商品图片</option>
                    </select>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                    <button type="button" class="btn btn-primary">确认</button>
                </div>
            </div>
        </div>
    </div>

</div>
