<?php
$retailer = $this->getRetailer();
?>
<form action="<?php echo $this->getBaseUrl('retailer/store/save/') ?>" method="post" class="form-inline" enctype="multipart/form-data">
    <input type="hidden" name="csrf" value="<?php echo $this->getCsrfKey() ?>" />
    <div class="fieldset">
        <div class="input-box">
            <label class="control-label required" for="profile"><?php echo $this->translate('Avatar') ?></label>
            <div class="cell">
                <label for="profile" class="avatar">
                    <img src="<?php if ($retailer->offsetGet('profile')): ?>data:image/png;base64, <?php
                        echo base64_encode($retailer->offsetGet('profile'));
                    else:
                        echo $this->getPubUrl('frontend/images/placeholder.png');
                    endif;
                    ?>" alt="" />
                    <span class="update"><?php echo $this->translate('Update Image') ?></span>
                </label>
                <input type="file" name="profile" hidden="hidden" id="profile" accept="image/*" class="form-control" />
            </div>
        </div>
        <div class="input-box">
            <label class="control-label required" for="store-name"><?php echo $this->translate('Store Name') ?></label>
            <div class="cell">
                <input type="text" name="store[name]" class="form-control required" id="store-name" value="<?php echo $this->getStore()->offsetGet('name') ?>" />
            </div>
        </div>
        <div class="input-box">
            <label class="control-label required" for="uri_key"><?php echo $this->translate('Uri Key') ?></label>
            <div class="cell">
                <input type="text" name="uri_key" class="form-control required" id="uri_key" value="<?php echo $retailer->offsetGet('uri_key') ?>" />
            </div>
        </div>
        <div class="input-box">
            <label class="control-label" for="address"><?php echo $this->translate('Address') ?></label>
            <div class="cell">
                <input type="text" name="address" id="address" class="form-control" value="<?php echo $retailer->offsetGet('address') ?>" />
            </div>
        </div>
        <div class="input-box">
            <label class="control-label" for="tel"><?php echo $this->translate('Phone Number') ?></label>
            <div class="cell">
                <input type="tel" name="tel" id="tel" class="form-control" value="<?php echo $retailer->offsetGet('tel') ?>" />
            </div>
        </div>
        <div class="input-box">
            <label class="control-label" for="tel"><?php echo $this->translate('Contact Infomation') ?></label>
            <div class="cell">
                <input type="tel" name="tel" id="tel" class="form-control" value="<?php echo $retailer->offsetGet('contact') ?>" />
            </div>
        </div>
        <div class="input-box">
            <label class="control-label" for="description"><?php echo $this->translate('Introduction') ?></label>
            <div class="cell">
                <textarea name="description" id="description" class="form-control"><?php echo $retailer->offsetGet('description') ?></textarea>
            </div>
        </div>
        <div class="input-box">
            <label class="control-label" for="keywords"><?php echo $this->translate('Keywords') ?>：</label>
            <div class="cell">
                <textarea name="keywords" id="keywords" class="form-control"><?php echo $retailer->offsetGet('keywords') ?></textarea>
            </div>
        </div>
        <div class="input-box">
            <label class="control-label" for="watermark"><?php echo $this->translate('Watermark') ?>：</label>
            <div class="cell">
                <label for="watermark" class="avatar">
                    <img src="<?php if ($retailer->offsetGet('watermark')): ?>data:image/png;base64, <?php
                        echo base64_encode($retailer->offsetGet('watermark'));
                    else:
                        echo $this->getPubUrl('frontend/images/placeholder.png');
                    endif;
                    ?>" alt="" />
                    <span class="update"><?php echo $this->translate('Update Image') ?></span>
                </label>
                <input type="file" name="watermark" hidden id="watermark" accept="image/*" class="" />
            </div>
        </div>
        <div class="buttons-set">
            <div class="cell">&nbsp;</div>
            <div class="cell">
                <button type="submit" class="btn btn-theme">
                    <span><?php echo $this->translate('Submit') ?></span>
                </button>
            </div>
        </div>
    </div>
</form>
