<form action="<?php echo $this->getBaseUrl('retailer/store/save/') ?>" method="post" class="form-inline" enctype="multipart/form-data">
    <input type="hidden" name="csrf" value="<?php echo $this->getCsrfKey() ?>" />
    <div class="fieldset">
        <div class="input-box">
            <label class="control-label required" for="store-name"><?php echo $this->translate('Store Name') ?></label>
            <div class="cell">
                <input type="text" name="store[name]" class="form-control required" id="store-name" value="<?php echo $this->getStore()->offsetGet('name') ?>" />
            </div>
        </div>
        <div class="input-box">
            <label class="control-label required" for="uri_key"><?php echo $this->translate('Uri Key') ?></label>
            <div class="cell">
                <input type="text" name="uri_key" id="uri_key" class="form-control required" value="<?php echo $this->getRetailer()->offsetGet('uri_key') ?>" />
            </div>
        </div>
        <div class="input-box">
            <label class="control-label" for="address"><?php echo $this->translate('Address') ?></label>
            <div class="cell">
                <input type="text" name="address" id="address" class="form-control" value="<?php echo $this->getRetailer()->offsetGet('address') ?>" />
            </div>
        </div>
        <div class="input-box">
            <label class="control-label" for="tel"><?php echo $this->translate('Phone Number') ?></label>
            <div class="cell">
                <input type="tel" name="tel" id="tel" class="form-control" value="<?php echo $this->getRetailer()->offsetGet('tel') ?>" />
            </div>
        </div>
        <div class="input-box">
            <label class="control-label" for="contact"><?php echo $this->translate('Contact Infomation') ?></label>
            <div class="cell">
                <textarea name="contact" id="contact" class="form-control"><?php echo $this->getRetailer()->offsetGet('contact') ?></textarea>
            </div>
        </div>
        <div class="input-box">
            <label class="control-label" for="description"><?php echo $this->translate('Description') ?></label>
            <div class="cell">
                <textarea name="description" id="description" class="form-control"><?php echo $this->getRetailer()->offsetGet('description') ?></textarea>
            </div>
        </div>
        <div class="input-box">
            <label class="control-label" for="keywords"><?php echo $this->translate('Keywords') ?></label>
            <div class="cell">
                <textarea name="keywords" id="keywords" class="form-control"><?php echo $this->getRetailer()->offsetGet('keywords') ?></textarea>
            </div>
        </div>
        <div class="input-box">
            <label class="control-label" for="profile"><?php echo $this->translate('Logo') ?></label>
            <div class="cell">
                <?php if ($profile = $this->getRetailer()->offsetGet('profile')): ?>
                    <img src="data:image/png;base64, <?php echo base64_encode($profile) ?>" width="100" alt="" />
                <?php endif ?>
                <input type="file" name="profile" id="profile" accept="image/*" class="form-control" />
            </div>
        </div>
        <div class="input-box">
            <label class="control-label" for="watermark"><?php echo $this->translate('Watermark') ?></label>
            <div class="cell">
                <?php if ($watermark = $this->getRetailer()->offsetGet('watermark')): ?>
                    <img src="data:image/png;base64, <?php echo base64_encode($watermark) ?>" width="100" alt="" />
                <?php endif ?>
                <input type="file" name="watermark" id="watermark" accept="image/*" class="form-control" />
            </div>
        </div>
        <div class="buttons-set">
            <div class="cell">&nbsp;</div>
            <div class="cell">
                <button type="submit" class="btn btn-theme">
                    <span><?php echo $this->translate('Submit') ?></span>
                </button>
            </div>
        </div>
    </div>
</form>
