<?php
$store_id = $this->getVariable("store_id");
$retailer = $this->getVariable("retailer");
$templateView = $this->getTemplateView($store_id);
$menuView = $this->template_menu(null, $store_id);
$logo_topView = $this->template_logo_top(!empty($templateView['stable_params']['logo_top']) ? $templateView['stable_params']['logo_top'] : '', $store_id, $retailer);
$logo_top_outerHeight = !empty($templateView['stable_params']['logo_top']['heightSet']) ? $templateView['stable_params']['logo_top']['heightSet'] + 4 : 200;
?>
<?php if (!empty($templateView)) { ?>
    <div class="decoration_logo_top stable_top" style="height:<?php echo $logo_top_outerHeight; ?>px;background-image:url(<?php echo $logo_topView; ?>)" >

    </div>
    <header class="header clearfix">
        <nav class="nav-main  store_menu">
            <ul class="nav nav-pills container">
                <li class="dropdown"><a class="dropdown-toggle" href="javascript:void(0);">全部商品分类</a><ul class="dropdown-menu">

                    </ul>
                </li>
                <?php echo $menuView; ?>
            </ul>
        </nav>
    </header>
    <div class="container">
        <div class="retailer-store">    

            <?php echo!empty($templateView) ? $templateView['src_model'] : ''; ?>
        </div>
    </div>
<?php } ?>
<script>
    $(function () {
        $('.header .nav-main').hide();
        $('.header .nav-main.store_menu').show();
    });
</script>


