<?php
$products = $this->getProducts();
?>
<div class="container">
    <?php if (count($products)): ?>
        <ul class="products-grid clearfix">
            <?php
            foreach ($products as $product):
                $thumbnail = $product->getThumbnail();
                ?>
            <li class="item col-xs-6 col-sm-4 col-md-3 col-lg-2 product-list">
                    <a href="<?php echo $product->getUrl($this->getCategory()) ?>" title="<?php echo $product['name'] ?>" class="product-image">
                        <?php if(strpos($thumbnail, 'http') === false): ?>
                        <img class="bttrlazyloading" data-bttrlazyloading-xs-src="<?php echo $this->getBaseUrl('pub/resource/image/resized/362x/' . $thumbnail) ?>" alt="<?php echo $product['name'] ?>" width="100%" />
                        <?php else: ?>
                        <img src="<?php echo $thumbnail ?>" alt="<?php echo $product['name'] ?>" />
                        <?php endif ?>
                    </a>                 
                    <h3 class="product-name">
                        <a href="<?php echo $product->getUrl($this->getCategory()) ?>" title="<?php echo $product['name'] ?>">
                            <?php echo $product['name'] ?>
                        </a>
                    </h3>
                    <div class="price-box">
                        <?php echo $this->getPriceBox($product) ?>
                    </div>
                </li>
            <?php endforeach ?>
        </ul>
    <?php else: ?>
        <p class="no-product"><?php echo $this->translate('There are no products matching the selection.') ?></p>
    <?php endif ?>
</div>