<?php
$customer = $this->getCustomer();
$order = $this->getLatestOrder();
$profile1 = new Seahinet\Customer\ViewModel\Dashboard\Profile;
$profile = $profile1->getPendingPayment();
$shipping = $profile1->getShipping();
$reviewing = $profile1->getReviewing();
$refund1 = new Seahinet\Sales\ViewModel\Refund;
$refund = $refund1->getApplication();
$refund->getSelect()->where->notEqualTo('status',5);
if ($order && $order->getId()):
    $flag = true;
    ?>
    <div class="panel order">
        <div class="panel-heading">
            <h3 class="panel-title"><span class="fa fa-calendar-check-o" aria-hidden="true"></span><?php echo $this->translate('Latest Order') ?>
                <a href="<?php echo $this->getBaseUrl('sales/order/list/') ?>" class="fa fa-chevron-right text-right" aria-hidden="true"></a>
            </h3>
        </div>
        <div class="panel-info">
            <ul>
                <li class="col-xs-3 col-sm-3 text-center">
                    <a href="<?php echo $this->getBaseUrl('sales/order/list/?status=1') ?>" class="fa fa-credit-card-alt fa-2x pad-5" aria-hidden="true"></a>
                    <span><?php echo $this->translate('Pending Payment') ?>(<?php echo $profile1->getPendingPayment() ?>)</span>
                <li class="col-xs-3 col-sm-3 text-center">
                    <a href="<?php echo $this->getBaseUrl('sales/order/list/?status=2') ?>" class="fa fa-truck fa-2x pad-5" aria-hidden="true"></a>
                    <span><?php echo $this->translate('To be received') ?>(<?php echo $profile1->getShipping() ?>)</span>
                </li>
                <li class="col-xs-3 col-sm-3 text-center">
                    <a href="<?php echo $this->getBaseUrl('sales/order/list/?status=3') ?>" class="fa fa-commenting-o fa-2x pad-5" aria-hidden="true"></a>
                    <span><?php echo $this->translate('Reviewing', [], 'customer') ?>(<?php echo $profile1->getReviewing() ?>)</span>
                </li>
                <li class="col-xs-3 col-sm-3 text-center">
                    <a href="<?php echo $this->getBaseUrl('sales/refund/?status=1') ?>" class="fa fa-jpy fa-2x pad-5" aria-hidden="true"></a>
                    <span><?php echo $this->translate('Refund rights') ?>(<?php echo count($refund); ?>)</span>
                </li>
            </ul>
        </div>
    </div>
        <?php /*
    <div class="panel assets">
        <div class="panel-heading">
            <h3 class="panel-title"><span class="fa fa-money" aria-hidden="true"></span><?php echo $this->translate('Asset Center') ?>

            </h3>
        </div>

        <div class="panel-info">
            <ul>
                <li class="col-xs-4 col-sm-4 text-center">
                    <a href="#" class=""><?php echo $this->getCurrency()->convert($customer->getBalance(), true) ?></a>
                    <span><?php echo $this->translate('The balance of') ?>(<?php echo $this->getCurrency()->convert($customer->getBalance(), true) ?>)</span>
                </li>
                <li class="col-xs-4 col-sm-4 text-center">
                    <a href="#" class="">16(条)</a>
                    <span><?php echo $this->translate('I discount information') ?>(0)</span>
                </li>
                <li class="col-xs-4 col-sm-4 text-center">
                    <a href="#" class="">400(分)</a>
                    <span><?php echo $this->translate('My Points') ?>(0)</span>
                </li>
            </ul>
        </div>
    </div>
        */ ?>
<?php endif; ?>
<div class="custom-info">
    <div class="panel-heading">
        <h3 class="panel-title"><span class="fa fa-cog" aria-hidden="true"></span><?php echo $this->translate('Account Infomation') ?><a href="<?php echo $this->getBaseUrl() ?>customer/account/edit/" class="fa fa-chevron-right text-right" aria-hidden="true"></a>
        </h3>
    </div>
    <div class="panel-heading">
        <h3 class="panel-title"><span class="fa fa-map-marker" aria-hidden="true"></span><?php echo $this->translate('Address Administration') ?><a href="<?php echo $this->getBaseUrl() ?>customer/account/address/" class="fa fa-chevron-right text-right" aria-hidden="true"></a>
        </h3>
    </div>
</div>
<div class="profile-foot">
    <ul class="col-xs-12 col-sm-12">
        <li class="col-xs-4 text-center">
            <a href="<?php echo $this->getBaseUrl() ?>"><?php echo $this->translate('Shopping'); ?></a>
        </li>
        <li class="col-xs-4 text-center">
            <a href="<?php echo $this->getBaseUrl('retailer/account/') ?>"><?php echo $this->translate('Enter the Store Center'); ?></a>
        </li>
        <li class="col-xs-4 text-center">
            <a href="<?php echo $this->getBaseUrl('customer/account/logout/') ?>"><?php echo $this->translate('Log out'); ?></a>
        </li>
    </ul>
</div>
