<?php
$customer = $this->getCustomer();
$order = $this->getOrder();
if ($order && $order->getId()):
    $flag = true;
    ?>
    <div class="panel order">
        <div class="panel-heading">
            <h3 class="panel-title"><span class="fa fa-check-circle" aria-hidden="true"></span><?php echo $this->translate('Latest Order') ?>
                <a href="<?php echo $this->getBaseUrl() ?>sales/order/list/" class="fa fa-chevron-right text-right" aria-hidden="true"></a>
            </h3>
        </div>
        <div class="panel-info">
            <ul>
                <li class="col-xs-3 col-sm-3 text-center">
                    <a href="#" class="fa fa-credit-card-alt fa-2x" aria-hidden="true"></a>
                    <span><?php echo $this->translate('Pending Payment') ?>(0)</span>
                </li>
                <li class="col-xs-3 col-sm-3 text-center">
                    <a href="#" class="fa fa-truck fa-2x" aria-hidden="true"></a>
                    <span><?php echo $this->translate('Shipping', [], 'customer') ?>(0)</span>
                </li>
                <li class="col-xs-3 col-sm-3 text-center">
                    <a href="#" class="fa fa-commenting-o fa-2x" aria-hidden="true"></a>
                    <span><?php echo $this->translate('Reviewing', [], 'customer') ?>(0)</span>
                </li>
                <li class="col-xs-3 col-sm-3 text-center">
                    <a href="<?php echo $this->getBaseUrl() ?>sales/refund/" class="fa fa-jpy fa-2x" aria-hidden="true"></a>
                    <span><?php echo $this->translate('Return &amp; Refund') ?>(0)</span>
                </li>
            </ul>
        </div>
    </div>
<?php endif; ?>
<div class="custom-info">
    <div class="panel-heading">
        <h3 class="panel-title"><span class="fa fa-cog" aria-hidden="true"></span><?php echo $this->translate('Account Infomation') ?><a href="<?php echo $this->getBaseUrl() ?>customer/account/edit/" class="fa fa-chevron-right text-right" aria-hidden="true"></a>
        </h3>
    </div>
    <div class="panel-heading">
        <h3 class="panel-title"><span class="fa fa-dot-circle-o" aria-hidden="true"></span><?php echo $this->translate('Address Administration') ?><a href="<?php echo $this->getBaseUrl() ?>customer/account/address/" class="fa fa-chevron-right text-right" aria-hidden="true"></a>
        </h3>
    </div>
</div>
<div class="profile-foot">
    <ul class="col-xs-12 col-sm-12">
        <li class="col-xs-4 col-sm-4 text-center">
            <a href="<?php echo $this->getBaseUrl() ?>clothes.html"><?php echo $this->translate('Shopping'); ?></a>
        </li>
        <li class="col-xs-4 col-sm-4 text-center">
            <a href="<?php echo $this->getBaseUrl() ?>retailer/account/processing/"><?php echo $this->translate('Enter the Store Center'); ?></a>
        </li>
        <li class="col-xs-4 col-sm-4 text-center">
            <a href="<?php echo $this->getBaseUrl() ?>customer/account/logout/"><?php echo $this->translate('Log out'); ?></a>
        </li>
    </ul>
</div>
