<?php
$customer = $this->getCustomer();
?>
<div class="profile clearfix">
    <div class="head_pic">
        <label for="avatar" class="avatar">
            <img src="<?php if ($customer->offsetGet('avatar')): ?>data:image/png;base64, <?php
                echo $customer->offsetGet('avatar');
            else:
                echo $this->getPubUrl('frontend/images/placeholder.png');
            endif;
            ?>" alt="" />
            <span class="update"><?php echo $this->translate('Update Image') ?></span>
        </label>
    </div>
    <div class="info col-xs-12 col-sm-10">
        <div class="name">
            <span><?php echo $customer->offsetGet('username') ?></span>
            <a class="level badge"><?php echo $customer->getLevel() ?></a>
            <div>
                <i class="fa  fa-star"></i>
                <i class="fa  fa-star-o"></i>
                <i class="fa   fa-star-o"></i>
                <i class="fa   fa-star-o"></i>
                <i class="fa   fa-star-o"></i>
                <div class="start">
                    <span class="start-v">V</span><span class="start-num">0</span>
                </div>
            </div>
            <span class=""></span>
        </div>
        <div class="wishlist_track">
            <ul class="col-xs-12 col-sm-12">
                <li class="col-xs-4 col-sm-4 text-center">
                    <a href="<?php echo $this->getBaseUrl('customer/wishlist/') ?>">0</a>
                    <span><?php echo $this->translate('Focus on shop'); ?></span>
                </li>
                <li class="col-xs-4 col-sm-4 text-center">
                    <a href="<?php echo $this->getBaseUrl('customer/wishlist/') ?>">0</a>
                    <span><?php echo $this->translate('My Wishlist'); ?></span>
                </li>
                <li class="col-xs-4 col-sm-4 text-center">
                    <a href="<?php echo $this->getBaseUrl('customer/history/') ?>">0</a>
                    <span><?php echo $this->translate('My Tracks'); ?></span>
                </li>
            </ul>
        </div>
    </div>
</div>
