<?php
$customer = $this->getCustomer();
$wishlist1 = new Seahinet\Customer\ViewModel\Wishlist;
$wishlist = $wishlist1->getItems();
$viewed1 = new Seahinet\Customer\ViewModel\ViewedProduct;
$viewed = $viewed1->getProducts();
$coupon1 = new Seahinet\Customer\ViewModel\Coupon;
$coupon = $coupon1->getCoupons();
?>
<div class="profile clearfix">
    <div class="head_pic">
        <label for="avatar" class="avatar">
            <img src="<?php if ($customer->offsetGet('avatar')): ?>data:image/png;base64, <?php
                echo $customer->offsetGet('avatar');
            else:
                echo $this->getPubUrl('frontend/images/placeholder.png');
            endif;
            ?>" alt="" width="100" height="100" />
        </label>
    </div>
    <div class="info col-xs-12 col-sm-10">
        <div class="name">
            <span><?php echo $customer->offsetGet('username') ?></span>
            <a class="level badge"><?php echo $customer->getLevel() ?></a>
        </div>
        <div class="wishlist_track">
            <ul class="col-xs-12 col-sm-12">
                <li class="col-xs-4 col-sm-4 text-center">
                    <a href="<?php echo $this->getBaseUrl('customer/coupon/') ?>"><?php echo count($coupon); ?></a>
                    <span><?php echo $this->translate('Coupon'); ?></span>
                </li>
                <li class="col-xs-4 col-sm-4 text-center">
                    <a href="<?php echo $this->getBaseUrl('customer/wishlist/') ?>"><?php echo count($wishlist); ?></a>
                    <span><?php echo $this->translate('My Wishlist'); ?></span>
                </li>
                <li class="col-xs-4 col-sm-4 text-center">
                    <a href="<?php echo $this->getBaseUrl('customer/history/') ?>"><?php echo count($viewed); ?></a>
                    <span><?php echo $this->translate('My Tracks'); ?></span>
                </li>
            </ul>
        </div>
    </div>
</div>
