<?php
$after = new \Seahinet\Sales\Model\Collection\Rma;
$after = $this->getAfterCollection();
?>
<div class="col-xs-12 col-sm-12 col-md-12 wishlist mg-bottom-40">
    <h5 class="title">
    	<div class="padding-0-5">
	    	 <?php echo $this->translate('After Service'); ?><span>(<?php echo count($after); ?>)</span>&nbsp;&nbsp; / &nbsp;&nbsp;
	        <span class="history_after_sale"><a href="#"><?php echo $this->translate('History after Sale Service'); ?></a></span>
    	</div>
   
    </h5>
 

  <div class="after-sales">
  			<ul  class="col-xs-12 col-sm-12 title-nav border-bottom padding-5">
	        		<li class="col-xs-3 col-sm-3 text-left  color-blue"><a href="" target="_blank">123456<span class="fa fa-qq padding-l-5"></span></a></li>
	        		<li class="col-xs-9 col-sm-9 text-right "> <span class="label">订单号：</span>
                                <span>1216102715572751</span>&nbsp;&nbsp;
<!--                                 <span class="list_time">2016-10-27</span></li>	 -->
	        			
	        			
	        </ul>
	        <ul class="col-xs-12 col-sm-12 inline">
	        <div class="order-details  padding-5">
	        <li class="col-xs-2 col-sm-2"><img src="http://ecomv2.seahinet.test1/pub/resource/image/resized/173x/TB1jLZiNFXXXXapXFXXXXXXXXXX_!!0-item_pic.jpg" style="display: inline;" width="50" height="50"></li>
	        		<li class="col-xs-6 col-sm-6"><span class="text-ovflow">女装 打褶中裙 173805 优衣库UNIQLO</span><p class="choose col-xs-12 col-sm-12 color-hui "><span class="col-xs-4 col-sm-4">颜色:棕色</span><span class="col-xs-4 col-sm-4">尺码:XL</span><span class="col-xs-4 col-sm-4"></span></p></li>
	        		<li class="col-xs-4 col-sm-4 text-right color-hui">
	        			<span class="col-xs-12 col-sm-12"><button class="after_bt">取消</button></span>
	        			<span class="col-xs-12 col-sm-12"><a href="">查看详情</a></span>
	        		</li>
	        </div>
	        		
	        		<li class="col-xs-12 col-sm-12 ">
	        		<div class="bt col-xs-12 col-sm-12 time-bt  padding-5 color-hui">
	        		<span class="time col-xs-9 col-sm-10 " >2016-10-27 15:57:51</span>
	        		<span class="col-xs-3 col-sm-2  text-right">买家提出申请</span>
	        		</div>
	        		
	        		</li>		
	       </ul>

  </div>          
            
            
            
    <div id="modal-refuse" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="refusedModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="refusedModalLabel">拒绝申请</h4>
                </div>
                <div class="modal-body">
                    <div>
                        <h1>您确定要拒绝买家的售后申请吗？</h1>
                        <p>订单号&nbsp;&nbsp;&nbsp;&nbsp;:<span>88888888889</span></p>
                        <dl>
                            <dt>拒绝原因:</dt>
                            <dd><textarea name="reason"></textarea></dd>
                        </dl>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                    <button type="button" class="btn btn-primary">确认</button>
                </div>
            </div>
        </div>
    </div>

    <div id="modal-agree" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="agreedModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="agreedModalLabel">同意售后</h4>
                </div>
                <div class="modal-body">
                    <div>买家:&nbsp;&nbsp;Stone<br>订单号&nbsp;&nbsp;:<strong>88888888889</strong></div>
                    <div>
                        <ul>
                            <li>
                                <h3>处理方式</h3>
                                <p>
                                    <select name="agree_method">
                                        <option value="退款">退款</option>
                                        <option value="退货">退货</option>
                                        <option value="补发">补发</option>
                                    </select>
                                </p>
                            </li>
                            <li>
                                <h3>同意原因</h3>
                                <p><textarea name="agree"></textarea></p>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                    <button type="button" class="btn btn-primary">确认</button>
                </div>
            </div>
        </div>
    </div>
</div>
