<div class="col-xs-9 col-sm-9 col-md-10 wishlist mg-bottom-40">
    <h3><?php echo $this->translate('After Service'); ?></h3>
    
    <div id="scarch_order">
        <form method="get">
            <div >
                <span>订单号:</span>
                <input type="text" value="" name="order_sn">
                <span>申请时间:</span>
                <input type="text" value="" id="apply_time_from" name="apply_time_from"> &ndash; <input type="text" value="" name="apply_time_to" id="apply_time_to">
                <span>买家:</span>
                <input type="text" value="" name="buyer_name">
                <input type="submit" value="搜索" class="btn">
            </div>
        </form>
    </div>
    <br /><br />
    
    <div>
        <table class="table table-bordered">
            <tr>
                <th>售后编号</th>
                <th>订单号</th>
                <th>买家</th>
                <th>售后原因</th>
                <th>状态</th>
                <th>申请时间</th>
            </tr>
            <tr>
                <td><span>44444444444</span></td>
                <td><span>88888888888</span></td>
                <td>Buyer</td>
                <td>未收到货</td>
                <td>处理完成</td>
                <td>2012-06-08 22:35</td>
            </tr>
            <tr>
                <td align="right" colspan="6">
                    <div>
                        <a target="_blank" href="<?php echo $this->getBaseUrl('retailer/transaction/afterview')?>">查看订单</a>
                    </div>
                </td>
            </tr>
            <tr>
                <td><span>44444444445</span></td>
                <td><span>88888888889</span></td>
                <td>Buyer</td>
                <td>未收到货</td>
                <td>售后申请</td>
                <td>2012-06-08 22:35</td>
            </tr>
            <tr>
                <td align="right" colspan="6">
                    <div>
                        <button data-toggle="modal" data-target="#modal-refuse">拒绝申请</button>
                        <button data-toggle="modal" data-target="#modal-agree">同意申请</button>
                        <a target="_blank" href="<?php echo $this->getBaseUrl('retailer/transaction/afterview')?>">查看订单</a>
                    </div>
                </td>
            </tr>
            <tr>
                <td colspan="6">
                    <div class="text-right">
                        <a>共 2 个项目</a>
                        <a href="#">上一页</a>
                        <a href="#">1</a>
                        <span>1 / 1</span>
                        <a href="#">下一页</a>
                    </div>
                </td>
            </tr>
        </table>
    </div>
    
    <div id="modal-refuse" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="refusedModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="refusedModalLabel">拒绝申请</h4>
                </div>
                <div class="modal-body">
                    <div >
                        <h1>您确定要拒绝买家的售后申请吗？</h1>
                        <p>订单号&nbsp;&nbsp;&nbsp;&nbsp;:<span>88888888889</span></p>
                        <dl>
                            <dt>拒绝原因:</dt>
                            <dd><textarea name="reason"></textarea></dd>
                        </dl>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                    <button type="button" class="btn btn-primary">确认</button>
                </div>
            </div>
        </div>
    </div>
    
    <div id="modal-agree" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="agreedModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="agreedModalLabel">同意售后</h4>
                </div>
                <div class="modal-body">
                    <div>买家:&nbsp;&nbsp;Stone<br>订单号&nbsp;&nbsp;:<strong>88888888889</strong></div>
                    <div>
                        <ul>
                            <li>
                                <h3>处理方式</h3>
                                <p>
                                    <select name="agree_method">
                                        <option value="退款">退款</option>
                                        <option value="退货">退货</option>
                                        <option value="补发">补发</option>
                                    </select>
                                </p>
                            </li>
                            <li>
                                <h3>同意原因</h3>
                                <p><textarea name="agree"></textarea></p>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                    <button type="button" class="btn btn-primary">确认</button>
                </div>
            </div>
        </div>
    </div>
    
</div>
