<div class="col-xs-12 col-sm-12 col-md-12 wishlist mg-bottom-40">
    <h4 class="title"><?php echo $this->translate('Review Management'); ?></h4>

    <div class="evaluate">
        <div class="down_icon"> <span class="span"><span>评价</span><i class="fa fa-caret-down text-center"></i></span><span class="span"><span>评语</span><i class="fa fa-caret-down text-center"></i></span></div>
        <div class="details comments">
            <table class="panel-body table">
                <tbody>
                <div class="border_left"></div>
                <tr>
                    <td class="title_img col-xs-3"><span class="title_img_mg"><img src="http://ecomv2.seahinet.test1/pub/resource/image/resized/45x/TB1fWOsLXXXXXXrXVXXXXXXXXXX_!!0-item_pic.jpg" alt="" data-label="" data-group="" width="45"></span><br><a href="" class="buyer">万物生dy</a></td>
                    <td class="title_txt col-xs-7"><a href="" class="Product_title">现货Eagle Energy雄鹰能量棒吸入式咖啡因缓解疲劳</a><p class="price" colspan="2">￥198.00</p></td>
                    <td class="text-right col-xs-2 reply"><button data-toggle="modal" data-target="#modal-reply">回复</button></td>
                </tr>
                <tr>
                    <td class="star"><i class="fa fa-star" aria-hidden="true"></i><i class="fa fa-star" aria-hidden="true"></i><i class="fa fa-star" aria-hidden="true"></i><i class="fa fa-star" aria-hidden="true"></i><i class="fa fa-star" aria-hidden="true"></i></td>
                    <td class=""><span class="">买家评价：</span><span>味道还可以</span></td>
                    <td class=""></td>
                </tr>
                <tr class="">
                    <td class="border_bt"></td>
                    <td class="border_bt"><span>[2016-09-19&nbsp;&nbsp;12:30:37]</span></td>
                    <td class="border_bt"></td>
                </tr>
                </tbody>
            </table>
        </div>
        <div class="border-width"></div>
        <div class="details comments">
            <table class="panel-body table">
                <tbody>
                <div class="border_left"></div>
                <tr>
                    <td class="title_img col-xs-3"><span class="title_img_mg"><img src="http://ecomv2.seahinet.test1/pub/resource/image/resized/45x/TB1fWOsLXXXXXXrXVXXXXXXXXXX_!!0-item_pic.jpg" alt="" data-label="" data-group="" width="45"></span><br><a href="" class="buyer">万物生dy</a></td>
                    <td class="title_txt col-xs-7"><a href="" class="Product_title">现货Eagle Energy雄鹰能量棒吸入式咖啡因缓解疲劳</a><p class="price" colspan="2">￥198.00</p></td>
                    <td class="text-right col-xs-2 reply"><button data-toggle="modal" data-target="#modal-reply">回复</button></td>
                </tr>
                <tr>
                    <td class="star"><i class="fa fa-star" aria-hidden="true"></i><i class="fa fa-star" aria-hidden="true"></i><i class="fa fa-star" aria-hidden="true"></i><i class="fa fa-star" aria-hidden="true"></i><i class="fa fa-star" aria-hidden="true"></i></td>
                    <td class=""><span class="">买家评价：</span><span>味道还可以</span></td>
                </tr>
                <tr>
                    <td class="border_bt"></td>
                    <td class=""><span class="">卖家回复：</span><span>欢迎下次光临</span></td>
                </tr>
                <tr class="">
                    <td class="border_bt"></td>
                    <td class="border_bt"><span>[2016-09-19&nbsp;&nbsp;12:30:37]</span></td>
                    <td class="border_bt"></td>
                </tr>
                </tbody>
            </table>
        </div>
    </div> 
    <div id="modal-reply" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="replyModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h5 class="modal-title" id="replyModalLabel">回复评论</h5>
                </div>
                <div class="modal-body">
                    <ul>
                        <li>
                            <span class="h5">评论内容：</span><span>宝贝很好我很喜欢</span>
                        </li>
                        <li>
                            <label class="control-label h5" for="description">回复内容：</label><span class="reply"> <textarea name="content">欢迎下次光临</textarea></span>

                        </li>
                    </ul>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary">确认</button>
                </div>
            </div>
        </div>
    </div>
</div>
