<?php
$customer = $this->getVariable('customer');
$logviewlist = $this->getVariable('log_view_list');
?>
<div class="dashboard">
  <div class="profile clearfix">
    <div class="head_pic">

        <label for="avatar" class="avatar">
                    <img src="<?php if ($customer->offsetGet('avatar')): ?>data:image/png;base64, <?php
                        echo $customer->offsetGet('avatar');
                    else:
                        echo $this->getPubUrl('frontend/images/placeholder.png');
                    endif;
                    ?>" alt="" />
                    <span class="update"><?php echo $this->translate('Update Image') ?></span>
                </label>
                 <div class="title_oic"><span>雄鹰能量棒</span>
                   <p><a href="">账户管理</a></p></div>   
    </div>
    <div class="info col-xs-12 col-sm-10">
        <div class="wishlist_track">
            <ul class="col-xs-12 col-sm-12">
             <li class="col-xs-4 col-sm-4 text-center">
                    <a href="<?php echo $this->getBaseUrl() ?>customer/wishlist/">0</a>
                    <span><?php echo $this->translate('Order today'); ?></span>
                </li>
                <li class="col-xs-4 col-sm-4 text-center">
                    <a href="<?php echo $this->getBaseUrl() ?>customer/wishlist/">0</a>
                    <span><?php echo $this->translate('Wait for delivery'); ?></span>
                </li>
                <li class="col-xs-4 col-sm-4 text-center">
                    <a href="<?php echo $this->getBaseUrl() ?>customer/history/">0</a>
                    <span><?php echo $this->translate('waiting for payment'); ?></span>
                </li>
              
                 <li class="col-xs-4 col-sm-4 text-center ">
                    <a href="<?php echo $this->getBaseUrl() ?>customer/history/">0</a>
                    <span><?php echo $this->translate('Refunding'); ?></span>
                </li>
                 <li class="col-xs-4 col-sm-4 text-center">
                    <a href="<?php echo $this->getBaseUrl() ?>customer/history/">0</a>
                    <span><?php echo $this->translate('Total visitors yesterday'); ?></span>
                </li>
                 <li class="col-xs-4 col-sm-4 text-center">
                    <a href="<?php echo $this->getBaseUrl() ?>customer/history/">0</a>
                    <span><?php echo $this->translate('Yesterday sales amount'); ?></span>
                </li>
            </ul>
        </div>
    </div>
</div>
				
<div class="myorder">
	<div class="panel-heading" onclick="i_btn($(this))">
		<h3 class="panel-title">
			<span class="fa fa-calculator" aria-hidden="true">
			</span>
			<?php echo $this->
				translate('Transaction Management') ?>
				<a href="javascript:void(0) " class="fa fa-chevron-up text-right" aria-hidden="true">
				</a>
		</h3>
	</div>
	<div class="Management-menu">
		<div class="panel-heading panel-menu">
			<h3 class="panel-title">
				<span>
					<?php echo $this->
						translate('Has sold the baby') ?>
				</span>
				<a href="<?php echo $this->getBaseUrl() ?>retailer/transaction/product/" class="fa fa-chevron-right text-right"
				aria-hidden="true">
				</a>
			</h3>
		</div>
		<div class="panel-heading panel-menu">
			<h3 class="panel-title" onclick="">
				<span>
					<?php echo $this->
						translate('Comment Management') ?>
				</span>
				<a href="<?php echo $this->getBaseUrl() ?>retailer/transaction/comment/" class="fa fa-chevron-right text-right"
				aria-hidden="true">
				</a>
			</h3>
		</div>
		<div class="panel-heading panel-menu">
			<h3 class="panel-title" onclick="">
				<span>
					<?php echo $this->
						translate('After Service') ?>
				</span>
				<a href="<?php echo $this->getBaseUrl() ?>retailer/transaction/after/" class="fa fa-chevron-right text-right"
				aria-hidden="true">
				</a>
			</h3>
		</div>
	</div>
</div>
				
<div class="myorder">
	<div class="panel-heading" onclick="i_btn($(this))">
		<h3 class="panel-title">
			<span class="fa fa-cart-plus" aria-hidden="true">
			</span>
			<?php echo $this->
				translate('Product Management') ?>
				<a href="javascript:void(0) " class="fa fa-chevron-up text-right" aria-hidden="true">
				</a>
		</h3>
	</div>
	<div class="Management-menu">
		<div class="panel-heading panel-menu">
			<h3 class="panel-title">
				<span>
					<?php echo $this->
						translate('Release Product') ?>
				</span>
				<a href="<?php echo $this->getBaseUrl() ?>retailer/product/release/" class="fa fa-chevron-right text-right"
				aria-hidden="true">
				</a>
			</h3>
		</div>
		<div class="panel-heading panel-menu">
			<h3 class="panel-title" onclick="">
				<span>
					<?php echo $this->
						translate('Sales of Product') ?>
				</span>
				<a href="<?php echo $this->getBaseUrl() ?>retailer/product/sales/" class="fa fa-chevron-right text-right"
				aria-hidden="true">
				</a>
			</h3>
		</div>
		<div class="panel-heading panel-menu">
			<h3 class="panel-title" >
				<span>
					<?php echo $this->
						translate('Stock') ?>
				</span>
				<a href="<?php echo $this->getBaseUrl() ?>retailer/product/stock/" class="fa fa-chevron-right text-right"
				aria-hidden="true">
				</a>
			</h3>
		</div>
		<div class="panel-heading panel-menu">
			<h3 class="panel-title" >
				<span>
					<?php echo $this->
						translate('History Record') ?>
				</span>
				<a href="<?php echo $this->getBaseUrl() ?>retailer/product/history/" class="fa fa-chevron-right text-right"
				aria-hidden="true">
				</a>
			</h3>
		</div>
	</div>
</div>
<div class="myorder">
	<div class="panel-heading" onclick="i_btn($(this))">
		<h3 class="panel-title">
			<span class="fa fa-bank" aria-hidden="true">
			</span>
			<?php echo $this->
				translate('Store Management') ?>
				<a href="javascript:void(0)" class="fa fa-chevron-up text-right" aria-hidden="true">
				</a>
		</h3>
	</div>
	<div class="Management-menu">
		<div class="panel-heading panel-menu">
			<h3 class="panel-title">
				<span>
					<?php echo $this->
						translate('View Store') ?>
				</span>
				<a href="<?php echo $this->getBaseUrl() ?>retailer/store/view/" class="fa fa-chevron-right text-right"
				aria-hidden="true">
				</a>
			</h3>
		</div>
		<div class="panel-heading panel-menu">
			<h3 class="panel-title" onclick="">
				<span>
					<?php echo $this->
						translate('Store Decoration') ?>
				</span>
				<a href="<?php echo $this->getBaseUrl() ?>retailer/store/decorationList " class="fa fa-chevron-right text-right"
				aria-hidden="true">
				</a>
			</h3>
		</div>
		<div class="panel-heading panel-menu">
			<h3 class="panel-title" onclick="">
				<span>
					<?php echo $this->
						translate('Photo Space') ?>
				</span>
				<a href="<?php echo $this->getBaseUrl() ?>retailer/resource/ " class="fa fa-chevron-right text-right"
				aria-hidden="true">
				</a>
			</h3>
		</div>
		<div class="panel-heading panel-menu">
			<h3 class="panel-title" onclick="">
				<span>
					<?php echo $this->
						translate('Photo Space') ?>
				</span>
				<a href="<?php echo $this->getBaseUrl() ?>retailer/store/mobile/" class="fa fa-chevron-right text-right"
				aria-hidden="true">
				</a>
			</h3>
		</div>
		<div class="panel-heading panel-menu">
			<h3 class="panel-title" onclick="">
				<span>
					<?php echo $this->
						translate('Product Category') ?>
				</span>
				<a href="<?php echo $this->getBaseUrl() ?>retailer/store/cotegory/" class="fa fa-chevron-right text-right"
				aria-hidden="true">
				</a>
			</h3>
		</div>
		<div class="panel-heading panel-menu">
			<h3 class="panel-title" onclick="">
				<span>
					<?php echo $this->
						translate('Store Settings') ?>
				</span>
				<a href="<?php echo $this->getBaseUrl() ?>retailer/store/setting/ " class="fa fa-chevron-right text-right"
				aria-hidden="true">
				</a>
			</h3>
		</div>
		<div class="panel-heading panel-menu">
			<h3 class="panel-title" onclick="">
				<span>
					<?php echo $this->
						translate('Brand Management') ?>
				</span>
				<a href="<?php echo $this->getBaseUrl() ?>retailer/store/brand/" class="fa fa-chevron-right text-right"
				aria-hidden="true">
				</a>
			</h3>
		</div>
	</div>
</div>
<div class="myorder">
	<div class="panel-heading" onclick="i_btn($(this))">
		<h3 class="panel-title">
			<span class="fa  fa-volume-up " aria-hidden="true">
			</span>
			<?php echo $this->
				translate('Marketing Center') ?>
				<a href="javascript:void(0) " class="fa fa-chevron-up text-right" aria-hidden="true">
				</a>
		</h3>
	</div>
	<div class="Management-menu">
		<div class="panel-heading panel-menu">
			<h3 class="panel-title">
				<span>
					<?php echo $this->
						translate('Activity Registration') ?>
				</span>
				<a href="<?php echo $this->getBaseUrl() ?>retailer/marketing/activity/" class="fa fa-chevron-right text-right"
				aria-hidden="true">
				</a>
			</h3>
		</div>
		<div class="panel-heading panel-menu">
			<h3 class="panel-title" onclick="">
				<span>
					<?php echo $this->
						translate('Promotion Management') ?>
				</span>
				<a href="<?php echo $this->getBaseUrl() ?>retailer/marketing/promotion/" class="fa fa-chevron-right text-right"
				aria-hidden="true">
				</a>
			</h3>
		</div>
		<div class="panel-heading panel-menu">
			<h3 class="panel-title" onclick="">
				<span>
					<?php echo $this->
						translate('Member Relationship Management') ?>
				</span>
				<a href="<?php echo $this->getBaseUrl() ?>retailer/marketing/relationship/" class="fa fa-chevron-right text-right"
				aria-hidden="true">
				</a>
			</h3>
		</div>
	</div>
</div>				
<div class="profile-foot">
    <ul class="col-xs-12 col-sm-12">
        <li class="col-xs-3 col-sm-3 text-center">
            <a href="<?php echo $this->getBaseUrl() ?>clothes.html"><?php echo $this->translate('Shopping'); ?></a>
        </li>
        <li class="col-xs-3 col-sm-3 text-center">
            <a href="<?php echo $this->getBaseUrl() ?>retailer/account/processing/"><?php echo $this->translate('Enter the Store Center'); ?></a>
        </li>
        <li class="col-xs-3 col-sm-3 text-center">
            <a href="<?php echo $this->getBaseUrl() ?>customer/account/logout/"><?php echo $this->translate('Log out'); ?></a>
        </li>
        <li class="col-xs-3 col-sm-3 text-center">
            <a href="<?php echo $this->getBaseUrl() ?>customer/account/logout/"><?php echo $this->translate('Give Feedback'); ?></a>
        </li>
    </ul>
</div>			

    
<script>
	function i_btn(env){
 		env.next('.Management-menu').find('.panel-menu').toggle();
		var btn_i = env.find('a');
		if(btn_i.is('.fa-chevron-down')){
			btn_i.removeClass();
			btn_i.addClass('fa fa-chevron-up text-center btn_i');
		}else{
			btn_i.removeClass();
			btn_i.addClass('fa fa-chevron-down text-center btn_i');
		}
	}
</script>
