<?php
$retailer = $this->getRetailer();
$store = $this->getStore();
?>
<div class="dashboard account-bg">
    <div class="profile clearfix">
        <form action="<?php echo $this->getBaseUrl('retailer/store/save/') ?>" method="post" class="form-inline" enctype="multipart/form-data">
            <input type="hidden" name="csrf" value="<?php echo $this->getCsrfKey() ?>" />
            <div class="head_pic">
                <div class="cell">
                    <label for="profile" class="avatar mobile-img">
                        <img src="<?php if ($retailer->offsetGet('profile')): ?>data:image/png;base64, <?php
                            echo base64_encode($retailer->offsetGet('profile'));
                        else:
                            echo $this->getPubUrl('frontend/images/placeholder.png');
                        endif;
                        ?>" width="100" height="100" />
                        <span class="update"><button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#myModal"><?php echo $this->translate('Update Image') ?></button></span>
                    </label>
                    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only"><?php echo $this->translate('Close') ?></span></button>
                                <h4 class="modal-title" id="myModalLabel"><?php echo $this->translate('Avatar') ?></h4>
                            </div>
                            <div class="modal-body">
                                <input type="file" name="profile" id="profile" accept="image/*" class="form-control required" />
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo $this->translate('Close') ?></button>
                                <button type="submit" class="btn btn-primary"><?php echo $this->translate('Submit') ?></button>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="title_oic">
                    <span><a href="<?php echo $this->translate('retailer/store/view/'); ?>"><?php echo $store['name'] ?></a></span>
                    <p><a href="<?php echo $this->getBaseUrl('customer/account/edit/'); ?>"><?PHP echo $this->translate('Account Management'); ?></a></p>
                </div>
            </div>
        </form>
        <div class="info col-xs-12 col-sm-10">
            <div class="wishlist_track">
                <ul class="col-xs-12 col-sm-12">
                    <li class="col-xs-4 col-sm-4 text-center">
                        <a href="<?php echo $this->getBaseUrl('customer/wishlist/') ?>">0</a>
                        <span><?php echo $this->translate('Order today'); ?></span>
                    </li>
                    <li class="col-xs-4 col-sm-4 text-center">
                        <a href="<?php echo $this->getBaseUrl('customer/wishlist/') ?>">0</a>
                        <span><?php echo $this->translate('Wait for delivery'); ?></span>
                    </li>
                    <li class="col-xs-4 col-sm-4 text-center">
                        <a href="<?php echo $this->getBaseUrl('customer/history/') ?>">0</a>
                        <span><?php echo $this->translate('waiting for payment'); ?></span>
                    </li>

                    <li class="col-xs-4 col-sm-4 text-center ">
                        <a href="<?php echo $this->getBaseUrl('customer/history/') ?>">0</a>
                        <span><?php echo $this->translate('Refunding'); ?></span>
                    </li>
                    <li class="col-xs-4 col-sm-4 text-center">
                        <a href="<?php echo $this->getBaseUrl('customer/history/') ?> ">0</a>
                        <span><?php echo $this->translate('Total visitors yesterday'); ?></span>
                    </li>
                    <li class="col-xs-4 col-sm-4 text-center">
                        <a href="<?php echo $this->getBaseUrl() ?>customer/history/">0</a>
                        <span><?php echo $this->translate('Yesterday sales amount'); ?></span>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="myorder-cont">	
        <div class="myorder">
            <div class="panel-heading" onclick="i_btn($(this))">
                <h3 class="panel-title">
                    <span class="fa fa-calculator" aria-hidden="true">
                    </span>
                    <?php echo $this->translate('Transaction Management') ?>
                    <a href="javascript:void(0)" class="fa fa-chevron-down text-right" aria-hidden="true"></a>
                </h3>
            </div>
            <div class="Management-menu">

                <div class="panel-heading panel-menu" >
                    <a href="<?php echo $this->getBaseUrl('retailer/transaction/product/') ?>">
                        <h3 class="panel-title">
                            <span>
                                <?php
                                echo $this->translate('Has sold the baby')
                                ?>
                            </span>
                            <i class="fa fa-chevron-right pull-right" aria-hidden="true">
                            </i>
                        </h3>
                    </a>	
                </div>
                <div class="panel-heading panel-menu">
                    <a href="<?php echo $this->getBaseUrl('retailer/transaction/review/') ?>">
                        <h3 class="panel-title" onclick=""><span><?php echo $this->translate('Comment Management') ?></span>
                            <i class="fa fa-chevron-right pull-right"></i>
                        </h3>
                    </a>
                </div>
                <div class="panel-heading panel-menu">
                    <a href="<?php echo $this->getBaseUrl('retailer/refund/') ?>">
                        <h3 class="panel-title" onclick="">
                            <span>
                                <?php
                                echo $this->translate('Return &amp; Refund')
                                ?>
                            </span>
                            <i class="fa fa-chevron-right pull-right">
                            </i>
                        </h3>
                    </a>
                </div>
            </div>
        </div>

        <div class="myorder" style="display: none">
            <div class="panel-heading" onclick="i_btn($(this))">
                <h3 class="panel-title">
                    <span class="fa fa-cart-plus" aria-hidden="true">
                    </span>
                    <?php
                    echo $this->
                            translate('Product Management')
                    ?>
                    <a href="javascript:void(0) " class="fa fa-chevron-up text-right" aria-hidden="true">
                    </a>
                </h3>
            </div>
            <div class="Management-menu">
                <div class="panel-heading panel-menu">
                    <a href="<?php echo $this->getBaseUrl() ?>retailer/product/release/">
                        <h3 class="panel-title">
                            <span>
                                <?php
                                echo $this->
                                        translate('Release Product')
                                ?>
                            </span>
                            <i class="fa fa-chevron-right pull-right"></i>
                        </h3>
                    </a>
                </div>
                <div class="panel-heading panel-menu">
                    <a href="<?php echo $this->getBaseUrl() ?>retailer/product/sales/">
                        <h3 class="panel-title" onclick="">
                            <span>
                                <?php
                                echo $this->
                                        translate('Sales of Product')
                                ?>
                            </span>
                            <i class="fa fa-chevron-right pull-right"
                               aria-hidden="true">
                            </i>
                        </h3>
                    </a>	
                </div>
                <div class="panel-heading panel-menu">
                    <a href="<?php echo $this->getBaseUrl() ?>retailer/product/stock/">
                        <h3 class="panel-title" >
                            <span>
                                <?php
                                echo $this->
                                        translate('Stock')
                                ?>
                            </span>
                            <i class="fa fa-chevron-right pull-right"
                               aria-hidden="true">
                            </i>
                        </h3>
                    </a>	
                </div>
                <div class="panel-heading panel-menu">
                    <a href="<?php echo $this->getBaseUrl() ?>retailer/product/history/">

                        <h3 class="panel-title" >
                            <span>
                                <?php
                                echo $this->
                                        translate('History Record')
                                ?>
                            </span>
                            <i  class="fa fa-chevron-right pull-right"
                                aria-hidden="true">
                            </i>
                        </h3>
                    </a>	
                </div>
            </div>
        </div>
        <div class="myorder "style="display: none">
            <div class="panel-heading" onclick="i_btn($(this))">
                <h3 class="panel-title">
                    <span class="fa fa-bank" aria-hidden="true">
                    </span>
                    <?php
                    echo $this->
                            translate('Store Management')
                    ?>
                    <a href="javascript:void(0)" class="fa fa-chevron-up text-right" aria-hidden="true">
                    </a>
                </h3>
            </div>
            <div class="Management-menu">

                <div class="panel-heading panel-menu">
                    <a href="<?php echo $this->getBaseUrl() ?>retailer/store/view/">
                        <h3 class="panel-title">
                            <span>
                                <?php
                                echo $this->
                                        translate('View Store')
                                ?>
                            </span>
                            <i class="fa fa-chevron-right pull-right"
                               aria-hidden="true">
                            </i>
                        </h3>
                    </a>
                </div>
                <div class="panel-heading panel-menu">
                    <a href="<?php echo $this->getBaseUrl() ?>retailer/store/freight/">
                        <h3 class="panel-title">
                            <span>
                                <?php
                                echo $this->
                                        translate('Freight Setting')
                                ?>
                            </span>
                            <i class="fa fa-chevron-right pull-right"
                               aria-hidden="true">
                            </i>
                        </h3>
                    </a>
                </div>

                <div class="panel-heading panel-menu">
                    <a href="<?php echo $this->getBaseUrl() ?>retailer/store/mobile/">
                        <h3 class="panel-title" onclick="">
                            <span>
                                <?php
                                echo $this->
                                        translate('Mobile Phone Store')
                                ?>
                            </span>
                            <i  class="fa fa-chevron-right pull-right"
                                aria-hidden="true">
                            </i>
                        </h3>
                    </a>
                </div>
                <div class="panel-heading panel-menu">
                    <a href="<?php echo $this->getBaseUrl() ?>retailer/store/cotegory/">
                        <h3 class="panel-title" onclick="">
                            <span>
                                <?php
                                echo $this->
                                        translate('Product Category')
                                ?>
                            </span>
                            <i class="fa fa-chevron-right pull-right"
                               aria-hidden="true">
                            </i>
                        </h3>
                    </a>
                </div>
                <div class="panel-heading panel-menu">
                    <a href="<?php echo $this->getBaseUrl() ?>retailer/store/setting/ ">
                        <h3 class="panel-title" onclick="">
                            <span>
                                <?php
                                echo $this->
                                        translate('Store Settings')
                                ?>
                            </span>
                            <i  class="fa fa-chevron-right pull-right"
                                aria-hidden="true">
                            </i>
                        </h3>
                    </a>
                </div>
                <div class="panel-heading panel-menu">
                    <a href="<?php echo $this->getBaseUrl() ?>retailer/store/brand/">
                        <h3 class="panel-title" onclick="">
                            <span>
                                <?php
                                echo $this->
                                        translate('Brand Management')
                                ?>
                            </span>
                            <i  class="fa fa-chevron-right pull-right"
                                aria-hidden="true">
                            </i>
                        </h3>
                    </a>
                </div>
            </div>
        </div>
        <div class="myorder " style="display: none">
            <div class="panel-heading" onclick="i_btn($(this))">
                <h3 class="panel-title">
                    <span class="fa  fa-volume-up " aria-hidden="true">
                    </span>
                    <?php
                    echo $this->
                            translate('Marketing Center')
                    ?>
                    <a href="javascript:void(0) " class="fa fa-chevron-up text-right" aria-hidden="true">
                    </a>
                </h3>
            </div>
            <div class="Management-menu">
                <div class="panel-heading panel-menu">
                    <a href="<?php echo $this->getBaseUrl() ?>retailer/marketing/activity/">
                        <h3 class="panel-title">
                            <span>
                                <?php
                                echo $this->
                                        translate('Activity Registration')
                                ?>
                            </span>
                            <i class="fa fa-chevron-right pull-right"
                               aria-hidden="true">
                            </i>
                        </h3>
                    </a>
                </div>
                <div class="panel-heading panel-menu">
                    <a href="<?php echo $this->getBaseUrl() ?>retailer/marketing/promotion/">
                        <h3 class="panel-title" onclick="">
                            <span>
                                <?php
                                echo $this->
                                        translate('Promotion Management')
                                ?>
                            </span>
                            <i class="fa fa-chevron-right pull-right"
                               aria-hidden="true">
                            </i>
                        </h3>
                    </a>
                </div>
                <div class="panel-heading panel-menu">
                    <a href="<?php echo $this->getBaseUrl('retailer/marketing/relationship/') ?>">
                        <h3 class="panel-title" onclick="">
                            <span>
                                <?php
                                echo $this->
                                        translate('Member Relationship Management')
                                ?>
                            </span>
                            <i class="fa fa-chevron-right pull-right"
                               aria-hidden="true">
                            </i>
                        </h3>
                    </a>
                </div>
            </div>
        </div>	
    </div>			
    <div class="profile-foot">
        <ul class="col-xs-12 col-sm-12">
            <li class="col-xs-3 col-sm-3 text-center">
                <a href="<?php echo $this->getBaseUrl('') ?>"><?php echo $this->translate('Shopping'); ?></a>
            </li>
            <li class="col-xs-3 col-sm-3 text-center">
                <a href="<?php echo $this->getBaseUrl('retailer/account/processing/') ?>"><?php echo $this->translate('Enter the Store Center'); ?></a>
            </li>
            <li class="col-xs-3 col-sm-3 text-center">
                <a href="<?php echo $this->getBaseUrl('customer/account/logout/') ?>"><?php echo $this->translate('Log out'); ?></a>
            </li>
            <li class="col-xs-3 col-sm-3 text-center">
                <a href="<?php echo $this->getBaseUrl('customer/account/logout/') ?>"><?php echo $this->translate('Give Feedback'); ?></a>
            </li>
        </ul>
    </div>			
    <script>
        function i_btn(env) {
            env.next('.Management-menu').find('.panel-menu').toggle();
            var btn_i = env.find('a');
            if (btn_i.is('.fa-chevron-down')) {
                btn_i.removeClass();
                btn_i.addClass('fa fa-chevron-up text-center btn_i');
            } else {
                btn_i.removeClass();
                btn_i.addClass('fa fa-chevron-down text-center btn_i');
            }
        }
    </script>
