<?php
$subtitle = $this->getVariable("subtitle");
$sales_products = $this->getRetailerHistoryProducts( );
$filter = $this->getVariable('filter');
?>
<div class="wishlist sales-products">
    <h4><?php echo $this->translate($subtitle); ?></h4>

     <div class="filter-bar" >
        <form id="filter_form" class="form-inline" action="<?php echo $this->getCurrentUrl() ?>" method="get" novalidate = "novalidate">
            <div class="sell">
                <ul class="commodity">
                    <li class="col-xs-12 col-sm-4"><span class="col-xs-3 col-sm-3" >商品名称:</span> <input class="form-control col-xs-8 col-sm-4" type="text" value="<?php echo isset($filter['name'])?$filter['name']:''; ?>" name="name"></li>
                    <li class="col-xs-12 col-sm-4"><span class="col-xs-3 col-sm-3" >商品编码:</span> <input class="form-control col-xs-8 col-sm-4" type="text" value="<?php echo isset($filter['sku'])?$filter['sku']:''; ?>" name="sku"></li>
                   
                     <li class="col-xs-12 col-sm-4"><span class="col-xs-3 col-sm-3" >商品类目:</span> 
                        <select class="form-control col-xs-8 col-sm-4" id="catalog" name="catalog" value="">
                            <option value="">全部</option>
                            <?php echo $this->renderCategory(0, 0, $filter['catalog']); ?>
                        </select>
                    </li>
                    <li class="col-xs-12 col-sm-4"><span class="col-xs-3 col-sm-3">商品分类:</span> 
                        <select class="form-control col-md-4" id="category" name="category" value="<?php echo $filter['category']; ?>">
                            <option value="">全部</option>
                        </select>
                    </li>
                    <li class="col-xs-12 col-sm-4"><span class="col-xs-3 col-sm-3">橱窗推荐:</span> 
                        <select class="form-control col-md-4" id="recomend_status" name="recomend_status">
                            <option value="">全部</option>
                            <option value="1" <?php echo (isset($filter['recommend_status']) && $filter['recommend_status'] == 1) ? 'selected' : ''; ?>>是</option>
                            <option value="0" <?php echo (isset($filter['recommend_status']) && $filter['recommend_status'] == 0) ? 'selected' : ''; ?>>否</option>
                        </select>
                    </li>
                     <li class="col-xs-12 col-sm-4"><span class="col-xs-3 col-sm-3" >价　　格:</span> <input id="form-time" class=" form-control form-time small-text col-xs-8 col-sm-4" type="text" value="<?php echo isset($filter['price_from'])?$filter['price_from']:''; ?>" name="price_from"><input id="form-time" class=" form-control small-text nomargin" type="text" value="<?php echo isset($filter['price_to'])?$filter['price_to']:''; ?>" name="price_to"> </li>
                    <div class="commodity_btn">
                    <a class="btn" href="<?php echo $this->getBaseUrl('retailer/product/sales/'); ?>">重置</a> 
                        &nbsp;&nbsp; <button class="btn">搜 索</button>
                    </div>
                   
                  	
                </ul>
            </div>
        </form>
    </div>
    <div style="clear:both"></div>

    <div class="seperation-title">共有 <span style="color:#FF0000"><?php echo count($sales_products) ?></span> 条记录</div>
   <hr class="seperation">
    <div class="products-content">
    <div class="table-responsive">
        <table class="table table-title">
        <thead>
            <tr>
                <td style="width: 45%;">商品名称</td>
                <td style="width: 14%;">价 格</td>
                <td style="width: 11%;"><span><a href=>库 存</a></span></td>
                <td style="width: 15%;"><span><a href=>发布时间</a></span></td>
                <td style="width: 15%;">操 作</td>
            </tr>
            <tr style="border-bottom: 1px solid #EDEDED;" >
                <td colspan="6"  style="text-align: left;" >
                    <input type="checkbox" class="selectall" data-cbtype="all">
                    <span>全选</span>
                    &nbsp;&nbsp;
                    <button class="btn-options enhancement product_remove" data-type=1>恢 复</button>
                </td>
            </tr>
            </thead>
             <?php
        foreach ($sales_products as $sales_product) {
            ?>
            <div class="transaction-list-sales" data-id="<?php echo $sales_product['id']; ?>">
          
                <tbody class="list-info">
                    <?php
                    $thumbnail = $this->getProduct($sales_product['id'])->getThumbnail();
                    ?>
                    <tr>
                        <td style="width: 45%;">
                            <div class="recommend">
                                <input type="checkbox" data-id="<?php echo $sales_product['id']; ?>">
                            </div>

                            <div class="product-pic">
                                <a href="<?php echo $sales_product->getUrl(); ?>" title="<?php echo $sales_product['name']; ?>" target="_blank">
                                    <?php if (strpos($thumbnail, 'http') === false) { ?>
                                        <img src="<?php echo $this->getBaseUrl('pub/resource/image/' . $thumbnail) ?>" class="bttrlazyloading" data-bttrlazyloading-lg-src="<?php echo $this->getBaseUrl('pub/resource/image/resized/50x/' . $thumbnail) ?>" data-bttrlazyloading-md-src="<?php echo $this->getBaseUrl('pub/resource/image/resized/108x/' . $thumbnail) ?>" data-bttrlazyloading-sm-src="<?php echo $this->getBaseUrl('pub/resource/image/resized/125x/' . $thumbnail) ?>" data-bttrlazyloading-xs-src="<?php echo $this->getBaseUrl('pub/resource/image/resized/256x/' . $thumbnail) ?>" alt="<?php echo $sales_product['name']; ?>" />
                                    <?php } else { ?>
                                        <img src="<?php echo $thumbnail ?>" alt="<?php echo $sales_product['name']; ?>" />
                                    <?php } ?>
                                </a>
                            </div>
                            <div class="product-title">
                                <p>
                                    <a target="_blank" href="<?php echo $sales_product->getUrl(); ?>" title="<?php echo $sales_product['name'] ?>">
                                        <span><?php echo $sales_product['name'] ?></span>
                                    </a>
                                </p>
                            </div>
                        </td>
                        <td style="width: 14%;">
                            <div>
                                <p class="text-center">
                                    <span class="money"  ><?php echo $this->getCurrency()->format($sales_product['price']); ?></span>
                                </p>
                            </div>
                        </td>
                        <td style="width: 11%;">
                            <div>
                                <p class="text-center"><?php echo $this->translate('%d', [$this->getInventory($sales_product['id'], $sales_product['sku'])]); ?></p>
                            </div>
                        </td>
                        <td class="border-right" style="width: 15%;"><?php echo empty($sales_product['created_at']) ? '&nbsp;' : $sales_product['created_at']; ?></td>
                        <td class="border-right" style="width: 15%;">
                            <div>
                                <p class="text-center">

                                    <span class="control-right" ><a href="<?php echo $this->getBaseUrl('retailer/product/release?id=' . $sales_product['id']) ?>" class="control-right" >编辑商品</a></span>

                                </p>
                            </div>
                        </td>
                    </tr>
                </tbody>
                
            </div>
            <?php
        }
        ?>
            
            
        </table>
        </div>
        <div class="clearfix mg-bottom-10"></div>
       
         <div class="table-responsive">
            <table class="table table-title">
                <tr style="background-color:#F1F2F4;">
                    <td  style="text-align: left;" >
                        <input type="checkbox" class="selectall" data-cbtype="all">
                        <span>全选</span>
                        &nbsp;&nbsp;
                        <button class="btn-options enhancement product_remove" data-type=1>恢 复</button>
                    </td>
                </tr>
            </table>
        </div>
        <div class="page-block">
            <div>
                <?php
                if (is_object($sales_products)) {
                    echo $this->getChild('pager')->setCollection($sales_products);
                }
                ?>
            </div>
        </div>
    </div>

    <div id="modal-receive" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="receiveModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="receiveModalLabel">收到货款</h4>
                </div>
                <div class="modal-body">
                    <div >
                        <h1>您确定已经收到买家的货款了吗？</h1>
                        <p>订单号&nbsp;&nbsp;&nbsp;&nbsp;:<span>88888888888</span></p>
                        <dl>
                            <dt>操作原因:</dt>
                            <dd><textarea name="remark"></textarea></dd>
                        </dl>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                    <button type="button" class="btn btn-primary">确认</button>
                </div>
            </div>
        </div>
    </div>

    <div id="modal-price" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="priceModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="priceModalLabel">费用调整</h4>
                </div>
                <div class="modal-body">
                    <div>买家:&nbsp;&nbsp;Stone<br>订单号&nbsp;&nbsp;:<strong>88888888888</strong></div>
                    <div>
                        <ul>
                            <li>
                                <h3>商品总价:<strong>¥100.00</strong></h3>
                                <p><input type="text" value="100.00" name="products_amount"></p>
                            </li>
                            <li>
                                <h3>配送费用:<strong>¥10.00</strong></h3>
                                <p><input type="text" value="10.00" name="shipping_fee"></p>
                            </li>
                        </ul>
                    </div>
                    <div><h3>订单总价:<strong>¥110.00</strong></h3></div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                    <button type="button" class="btn btn-primary">确认</button>
                </div>
            </div>
        </div>
    </div>

    <div id="modal-cancel" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="cancelModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="cancelModalLabel">费用调整</h4>
                </div>
                <div class="modal-body">
                    <h1>您是否确定要取消以下订单？</h1>
                    <p>订单号&nbsp;&nbsp;&nbsp;&nbsp;:<span>88888888888</span></p>
                    <dl>
                        <dt>取消原因:</dt>
                        <dd>
                            <div class="li">
                                <input type="radio" value="无法备齐货物" id="d1" name="cancel_reason" checked=""> <label for="d1">无法备齐货物</label>
                            </div>
                            <div class="li">
                                <input type="radio" value="不是有效的订单" id="d2" name="cancel_reason"> <label for="d2">不是有效的订单</label>
                            </div>
                            <div class="li">
                                <input type="radio" value="买家主动要求" id="d3" name="cancel_reason"> <label for="d3">买家主动要求</label>
                            </div>
                            <div class="li">
                                <input type="radio" value="其他原因" id="d4" flag="other_reason" name="cancel_reason"> <label for="d4">其他原因</label>
                            </div>
                        </dd>
                        <dd id="other_reason">
                            <textarea name="remark" id="other_reason_input"></textarea>
                        </dd>
                    </dl>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary">确认</button>
                </div>
            </div>
        </div>
    </div>
</div>
