<?php
$transactions = $this->getRetailerTransaction();
$sales_status = $this->getAllSalesStatus();
?>
<div class="wishlist">
    <div id="Has-sold" class="seller-tab">
        <div class="search padding-5 col-xs-12 col-sm-12">
            <form class="form-inline" action="" method="get" novalidate = "novalidate">
                <span class="fa fa-search" aria-hidden="true"></span>
                <input type="search" name="increment_id" value="" class="col-xs-10 col-sm-10" />
                <button type="submit" class="btn btn-default"><?php echo $this->translate('Search'); ?></button>
            </form>
        </div>
        <div id="Product-details" class="tab-content">
            <div class="tab-pane fade in active margin-bj" id="all">

                <div class="order col-xs-12 col-sm-12">
                    <ul class="col-xs-12 col-sm-12 title-navw name padding-5">
                        <li class="col-xs-6 col-sm-6 text-left font-12"><?php echo $this->translate('Order Number'); ?>:<?php echo $transactions->offsetGet('increment_id'); ?></li>
                        <li class="col-xs-6 col-sm-6 text-right font-12"></li>
                    </ul>
                        <ul class="col-xs-12 col-sm-12 title-nav name  padding-5 font-12">
                            <li class="text-left col-xs-6 col-sm-6" colspan="2"><?php echo $customer = $this->getCustomerByID($transactions['customer_id'])->username; ?></li>
                            <li class="col-xs-6 col-sm-6 text-right" colspan="2">
                            </li>
                        </ul>
                        <ul class="col-xs-12 col-sm-12 inline padding-10-5">
                            <li class="col-xs-2"><img src="" width="50" height="50"></li>
                            <li class="col-xs-6 "><span class="text-ovflow">女装 打褶中裙 173805 优衣库UNIQLO</span><p class="choose col-xs-12 col-sm-12 "><span class="col-xs-4 col-sm-4">颜色:棕色</span><span  class="col-xs-4 col-sm-4">尺码:XL</span><span  class="col-xs-4 col-sm-4"></span></p></li>
                            <li class="col-xs-3 text-right">
                                <span class="price ">￥198.00</span>
                                <span>x1</span>
                                <span class="color-blue">已付款</span>
                                <button class="padding-0 color-blue">未确认收货</button>
                            </li>
                        </ul>
                </div>
                <div class="address col-xs-12 col-sm-12">
                    <ul class="col-xs-12 col-sm-12 font-12">
                        <li class="bg font-14 "><span>收货信息</span></li>
                        <ul class="padding-5">
                            <li class="col-xs-4 col-sm-4">刘筱菲</li>
                            <li class="col-xs-8 col-sm-8">18865529426</li>
                            <li>山东省烟台市莱山区港城东大街100号3号楼206</li>	
                        </ul>
                    </ul>
                </div>
                <div class="logistics-ct col-xs-12 col-sm-12">
                    <ul class="logistics font-12">
                        <li class="bg font-14"><span>物流状态</span></li>
                        <ul class="padding-5">
                            <li class="col-xs-9 col-sm-9 padding-5"><span class="col-xs-4 col-sm-4">物流单号：</span> <input class="form-control " type="text" value="" name=""></li>
                            <li class="col-xs-3 col-sm-3 padding-5"><button>发货</button></li>
                        </ul>
                    </ul>
                    <ul class="col-xs-12 col-sm-12 font-12 padding-5 ">
                        <li class="col-xs-12 col-sm-12 padding-0"><span class="col-xs-6 col-sm-6">创建时间:</span> <span class="col-xs-6 col-sm-6">2016-10-20 11:09:33</span></li>
                        <li class="col-xs-12 col-sm-12 padding-0"><span class="col-xs-6 col-sm-6">付款时间:</span> <span class="col-xs-6 col-sm-6">2016-10-20 11:09:33</span></li>
                    </ul>
                </div>
                <div class="xq col-xs-12 col-sm-12">
                    <ul class="col-xs-12 col-sm-12 inline text-center operation padding-0-10">
                        <li class="col-xs-3"><span><a href="">详情</a></span></li>
                        <li class="col-xs-3 "><span><a href="">账单</a></span></li>
                        <li class="col-xs-3 "><span><a href="">发货</a></span></li>
                        <li class="col-xs-3"><span><a href="">打印</a></span></li>		
                    </ul>
                </div>
            </div>  

            <div class="tab-pane fade " id="delivery">
                2
            </div>
            <div class="tab-pane fade" id="payment">
                3
            </div>
            <div class="tab-pane fade " id="refund">
                4
            </div>
        </div>		
    </div>
</div>
