<?php
$subtitle = $this->getVariable("subtitle");
$filter = $this->getVariable("filter");
$transactions = $this->getRetailerTransaction();
$sales_status = $this->getAllSalesStatus();
?>
<div class="wishlist">
    <h4 class="title"><?php echo $this->translate($subtitle); ?></h4>
    <div id="Has-sold" class="seller-tab">
        <div class="tab-nav">
            <ul id="myTab" class="nav nav-tabs col-xs-12 col-sm-12">
                <li class="active col-xs-3 col-sm-3">
                    <a href="#all" data-toggle="tab">
                        全部(18)
                    </a>
                </li>
                <li class="col-xs-3 col-sm-3">
                    <a href="#delivery" data-toggle="tab">
                        待发货(13)
                    </a>
                </li>
                <li class="col-xs-3 col-sm-3">
                    <a href="#payment" data-toggle="tab">
                        待付款(13)
                    </a>
                </li>
                <li class="col-xs-3 col-sm-3">
                    <a href="#refund" data-toggle="tab">
                        退款中(12)
                    </a>
                </li>
            </ul>
        </div>	

        <div class="search col-xs-12 col-sm-12">
            <div class="search_center">
                <i class="fa fa-search" aria-hidden="true"></i>
                <input type="search" name="search" value="收件人姓名/电话/运单号/地址信息关键字" class="col-xs-12 col-sm-12"/>
            </div>
        </div>
        <div id="Product-details" class="tab-content">
            <div class="tab-pane fade in active" id="all">
                <div>
                    <ul  class="col-xs-12 col-sm-12 title-navw bt">
                        <li class="col-xs-6 col-sm-6 text-left font-14"><a href="" target="_blank">denny</a></li>
                        <li class="col-xs-6 col-sm-6 text-right font-14"><a href="">实付:￥123.00(包邮)</a></li>
                    </ul>
                    <ul class="col-xs-12 col-sm-12 inline bt">
                        <li class="col-xs-2"><img src="http://ecomv2.seahinet.test1/pub/resource/image/resized/173x/TB1jLZiNFXXXXapXFXXXXXXXXXX_!!0-item_pic.jpg" style="display: inline;" width="50" height="50"></li>
                        <li class="col-xs-7 "><span class="text-ovflow">女装 打褶中裙 173805 优衣库UNIQLO</span><p class="choose col-xs-12 col-sm-12 "><span class="col-xs-4 col-sm-4">颜色:棕色</span><span  class="col-xs-4 col-sm-4">尺码:XL</span><span  class="col-xs-4 col-sm-4"></span></p></li>
                        <li class="col-xs-3 text-right">
                            <span class="price color-blue font-14">￥198.00</span>
                            <span>x1</span>
                            <!--If paid，Status Displays Ship  Billing -->
                            <span>已付款</span>
                            <!-- If not paying the following status display to cancel the bill -->
                            <!-- <span>未付款</span> -->

                        </li>

                    </ul>
                    <ul class="col-xs-12 col-sm-12 inline text-center operation">
                        <li class="col-xs-6 col-sm-6"><span><a  href="">发货</a></span></li>
                        <li class="col-xs-6 col-sm-6"><span>账单</span></li>

                        <!-- If not paying the following status display to cancel the bill -->

<!-- 	        		<li class="col-xs-6 col-sm-6"><span><a  href=" ">取消</a></span></li> -->
<!-- 	        		<li class="col-xs-6 col-sm-6"><span>账单</span></li> -->     		
                    </ul>	
                </div>  
            </div>
            <div class="tab-pane fade " id="delivery">
                2
            </div>
            <div class="tab-pane fade" id="payment">
                3
            </div>
            <div class="tab-pane fade " id="refund">
                4
            </div>
        </div>		
    </div>


    <div id="modal-receive" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="receiveModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="receiveModalLabel">收到货款</h4>
                </div>
                <div class="modal-body">
                    <div >
                        <h1>您确定已经收到买家的货款了吗？</h1>
                        <p>订单号&nbsp;&nbsp;&nbsp;&nbsp;:<span>88888888888</span></p>
                        <dl>
                            <dt>操作原因:</dt>
                            <dd><textarea name="remark"></textarea></dd>
                        </dl>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                    <button type="button" class="btn btn-primary">确认</button>
                </div>
            </div>
        </div>
    </div>

    <div id="modal-price" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="priceModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="priceModalLabel">费用调整</h4>
                </div>
                <div class="modal-body">
                    <div>买家:&nbsp;&nbsp;Stone<br>订单号&nbsp;&nbsp;:<strong>88888888888</strong></div>
                    <div>
                        <ul>
                            <li>
                                <h3>商品总价:<strong>¥100.00</strong></h3>
                                <p><input type="text" value="100.00" name="products_amount"></p>
                            </li>
                            <li>
                                <h3>配送费用:<strong>¥10.00</strong></h3>
                                <p><input type="text" value="10.00" name="shipping_fee"></p>
                            </li>
                        </ul>
                    </div>
                    <div><h3>订单总价:<strong>¥110.00</strong></h3></div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                    <button type="button" class="btn btn-primary">确认</button>
                </div>
            </div>
        </div>
    </div>

    <div id="modal-cancel" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="cancelModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="cancelModalLabel">费用调整</h4>
                </div>
                <div class="modal-body">
                    <h1>您是否确定要取消以下订单？</h1>
                    <p>订单号&nbsp;&nbsp;&nbsp;&nbsp;:<span>88888888888</span></p>
                    <dl>
                        <dt>取消原因:</dt>
                        <dd>
                            <div class="li">
                                <input type="radio" value="无法备齐货物" id="d1" name="cancel_reason" checked=""> <label for="d1">无法备齐货物</label>
                            </div>
                            <div class="li">
                                <input type="radio" value="不是有效的订单" id="d2" name="cancel_reason"> <label for="d2">不是有效的订单</label>
                            </div>
                            <div class="li">
                                <input type="radio" value="买家主动要求" id="d3" name="cancel_reason"> <label for="d3">买家主动要求</label>
                            </div>
                            <div class="li">
                                <input type="radio" value="其他原因" id="d4" flag="other_reason" name="cancel_reason"> <label for="d4">其他原因</label>
                            </div>
                        </dd>
                        <dd id="other_reason">
                            <textarea name="remark" id="other_reason_input"></textarea>
                        </dd>
                    </dl>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary">确认</button>
                </div>
            </div>
        </div>
    </div>
</div>
