<?php
$subtitle = $this->getVariable("subtitle");
$filter = $this->getVariable("filter");
$transactions = $this->getRetailerTransaction();
$sales_status = $this->getAllSalesStatus();
$profile = new Seahinet\Retailer\ViewModel\Dashboard\Profile;
$payment = $profile->getPendingPayment();
$processing = $profile->getProcessing();
$refund1 = new Seahinet\Retailer\ViewModel\Refund;
$refund = $refund1->getApplication();
$refund->getSelect()->where->notEqualTo('status',5);
?>
<div class="wishlist">
    <div id="Has-sold" class="seller-tab">
        <ul id="myTab" class="nav nav-tabs col-xs-12 col-sm-12 text-center">
            <li class="col-xs-3 col-sm-3" <?php if (count($transactions) != 0): ?> class="active"<?php endif ?>>
                <a href="<?php echo $this->getBaseUrl('retailer/transaction/product/'); ?> ">
                    <?php echo $this->translate('All'); ?>(<span><?php echo count($transactions); ?></span>)
                </a>
            </li>
            <li class="col-xs-3 col-sm-3" id="delivery">
                <a href="<?php echo $this->getBaseUrl('retailer/transaction/product/?order_status=1'); ?>">
                    <?php echo $this->translate('Pending Payment'); ?>(<span><?php echo $profile->getPendingPayment(); ?></span>)
                </a>
            </li>
            <li class="col-xs-3 col-sm-3" id="payment">
                <a href="<?php echo $this->getBaseUrl('retailer/transaction/product/?order_status=3'); ?>">
                    <?php echo $this->translate('Processing', [], 'customer'); ?>(<span><?php echo $profile->getProcessing(); ?></span>)
                </a>
            </li>
            <li class="col-xs-3 col-sm-3" id="refund">
                <a href="<?php echo $this->getBaseUrl('retailer/refund/?status=1'); ?>">
                    <?php echo $this->translate('Refund rights'); ?>(<span><?php echo count($refund); ?></span>)
                </a>
            </li>
        </ul>
        <div class="search padding-5 col-xs-12 col-sm-12">
            <form class="form-inline" action="<?php echo $this->getCurrentUrl() ?>" method="get" novalidate = "novalidate">
                <span class="fa fa-search" aria-hidden="true"></span>
                <input type="search" name="increment_id" value="<?php echo isset($filter['increment_id']) ? $filter['increment_id'] : ''; ?>" class="col-xs-10 col-sm-10" />
                <button type="submit" class="btn btn-default"><?php echo $this->translate('Search'); ?></button>
            </form>
        </div>
        <div id="Product-details" class="tab-content">
            <div class="tab-pane fade in active" id="all">
                <?php
                foreach ($transactions as $transaction) :
                    ?>
                    <div class="transaction-list">
                        <ul class="col-xs-12 col-sm-12 title-navw name padding-5 font-12">
                            <li class="col-xs-6 col-sm-6 text-left"><?php echo $customer = $this->getCustomerByID($transaction['customer_id'])->username; ?></li>
                            <li class="col-xs-6 col-sm-6 text-right"><?php echo $transaction->getCurrency()->format($transaction->offsetGet('total')); ?><span class="font-12"><?php echo $this->translate('(Including Shipping Fee: %s)', [$transaction->getCurrency()->format($transaction->offsetGet('shipping'))]); ?></span></li>
                        </ul>
                        <?php
                        if (!empty($transaction['items'])) :
                            $items = $transaction->getItems();
                            ?>  
                            <table class="table inline bt padding-5">
                                <?php
                                $flag = TRUE;
                                foreach ($transaction['items'] as $key => $item) :
                                    $product = $item['product'];
                                    $thumbnail = $product->getThumbnail();
                                    ?>
                                    <tr>
                                        <td class="col-xs-2 col-sm-2">
                                            <a href="<?php echo $this->getProduct($item['product_id'])->getUrl(); ?>" title="<?php echo $item['product_name']; ?>">
                                                <img src="<?php echo strpos($thumbnail, '//') === false ? $this->getResourceUrl('image/resized/50x50/' . $thumbnail) : $thumbnail ?>" width="50" height="50" alt="<?php echo $product->offsetGet('name') ?>" />
                                            </a>
                                        </td>
                                        <td class="col-xs-6 col-sm-6">
                                            <h4 class="font-12">
                                                <a href="<?php echo $this->getProduct($item['product_id'])->getUrl(); ?>" title="<?php echo $item['product_name']; ?>">
                                                    <?php echo $item['product_name'] ?>
                                                </a>
                                            </h4>
                                            <?php
                                            $options = json_decode($item['options'], true);
                                            if ($item['product_id'] && count($options)):
                                                ?>
                                                <dl class="options">
                                                    <?php
                                                    foreach ($product->getOptions() as $option):
                                                        if (isset($options[$option->getId()])):
                                                            ?>
                                                            <dt><?php echo $option['title'] ?></dt>
                                                            <dd>
                                                                <?php
                                                                echo (in_array($option['input'], ['select', 'radio', 'checkbox', 'multiselect']) ?
                                                                        $option->getValue($options[$option->getId()]) : $options[$option->getId()])
                                                                ?>
                                                            </dd>
                                                            <?php
                                                        endif;
                                                    endforeach;
                                                    ?>
                                                </dl>
                                            <?php endif; ?>
                                        </td>
                                        <td class="col-xs-1 col-sm-1 text-right">
                                            <span class="price"><?php echo $transaction->getCurrency()->format($item->offsetGet('price')); ?></span>
                                            <span><?php echo (float) $item->offsetGet('qty'); ?></span>
                                        </td>                          
                                        <?php if ($flag) : ?>
                                            <td rowspan="<?php echo count($items) ?>" class="col-xs-3 col-sm-3 border-left action text-center">
                                                <span class="color-blue"><?php echo $this->translate($transaction['status_name']); ?></span>
                                            </td>
                                            <?php
                                            $flag = FALSE;
                                        endif;
                                        ?>
                                    </tr>
                                    <?php
                                endforeach;
                                ?>
                            </table>
                            <?php
                        endif;
                        ?>
                        <ul class="sale_status">
                            <?php
                            $order_obj = $this->getOrder($transaction['id']);
                            ?>
                            <li class="col-xs-12 col-sm-12 text-right">
                                <?php if ($order_obj->canCancel()) : ?>
                                    <a href="<?php echo $this->getBaseUrl('retailer/sales_order/cancel/?id=' . $order_obj->getId()) ?>" onclick="if (!confirm('<?php echo $this->translate('Are you sure to cancel this order?') ?>'))
                                                return false;" class="btn btn-cancel">
                                       <?php echo $this->translate('Cancel', [], 'sales') ?>
                                    </a>
                                <?php endif; ?>
                                <?php if ($order_obj->canHold()) : ?>
                                    <a href="<?php echo $this->getBaseUrl('retailer/sales_order/hold/?id=' . $order_obj->getId()) ?>"  class="btn">
                                        <?php echo $this->translate('Hold', [], 'sales') ?>
                                    </a>
                                <?php endif; ?>
                                <?php if ($order_obj->canUnhold()) : ?>
                                    <a href="<?php echo $this->getBaseUrl('retailer/sales_order/unhold/?id=' . $order_obj->getId()) ?>"  class="btn">
                                        <?php echo $this->translate('Unhold', [], 'sales') ?>
                                    </a>
                                <?php endif; ?>
                                <?php if ($order_obj->canInvoice()) : ?>
                                    <a href="<?php echo $this->getBaseUrl('retailer/sales_order/invoice/?id=' . $order_obj->getId()) ?>"  class="btn">
                                        <?php echo $this->translate('Invoice', [], 'sales') ?>
                                    </a>
                                <?php endif; ?>
                                <?php if ($order_obj->canShip()) : ?>
                                    <a href="<?php echo $this->getBaseUrl('retailer/sales_order/ship/?id=' . $order_obj->getId()) ?>"  class="btn">
                                        <?php echo $this->translate('Ship', [], 'sales') ?>
                                    </a>
                                <?php endif; ?>
                                <?php if ($order_obj->canRefund()) : ?>
                                    <a href="<?php echo $this->getBaseUrl('retailer/sales_order/refund/?id=' . $order_obj->getId()) ?>"  class="btn">
                                        <?php echo $this->translate('Refund', [], 'sales') ?>
                                    </a>
                                <?php endif; ?>
                                <a class="btn" style="background:#eee"></a>
                            </li>
                        </ul>
                    </div>
                    <?php
                endforeach;
                ?>
            </div>
            <div class="tab-pane fade " id="delivery">
                2
            </div>
            <div class="tab-pane fade" id="payment">
                3
            </div>
            <div class="tab-pane fade " id="refund">
                4
            </div>
        </div>
    </div>
</div>
