<div class="container">
    <div class="col-md-12">
        <div>
            <h3>交易记录</h3>
        </div>
        <br />
        
        <div class="row">
            <table class="table table-bordered">
                <tr>
                    <th>商品名称</th>
                    <th>价格</th>
                    <th>购买数量</th>
                    <th>成交时间</th>
                    <th>状态</th>
                </tr>
                <tr>
                    <td>test</td>
                    <td><span>68</span></td>
                    <td><span>1</span></td>
                    <td><span>2013-08-22 13:33:33</span></td>
                    <td>成交</td>
                </tr>
                <tr>
                    <td>test2</td>
                    <td><span>100</span></td>
                    <td><span>10</span></td>
                    <td><span>2013-08-31 13:33:33</span></td>
                    <td>退货</td>
                </tr>
                <tr>
                    <td colspan="5">
                        <div class="text-right">
                            <a>共 2 个项目</a>
                            <a href="#">上一页</a>
                            <a href="#">1</a>
                            <span>1 / 1</span>
                            <a href="#">下一页</a>
                        </div>
                    </td>
                </tr>
            </table>
            <br /><br />
        </div>
    </div>
</div>
