---
currency.switch:
    -
        listener: [\Seahinet\Sales\Listeners\Cart, afterCurrencySwitch]
        priority: 0
customer.login.after:
    -
        listener: [\Seahinet\Sales\Listeners\Cart, afterLoggedIn]
        priority: 10
customer.logout.after:
    -
        listener: [\Seahinet\Sales\Listeners\Cart, afterLoggedOut]
        priority: 10
Seahinet\Sales\Model\Order.model.save.before:
    -
        listener: [\Seahinet\Sales\Listeners\Increment, generate]
        priority: 10
Seahinet\Sales\Model\Invoice.model.save.before:
    -
        listener: [\Seahinet\Sales\Listeners\Increment, generate]
        priority: 10
Seahinet\Sales\Model\Shipment.model.save.before:
    -
        listener: [\Seahinet\Sales\Listeners\Increment, generate]
        priority: 10
Seahinet\Sales\Model\CreditMemo.model.save.before:
    -
        listener: [\Seahinet\Sales\Listeners\Increment, generate]
        priority: 10
