---
admin_sales_cart_list:
    update: grid
    root:
        children:
            head:
                action:
                    -
                        method: setTitle
                        params: Abandoned Cart / Sales
            content:
                children:
                    breadcrumb:
                        action:
                            -
                                method: addCrumb
                                params: [{link:':ADMIN/sales_cart/',label:'Abandoned Cart'}]
                    grid:
                        type: Seahinet\Admin\ViewModel\Sales\Grid\Cart
admin_sales_cart_view:
    update: grid
    root:
        children:
            head:
                action:
                    -
                        method: setTitle
                        params: Abandoned Cart / Sales
            content:
                children:
                    breadcrumb:
                        action:
                            -
                                method: addCrumb
                                params: [{link:':ADMIN/sales_cart/',label:'Abandoned Cart'}]
                            -
                                method: addCrumb
                                params: [{label:'View'}]
                    grid:
                        type: Seahinet\Admin\ViewModel\Sales\View\Cart
                        template: admin/sales/cart
admin_sales_order_list:
    update: grid
    root:
        children:
            head:
                action:
                    -
                        method: setTitle
                        params: Order / Sales
            content:
                children:
                    breadcrumb:
                        action:
                            -
                                method: addCrumb
                                params: [{link:':ADMIN/sales_order/',label:'Order'}]
                    grid:
                        type: Seahinet\Admin\ViewModel\Sales\Grid\Order
admin_sales_order_view:
    update: admin
    root:
        children:
            head:
                action:
                    -
                        method: setTitle
                        params: Order / Sales
            content:
                children:
                    breadcrumb:
                        action:
                            -
                                method: addCrumb
                                params: [{link:':ADMIN/sales_order/',label:'Order'}]
                            -
                                method: addCrumb
                                params: [{label:'View'}]
                    main:
                        type: Seahinet\Admin\ViewModel\Sales\View\Order
                        template: admin/sales/order
admin_sales_invoice_list:
    update: grid
    root:
        children:
            head:
                action:
                    -
                        method: setTitle
                        params: Invoice / Sales
            content:
                children:
                    breadcrumb:
                        action:
                            -
                                method: addCrumb
                                params: [{link:':ADMIN/sales_invoice/',label:'Invoice'}]
                    grid:
                        type: Seahinet\Admin\ViewModel\Sales\Grid\Invoice
admin_sales_invoice_view:
    update: admin
    root:
        children:
            head:
                action:
                    -
                        method: setTitle
                        params: Invoice / Sales
            content:
                children:
                    breadcrumb:
                        action:
                            -
                                method: addCrumb
                                params: [{link:':ADMIN/sales_invoice/',label:'Invoice'}]
                            -
                                method: addCrumb
                                params: [{label:'View'}]
                    main:
                        type: Seahinet\Admin\ViewModel\Sales\View\Invoice
                        template: admin/sales/order
admin_sales_shipment_list:
    update: grid
    root:
        children:
            head:
                action:
                    -
                        method: setTitle
                        params: Shipment / Sales
            content:
                children:
                    breadcrumb:
                        action:
                            -
                                method: addCrumb
                                params: [{link:':ADMIN/sales_shipment/',label:'Shipment'}]
                    grid:
                        type: Seahinet\Admin\ViewModel\Sales\Grid\Shipment
admin_sales_shipment_view:
    update: admin
    root:
        children:
            head:
                action:
                    -
                        method: setTitle
                        params: Shipment / Sales
            content:
                children:
                    breadcrumb:
                        action:
                            -
                                method: addCrumb
                                params: [{link:':ADMIN/sales_shipment/',label:'Shipment'}]
                            -
                                method: addCrumb
                                params: [{label:'View'}]
                    main:
                        type: Seahinet\Admin\ViewModel\Sales\View\Shipment
                        template: admin/sales/order
admin_sales_creditmemo_list:
    update: grid
    root:
        children:
            head:
                action:
                    -
                        method: setTitle
                        params: Credit Memo / Sales
            content:
                children:
                    breadcrumb:
                        action:
                            -
                                method: addCrumb
                                params: [{link:':ADMIN/sales_creditmemo/',label:'Credit Memo'}]
                    grid:
                        type: Seahinet\Admin\ViewModel\Sales\Grid\CreditMemo
admin_sales_creditmemo_view:
    update: admin
    root:
        children:
            head:
                action:
                    -
                        method: setTitle
                        params: Credit Memo / Sales
            content:
                children:
                    breadcrumb:
                        action:
                            -
                                method: addCrumb
                                params: [{link:':ADMIN/sales_creditmemo/',label:'Credit Memo'}]
                            -
                                method: addCrumb
                                params: [{label:'View'}]
                    main:
                        type: Seahinet\Admin\ViewModel\Sales\View\Creditmemo
                        template: admin/sales/order