---
admin_sales_cart_list:
    update: grid
    root:
        children:
            head:
                action:
                    -
                        method: setTitle
                        params: Abandoned Cart / Sales
            content:
                children:
                    breadcrumb:
                        action:
                            -
                                method: addCrumb
                                params: [{link:':ADMIN/sales_cart/',label:'Abandoned Cart'}]
                    grid:
                        type: Seahinet\Admin\ViewModel\Sales\Grid\Cart
admin_sales_cart_view:
    update: grid
    root:
        children:
            head:
                action:
                    -
                        method: setTitle
                        params: Abandoned Cart / Sales
            content:
                children:
                    breadcrumb:
                        action:
                            -
                                method: addCrumb
                                params: [{link:':ADMIN/sales_cart/',label:'Abandoned Cart'}]
                            -
                                method: addCrumb
                                params: [{label:'View'}]
                    grid:
                        type: Seahinet\Admin\ViewModel\Sales\View\Cart
                        template: admin/sales/cart
admin_sales_order_list:
    update: grid
    root:
        children:
            head:
                action:
                    -
                        method: setTitle
                        params: Order / Sales
            content:
                children:
                    breadcrumb:
                        action:
                            -
                                method: addCrumb
                                params: [{link:':ADMIN/sales_order/',label:'Order'}]
                    grid:
                        type: Seahinet\Admin\ViewModel\Sales\Grid\Order
admin_sales_order_view:
    update: admin
    root:
        children:
            head:
                action:
                    -
                        method: setTitle
                        params: Order / Sales
                    -
                        method: addScript
                        params: backend/js/locate.js
                    -
                        method: addScript
                        params: [{'src':'backend/js/modal.js','defer':'defer','async':'async'}]
            content:
                children:
                    breadcrumb:
                        action:
                            -
                                method: addCrumb
                                params: [{link:':ADMIN/sales_order/',label:'Order'}]
                            -
                                method: addCrumb
                                params: [{label:'View'}]
                    main:
                        type: Seahinet\Admin\ViewModel\Sales\View\Order
                        template: admin/sales/order
            extra:
                children:
                    address:
                        type: Seahinet\Admin\ViewModel\Sales\Edit\Address
                        template: admin/customer/addressForm
                    discount:
                        type: Seahinet\Lib\ViewModel\Template
                        template: admin/sales/edit/discount
admin_sales_order_print:
    update: admin
    root:
        template: page/ajax
        unset: [head]
        children:
            content:
                unset: [breadcrumb,messages]
                children:
                    main:
                        type: Seahinet\Admin\ViewModel\Sales\View\Order
                        template: admin/sales/print/order
admin_sales_invoice_list:
    update: grid
    root:
        children:
            head:
                action:
                    -
                        method: setTitle
                        params: Invoice / Sales
            content:
                children:
                    breadcrumb:
                        action:
                            -
                                method: addCrumb
                                params: [{link:':ADMIN/sales_invoice/',label:'Invoice'}]
                    grid:
                        type: Seahinet\Admin\ViewModel\Sales\Grid\Invoice
admin_sales_invoice_view:
    update: admin
    root:
        children:
            head:
                action:
                    -
                        method: setTitle
                        params: Invoice / Sales
            content:
                children:
                    breadcrumb:
                        action:
                            -
                                method: addCrumb
                                params: [{link:':ADMIN/sales_invoice/',label:'Invoice'}]
                            -
                                method: addCrumb
                                params: [{label:'View'}]
                    main:
                        type: Seahinet\Admin\ViewModel\Sales\View\Invoice
                        template: admin/sales/invoice
admin_sales_invoice_edit:
    update: admin
    root:
        children:
            head:
                action:
                    -
                        method: setTitle
                        params: Invoice / Sales
                    -
                        method: addScript
                        params: [{src:'backend/js/sales.js',defer:'defer',async:'async'}]
            content:
                children:
                    edit:
                        type: Seahinet\Admin\ViewModel\Sales\Edit\Invoice
                        template: admin/sales/edit/invoice
admin_sales_invoice_print:
    update: admin
    root:
        template: page/ajax
        unset: [head]
        children:
            content:
                unset: [breadcrumb,messages]
                children:
                    main:
                        type: Seahinet\Admin\ViewModel\Sales\View\Invoice
                        template: admin/sales/print/invoice
admin_sales_shipment_list:
    update: grid
    root:
        children:
            head:
                action:
                    -
                        method: setTitle
                        params: Shipment / Sales
            content:
                children:
                    breadcrumb:
                        action:
                            -
                                method: addCrumb
                                params: [{link:':ADMIN/sales_shipment/',label:'Shipment'}]
                    grid:
                        type: Seahinet\Admin\ViewModel\Sales\Grid\Shipment
admin_sales_shipment_view:
    update: admin
    root:
        children:
            head:
                action:
                    -
                        method: setTitle
                        params: Shipment / Sales
            content:
                children:
                    breadcrumb:
                        action:
                            -
                                method: addCrumb
                                params: [{link:':ADMIN/sales_shipment/',label:'Shipment'}]
                            -
                                method: addCrumb
                                params: [{label:'View'}]
                    main:
                        type: Seahinet\Admin\ViewModel\Sales\View\Shipment
                        template: admin/sales/shipment
admin_sales_shipment_edit:
    update: admin
    root:
        children:
            head:
                action:
                    -
                        method: setTitle
                        params: Invoice / Sales
                    -
                        method: addScript
                        params: [{src:'backend/js/sales.js',defer:'defer',async:'async'}]
            content:
                children:
                    edit:
                        type: Seahinet\Admin\ViewModel\Sales\Edit\Shipment
                        template: admin/sales/edit/shipment
admin_sales_shipment_print:
    update: admin
    root:
        template: page/ajax
        unset: [head]
        children:
            content:
                unset: [breadcrumb,messages]
                children:
                    main:
                        type: Seahinet\Admin\ViewModel\Sales\View\Shipment
                        template: admin/sales/print/shipment
admin_sales_creditmemo_list:
    update: grid
    root:
        children:
            head:
                action:
                    -
                        method: setTitle
                        params: Credit Memo / Sales
            content:
                children:
                    breadcrumb:
                        action:
                            -
                                method: addCrumb
                                params: [{link:':ADMIN/sales_creditmemo/',label:'Credit Memo'}]
                    grid:
                        type: Seahinet\Admin\ViewModel\Sales\Grid\CreditMemo
admin_sales_creditmemo_view:
    update: admin
    root:
        children:
            head:
                action:
                    -
                        method: setTitle
                        params: Credit Memo / Sales
            content:
                children:
                    breadcrumb:
                        action:
                            -
                                method: addCrumb
                                params: [{link:':ADMIN/sales_creditmemo/',label:'Credit Memo'}]
                            -
                                method: addCrumb
                                params: [{label:'View'}]
                    main:
                        type: Seahinet\Admin\ViewModel\Sales\View\Creditmemo
                        template: admin/sales/creditmemo
admin_sales_creditmemo_edit:
    update: admin
    root:
        children:
            head:
                action:
                    -
                        method: setTitle
                        params: Credit Memo / Sales
                    -
                        method: addScript
                        params: [{src:'backend/js/sales.js',defer:'defer',async:'async'}]
            content:
                children:
                    edit:
                        type: Seahinet\Admin\ViewModel\Sales\Edit\CreditMemo
                        template: admin/sales/edit/creditmemo
admin_sales_creditmemo_print:
    update: admin
    root:
        template: page/ajax
        unset: [head]
        children:
            content:
                unset: [breadcrumb,messages]
                children:
                    main:
                        type: Seahinet\Admin\ViewModel\Sales\View\Creditmemo
                        template: admin/sales/print/creditmemo
admin_order_status_list:
    update: grid
    root:
        children:
            content:
                children:
                    breadcrumb:
                        action:
                            -
                                method: addCrumb
                                params: [{link:':ADMIN/sales_status/',label:'Order Statuses'}]
                            -
                                method: addAdditional
                                params: [{link:':ADMIN/sales_status/edit/',label:'Add New Status'}]
                    grid:
                        type: Seahinet\Admin\ViewModel\Sales\Grid\Status
                        template: admin/grid-simple
admin_order_status_edit:
    update: edit
    root:
        children:
            content:
                children:
                    breadcrumb:
                        action:
                            -
                                method: addCrumb
                                params: [{link:':ADMIN/sales_status/',label:'Order Statuses'}]
                            -
                                method: addCrumb
                                params: [{link:':ADMIN/sales_status/edit/',label:'Edit'}]
                    edit:
                        type: Seahinet\Admin\ViewModel\Sales\Edit\Status
admin_refund_list:
    update: grid
    root:
        children:
            head:
                action:
                    -
                        method: setTitle
                        params: Refund Rights / Sales
            content:
                children:
                    breadcrumb:
                        action:
                            -
                                method: addCrumb
                                params: [{link:':ADMIN/sales_refund/',label:'Refund Rights'}]
                            -
                                method: addAdditional
                                params: [{link:':ADMIN/sales_refund/edit/',label:'Add New Refund'}]
                    grid:
                        type: Seahinet\Admin\ViewModel\Sales\Grid\Refund
                        template: admin/grid
admin_refund_view:
    update: admin
    root:
        children:
            head:
                action:
                    -
                        method: setTitle
                        params: Refund Rights / Sales
            content:
                children:
                    breadcrumb:
                        action:
                            -
                                method: addCrumb
                                params: [{link:':ADMIN/sales_refund/',label:'Refund Rights'}]
                            -
                                method: addCrumb
                                params: [{label:'View'}]
                    main:
                        type: Seahinet\Admin\ViewModel\Sales\View\Refund
                        template: admin/sales/refund
sales_refund:
    update: customer_account
    root:
        children:
            head:
                action:
                    -
                        method: setTitle
                        params: Refund Rights
            content:
                children:
                    main:
                        type: Seahinet\Lib\ViewModel\Template
                        template: sales/refund
sales_myorder:
    update: customer_account
    root:
        children:
            head:
                action:
                    -
                        method: setTitle
                        params: My Order
            content:
                children:
                    main:
                        type: Seahinet\Lib\ViewModel\Template
                        template: sales/order
sales_view:
    update: customer_account
    root:
        children:
            head:
                action:
                    -
                        method: setTitle
                        params: My Order
            content:
                children:
                    main:
                        type: Seahinet\Lib\ViewModel\Template
                        template: sales/view
                        children:
                            order_info:
                                type: Seahinet\Lib\ViewModel\Template
                                template: sales/view/order
                            invoice_info:
                                type: Seahinet\Lib\ViewModel\Template
                                template: sales/view/invoice
                            shipment_info:
                                type: Seahinet\Lib\ViewModel\Template
                                template: sales/view/shipment
                            creditmemo_info:
                                type: Seahinet\Lib\ViewModel\Template
                                template: sales/view/creditmemo
         