---
admin_login:
    update: default
    root:
        template: page/empty
        children:
            content:
                children:
                    login:
                        type: Seahinet\Lib\ViewModel\Template
                        template: admin/login
                    messages:
                        action:
                            method: addHandledSegment
                            params: admin
admin_forgot_password:
    update: default
    root:
        template: page/empty
        children:
            content:
                children:
                    login:
                        type: Seahinet\Lib\ViewModel\Template
                        template: admin/forgotPwd
                    messages:
                        action:
                            method: addHandledSegment
                            params: admin
admin_reset_password:
    update: default
    root:
        template: page/empty
        children:
            content:
                children:
                    login:
                        type: Seahinet\Lib\ViewModel\Template
                        template: admin/resetPwd
                    messages:
                        action:
                            method: addHandledSegment
                            params: admin
admin:
    update: default
    root:
        action:
            method: addBodyClass
            params: admin
        children:
            content:
                children:
                    messages:
                        action:
                            method: addHandledSegment
                            params: admin
admin_dashboard:
    update: admin