---
admin_login:
    update: default
    root:
        template: page/empty
        children:
            head:
                action:
                    -
                        method: addLink
                        params: pub/backend/css/normalize.css
                    -
                        method: addLink
                        params: pub/backend/css/styles.css
                    -
                        method: addLink
                        params: [pub/backend/css/styles.css,stylesheet,lt IE 9]
                    -
                        method: addScript
                        params: pub/backend/js/jquery.js
                    -
                        method: addScript
                        params: pub/backend/js/validate/jquery.validate.min.js
                    -
                        method: addScript
                        params: pub/backend/js/validate/config.js
                    -
                        method: addScript
                        params: pub/backend/js/modernizr.js
                    -
                        method: addScript
                        params: pub/backend/js/app.js
                    -
                        method: addScript
                        params: [pub/backend/js/selectivizr.js,lt IE 9]
                    -
                        method: setTitle
                        params: Log Into Seahinet Admin Panel
            content:
                children:
                    login:
                        type: Seahinet\Lib\ViewModel\Template
                        template: admin/login
                    messages:
                        action:
                            -
                                method: addHandledSegment
                                params: admin
admin_forgot_password:
    update: admin_login
    root:
        action:
            -
                method: addBodyClass
                params: admin-login
        children:
            content:
                children:
                    login:
                        template: admin/forgotPwd
admin_reset_password:
    update: admin_login
    root:
        action:
            -
                method: addBodyClass
                params: admin-login
        children:
            content:
                children:
                    login:
                        template: admin/resetPwd
admin:
    update: default
    root:
        action:
            method: addBodyClass
            params: admin
        children:
            head:
                action:
                    -
                        method: addLink
                        params: pub/backend/css/normalize.css
                    -
                        method: addLink
                        params: pub/backend/css/font-awesome.css
                    -
                        method: addLink
                        params: pub/backend/css/styles.css
                    -
                        method: addLink
                        params: [pub/backend/css/styles-ie.css,stylesheet,lt IE 9]
                    -
                        method: addScript
                        params: pub/backend/js/jquery.js
                    -
                        method: addScript
                        params: pub/backend/js/validate/jquery.validate.min.js
                    -
                        method: addScript
                        params: pub/backend/js/validate/config.js
                    -
                        method: addScript
                        params: [{src:'pub/backend/js/modernizr.js',defer:'defer',async:'async'}]
                    -
                        method: addScript
                        params: [{src:'pub/backend/js/dropdown.js',defer:'defer',async:'async'}]
                    -
                        method: addScript
                        params: [{src:'pub/backend/js/app.js',defer:'defer'}]
                    -
                        method: addScript
                        params: [{src:'pub/backend/js/selectivizr.js',defer:'defer'},lt IE 9]
                    -
                        method: setTitle
                        params: ''
            header:
                type: Seahinet\Lib\ViewModel\Template
                template: admin/header
                children:
                    messages:
                        type: Seahinet\Lib\ViewModel\Message
                        action:
                            -
                                method: addHandledSegment
                                params: admin
            footer:
                type: Seahinet\Lib\ViewModel\Template
                template: admin/footer
            beforeContent:
                children:
                    nav:
                        type: Seahinet\Admin\ViewModel\Navigation
                        template: admin/navigation
            content:
                children:
                    breadcrumb:
                        action:
                            -
                                method: showLabel
                                params: true
                unset: [messages]
grid:
    update: admin
    root:
        children:
            content:
                children:
                    grid:
                        type: Seahinet\Admin\ViewModel\Grid
                        children:
                            pager:
                                type: Seahinet\Lib\ViewModel\Pager
admin_dashboard:
    update: admin
admin_user:
    update: admin
admin_cache:
    update: grid
    root:
        children:
            content:
                children:
                    breadcrumb:
                        action:
                            -
                                method: addCrumb
                                params: [{link:':ADMIN/cache/',label:'Cache Management'}]
                            -
                                method: addAdditional
                                params: [{link:':ADMIN/cache/flush',label:'Flush All'}]
                    grid:
                        type: Seahinet\Admin\ViewModel\Cache
                        template: admin/cache