---
global:
    label: Global Configuration
    children:
        url:
            label: Url
            priority: 0
            scope: [merchant,store]
            children:
                base_url:
                    type: url
                    required: required
                    label: Base Url
                    priority: 0
                    scope: [merchant,store]
                    default: /
                    comment: Make sure that the Url ends with '/' (slash), e.g. http://yourdomain/
                cookie_free_domain:
                    type: url
                    label: Cookie-free Domain
                    priority: 1
                    scope: [merchant,store]
                    comment: Make sure that the Url ends with '/' (slash), e.g. http://yourdomain/
                admin_path:
                    type: text
                    required: required
                    label: Backend Path
                    priority: 10
                    scope: [merchant,store]
                    default: admin
        locale:
            label: Locale
            priority: 10
            scope: [merchant,store]
            children:
                timezone:
                    type: select
                    required: required
                    label: Timezone
                    priority: 0
                    scope: [merchant]
                    default: Etc/GMT
                    source: Seahinet\Lib\Source\Timezone
                country:
                    type: select
                    required: required
                    label: Default Country
                    priority: 10
                    default: CN
                    scope: [merchant]
                    source: Seahinet\I18n\Source\Country
theme:
    label: Theme Configuration
    children:
        global:
            label: Global
            scope: merchant
            priority: 0
            children:
                notice:
                    type: text
                    label: Global Notice
                    priority: 0
                    scope: merchant
                css_preprocessor:
                    type: select
                    required: reqired
                    label: CSS Preprocessor
                    priority: 90
                    scope: merchant
                    default: 1
                    options: [SCSS,LESS]
                combine_css:
                    type: select
                    label: Combine CSS File
                    required: required
                    priority: 100
                    scope: merchant
                    default: 0
                    options: ['Disabled','Enabled']
                combine_js:
                    type: select
                    label: Combine JS File
                    required: required
                    priority: 110
                    scope: merchant
                    default: 0
                    options: ['Disabled','Enabled']
        frontend:
            label: Frontend
            scope: merchant
            priority: 10
            children:
                template:
                    type: text
                    required: required
                    label: Template
                    priority: 0
                    scope: merchant
                    default: default
                static:
                    type: text
                    required: required
                    label: Static Files
                    priority: 10
                    scope: merchant
                    default: default
        backend:
            label: Backend
            scope: merchant
            priority: 20
            children:
                template:
                    type: text
                    required: required
                    label: Template
                    priority: 0
                    scope: merchant
                    default: default
                static:
                    type: text
                    required: required
                    label: Static Files
                    priority: 10
                    scope: merchant
                    default: default
