---
global:
    label: Global Configuration
    children:
        base_url:
            type: url
            required: required
            label: Base Url
            priority: 10
            scope: [merchant,store]
            default: /
            comment: Make sure that the Url ends with '/' (slash), e.g. http://yourdomain/
        cookie_free_domain:
            type: url
            label: Cookie-free Domain
            priority: 11
            scope: [merchant,store]
            comment: Make sure that the Url ends with '/' (slash), e.g. http://yourdomain/
        admin_path:
            type: text
            required: required
            label: Backend Path
            priority: 20
            scope: [merchant,store]
            default: admin
        frontend_theme:
            type: text
            required: required
            label: Frontend Template Theme
            priority: 30
            scope: [merchant,store]
            default: default
        frontend_pub_theme:
            type: text
            required: required
            label: Frontend Public Theme
            priority: 31
            scope: [merchant,store]
            default: default
        backend_theme:
            type: text
            required: required
            label: Backend Template Theme
            priority: 35
            scope: [merchant,store]
            default: default
        backend_pub_theme:
            type: text
            required: required
            label: Backend Public Theme
            priority: 36
            scope: [merchant,store]
            default: default
        css_preprocessor:
            type: select
            required: reqired
            label: CSS Preprocessor
            priority: 90
            scope: merchant
            default: 1
            options: [SCSS,LESS]
        combine_css:
            type: select
            label: Combine CSS File
            required: required
            priority: 100
            scope: merchant
            default: 0
            options: ['Disabled','Enabled']
        combine_js:
            type: select
            label: Combine JS File
            required: required
            priority: 110
            scope: merchant
            default: 0
            options: ['Disabled','Enabled']
