<?php
$products = $this->getProducts();
if (count($products)):
?>
    <div class="product-link">
        <ul class="products-grid clearfix">
            <?php
            foreach ($products as $product):
                $thumbnail = $product->getThumbnail();
                ?>
                <li class="item col-xs-6 col-sm-4 col-md-3 col-lg-2">
                    <a href="<?php echo $product->getUrl() ?>" title="<?php echo $product['name'] ?>" class="product-image">
                        <img src="<?php echo strpos($thumbnail, 'http') === false ? $this->
                                getBaseUrl('pub/resource/image/resized/131x/' . $thumbnail) : $thumbnail ?>" 
                                alt="<?php echo $product['name'] ?>" />
                    </a>
                    
                    <div class="price-box">
                        <?php echo $this->getPriceBox($product) ?>
                    </div>
                    <div class="action">
                        <a href="<?php echo $this->getBaseUrl('checkout/cart/add/?product_id=' . $product['id'] . 
                                '&qty=1&csrf=' . $this->getCsrfKey()) ?>" class="add2cart">
                        </a>
                    </div>
                </li>
            <?php endforeach ?>
        </ul>
    </div>
<?php endif; ?>