<?php
$product = $this->getVariable('product');
$images = $product->offsetGet('images');
?>
<div id="product-media" class="carousel slide" data-ride="carousel" data-interval="false">
    <?php if (count($images)): ?>
        <ol class="carousel-indicators">
            <?php
            foreach ($images as $key => $image):
                if ($image['id'] == $product->offsetGet('default_image')) {
                    $default = $image;
                }
                ?>
                <li data-target="#product-media" data-slide-to="<?php echo $key ?>"<?php if ($image['id'] == $product->offsetGet('default_image')): ?> class="active"<?php endif ?>>
                    <img src="<?php echo $this->getBaseUrl('pub/resource/image/resized/45x60/'), $image['src'] ?>" alt="" data-label="<?php echo $image['label'] ?>" data-group="<?php echo $image['group'] ?>" />
                </li>
            <?php endforeach ?>
        </ol>
        <div class="carousel-inner" role="listbox">
            <div class="item active">
                <img src="<?php echo $this->getBaseUrl('pub/resource/image/resized/345x448/'), $default['src'] ?>" width="345" height="448" alt="<?php echo $product->offsetGet('name') ?>">
            </div>
        </div>
    <div class="list-inline">
        <a class="left carousel-control" href="#product-media" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#product-media" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
    <?php else: ?>
        <div class="carousel-inner" role="listbox">
            <div class="item active">
                <img src="<?php echo $this->getPubUrl('frontend/images/placeholder.png') ?>" width="345" height="448" alt="<?php echo $product->offsetGet('name') ?>" />
            </div>
        </div>
    <?php endif ?>
</div>