<?php
$product = $this->getVariable('product');
$currency = $this->getCurrency();
$format = $currency['format'];
$symbol = $currency['symbol'];
?>
<?php if ($product->getFinalPrice() == $product['prices']['regular']): ?>
    <span class="regular-price">
        <span class="label"><?php echo $this->translate('Price') ?></span>
        <span class="price"><?php printf($format, $symbol, $product['prices']['regular']) ?></span>
    </span>
<?php else: ?>
    <span class="special-price">
        <span class="label"><?php echo $this->translate('Special Price') ?></span>
        <span class="price"><?php printf($format, $symbol, $product->getFinalPrice()) ?></span>
    </span>
    <span class="old-price">
        <span class="label"><?php echo $this->translate('Old Price') ?></span>
        <span class="price"><?php printf($format, $symbol, $product['prices']['regular']) ?></span>
    </span>
<?php endif; ?>
