<?php
$reviews = $this->getProduct()->getReviews();
//$customer = $this->getProduct()->getCustomer();
if ($reviews):
    ?>
    <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active"><a href="#user" aria-controls="description" role="tab" data-toggle="tab"><?php echo $this->translate('Review') ?></a></li>
        <li role="presentation"><a href="#visitors" aria-controls="review" role="tab" data-toggle="tab"><?php echo $this->translate('Discussion') ?></a></li>
    </ul>
    <div class="tab-content">
        <div role="tabpanel" class="tab-pane active" id="user">
            <?php foreach ($reviews as $review): ?>
            	<?php if (!is_null($review['order_id'])):?>
                    <div class="content-box">
                        <div class="subject-li"><?php echo $review['username'] ?>:</div>
                        <div class="content-li"><?php echo $review['content'] ?></div>
                    </div>
                <?php endif ?>
            <?php endforeach ?>
        </div>
        <div role="tabpanel" class="tab-pane" id="visitors">
        	<?php foreach ($reviews as $review): ?>
        		<?php if (is_null($review['order_id'])):?>
                    <div class="content-box">
                        <div class="subject-li"><?php echo $review['username'] ? $review['username'] : $this->translate('Visitor') ?>:</div>
                        <div class="content-li"><?php echo $review['content'] ?></div>
                    </div>
                <?php endif ?>
            <?php endforeach ?>
        </div>
    </div>
<?php endif; ?>
<div class="review-form">
    <span><br /><?php echo $this->translate('Discussion') ?>:</span>
	<div class="review-padding">
    	<form action="<?php echo $this->getBaseUrl('product/review') ?>" method="post">
    		<p><?php echo $this->translate('Subject') ?>：<input type="text" name="subject" /></p>
    		<p><?php echo $this->translate('Content') ?>：<textarea rows="4" name="content" ></textarea></p>
    		<button class="btn" type="submit" ><?php echo $this->translate('Submit') ?></button>
    	</form>
	</div>
</div>