<?php
$collection = $this->getVariable('collection');
$product = $this->getProduct();
$images = $product->offsetGet('images');

?>
<div class="container">
    <form action="<?php echo $this->getBaseUrl('checkout/cart/add/') ?>" method="post" enctype="multipart/form-data">
        <input type="hidden" name="csrf" value="<?php echo $this->getCsrfKey() ?>" />
        <input type="hidden" name="product" value="<?php echo $product->getId() ?>" />
        <div class="product-detail clearfix">
            <div class="col-lg-4">
                <?php echo $this->getChild('media')->setVariable('product', $product) ?>
                <div class="clearfix wishlist">
                    <ul>
                        <li><span class="fa fa-star"></span><a href="<?php echo $this->getBaseUrl('customer/wishlist/')?>"><?php echo $this->translate('Wish baby'); ?></a></li>
                        <li>|</li>
                        <li><span class="fa fa-share-alt" aria-hidden="true"></span><a href="#"><?php echo $this->translate('Share'); ?></a></li>
                    </ul>
                    <ul>
                        <li><a href="#"></a></li>
                        <li><a href="#"></a></li>
                        <li><a href="#"></a></li>
                        <li><a href="#"></a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-6 product-info">
                <h3><?php echo $product['name'] ?></h3>
                <div class="clearfix main-box">
                    <div class="price-box">
                        <p>
                        <span class="price-text"><?php echo $this->translate('Price'); ?></span>
                        <?php echo $this->getPriceBox() ?>
                        <p>
                    </div>
                    <div class="product-review">
                        <span><?php echo count($this->product['review_id']); ?></span>
                        <span><?php echo $this->translate('Product review'); ?></span>
                    </div>
                    <div class="sale-decimals">
                        <span><?php echo count($this->product['order_id']); ?></span>
                        <span><?php echo $this->translate('Sale decimals'); ?></span>
                    </div>
                </div>
                <div class=" clearfix product-distribution">
                    <p>
                        <span><?php echo $this->translate('Distribution'); ?></span>
                        <span><?php echo $this->translate('Shandongqingdao'); ?></span>
                        <select name="address">
                            <option name="1">address</option>
                        </select>
                        <select name="express">
                            <option name="1">Express</option>
                        </select>
                    </p>
                </div>
                <div class="clearfix product-color">
                    <p><?php echo $this->translate('Product color'); ?><span><?php echo $this->$product[''];?></span></p>
                </div>
                <div class="clearfix product-decimal">
                    <p><?php echo $this->translate('Product decimal'); ?>
                        <span class="tb-stock" id="J_Stock">
                            <a href="#"></a>
                            <input class="tb-text" value="1" maxlength="8" title="Please enter the purchase quantity" type="text">
                            <a href="#"></a>pcs
                        </span>
                        (Reserved Qty<span id="J_SpanStock" class="tb-count">5</span>pcs)</p>
                </div>
                <div class="clearfix product-action">
                    <div class="product-sale">
                        <button type="submit" class="btn btn-sm"><?php echo $this->translate('Buy it now'); ?></button>
                        <span class="fa fa-shopping-cart" aria-hidden="true"></span>
                        <button type="submit" class="btn btn-add">
                            <?php echo $this->translate('Join a shopping cart'); ?>
                        </button>
                    </div>
                </div> 
            </div>
            <div class="col-lg-2">
                <div class="upsells">
                    <?php echo $this->getChild('upsells')->setVariable('product', $product)->setLimit(3) ?>
                </div>
            </div>
            <div class="clearfix product-recommend">
                <h2><span><?php echo $this->translate('Red hot'); ?></span></h2>
                <?php echo $this->getChild('related')->setVariable('product', $product)->setLimit(7) ?>
            </div>
        </div>        
    </form>
</div>