<?php
$collection = $this->getVariable('collection');
$product = $this->getProduct();
$images = $product->offsetGet('images');
$warehouse = new Seahinet\Catalog\Model\Warehouse;
$warehouse->load(1);
$inventory = $warehouse->getInventory($product->getId(), $product['sku']);
$store = $product->getStore();
$retailer = new Seahinet\Retailer\Model\Retailer;
$retailer->load($store->getId(), 'store_id');
$SDview = new Seahinet\Retailer\ViewModel\StoreDecoration;
$decorations = $SDview->getProductDetailTemplateView($store->getId());
?>
<div class="container">
    <form action="<?php echo $this->getBaseUrl('checkout/cart/add/') ?>" method="post" enctype="multipart/form-data">
        <input type="hidden" name="csrf" value="<?php echo $this->getCsrfKey() ?>" />
        <input type="hidden" name="product_id" value="<?php echo $product->getId() ?>" />
        <input type="hidden" name="warehouse_id" value="<?php echo 1 ?>" />
        <div class="product-essential clearfix">
            <div class="col-xs-12 col-sm-4">
                <?php echo $this->getChild('media')->setVariable('product', $product), $this->getChild('share') ?>
            </div>
            <div class="col-xs-12 col-sm-8 col-md-6 product-info">
                <h2 class="product-name"><?php echo $product['name'] ?></h2>
                <div class="clearfix price-box">
                    <div class="col-xs-12 col-sm-8">
                        <?php echo $this->getPriceBox() ?>
                    </div>
                    <div class="hidden-xs col-sm-2 review">
                        <span class="count"><?php echo count($product->getReviews()) ?></span>
                        <span><?php echo $this->translate('Review(s)', [], 'catalog'); ?></span>
                    </div>
                    <div class="hidden-xs col-sm-2 order">
                        <span class="count">0</span>
                        <span><?php echo $this->translate('Order(s)', [], 'catalog'); ?></span>
                    </div>
                </div>
                <div class="options">
                    <?php echo $this->getChild('option')->setVariable('product', $product) ?>
                    <div class="input-box">
                        <label for="qty" class="control-label"><?php echo $this->translate('Qty') ?></label>
                        <div class="cell qty">
                            <label for="qty" class="spin minus">-</label>
                            <input id="qty" class="form-control required" value="<?php echo (float) $inventory['min_qty'] ?>" 
                                   min="<?php echo (float) $inventory['min_qty'] ?>" 
                                   max="<?php echo min((float) $inventory['max_qty'], (float) $inventory['qty']) ?>" 
                                   step="<?php echo (float) $inventory['increment'] ?>" name="qty" type="number" />
                            <label for="qty" class="spin plus">+</label>
                        </div>
                    </div>
                </div>
                <div class="clearfix action">
                    <button type="submit" class="btn"><?php echo $this->translate('Buy Now') ?></button>
                    <button type="submit" class="btn btn-checkout">
                        <span class="fa fa-shopping-cart" aria-hidden="true"></span>
                        <span><?php echo $this->translate('Add to Cart') ?></span>
                    </button>
                </div> 
            </div>
            <div class="col-xs-12 col-md-2 upsells">
                <?php
                echo $this->getChild('upsells')
                        ->setVariable('product', $product)
                        ->setLimit(3)
                        ->setVariable('class', 'col-xs-4 col-md-12')
                        ->setVariable('width', [
                            'xs' => '219',
                            'sm' => '228',
                            'md' => '104',
                            'lg' => '137',
                        ])
                ?>
            </div>
            <div class="related">
                <?php
                echo $this->getChild('related')
                        ->setVariable('product', $product)
                        ->setVariable('title', 'Featured Products')
                        ->setLimit(6)
                        ->setVariable('width', [
                            'xs' => '362',
                            'sm' => '228',
                            'md' => '221',
                            'lg' => '173',
                        ])
                ?>
            </div>
        </div>        
    </form>
    <div class="store_info retailer-store">
        <h3 class="tops"><?php echo $store['name'] ?></h3>
        <div class="store_detail" style="margin-bottom:9px">
            <table class="table text-center">
                <tbody>
                    <tr><td></td></tr>
                    <tr>
                        <td rowspan="3"><h4>9.7</h4></td>
                        <td><?php echo $this->translate('Commodity Evaluation'); ?>&nbsp;9.57&nbsp;<span class="fa fa-arrow-up" aria-hidden="true"></span></td>
                    </tr>
                    <tr>                
                        <td><?php echo $this->translate('Service Attitude'); ?>&nbsp;9.57&nbsp;<span class="fa fa-arrow-up" aria-hidden="true"></span></td>
                    </tr>
                    <tr>
                        <td><?php echo $this->translate('Logistics Speed'); ?>&nbsp;9.57&nbsp;<span class="fa fa-arrow-up" aria-hidden="true"></span></td>
                    </tr> 
                    <tr><td></td></tr>
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="2"><a href="<?php echo $this->getBaseUrl($retailer->getStoreUrl()); ?>" class="store_entry"><span class="fa fa-home" aria-hidden="true"></span>&nbsp;<?php echo $this->translate('Store Entry'); ?></a></td>
                    </tr>
                </tfoot>
            </table>
        </div>
        <?php echo !empty($decorations) ? $decorations['src_model'] : ''; ?>
		
    </div>
    <div class="product-detail">
        <ul class="nav nav-tabs" role="tablist">
            <li role="presentation" class="active"><a href="#description" aria-controls="description" role="tab" data-toggle="tab"><?php echo $this->translate('Description') ?></a></li>
            <li role="presentation"><a href="#review" aria-controls="review" role="tab" data-toggle="tab"><?php echo $this->translate('Review(s)') ?></a></li>
        </ul>
        <div class="tab-content">
            <div role="tabpanel" class="tab-pane active" id="description">
                <?php echo $this->getChild('attribute'), $product->offsetGet('description') ?>
            </div>
            <div role="tabpanel" class="tab-pane" id="review">
                <?php echo $this->getChild('review') ?>
            </div>
        </div>
    </div>
</div>
