<?php
$item = $this->getVariable('item');
$product = $item['product'];
$thumbnail = $product->getThumbnail();
?>
<ul class="col-xs-12 col-sm-12 product-list">
    <li class="col-xs-9 col-xs-9">
        <div class="product-img">
            <img src="<?php echo strpos($thumbnail, '//') === false ? $this->getBaseUrl('pub/resource/image/resized/88x/' . $thumbnail) : $thumbnail ?>" width="90%" alt="" />
        </div>
        <div class="product-name">
            <h4><?php echo $item['product_name'] ?></h4>
            <?php
            $options = json_decode($item['options'], true);
            if ($item['product_id'] && count($options)):
                ?>
                <ul class="options">
                    <?php
                    foreach ($item['product']->getOptions() as $option):
                        if (isset($options[$option->getId()])):
                            ?>
                            <li><?php echo $option['title'] ?>
                            <span>
                                <?php
                                echo (in_array($option['input'], ['select', 'radio', 'checkbox', 'multiselect']) ?
                                        $option->getValue($options[$option->getId()]) : $options[$option->getId()])
                                ?>
                            </span>
                            </li>
                            <?php
                        endif;
                    endforeach;
                    ?>
                </ul>
            <?php endif; ?>
        </div>
    </li>  
    <li class="col-xs-2 col-sm-2 qty">
    	x
        <?php echo (float) $item['qty'] ?>
    </li>
	<li>
		 <div class="price" data-price="<?php echo $item['price'] ?>">
            <p><?php echo $this->getCurrency()->format($item['price']) ?></p>
        </div>
	</li>

    
</ul>