<div id="modal-reply" class="modal fade" tabindex="-1">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">回复评论</h4>
            </div>
            <div class="modal-body">
                <ul>
                    <li>
                        <span class="h5">评论内容：</span><span>宝贝很好我很喜欢</span>
                    </li>
                    <li>
                        <span class="h5">回复评论：</span><span class="reply"> <textarea name="content">欢迎下次光临</textarea></span>
                    </li>
                </ul>
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-primary">确认</button>
            </div>
        </div>
    </div>
</div>