<?php
$data = $this->getVariable('data', []);
?>
<h2 class="page-title"><?php echo $this->translate('Register for a Business Account') ?></h2>
<div class="page-content">
    <div class="alert alert-warning">
        <?php echo $this->translate('Application to open a store is completely free. Each ID could only open one store.', [], 'retailer') ?><br />
        <?php echo $this->translate('The approval would speed 1~3 working days. Click here to know more about it.', [], 'retailer') ?>
    </div>
    <div class="flow">
        <ol>
            <li><?php echo $this->translate('Application', [], 'retailer') ?></li>
            <li><?php echo $this->translate('Supplementation', [], 'retailer') ?></li>
            <li><?php echo $this->translate('Approving', [], 'retailer') ?></li>
        </ol>
    </div>
    <div class="form">
        <button type="button" class="btn btn-theme" onclick="$(this).next('form').show();$(this).hide();$('.flow li').first().addClass('active');"><?php echo $this->translate('Register Now') ?></button>
        <form action="<?php echo $this->getBaseUrl('retailer/account/applypost/') ?>" method="post" enctype="multipart/form-data" style="display:none">
            <input type="hidden" name="csrf" value="<?php echo $this->getCsrfKey() ?>" />
            <div class="input-box clearfix">
                <label class="control-label"><?php echo $this->translate('ID Card 1') ?></label>
                <div class="cell dropdown">
                    <input type="file" name="id1" class="form-control required preview" />
                </div>
            </div>
            <div class="input-box clearfix">
                <label class="control-label"><?php echo $this->translate('ID Card 2') ?></label>
                <div class="cell dropdown">
                    <input type="file" name="id2" class="form-control required preview" />
                </div>
            </div>
            <div class="input-box clearfix">
                <label class="control-label"><?php echo $this->translate('Phone Number') ?></label>
                <div class="cell">
                    <input type="tel" name="phone" class="form-control required digits" value="<?php echo isset($data['phone']) ? $data['phone'] : '' ?>" />
                </div>
            </div>
            <div class="input-box clearfix">
                <label class="control-label"><?php echo $this->translate('Brand') ?></label>
                <div class="cell">
                    <input type="radio" name="brand_type" class="required" id="brand-1" value="1"<?php if (isset($data['brand_type']) && $data['brand_type'] == 1): ?> checked="checked"<?php endif ?> />
                    <label for="brand-1"><?php echo $this->translate('Own', [], 'retailer') ?></label>
                    <input type="radio" name="brand_type" class="required" id="brand-2" value="0"<?php if (isset($data['brand_type']) && $data['brand_type'] === '0'): ?> checked="checked"<?php endif ?> />
                    <label for="brand-2"><?php echo $this->translate('Agency', [], 'retailer') ?></label>
                </div>
            </div>
            <div class="input-box clearfix">
                <label class="control-label"><?php echo $this->translate('Product Type') ?></label>
                <div class="cell">
                    <input type="text" name="product_type" class="form-control required" value="<?php echo isset($data['product_type']) ? $data['product_type'] : '' ?>" />
                </div>
            </div>
            <div class="buttons-set">
                <button type="submit" class="btn btn-default"><?php echo $this->translate('Next') ?></button>
            </div>
        </form>
    </div>
</div>
