<div class="modal fade" id="modal-edit-address">
    <div class="modal-dialog">
        <div class="modal-content">
            <form action="<?php echo $this->getSaveUrl() ?>" method="post" data-ajax="true">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title"><?php echo $this->translate('Address Infomation') ?></h4>
                </div>
                <div class="modal-body">
                    <?php
                    foreach ($this->getElements() as $key => $item) {
                        echo $this->getInputBox($key, $item);
                    }
                    ?>
                    <script>
                        new Locate();
                    </script>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn" data-dismiss="modal"><?php echo $this->translate('Close') ?></button>
                    <button type="submit" class="btn btn-theme"><?php echo $this->translate('Save') ?></button>
                </div>
            </form>
        </div>
    </div>
</div>
