<?php
$item = $this->getVariable('item');
$key = $this->getVariable('key');
$id = trim(preg_replace('/\W+/', '-', $key), '-');
$parent = $this->getVariable('parent');
$required = isset($item['required'])?' required ':'';
?>
<div class="select-icon">
    <input type="radio" name="<?php echo $key.'"'.$required ?> <?php if ($item['value']=='qq'):?>checked<?php endif?> value="qq" id="qq" /><label for="qq" class="fa fa-fw fa-qq"></label>
    <input type="radio" name="<?php echo $key.'"'.$required ?> <?php if ($item['value']=='wechat'):?>checked<?php endif?> value="wechat" id="wechat" /><label for="wechat" class="fa fa-fw fa-wechat"></label>
    <input type="radio" name="<?php echo $key.'"'.$required ?> <?php if ($item['value']=='weibo'):?>checked<?php endif?> value="weibo" id="weibo" /><label for="weibo" class="fa fa-fw fa-weibo"></label>
    <input type="radio" name="<?php echo $key.'"'.$required ?> <?php if ($item['value']=='renren'):?>checked<?php endif?> value="renren" id="renren" /><label for="renren" class="fa fa-fw fa-renren"></label>
    <input type="radio" name="<?php echo $key.'"'.$required ?> <?php if ($item['value']=='facebook'):?>checked<?php endif?> value="facebook" id="facebook" /><label for="facebook" class="fa fa-fw fa-facebook"></label>
    <input type="radio" name="<?php echo $key.'"'.$required ?> <?php if ($item['value']=='twitter'):?>checked<?php endif?> value="twitter" id="twitter" /><label for="twitter" class="fa fa-fw fa-twitter"></label>
    <input type="radio" name="<?php echo $key.'"'.$required ?> <?php if ($item['value']=='linkedin'):?>checked<?php endif?> value="linkedin" id="linkedin" /><label for="linkedin" class="fa fa-fw fa-linkedin"></label>
    <input type="radio" name="<?php echo $key.'"'.$required ?> <?php if ($item['value']=='pinterest'):?>checked<?php endif?> value="pinterest" id="pinterest" /><label for="pinterest" class="fa fa-fw fa-pinterest"></label>
    <input type="radio" name="<?php echo $key.'"'.$required ?> <?php if ($item['value']=='google'):?>checked<?php endif?> value="google" id="google" /><label for="google" class="fa fa-fw fa-google"></label>
    <input type="radio" name="<?php echo $key.'"'.$required ?> <?php if ($item['value']=='tumblr'):?>checked<?php endif?> value="tumblr" id="tumblr" /><label for="tumblr" class="fa fa-fw fa-tumblr"></label>
    <input type="radio" name="<?php echo $key.'"'.$required ?> <?php if ($item['value']=='instagram'):?>checked<?php endif?> value="instagram" id="instagram" /><label for="instagram" class="fa fa-fw fa-instagram"></label>
    <input type="radio" name="<?php echo $key.'"'.$required ?> <?php if ($item['value']=='vk'):?>checked<?php endif?> value="vk" id="vk" /><label for="vk" class="fa fa-fw fa-vk"></label>
    <input type="radio" name="<?php echo $key.'"'.$required ?> <?php if ($item['value']=='flickr'):?>checked<?php endif?> value="flickr" id="flickr" /><label for="flickr" class="fa fa-fw fa-flickr"></label>
    <input type="radio" name="<?php echo $key.'"'.$required ?> <?php if ($item['value']=='yahoo'):?>checked<?php endif?> value="yahoo" id="yahoo" /><label for="yahoo" class="fa fa-fw fa-yahoo"></label>
    <input type="radio" name="<?php echo $key.'"'.$required ?> <?php if ($item['value']=='pinterest-p'):?>checked<?php endif?> value="pinterest-p" id="pinterest-p" /><label for="pinterest-p" class="fa fa-fw fa-pinterest-p"></label>
    <input type="radio" name="<?php echo $key.'"'.$required ?> <?php if ($item['value']=='pinterest-square'):?>checked<?php endif?> value="pinterest-square" id="pinterest-square" /><label for="pinterest-square" class="fa fa-fw fa-pinterest-square"></label>
    <input type="radio" name="<?php echo $key.'"'.$required ?> <?php if ($item['value']=='500px'):?>checked<?php endif?> value="500px" id="500px" /><label for="500px" class="fa fa-fw fa-500px"></label>
    <input type="radio" name="<?php echo $key.'"'.$required ?> <?php if ($item['value']=='behance'):?>checked<?php endif?> value="behance" id="behance" /><label for="behance" class="fa fa-fw fa-behance"></label>
    <input type="radio" name="<?php echo $key.'"'.$required ?> <?php if ($item['value']=='buysellads'):?>checked<?php endif?> value="buysellads" id="buysellads" /><label for="buysellads" class="fa fa-fw fa-buysellads"></label>
    <input type="radio" name="<?php echo $key.'"'.$required ?> <?php if ($item['value']=='connectdevelop'):?>checked<?php endif?> value="connectdevelop" id="connectdevelop" /><label for="connectdevelop" class="fa fa-fw fa-connectdevelop"></label>
    <input type="radio" name="<?php echo $key.'"'.$required ?> <?php if ($item['value']=='dashcube'):?>checked<?php endif?> value="dashcube" id="dashcube" /><label for="dashcube" class="fa fa-fw fa-dashcube"></label>
    <input type="radio" name="<?php echo $key.'"'.$required ?> <?php if ($item['value']=='delicious'):?>checked<?php endif?> value="delicious" id="delicious" /><label for="delicious" class="fa fa-fw fa-delicious"></label>
    <input type="radio" name="<?php echo $key.'"'.$required ?> <?php if ($item['value']=='deviantart'):?>checked<?php endif?> value="deviantart" id="deviantart" /><label for="deviantart" class="fa fa-fw fa-deviantart"></label>
    <input type="radio" name="<?php echo $key.'"'.$required ?> <?php if ($item['value']=='digg'):?>checked<?php endif?> value="digg" id="digg" /><label for="digg" class="fa fa-fw fa-digg"></label>
    <input type="radio" name="<?php echo $key.'"'.$required ?> <?php if ($item['value']=='empire'):?>checked<?php endif?> value="empire" id="empire" /><label for="empire" class="fa fa-fw fa-empire"></label>
    <input type="radio" name="<?php echo $key.'"'.$required ?> <?php if ($item['value']=='envira'):?>checked<?php endif?> value="envira" id="envira" /><label for="envira" class="fa fa-fw fa-envira"></label>
    <input type="radio" name="<?php echo $key.'"'.$required ?> <?php if ($item['value']=='expeditedssl'):?>checked<?php endif?> value="expeditedssl" id="expeditedssl" /><label for="expeditedssl" class="fa fa-fw fa-expeditedssl"></label>
    <input type="radio" name="<?php echo $key.'"'.$required ?> <?php if ($item['value']=='first-order'):?>checked<?php endif?> value="first-order" id="first-order" /><label for="first-order" class="fa fa-fw fa-first-order"></label>
    <input type="radio" name="<?php echo $key.'"'.$required ?> <?php if ($item['value']=='foursquare'):?>checked<?php endif?> value="foursquare" id="foursquare" /><label for="foursquare" class="fa fa-fw fa-foursquare"></label>
    <input type="radio" name="<?php echo $key.'"'.$required ?> <?php if ($item['value']=='get-pocket'):?>checked<?php endif?> value="get-pocket" id="get-pocket" /><label for="get-pocket" class="fa fa-fw fa-get-pocket"></label>
    <input type="radio" name="<?php echo $key.'"'.$required ?> <?php if ($item['value']=='gratipay'):?>checked<?php endif?> value="gratipay" id="gratipay" /><label for="gratipay" class="fa fa-fw fa-gratipay"></label>
    <input type="radio" name="<?php echo $key.'"'.$required ?> <?php if ($item['value']=='hacker-news'):?>checked<?php endif?> value="hacker-news" id="hacker-news" /><label for="hacker-news" class="fa fa-fw fa-hacker-news"></label>
    <input type="radio" name="<?php echo $key.'"'.$required ?> <?php if ($item['value']=='houzz'):?>checked<?php endif?> value="houzz" id="houzz" /><label for="houzz" class="fa fa-fw fa-houzz"></label>
    <input type="radio" name="<?php echo $key.'"'.$required ?> <?php if ($item['value']=='lastfm'):?>checked<?php endif?> value="lastfm" id="lastfm" /><label for="lastfm" class="fa fa-fw fa-lastfm"></label>
    <input type="radio" name="<?php echo $key.'"'.$required ?> <?php if ($item['value']=='leanpub'):?>checked<?php endif?> value="leanpub" id="leanpub" /><label for="leanpub" class="fa fa-fw fa-leanpub"></label>
    <input type="radio" name="<?php echo $key.'"'.$required ?> <?php if ($item['value']=='odnoklassniki'):?>checked<?php endif?> value="odnoklassniki" id="odnoklassniki" /><label for="odnoklassniki" class="fa fa-fw fa-odnoklassniki"></label>
    <input type="radio" name="<?php echo $key.'"'.$required ?> <?php if ($item['value']=='optin-monster'):?>checked<?php endif?> value="optin-monster" id="optin-monster" /><label for="optin-monster" class="fa fa-fw fa-optin-monster"></label>
    <input type="radio" name="<?php echo $key.'"'.$required ?> <?php if ($item['value']=='product-hunt'):?>checked<?php endif?> value="product-hunt" id="product-hunt" /><label for="product-hunt" class="fa fa-fw fa-product-hunt"></label>
    <input type="radio" name="<?php echo $key.'"'.$required ?> <?php if ($item['value']=='ra'):?>checked<?php endif?> value="ra" id="ra" /><label for="ra" class="fa fa-fw fa-ra"></label>
    <input type="radio" name="<?php echo $key.'"'.$required ?> <?php if ($item['value']=='reddit'):?>checked<?php endif?> value="reddit" id="reddit" /><label for="reddit" class="fa fa-fw fa-reddit"></label>
    <input type="radio" name="<?php echo $key.'"'.$required ?> <?php if ($item['value']=='reddit-alien'):?>checked<?php endif?> value="reddit-alien" id="reddit-alien" /><label for="reddit-alien" class="fa fa-fw fa-reddit-alien"></label>
    <input type="radio" name="<?php echo $key.'"'.$required ?> <?php if ($item['value']=='reddit-square'):?>checked<?php endif?> value="reddit-square" id="reddit-square" /><label for="reddit-square" class="fa fa-fw fa-reddit-square"></label>
    <input type="radio" name="<?php echo $key.'"'.$required ?> <?php if ($item['value']=='sellsy'):?>checked<?php endif?> value="sellsy" id="sellsy" /><label for="sellsy" class="fa fa-fw fa-sellsy"></label>
    <input type="radio" name="<?php echo $key.'"'.$required ?> <?php if ($item['value']=='share-alt'):?>checked<?php endif?> value="share-alt" id="share-alt" /><label for="share-alt" class="fa fa-fw fa-share-alt"></label>
    <input type="radio" name="<?php echo $key.'"'.$required ?> <?php if ($item['value']=='share-alt-square'):?>checked<?php endif?> value="share-alt-square" id="share-alt-square" /><label for="share-alt-square" class="fa fa-fw fa-share-alt-square"></label>
    <input type="radio" name="<?php echo $key.'"'.$required ?> <?php if ($item['value']=='shirtsinbulk'):?>checked<?php endif?> value="shirtsinbulk" id="shirtsinbulk" /><label for="shirtsinbulk" class="fa fa-fw fa-shirtsinbulk"></label>
    <input type="radio" name="<?php echo $key.'"'.$required ?> <?php if ($item['value']=='simplybuilt'):?>checked<?php endif?> value="simplybuilt" id="simplybuilt" /><label for="simplybuilt" class="fa fa-fw fa-simplybuilt"></label>
    <input type="radio" name="<?php echo $key.'"'.$required ?> <?php if ($item['value']=='skyatlas'):?>checked<?php endif?> value="skyatlas" id="skyatlas" /><label for="skyatlas" class="fa fa-fw fa-skyatlas"></label>
    <input type="radio" name="<?php echo $key.'"'.$required ?> <?php if ($item['value']=='slack'):?>checked<?php endif?> value="slack" id="slack" /><label for="slack" class="fa fa-fw fa-slack"></label>
    <input type="radio" name="<?php echo $key.'"'.$required ?> <?php if ($item['value']=='snapchat'):?>checked<?php endif?> value="snapchat" id="snapchat" /><label for="snapchat" class="fa fa-fw fa-snapchat"></label>
    <input type="radio" name="<?php echo $key.'"'.$required ?> <?php if ($item['value']=='spotify'):?>checked<?php endif?> value="spotify" id="spotify" /><label for="spotify" class="fa fa-fw fa-spotify"></label>
    <input type="radio" name="<?php echo $key.'"'.$required ?> <?php if ($item['value']=='steam'):?>checked<?php endif?> value="steam" id="steam" /><label for="steam" class="fa fa-fw fa-steam"></label>
    <input type="radio" name="<?php echo $key.'"'.$required ?> <?php if ($item['value']=='tencent-weibo'):?>checked<?php endif?> value="tencent-weibo" id="tencent-weibo" /><label for="tencent-weibo" class="fa fa-fw fa-tencent-weibo"></label>
    <input type="radio" name="<?php echo $key.'"'.$required ?> <?php if ($item['value']=='tripadvisor'):?>checked<?php endif?> value="tripadvisor" id="tripadvisor" /><label for="tripadvisor" class="fa fa-fw fa-tripadvisor"></label>
    <input type="radio" name="<?php echo $key.'"'.$required ?> <?php if ($item['value']=='twitch'):?>checked<?php endif?> value="twitch" id="twitch" /><label for="twitch" class="fa fa-fw fa-twitch"></label>
    <input type="radio" name="<?php echo $key.'"'.$required ?> <?php if ($item['value']=='viacoin'):?>checked<?php endif?> value="viacoin" id="viacoin" /><label for="viacoin" class="fa fa-fw fa-viacoin"></label>
    <input type="radio" name="<?php echo $key.'"'.$required ?> <?php if ($item['value']=='vimeo'):?>checked<?php endif?> value="vimeo" id="vimeo" /><label for="vimeo" class="fa fa-fw fa-vimeo"></label>
    <input type="radio" name="<?php echo $key.'"'.$required ?> <?php if ($item['value']=='whatsapp'):?>checked<?php endif?> value="whatsapp" id="whatsapp" /><label for="whatsapp" class="fa fa-fw fa-whatsapp"></label>
    <input type="radio" name="<?php echo $key.'"'.$required ?> <?php if ($item['value']=='wpbeginner'):?>checked<?php endif?> value="wpbeginner" id="wpbeginner" /><label for="wpbeginner" class="fa fa-fw fa-wpbeginner"></label>
    <input type="radio" name="<?php echo $key.'"'.$required ?> <?php if ($item['value']=='wpforms'):?>checked<?php endif?> value="wpforms" id="wpforms" /><label for="wpforms" class="fa fa-fw fa-wpforms"></label>
    <input type="radio" name="<?php echo $key.'"'.$required ?> <?php if ($item['value']=='xing'):?>checked<?php endif?> value="xing" id="xing" /><label for="xing" class="fa fa-fw fa-xing"></label>
    <input type="radio" name="<?php echo $key.'"'.$required ?> <?php if ($item['value']=='yelp'):?>checked<?php endif?> value="yelp" id="yelp" /><label for="yelp" class="fa fa-fw fa-yelp"></label>
    <input type="radio" name="<?php echo $key.'"'.$required ?> <?php if ($item['value']=='yoast'):?>checked<?php endif?> value="yoast" id="yoast" /><label for="yoast" class="fa fa-fw fa-yoast"></label>
    <input type="radio" name="<?php echo $key.'"'.$required ?> <?php if ($item['value']=='youtube'):?>checked<?php endif?> value="youtube" id="youtube" /><label for="youtube" class="fa fa-fw fa-youtube"></label>
</div>