<div class="input-box">
    <label for="password" class="control-label"><?php echo $this->translate('Password') ?></label>
    <div class="cell">
        <input type="password" name="password" id="password" class="form-control" minlength="6" />
    </div>
</div>
<div class="input-box">
    <label for="password" class="control-label"></label>
    <div class="cell">
        <input type="checkbox" name="generate_password" id="generate-password" value="1" />
        <label for="generate-password"><?php echo $this->translate('Generate Password') ?></label>
    </div>
</div>
