<?php
$attributes = $this->getVariable('attributes');
$count = count($attributes);
$query = $this->getQuery();
?>
<div class="grid">
    <table class="table table-hover table-striped table-no-border">
        <thead class="sort-by">
            <tr>
                <th class="checkbox"><input type="checkbox" /></th>
                <?php foreach ($attributes as $attr => $name): ?>
                    <th>
                        <?php echo $this->translate($name['label'], [], $this->getTranslateDomain()) ?>
                    </th>
                <?php endforeach ?>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->getVariable('collection') as $item) : ?>
                <tr>
                    <td class="text-center checkbox"><input type="checkbox" name="id[]" value="<?php echo $item['id'] ?>" /></td>
                    <?php foreach ($attributes as $attr => $name): ?>
                        <td<?php if (isset($name['class'])): ?> class="<?php echo $name['class'] ?>"<?php endif ?>>
                            <?php echo is_array($item[$attr]) ? implode(',', $item[$attr]) : $this->translate(isset($name['options'][$item[$attr]]) ? $name['options'][$item[$attr]] : $item[$attr], [], $this->getTranslateDomain()) ?>
                        </td>
                    <?php endforeach ?>
                </tr>
            <?php endforeach ?>
        </tbody>
        <tfoot>
            <tr>
                <td colspan="<?php echo $count + 1 ?>" class="text-right">
                    <?php echo $this->pager->setCollection($this->getVariable('collection')) ?>
                </td>
            </tr>
        </tfoot>
    </table>
</div>
