<?php
$filters = $this->getFilters();
$current = $this->getCurrentFilters();
?>
 	
<table class="filters goods-filter table">
    <?php foreach ($filters as $key => $filter): ?>
        <tr class="goods-filter-tr">
            <th class="goods-filter-th"><?php echo $filter['label'] ?></th>
            <td class="goods-filter-td">            
                <ul class="list-inline goods-filter-ul">
                    <li class="goods-li-all">
                        <a href="<?php echo $this->getInitFilterUrl($key) ?>">
                        	<?php echo $this->translate('All')?>
                   		</a>
                    </li>
                    <?php foreach ($filter['values'] as $value => $values): ?>
                        <li class="goods-filter-li">
                            <a href="<?php echo $this->getFilterUrl($key, $value) ?>">
                                <span><?php echo $values['label'] ?></span>
                                <?php if ($this->showCount()): ?>
                                    <span class="count"><?php echo $values['count'] ?></span>
                                <?php endif ?>
                            </a>
                        </li>
                    <?php endforeach ?>                    
                </ul>
            </td>
            <td class="goods-filter-more">
                <a href="javascript:;">
                	<?php echo $this->translate('More')?>
           		</a>
            </td>
        </tr>
    <?php endforeach ?>
</table>