<?php
$attributes = json_decode($this->getProduct()->offsetGet('additional'), true);
if ($attributes):
    ?>
    <ul class="product-attributes clearfix">
        <?php
        foreach ($attributes as $key => $value):
            if ($key !== '' && $value !== ''):
                ?>
                <li class="col-xs-4 col-sm-6 col-md-4">
                    <span class="label"><?php echo $key ?>:</span>
                    <span class="value" title="<?php echo $value ?>"><?php echo $value ?></span>
                </li>
                <?php
            endif;
        endforeach;
        ?>
    </ul>
<?php endif; ?>
