<?php
$products = $this->getProducts();
if (count($products)):
    ?>
    <?php if ($this->getVariable('title')): ?>
        <h4 class="title">
            <span><?php echo $this->translate($this->getVariable('title')) ?></span>
        </h4>
    <?php endif ?>
    <div class="carousel slide product-link" id="carousel-example-generic" data-ride="carousel" data-interval="false">
        <div class="products-grid carousel-inner clearfix"  role="listbox">
            <?php
            $class = $this->getVariable('class', 'col-xs-4 col-sm-4 col-md-3 col-lg-2');
            $width = $this->getVariable('width');
            foreach ($products as $product):
                $thumbnail = $product->getThumbnail();         
                ?>
            <ul class="  active">
                <li class="item <?php echo $class;?>">
                        <a href="<?php echo $product->getUrl() ?>" title="<?php echo $product['name'] ?>" class="product-image">
                            <?php
                            if (strpos($thumbnail, 'http') !== false):
                                ?>
                                <img src="<?php echo $thumbnail ?>" alt="<?php echo $product['name'] ?>" />
                            <?php elseif ($width): ?>
                                <img class="bttrlazyloading"<?php foreach ($width as $key => $value): ?> data-bttrlazyloading-<?php echo $key ?>-src="<?php echo $this->getBaseUrl('pub/resource/image/resized/' . $value . 'x/' . $thumbnail) ?>"<?php endforeach ?> alt="<?php echo $product['name'] ?>" />
                            <?php else: ?>
                                <img src="<?php echo $this->getBaseUrl('pub/resource/image/resized/131x/' . $thumbnail) ?>" alt="<?php echo $product['name'] ?>" />
                            <?php endif ?>
                        </a>
                        <p><?php echo $product['name'] ?></p>
                        <div class="price-box">
                            <?php echo $this->getPriceBox($product) ?>
                        </div>
                        <div class="action">
                            <a href="<?php
                            echo $this->getBaseUrl('checkout/cart/add/?product_id=' . $product['id'] .
                                    '&qty=1&csrf=' . $this->getCsrfKey())
                            ?>" class="add2cart">
                            </a>
                        </div>
                    </li>   
                </ul>
            <?php        
            endforeach;
            ?>
        </div>
        <ol class="carousel-indicators">
            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
            <li data-target="#carousel-example-generic" data-slide-to="1"></li>
            <li data-target="#carousel-example-generic" data-slide-to="2"></li>
        </ol>
    </div>
    <?php
else:
    return false;
    ?>
<?php endif; ?>
