<?php
$product = $this->getVariable('product');
$images = $product->offsetGet('images');
$default = (int) $product->offsetGet('default_image');
?>
<div id="product-media" class="carousel slide" data-ride="carousel" data-interval="false">
    <?php if (count($images)): ?>
        <ol class="carousel-indicators">
            <?php
            foreach ($images as $key => $image):
                ?>
                <li data-target="#product-media" data-slide-to="<?php echo $key ?>"<?php if (!$default || (int) $image['id'] === $default): ?> class="active"<?php $default = true;endif;?>>
                    <img src="<?php echo $this->getBaseUrl('pub/resource/image/resized/45x/'), $image['src'] ?>" width="45" alt="" data-label="<?php echo $image['label'] ?>" data-group="<?php echo $image['group'] ?>" />
                </li>
    <?php endforeach ?>
        </ol>
        <div class="carousel-inner" role="listbox">
            <?php
            $default = (int) $product->offsetGet('default_image');
            foreach ($images as $key => $image):
                ?>
                <div class="item<?php if (!$default || (int) $image['id'] === $default): ?> active<?php $default = true; endif; ?>">
                    <img class="bttrlazyloading magnifying" data-bttrlazyloading-xs-src="<?php
                    echo $this->getBaseUrl('pub/resource/image/resized/345x/'),
                    $image['src']
                    ?>" data-bttrlazyloading-md-src="<?php
                         echo $this->getBaseUrl('pub/resource/image/resized/278x/'),
                         $image['src']
                         ?>" data-bttrlazyloading-sm-src="<?php
                         echo $this->getBaseUrl('pub/resource/image/resized/205x/'),
                         $image['src']
                         ?>" data-bttrlazyloading-lg-src="<?php
                         echo $this->getBaseUrl('pub/resource/image/resized/704x/'),
                         $image['src']
                         ?>" alt="<?php echo $product->offsetGet('name') ?>">
                </div>
        <?php endforeach ?>
        </div>
<?php else: ?>
        <div class="carousel-inner" role="listbox">
            <div class="item active">
                <img src="<?php echo $this->getPubUrl('frontend/images/placeholder.png') ?>" 
                     width="345" height="448" alt="<?php echo $product->offsetGet('name') ?>" />
            </div>
        </div>
<?php endif ?>
</div>