<?php
$reviews = $this->getProduct()->getReviews();
$customer = $this->getProduct()->getCustomerID();
if ($reviews):
    ?>
    <div class="">
        <?php echo $this->translate('Review') ?>
        <div class="content-box">
                <div class="subject-li">&nbsp;</div>
                <div class="content-li">&nbsp;</div>
            </div>
            <?php foreach ($reviews as $review){ ?>
            	<?php if (!is_null($review['order_id'])):?>
                    <div class="content-box">
                    <?php if (isset($review['title'][0])){
                        ?>
                        <div class="subject-li"><?php echo $review['username'].':&nbsp;&nbsp;'.$this->translate('Rating').':' ?>
                        <?php 
                            foreach ($review['title'] as $key=>$item){
                                 echo $item,$review['value'][$key];
                            }
                        ?>
                        </div>
                        <div class="content-li"><?php echo $review['content'][0] ?></div>
                    <?php 
                    }else { ?>
                        <div class="subject-li"><?php echo $review['username'].':';echo $review['value'] ? $this->translate('Rating').$review['title'].$review['value'] : ''; ?></div>
                        <div class="content-li"><?php echo $review['content'] ?></div>
                    <?php }?>
                    </div>
                <?php endif ?>
            <?php } ?>
            <div class="content-box">
                <div class="subject-li">&nbsp;</div>
                <div class="content-li">&nbsp;</div>
            </div>
        <?php echo $this->translate('Discussion') ?>
        <div class="content-box">
                <div class="subject-li">&nbsp;</div>
                <div class="content-li">&nbsp;</div>
            </div>
        	<?php foreach ($reviews as $review): ?>
        		<?php if (is_null($review['order_id'])):?>
                    <div class="content-box">
                        <div class="subject-li"><?php echo $review['username'] ? $review['username'] : $this->translate('Visitor') ?>:</div>
                        <div class="content-li"><?php echo $review['content'] ?></div>
                    </div>
                <?php endif ?>
            <?php endforeach ?>
    </div>
<?php endif; ?>
<?php if ($this->getConfig()['catalog/review/allow_guests'] || $customer):?>
    <div class="review-form">
        <span><br /><?php echo $this->translate('Discussion') ?>:</span>
    	<div class="review-padding">
        	<form action="<?php echo $this->getBaseUrl('catalog/review/save') ?>" method="post">
        		<p><?php echo $this->translate('Subject') ?>：<input type="text" name="subject" /></p>
        		<p><?php echo $this->translate('Content') ?>：<textarea rows="4" name="content" ></textarea></p>
        		<input type="hidden" name="product_id" value="<?php echo $this->getProduct()->getId() ?>" />
        		<input type="hidden" name="customer_id" value="<?php echo $this->getProduct()->getCustomerID() ?>" />
        		<button class="btn" type="submit" ><?php echo $this->translate('Submit') ?></button>
        	</form>
    	</div>
    </div>
<?php endif ?>