<?php
$medias = $this->getMedia();
?>
<ul class="col-xs-6 col-sm-6 links list-inline">
    <?php if ($medias): ?>
        <li class="dropdown share">
            <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown">
                <span class="fa fa-share-alt" aria-hidden="true"></span><?php echo $this->translate('Share'); ?>
            </a>
            <ul class="dropdown-menu">
                <?php foreach ($medias as $media): ?>
                    <li>
                        <a href="<?php echo $this->getLink($media['link']) ?>" class="<?php echo $media['label'] ?>" rel="nofollow">
                            <span class="fa fa-fw fa-<?php echo $media['icon'] ?>"></span>
                            <span><?php echo $this->translate('Share to '), $this->translate($media['label']) ?></span>
                        </a>
                    </li>
                <?php endforeach ?>
            </ul>
        </li>
    <?php endif ?>
</ul>