<?php
$collection = $this->getVariable('collection');
$product = $this->getProduct();
$images = $product->offsetGet('images');
$warehouse = new Seahinet\Catalog\Model\Warehouse;
$warehouse->load(1);
$inventory = $warehouse->getInventory($product->getId(), $product['sku']);
$store = $product->getStore();
$retailer = new Seahinet\Retailer\Model\Retailer;
$retailer->load($store->getId(), 'store_id');
$SDview = new Seahinet\Retailer\ViewModel\StoreDecoration;
$decorations = $SDview->getProductDetailTemplateView($store->getId());
?>
<div class="container prodcut-box">
    <form action="<?php echo $this->getBaseUrl('checkout/cart/add/') ?>" method="post" enctype="multipart/form-data">
        <input type="hidden" name="csrf" value="<?php echo $this->getCsrfKey() ?>" />
        <input type="hidden" name="product_id" value="<?php echo $product->getId() ?>" />
        <input type="hidden" name="warehouse_id" value="<?php echo 1 ?>" />
        <div class="product-essential clearfix" id="product">
            <div class="col-xs-12 col-sm-6 col-md-6">
                <?php echo $this->getChild('media')->setVariable('product', $product) ?>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-6 product-info product-info-bg">
                <h2 class="product-name details"><?php echo $product['name'] ?></h2>
                <div class="clearfix col-xs-12 price-box">
                    <div class="col-xs-6 col-sm-6">
                        <?php echo $this->getPriceBox() ?>
                    </div>
                    <?php echo $this->getChild('share') ?>
                </div>
                <div class="hidden-lg selected">
                    <a type="button" data-info="{}" data-toggle="modal" data-target="#modal-color-size" data-type="add">
                        <?php echo $this->translate('Please select the color size') ?>
                        <span class="fa fa-chevron-down" aria-hidden="true"></span>
                    </a>
                </div>
                <div class="modal fade" id="modal-color-size">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                                <div class=""></div>
                            </div>
                            <div class="modal-body">
                                <div class="col-xs-12 options">
                                    <?php echo $this->getChild('option')->setVariable('product', $product) ?>
                                    <div class="input-box">
                                        <label for="qty" class="control-label" style="line-height:28px;margin-right:5px"><?php echo $this->translate('Qty') ?></label>
                                        <div class="cell qty display-inline-block">
                                            <label for="qty" class="spin minus">-</label>
                                            <input id="qty" class="form-control required" value="<?php echo (float) $inventory['min_qty'] ?>" min="<?php echo (float) $inventory['min_qty'] ?>" max="<?php echo min((float) $inventory['max_qty'], (float) $inventory['qty']) ?>" step="<?php echo (float) $inventory['increment'] ?>" name="qty" type="number" />
                                            <label for="qty" class="spin plus">+</label>
                                        </div>
                                    </div>
                                </div>
                                <script>
                                    new Locate();
                                </script>
                            </div>
                            <div class="modal-footer">
                                <div class="clearfix action">
                                    <button type="submit" formaction="<?php echo $this->getBaseUrl('customer/wishlist/add/') ?>" class="btn"><?php echo $this->translate('Add to Wishlist') ?></button>
                                    <button type="submit" class="btn"><?php echo $this->translate('Buy Now') ?></button>
                                    <button type="submit" class="btn btn-checkout" style="float:left">
                                        <span class="fa fa-shopping-cart" aria-hidden="true"></span>
                                        <span><?php echo $this->translate('Add to Cart') ?></span>
                                    </button>
                                </div> 
                            </div>
                        </div>
                    </div>
                </div>
                <div class="distribution">
                    <div class="distr_ft padding-15">
                        <span class="font-13 padding-15" ><?php echo $this->translate('Distribution') ?></span><span class="padding-10"><?php echo $this->translate('Qingdao, Shandong') ?></span><?php echo $this->translate('To') ?><span class="padding-10"><?php echo $this->translate('Qingdao, Shandong') ?></span><span class="padding-15"><?php echo $this->translate('Express delivery') ?>&nbsp;&nbsp;10<?php echo $this->translate('yuan') ?></span>
                        <p class="padding-15 padding-4"><?php echo $this->translate('New store opening, a lot of concessions, each single order over 300 yuan, the package of mail') ?></p>
                    </div>
                </div> 
                <div class="shop">
                    <div class="shop_cont">
                        <ul class="shop_ul">
                            <li class="shop_icon"><img alt="" src="<?php echo $this->getPubUrl('frontend/images/placeholder.png') ?>" height="35" width="120"></li>
                            <li class="shop_name">
                                <span class="font-color-0 font-13"><a href="<?php echo $this->getBaseUrl($retailer->getStoreUrl()); ?>"><?php echo $store['name'] ?></a></span>
                                <div class="font-12 font-family-x">
                                    <span>新店开张</span><span>满300元减50元</span>
                                </div>
                            </li>
                        </ul>
                        <div class="shop_state font-12 text-center ">
                            <span><?php echo $this->translate('Product evaluation') ?> 9.57<i class="fa fa-arrow-up font-color-orange" aria-hidden="true"></i></span>
                            <span><?php echo $this->translate('Service attitude') ?>  9.55<i class="fa fa-arrow-up font-color-orange" aria-hidden="true"></i></span>
                            <span><?php echo $this->translate('Logistics speed') ?>  9.57<i class="fa fa-arrow-up font-color-orange" aria-hidden="true"></i></span>
                        </div>
                        <div class="shop_link font-12 text-center ">
                            <a href="<?php echo $this->getBaseUrl($retailer->getStoreUrl()); ?>" class="store_entry"><span class="fa fa-home" aria-hidden="true"></span>&nbsp;<?php echo $this->translate('Store Entry'); ?></a>	
                        </div>
                    </div>
                </div> 
            </div>
            <div class="col-xs-12 col-sm-12 product-store">
                <ul class="col-xs-12 col-sm-12">
                    <li class="col-xs-2 col-sm-2">
                        <a href=""><span class="fa fa-qq"></span><?php echo $this->translate('Custom Service'); ?></a>
                    </li>
                    <li class="col-xs-2 col-sm-2">
                        <a href="#modal-color-size" data-toggle="modal"><span class="fa fa-star"></span><?php echo $this->translate('Wishlist'); ?></a>
                    </li>
                    <li class="col-xs-2 col-sm-2">
                        <a href="<?php echo $this->getBaseUrl('checkout/cart/') ?>"> <span class="fa fa-shopping-cart"></span><?php echo $this->translate('Cart'); ?></a>
                    </li>
                    <li class="col-xs-3 col-sm-3">
                        <button type="button" class="btn" data-info="{}" data-toggle="modal" data-target="#modal-color-size" data-type="add"><?php echo $this->translate('Buy Now') ?></button>
                    </li>
                    <li class="col-xs-3 col-sm-3">
                        <button type="button" class="btn btn-checkout" data-info="{}" data-toggle="modal" data-target="#modal-color-size" data-type="add"><?php echo $this->translate('Add to Cart') ?></button>
                    </li>
                </ul>
            </div>
        </div>        
    </form>
    <div class="col-xs-12 col-sm-12 related clearfix">
        <?php
        echo $this->getChild('related')
                ->setVariable('product', $product)
                ->setVariable('title', 'Featured Products')
                ->setLimit(3)
                ->setVariable('width', [
                    'xs' => '100', '115', '128',
                    'sm' => '240',
                    'md' => '240',
                    'lg' => '173',
                ])
        ?>
    </div>
    <div class="product-detail clearfix" id="myAffix">
        <div class="col-xs-12 col-sm-12 info" data-spy="affix" data-offset-top="718" data-offset-bottom="200">
            <a href="javascript:viod(0);" onclick="javascript:history.back(-1);" class="fa fa-angle-left fa-3x text-right col-xs-1 col-sm-1"></a>
            <div class="content-list col-xs-10 col-sm-10 text-center">
                <ul class="nav nav-tabs font-13" role="tablist">
                    <li class="col-xs-4 col-sm-4" role="presentation"><a href="#product" aria-controls="product" role="tab" data-toggle="tab"><?php echo $this->translate('Product'); ?></a></li>
                    <li class="col-xs-4 col-sm-4" role="presentation"><a href="#description" aria-controls="description" role="tab" data-toggle="tab"><?php echo $this->translate('Description') ?></a></li>
                    <li class="col-xs-4 col-sm-4" role="presentation"><a href="#review" aria-controls="review" role="tab" data-toggle="tab"><?php echo $this->translate('Review(s)') ?></a></li>
                </ul>
            </div>
            <a href="javascript:viod(0);" class="fa fa-bars fa-2x text-left col-xs-1 col-sm-1"></a>
        </div>
        <div class="tab-content">
            <div role="tabpanel" class="tab-pane active" id="description">
                <?php echo $this->getChild('attribute'), $product->offsetGet('description') ?>
            </div>
            <div role="tabpanel" class="tab-pane padding-10" id="review"></div>
        </div>
    </div>
</div>
