<?php
$attributes = json_decode($this->getProduct()->offsetGet('additional'), true);
if ($attributes):
    ?>
    <ul class="unstyled inline blog-tags span12">
        <?php
        foreach ($attributes as $key => $value):
            if ($key !== '' && $value !== ''):
                ?>
                <li class="span6">
                    <span class="label"><?php echo $key ?></span>
                    <span class="value" title="<?php echo $value ?>"><?php echo $value ?></span>
                </li>
                <?php
            endif;
        endforeach;
        ?>
    </ul>
<?php endif; ?>
