<?php
$products = $this->getProducts();

if (count($products)):
    ?>
    <div class="product-link">
        <?php if ($this->getVariable('title')): ?>
            <h4 class="title">
                <span><?php echo $this->translate($this->getVariable('title')) ?></span>
            </h4>
        <?php endif ?>
        <ul class="products-grid clearfix">
            <?php
            $class = $this->getVariable('class', 'col-xs-6 col-sm-4 col-md-3 col-lg-2');
            $width = $this->getVariable('width');
            foreach ($products as $product):
                $thumbnail = $product->getThumbnail();
                ?>
                <li class="item <?php echo $class ?>">
                    <a href="<?php echo $product->getUrl() ?>" title="<?php echo $product['name'] ?>" class="product-image">
                        <?php
                        if (strpos($thumbnail, '//') !== false):
                            ?>
                            <img src="<?php echo $thumbnail ?>" alt="<?php echo $product['name'] ?>" />
                        <?php elseif ($width): ?>
                            <img class="bttrlazyloading"<?php foreach ($width as $key => $value): ?> data-bttrlazyloading-<?php echo $key ?>-src="<?php echo $this->getResourceUrl('image/resized/' . $value . 'x/' . $thumbnail) ?>"<?php endforeach ?> alt="<?php echo $product['name'] ?>" />
                        <?php else: ?>
                            <img src="<?php echo $this->getResourceUrl('image/resized/131x/' . $thumbnail) ?>" alt="<?php echo $product['name'] ?>" />
                        <?php endif ?>
                    </a>
                    <div class="price-box">
                        <?php echo $this->getPriceBox($product) ?>
                    </div>
                    <div class="action">
                        <a href="<?php
                        echo $this->getBaseUrl('checkout/cart/add/?product_id=' . $product['id'] .
                                '&qty=1&csrf=' . $this->getCsrfKey())
                        ?>" class="add2cart">
                        </a>
                    </div>
                </li>
            <?php endforeach ?>
        </ul>
    </div>
<?php
else:
    return false;
    ?>
<?php endif; ?>
<!-- Recent Works -->
<div class="headline"><h3>Recent Works</h3></div>
<div class="row-fluid margin-bottom-40">
    <ul id="list" class="bxslider recent-work">
        <li>
            <a href="#">
                <em class="overflow-hidden"><img src="assets/img/carousel/2.jpg" alt="" /></em>
                <span>
                    <strong>Happy New Year</strong>
                    <i>Anim pariatur cliche reprehenderit</i>
                </span>
            </a>
        </li>
        <li>
            <a href="#">
                <em class="overflow-hidden"><img src="assets/img/carousel/9.jpg" alt="" /></em>
                <span>
                    <strong>Award Winning Agency</strong>
                    <i>Responsive Bootstrap Template</i>
                </span>
            </a>
        </li>
        <li>
            <a href="#">
                <em class="overflow-hidden"><img src="assets/img/carousel/4.jpg" alt="" /></em>
                <span>
                    <strong>Wolf Moon Officia</strong>
                    <i>Pariatur prehe cliche reprehrit</i>
                </span>
            </a>
        </li>
        <li>
            <a href="#">
                <em class="overflow-hidden"><img src="assets/img/carousel/5.jpg" alt="" /></em>
                <span>
                    <strong>Food Truck Quinoa Nesciunt</strong>
                    <i>Craft labore wes anderson cred</i>
                </span>
            </a>
        </li>
        <li>
            <a href="#">
                <em class="overflow-hidden"><img src="assets/img/carousel/6.jpg" alt="" /></em>
                <span>
                    <strong>Happy New Year</strong>
                    <i>Anim pariatur cliche reprehenderit</i>
                </span>
            </a>
        </li>
        <li>
            <a href="#">
                <em class="overflow-hidden"><img src="assets/img/carousel/7.jpg" alt="" /></em>
                <span>
                    <strong>Award Winning Agency</strong>
                    <i>Responsive Bootstrap Template</i>
                </span>
            </a>
        </li>
        <li>
            <a href="#">
                <em class="overflow-hidden"><img src="assets/img/carousel/8.jpg" alt="" /></em>
                <span>
                    <strong>Wolf Moon Officia</strong>
                    <i>Pariatur prehe cliche reprehrit</i>
                </span>
            </a>
        </li>
        <li>
            <a href="#">
                <em class="overflow-hidden"><img src="assets/img/carousel/9.jpg" alt="" /></em>
                <span>
                    <strong>Food Truck Quinoa Nesciunt</strong>
                    <i>Craft labore wes anderson cred</i>
                </span>
            </a>
        </li>
    </ul>        
</div><!--/row-->
<!-- //End Recent Works -->