<?php
$collection = $this->getVariable('collection');
$product = $this->getProduct();
$images = $product->offsetGet('images');
?>
<!--
<div class="container">
    <div class="product-essential clearfix">
        <h2 class="product-name"><?php echo $product['name'] ?></h2>
        <div class="col-xs-12 col-md-2 upsells">
<?php
echo $this->getChild('upsells')
        ->setVariable('product', $product)
        ->setLimit(3)
        ->setVariable('class', 'col-xs-4 col-md-12')
        ->setVariable('width', [
            'xs' => '219',
            'sm' => '228',
            'md' => '104',
            'lg' => '137',
        ])
?>
        </div>
        <div class="related">
<?php
echo $this->getChild('related')
        ->setVariable('product', $product)
        ->setVariable('title', 'Featured Products')
        ->setLimit(6)
        ->setVariable('width', [
            'xs' => '362',
            'sm' => '228',
            'md' => '221',
            'lg' => '173',
        ])
?>
        </div>
    </div>
    <div class="product-detail">
        <ul class="nav nav-tabs" role="tablist">
            <li role="presentation" class="active"><a href="#description" aria-controls="description" role="tab" data-toggle="tab"><?php echo $this->translate('Description') ?></a></li>
            <li role="presentation"><a href="#review" aria-controls="review" role="tab" data-toggle="tab"><?php echo $this->translate('Review(s)') ?></a></li>
        </ul>
        <div class="tab-content">
            <div role="tabpanel" class="tab-pane active" id="description">
<?php echo $this->getChild('attribute'), $product->offsetGet('description') ?>
            </div>
            <div role="tabpanel" class="tab-pane" id="review"></div>
        </div>
    </div>
</div>-->
<!--=== Content Part ===-->
<div class="container">		
    <div class="row-fluid blog-page blog-item">
        <!-- Left Sidebar -->
        <div class="span9">
            <div class="blog margin-bottom-30">
                <h3><?php echo $product['name'] ?></h3>
                <ul class="unstyled inline blog-info">
                    <li><i class="icon-calendar"></i><?php echo date('F, j, Y', strtotime($product['created_at'])); ?></li>
                    <li><i class="icon-pencil"></i><?php echo $product['author']; ?></li>
                    <li><i class="icon-comments"></i> <a href="#">24 Comments</a></li>
                </ul>
                <ul class="unstyled inline blog-tags span8">
                    <li>
                        <i class="icon-tags"></i> 
                        <a href="#">Technology</a> 
                        <a href="#">Education</a>
                        <a href="#">Internet</a>
                        <a href="#">Media</a>
                    </li>
                </ul>
                <ul class="unstyled inline blog-twitter text-right span4">
                    <?php echo $this->getChild('share') ?>
                </ul>
                <div class="section-cotent" id="description">
                    <?php echo $this->getChild('attribute'), $product->offsetGet('description') ?>
                    <div class="blog-img"><img src="<?php echo $this->getPubUrl('frontend/img/posts/1.jpg') ?>" alt="" /></div>
                    <p>At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut non libero consectetur adipiscing elit magna. Sed et quam lacus. Fusce condimentum eleifend enim a feugiat. Pellentesque viverra vehicula sem ut volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut non libero magna. Sed et quam lacus. Fusce condimentum eleifend enim a feugiat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut non libero magna. Sed et quam lacus. Fusce condimentum eleifend enim a feugiat.</p>
                    <blockquote class="hero">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit posuere erat a ante.</p>
                        <small>Someone famous <cite title="Source Title">Source Title</cite></small>
                    </blockquote>
                    <p>Accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias feugiat. Pellentesque viverra vehicula sem ut volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut non libero magna. Sed et quam lacus. Fusce condimentum eleifend enim a feugiat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut non libero magna. Sed et quam lacus. Fusce condimentum eleifend enim a feugiat.</p>
                </div>
            </div><!--/blog-->
            <hr />
            <!-- Media -->
            <div class="media" id="review">
                <h3 class="color-green">Comments</h3>
                <a class="pull-left" href="#">
                    <img class="media-object" src="<?php echo $this->getPubUrl('frontend/img/sliders/elastislide/2.jpg') ?>" alt="" />
                </a>
                <div class="media-body">
                    <h4 class="media-heading">Media heading <span>5 hours ago / <a href="#">Reply</a></span></h4>
                    <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>

                    <hr />

                    <!-- Nested media object -->
                    <div class="media">
                        <a class="pull-left" href="#">
                            <img class="media-object" src="<?php echo $this->getPubUrl('frontend/img/sliders/elastislide/5.jpg') ?>" alt="" />
                        </a>
                        <div class="media-body">
                            <h4 class="media-heading">Media heading <span>17 hours ago / <a href="#">Reply</a></span></h4>
                            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
                        </div>
                    </div><!--/media-->

                    <hr />

                    <div class="media">
                        <a class="pull-left" href="#">
                            <img class="media-object" src="<?php echo $this->getPubUrl('frontend/img/sliders/elastislide/11.jpg') ?>" alt="" />
                        </a>
                        <div class="media-body">
                            <h4 class="media-heading">Media heading <span>2 days ago / <a href="#">Reply</a></span></h4>
                            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
                        </div>
                    </div><!--/media-->
                </div>
            </div><!--/media-->

            <div class="media">
                <a class="pull-left" href="#">
                    <img class="media-object" src="<?php echo $this->getPubUrl('frontend/img/sliders/elastislide/9.jpg') ?>" alt="" />
                </a>
                <div class="media-body">
                    <h4 class="media-heading">Media heading <span>July 5,2013 / <a href="#">Reply</a></span></h4>
                    <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
                </div>
            </div><!--/media-->

            <hr />

            <!-- Leave a Comment -->
            <div class="post-comment">
                <h3 class="color-green">Leave a Comment</h3>
                <form />
                <label>Name</label>
                <input type="text" class="span7" />
                <label>Email <span class="color-red">*</span></label>
                <input type="text" class="span7" />
                <label>Message</label>
                <textarea rows="8" class="span10"></textarea>
                <p><button type="submit" class="btn-u">Send Message</button></p>
                </form>
            </div><!--/post-comment-->
        </div><!--/span9-->

        <!-- Right Sidebar -->
        <div class="span3">
            <!-- Photo Stream -->
            <div class="headline"><h3>Photo Stream</h3></div>
            <ul class="unstyled blog-ads">
                <li><a href="#"><img src="<?php echo $this->getPubUrl('frontend/img/sliders/elastislide/5.jpg') ?>" alt="" class="hover-effect" /></a></li>
                <li><a href="#"><img src="<?php echo $this->getPubUrl('frontend/img/sliders/elastislide/6.jpg') ?>" alt="" class="hover-effect" /></a></li>
                <li><a href="#"><img src="<?php echo $this->getPubUrl('frontend/img/sliders/elastislide/8.jpg') ?>" alt="" class="hover-effect" /></a></li>
                <li><a href="#"><img src="<?php echo $this->getPubUrl('frontend/img/sliders/elastislide/10.jpg') ?>" alt="" class="hover-effect" /></a></li>
                <li><a href="#"><img src="<?php echo $this->getPubUrl('frontend/img/sliders/elastislide/11.jpg') ?>" alt="" class="hover-effect" /></a></li>
                <li><a href="#"><img src="<?php echo $this->getPubUrl('frontend/img/sliders/elastislide/1.jpg') ?>" alt="" class="hover-effect" /></a></li>
                <li><a href="#"><img src="<?php echo $this->getPubUrl('frontend/img/sliders/elastislide/2.jpg') ?>" alt="" class="hover-effect" /></a></li>
                <li><a href="#"><img src="<?php echo $this->getPubUrl('frontend/img/sliders/elastislide/7.jpg') ?>" alt="" class="hover-effect" /></a></li>
            </ul>

            <!-- Blog Tags -->
            <div class="headline"><h3>Blog Tags</h3></div>
            <ul class="unstyled inline blog-tags">
                <li><a href="#"><i class="icon-tags"></i> Business</a></li>
                <li><a href="#"><i class="icon-tags"></i> Music</a></li>
                <li><a href="#"><i class="icon-tags"></i> Internet</a></li>
                <li><a href="#"><i class="icon-tags"></i> Education</a></li>
                <li><a href="#"><i class="icon-tags"></i> People</a></li>
                <li><a href="#"><i class="icon-tags"></i> Math</a></li>
                <li><a href="#"><i class="icon-tags"></i> Photos</a></li>
                <li><a href="#"><i class="icon-tags"></i> Electronics</a></li>
                <li><a href="#"><i class="icon-tags"></i> Apple</a></li>
                <li><a href="#"><i class="icon-tags"></i> Canada</a></li>
            </ul>

            <!-- Blog Latest Tweets -->
            <div class="blog-twitter">
                <div class="headline"><h3>Latest Tweets</h3></div>
                <p><a href="">@htmlstream</a> At vero eos et accusamus et iusto odio dignissimos. <a href="#">http://t.co/sBav7dm</a> <span>5 hours ago</span></p>
                <p><a href="">@unify</a> At vero eos et accusamus et iusto odio dignissimos. <a href="#">http://t.co/f58Ddg4</a> <span>8 hours ago</span></p>
                <p><a href="">@veroeos</a> At vero eos et accusamus et iusto odio dignissimos. <a href="#">http://t.co/adVs9f</a> <span>17 hours ago</span></p>
                <p><a href="">@accusamus </a> At vero eos et accusamus et iusto odio dignissimos. <a href="#">http://t.co/wf5Fs6</a> <span>23 hours ago</span></p>
                <p><a href="">@veroeoset</a> At vero eos et accusamus et iusto odio dignissimos. <a href="#">http://t.co/7EsffP</a> <span>1 day ago</span></p>
            </div>
        </div><!--/span3-->
    </div><!--/row-fluid-->        
</div><!--/container-->		
<!--=== End Content Part ===-->

