---
cms_page:
    update: default
    root:
        children:
            content:
                children:
                    page:
                        type: Seahinet\Cms\ViewModel\Page
admin_cms_page_list:
    update: admin
    root:
        children:
            content:
                children:
                    grid:
                        type: Seahinet\Admin\ViewModel\Cms\Page
admin_cms_page_edit:
    update: admin
    root:
        children:
            content:
                children:
                    edit:
                        type: Seahinet\Admin\ViewModel\Cms\PageEdit
admin_cms_block_list:
    update: admin
    root:
        children:
            content:
                children:
                    grid:
                        type: Seahinet\Admin\ViewModel\Cms\Block
admin_cms_block_edit:
    update: admin
    root:
        children:
            content:
                children:
                    edit:
                        type: Seahinet\Admin\ViewModel\Cms\BlockEdit
