---
cms_page:
    update: frontend
    root:
        children:
            content:
                children:
                    page:
                        type: Seahinet\Cms\ViewModel\Page
cms_page_with_nav:
    update: frontend
    root:
        children:
            content:
                children:
                    main:
                        type: Seahinet\Lib\ViewModel\Template
                        template: cms/main
                        children:
                            navigation:
                                type: Seahinet\Cms\ViewModel\Navigation
                                template: cms/navigation
                            page:
                                type: Seahinet\Cms\ViewModel\Page
cms_help_order_status:
    update: frontend
    root:
        children:
            head:
                action:
                    -
                        method: setTitle
                        params: Select Orders
            content:
                action:
                    -
                        method: setVariable
                        params:
                            - title
                            - Select Orders
                children:
                    main:
                        type: Seahinet\Lib\ViewModel\Template
                        template: cms/main
                        children:
                            navigation:
                                type: Seahinet\Cms\ViewModel\Navigation
                                template: cms/navigation
                            order_status:
                                type: Seahinet\Cms\ViewModel\Order_status
                                template: cms/order_status
                                
admin_cms_page_list:
    update: grid
    root:
        children:
            head:
                action:
                    -
                        method: setTitle
                        params: Page Management / CMS
            content:
                children:
                    breadcrumb:
                        action:
                            -
                                method: addCrumb
                                params: [{link:':ADMIN/cms_page/',label:'Page Management'}]
                            -
                                method: addAdditional
                                params: [{link:':ADMIN/cms_page/edit/',label:'Add New Page'}]
                    grid:
                        type: Seahinet\Admin\ViewModel\Cms\Grid\Page
admin_cms_page_edit:
    update: edit
    root:
        children:
            head:
                action:
                    -
                        method: addScript
                        params: [{src:'backend/js/modal.js',defer:'defer',async:'async'}]
                    -
                        method: addScript
                        params: backend/js/jquery.ui/core.js
                    -
                        method: addScript
                        params: backend/js/jquery.ui/widget.js
                    -
                        method: addScript
                        params: backend/js/jquery.ui/mouse.js
                    -
                        method: addScript
                        params: backend/js/jquery.ui/sortable.js
                    -
                        method: addScript
                        params: backend/js/jquery.fileupload/core.js
                    -
                        method: addScript
                        params: backend/js/jquery.fileupload/config.js
                    -
                        method: addLink
                        params: backend/css/jquery-ui.min.css
            content:
                children:
                    breadcrumb:
                        action:
                            -
                                method: addCrumb
                                params: [{link:':ADMIN/cms_page/',label:'Page Management'}]
                            -
                                method: addCrumb
                                params: [{label:'Edit'}]
                    edit:
                        type: Seahinet\Admin\ViewModel\Cms\Edit\Page
                        children:
                            upload:
                                type: Seahinet\Lib\ViewModel\Template
                                template: resource/widget
            extra:
                children:
                    modal:
                        type: Seahinet\Admin\ViewModel\Resource\Modal
                        template: resource/modal
admin_cms_block_list:
    update: grid
    root:
        children:
            head:
                action:
                    -
                        method: setTitle
                        params: Block Management / CMS
            content:
                children:
                    breadcrumb:
                        action:
                            -
                                method: addCrumb
                                params: [{link:':ADMIN/cms_block/',label:'Block Management'}]
                            -
                                method: addAdditional
                                params: [{link:':ADMIN/cms_block/edit/',label:'Add New Block'}]
                    grid:
                        type: Seahinet\Admin\ViewModel\Cms\Grid\Block
admin_cms_block_edit:
    update: edit
    root:
        children:
            content:
                children:
                    breadcrumb:
                        action:
                            -
                                method: addCrumb
                                params: [{link:':ADMIN/cms_block/',label:'Block Management'}]
                            -
                                method: addCrumb
                                params: [{label:'Edit'}]
                    edit:
                        type: Seahinet\Admin\ViewModel\Cms\Edit\Block
admin_cms_category_list:
    update: grid
    root:
        children:
            head:
                action:
                    -
                        method: setTitle
                        params: Category Management / CMS
            content:
                children:
                    breadcrumb:
                        action:
                            -
                                method: addCrumb
                                params: [{link:':ADMIN/cms_category/',label:'Category Management'}]
                            -
                                method: addAdditional
                                params: [{link:':ADMIN/cms_category/edit/',label:'Add New Category'}]
                    grid:
                        type: Seahinet\Admin\ViewModel\Cms\Grid\Category
admin_cms_category_edit:
    update: edit
    root:
        children:
            content:
                children:
                    breadcrumb:
                        action:
                            -
                                method: addCrumb
                                params: [{link:':ADMIN/cms_category/',label:'Category Management'}]
                            -
                                method: addCrumb
                                params: [{label:'Edit'}]
                    edit:
                        type: Seahinet\Admin\ViewModel\Cms\Edit\Category
