---
cms_page:
    update: default
    root:
        children:
            content:
                children:
                    page:
                        type: Seahinet\Cms\ViewModel\Page
admin_cms_page_list:
    update: grid
    root:
        children:
            head:
                action:
                    -
                        method: setTitle
                        params: Page Management / CMS
            content:
                children:
                    breadcrumb:
                        action:
                            -
                                method: addCrumb
                                params: [{link:':ADMIN/cms_page/',label:'Page Management'}]
                            -
                                method: addAdditional
                                params: [{link:':ADMIN/cms_page/edit/',label:'Add New Page'}]
                    grid:
                        type: Seahinet\Admin\ViewModel\Cms\Page
admin_cms_page_edit:
    update: edit
    root:
        children:
            content:
                children:
                    breadcrumb:
                        action:
                            -
                                method: addCrumb
                                params: [{link:':ADMIN/cms_page/',label:'Page Management'}]
                            -
                                method: addCrumb
                                params: [{label:'Edit'}]
                    edit:
                        type: Seahinet\Admin\ViewModel\Cms\PageEdit
                        children:
                            testimages:
                                type: Seahinet\Lib\ViewModel\Template
                        	    template: Resources/imagesbutton
                        
admin_cms_block_list:
    update: grid
    root:
        children:
            head:
                action:
                    -
                        method: setTitle
                        params: Block Management / CMS
            content:
                children:
                    breadcrumb:
                        action:
                            -
                                method: addCrumb
                                params: [{link:':ADMIN/cms_block/',label:'Block Management'}]
                            -
                                method: addAdditional
                                params: [{link:':ADMIN/cms_block/edit/',label:'Add New Block'}]
                    grid:
                        type: Seahinet\Admin\ViewModel\Cms\Block
admin_cms_block_edit:
    update: edit
    root:
        children:
            content:
                children:
                    breadcrumb:
                        action:
                            -
                                method: addCrumb
                                params: [{link:':ADMIN/cms_block/',label:'Block Management'}]
                            -
                                method: addCrumb
                                params: [{label:'Edit'}]
                    edit:
                        type: Seahinet\Admin\ViewModel\Cms\BlockEdit
admin_cms_category_list:
    update: grid
    root:
        children:
            head:
                action:
                    -
                        method: setTitle
                        params: Category Management / CMS
            content:
                children:
                    breadcrumb:
                        action:
                            -
                                method: addCrumb
                                params: [{link:':ADMIN/cms_category/',label:'Category Management'}]
                            -
                                method: addAdditional
                                params: [{link:':ADMIN/cms_category/edit/',label:'Add New Category'}]
                    grid:
                        type: Seahinet\Admin\ViewModel\Cms\Category
admin_cms_category_edit:
    update: edit
    root:
        children:
            content:
                children:
                    breadcrumb:
                        action:
                            -
                                method: addCrumb
                                params: [{link:':ADMIN/cms_category/',label:'Category Management'}]
                            -
                                method: addCrumb
                                params: [{label:'Edit'}]
                    edit:
                        type: Seahinet\Admin\ViewModel\Cms\CategoryEdit
