---
admin:
    cms:
        icon: television
        title: CMS
        priority: 10
        children:
            -
                link: 'cms_page/'
                title: 'Page Management'
                priority: 0
            -
                link: 'cms_block/'
                title: 'Block Management'
                priority: 20
