<div id="category_name">
<?php 
$item = $this->getVariable('item');
if(isset($item['namelanguage'])&&count($item['namelanguage'])>0){
    $strHtml='<table>';
    foreach ($item['namelanguage'] as $languageId => $names){
        $strHtml.='<tr><td>'.$names['language_name'].'</td><td> <input type="text" class="form-control required" id="name_'.$languageId.'" name="name_'.$languageId.'" value="'.$names['name'].'" /></td></tr>';
          
    }
    $strHtml.='</table>';
    echo $strHtml;
}
?>
</div>