<?php
$attributes = $this->getVariable('attributes');
$count = count($attributes);
$query = $this->getQuery();
?>
<div class="grid">
    <div class="filters">
        <form action="<?php echo $this->getCurrentUrl() ?>" method="get" class="form-inline">
            <?php
            foreach ($attributes as $attr => $name) {
                if (isset($name['use4filter']) && !$name['use4filter']) {
                    continue;
                }
                if (!isset($name['type'])) {
                    $name['type'] = 'text';
                }
                if(isset($query[$attr])){
                    $name['value'] = $query[$attr];
                }
                echo $this->getInputBox($attr, $name);
            }
            ?>
            <div class="input-box">
                <label class="control-label" for="sortby:limit"><?php echo $this->translate('Item(s) per page') ?></label>
                <div class="cell">
                    <input type="tel" name="limit" id="sortby:limit" class="form-control" value="<?php echo isset($query['limit']) ? $query['limit'] : 20 ?>" />
                </div>
            </div>
            <div class="buttons-set">
                <button type="submit" class="btn"><?php echo $this->translate('Search') ?></button>
                <a href="<?php echo $this->getCurrentUrl() ?>" class="btn"><?php echo $this->translate('Reset') ?></a>
            </div>
        </form>
    </div>
    
    
    <table class="table table-hover table-striped table-no-border">
        <thead class="sort-by">
            <tr>
                <?php if ($this->getMessAction()): ?>
                    <th class="checkbox"><input type="checkbox" class="selectall" /></th>
                <?php endif ?>
                <?php foreach ($attributes as $attr => $name): ?>
                    <th>
                        <?php if (!isset($name['use4sort']) || $name['use4sort']): ?>
                            <a href="<?php echo $this->getOrderByUrl(isset($name['sortby']) ? $name['sortby'] : $attr) ?>"
                            <?php if (isset($query['asc']) && $query['asc'] === $attr): ?>
                                   class="asc"
                               <?php elseif (isset($query['desc']) && $query['desc'] === $attr): ?>
                                   class="desc"
                               <?php endif ?>>
                               <?php endif ?>
                               <?php echo $this->translate($name['label'], [], $this->getTranslateDomain()) ?>
                               <?php if (!isset($name['use4sort']) || $name['use4sort']): ?>
                            </a>
                        <?php endif ?>
                    </th>
                <?php endforeach ?>
                <?php if ($this->getAction()): ?>
                    <th class="action"><?php echo $this->translate('Action') ?></th>
                <?php endif ?>
            </tr>
        </thead>
        <tbody>
            <?php 
            foreach ($this->getVariable('collection')->toArray() as $item): 
            
            ?>
                <tr>
                
                    <?php if ($this->getMessAction()): ?>
                        <td class="text-center checkbox"><input type="checkbox" name="id[]" value="<?php echo $item['id'] ?>" /></td>
                    <?php endif ?>
                    
                    <?php foreach ($attributes as $attr => $name): ?>
                        <td<?php if (isset($name['class'])): ?> class="<?php echo $name['class'] ?>"<?php endif ?>>
                            <?php
                            if($attr==='file_name'){
                                if($item['file_type']==='images'){
                                    echo '<img src="'.$name['fileUrl'].'images/50x50/' . $item['file_name'].'" alt="'.$item['file_name'].'" id="'.$item['id'].'" />';
                                }else{
                                    echo is_array($item[$attr]) ? implode(',', $item[$attr]) : $this->translate(isset($name['options'][$item[$attr]]) ? $name['options'][$item[$attr]] : $item[$attr], [], $this->getTranslateDomain());
                                }
                            }else{
                                echo is_array($item[$attr]) ? implode(',', $item[$attr]) : $this->translate(isset($name['options'][$item[$attr]]) ? $name['options'][$item[$attr]] : $item[$attr], [], $this->getTranslateDomain());
                            }
                            ?>
                        </td>
                    <?php endforeach ?>
                    
                    
                    <?php if ($this->getAction()): ?>
                        <td class="text-center action">
                            <?php
                            foreach ($this->getAction() as $action) {
                                if (is_callable([$this, $action])) {
                                    echo $this->$action($item);
                                }
                            }
                            ?>
                        </td>
                    <?php endif ?>
                </tr>
            <?php endforeach ?>
        </tbody>
        <tfoot>
            <tr>
                <?php if ($this->getMessAction()): ?>
                    <td class="checkbox">
                        <input type="checkbox" class="selectall" />
                    </td>
                    <td colspan="<?php printf('%d', $count/= 2) ?>" class="text-left">
                        <?php
                        foreach ($this->getMessAction() as $action) {
                            if (is_callable([$this, $action])) {
                                echo $this->$action();
                            }
                        }
                        ?>
                    </td>
                <?php endif ?>
                <td colspan="<?php echo $count + 1 ?>" class="text-right">
                    <?php echo $this->getChild('pager')->setCollection($this->getVariable('collection')) ?>
                </td>
            </tr>
        </tfoot>
    </table>
</div>
