<?php
$attributes = $this->getVariable('attributes');
$count = count($attributes);
$query = $this->getQuery();
?>
<div class="grid">
    <div class="filters upimage-header">
        <form action="<?php echo $this->getCurrentUrl() ?>" method="get" class="form-inline">
            <?php
            foreach ($attributes as $attr => $name) {
                if (isset($name['use4popupfilter']) && !$name['use4popupfilter']) {
                    continue;
                }
                if (!isset($name['type'])) {
                    $name['type'] = 'text';
                }
                if (isset($query[$attr])) {
                    $name['value'] = $query[$attr];
                }
                if ($attr === 'file_type' && isset($query['file_type']) && strpos($query['file_type'], '%')) {
                    $name['type'] = 'hidden';
                }
                echo $this->getInputBox($attr, $name);
            }
            ?>
            <div class="input-box">
                <label class="control-label" for="sortby:limit"><?php echo $this->translate('Item(s) per page') ?></label>
                <div class="cell">
                    <input type="tel" name="limit" id="sortby:limit" class="form-control" value="<?php echo isset($query['limit']) ? $query['limit'] : 20 ?>" />
                </div>
            </div>
            <div class="buttons-set">
                <button type="submit" class="btn"><?php echo $this->translate('Search') ?></button>
                <button type="reset" class="btn"><?php echo $this->translate('Reset') ?></button>
            </div>
        </form>
    </div>
    <div class="image-body-list"> 
        <table class="table table-hover table-striped table-no-border">
            <tbody>
                <tr>  
                    <?php
                    $i = 0;
                    foreach ($this->getVariable('collection')->toArray() as $item):
                        ?>
                        <td>
                            <a href="javascript:void(0);" class="select" title="<?php echo $item['real_name'] ?>">
                                <img src="<?php echo $attributes['real_name']['fileUrl'], 'image/resized/100x100/', $item['real_name'] ?>" alt="<?php echo $item['real_name'] ?>" data-id="<?php echo $item['id'] ?>" />
                                <span class="title"><?php echo $item['real_name'] ?></span>
                            </a>
                        </td>
                        <?php
                        if (($i + 1) % 6 == 0) {
                            echo '</tr><tr>';
                        }
                        $i++;
                    endforeach;
                    ?> 
                </tr>
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="6" class="text-right">
                        <?php echo $this->getChild('pager')->setCollection($this->getVariable('collection')) ?>
                    </td>
                </tr>
            </tfoot>
        </table>
    </div>
</div>
