<?php
$attributes = $this->getVariable('attributes');
$count = count($attributes);
$query = $this->getQuery();
?>
<div class="grid">
    <div class="filters upimage-header">
        <form action="<?php echo $this->getCurrentUrl() ?>" method="get" class="form-inline">
            <?php
            foreach ($attributes as $attr => $name) {
                if (isset($name['use4popupfilter']) && !$name['use4popupfilter']) {
                    continue;
                }
                if (!isset($name['type'])) {
                    $name['type'] = 'text';
                }
                echo $this->getInputBox($attr, $name);
            }
            ?>
            <div class="input-box">
                <label class="control-label" for="sortby:limit"><?php echo $this->translate('Item(s) per page') ?></label>
                <div class="cell">
                    <input type="tel" name="limit" id="sortby:limit" class="form-control" value="<?php echo isset($query['limit']) ? $query['limit'] : 20 ?>" />
                </div>
            </div>
            <div class="buttons-set">
                <button type="submit" class="btn"><?php echo $this->translate('Search') ?></button>
                <a href="<?php echo $this->getCurrentUrl() ?>" class="btn"><?php echo $this->translate('Reset') ?></a>
            </div>
        </form>
    </div>
    
    
   <div class="image-body-list"> 
    <table class="table table-hover table-striped table-no-border">
        <tbody>
        <tr>  
            <?php
            $i=0;
            foreach ($this->getVariable('collection')->toArray() as $item):
            echo '<td>';
            echo '<img src="'.$attributes['file_name']['fileUrl'].'images/100x100/' . $item['file_name'].'" alt="'.$item['file_name'].'" id="'.$item['id'].'" />';
           echo '</td>';
           if (($i+1)%6==0){
               echo '</tr><tr>';
           }
           $i++;
           endforeach;
           ?> 
                </tr>
        </tbody>
    </table>
</div>    
    
    <div class="image-body-list-b"><?php echo $this->getChild('pager')->setCollection($this->getVariable('collection')) ?></div>
</div>
