<?php
$item = $this->getVariable('item');
$key = $this->getVariable('key');
$id = preg_replace('/\W/', '-', $key);
$parent = $this->getVariable('parent');
$values = $parent->$key;
if (is_object($values)) {
    $values = [$values];
} else if (!is_array($values)) {
    $values = (array) $values;
}
if (count($values)):
    foreach ($values as $value):
        ?>
        <div class="inline-box">
            <button type="button" class="btn" data-toggle="modal" data-target="#resource-modal" title="<?php echo $this->translate('Select Resource') ?>">
                <img src="<?php echo $this->getResourceUrl('images/resized/120x120/' . $value['file_name']) ?>" height="120" alt="" />
            </button>
            <a href="javascript:void(0);" class="delete">
                <span class="fa fa-trash-o" aria-hidden="true"></span>
                <span class="sr-only"><?php echo $this->translate('Delete') ?></span>
            </a>
            <input type="hidden" name="<?php echo $key ?>" value="<?php echo $value['file_name'] ?>" />
        </div>
        <?php
    endforeach;
else:
    ?>
    <div class="inline-box">
        <button type="button" class="btn" data-toggle="modal" data-target="#resource-modal" title="<?php echo $this->translate('Select Resource') ?>">
            <img src="<?php echo $this->getPubUrl('backend/images/placeholder.png') ?>" height="120" alt="" /><br />
        </button>
        <a href="javascript:void(0);" class="delete">
            <span class="fa fa-trash-o" aria-hidden="true"></span>
            <span class="sr-only"><?php echo $this->translate('Delete') ?></span>
        </a>
        <input type="hidden" name="<?php echo $key ?>" value="" />
    </div>
<?php
endif;
if (isset($item['multiple'])):
    ?>
    <a href="javascript:void(0);" class="add">
        <span class="fa fa-plus-square" aria-hidden="true"></span>
        <span class="sr-only"><?php echo $this->translate('Add') ?></span>
    </a>
<?php endif; ?>
