<?php
$attributes = $this->getAttributes();
$privileges = $this->getPrivileges();
$group = [];
?>
<table class="table table-hover table-striped">
    <thead>
        <tr>
            <th><?php echo $this->translate('Attribute', [], 'api') ?></th>
            <th><?php echo $this->translate('Readable', [], 'api') ?></th>
            <th><?php echo $this->translate('Writeable', [], 'api') ?></th>
        </tr>
    </thead>
    <tbody>
        <?php
        foreach ($attributes as $attribute):
            ?>
            <tr>
                <?php if (!in_array($attribute['entity_type'], $group)): ?>
                    <th><?php echo $attribute['entity_type'] ?></th>
                    <th></th>
                    <th></th>
                </tr><tr>
                <?php endif ?>
                <td><?php echo $attribute['label'] ?></td>
                <td><input type="checkbox" name="attribute_id[<?php echo $attribute['id'] ?>][readable]"<?php if (isset($privileges[$attribute['id']]) && $privileges[$attribute['id']]['readable']): ?> checked="checked"<?php endif ?> value="1" /></td>
                <td><input type="checkbox" name="attribute_id[<?php echo $attribute['id'] ?>][writeable]"<?php if (isset($privileges[$attribute['id']]) && $privileges[$attribute['id']]['writeable']): ?> checked="checked"<?php endif ?> value="1" /></td>
            </tr>
        <?php endforeach ?>
    </tbody>
</table>
