<?php
$items = $this->getItems();
?>
<!--
<div class="panel panel-rank">
    <div class="panel-heading">
        <h3 class="panel-title">
            <span><?php echo $this->translate('Ranking') ?></span>
        </h3>
    </div>
    <div class="panel-body">
        <table class="table">
            <thead>
                <tr>
                    <th colspan="2" class="text-nowrap"><?php echo $this->translate('Product Infomation') ?></th>
                    <th>SKU</th>
                    <th class="text-nowrap"><?php echo $this->translate('Qty') ?></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($items as $item): ?>
                    <tr>
                        <td><img src="<?php
                            $thumbnail = $item->getThumbnail();
                            echo strpos($thumbnail, '//') === false ? $this->getResourceUrl('image/resized/100x/' . $thumbnail) : $thumbnail;
                            ?>" alt="<?php echo $item->offsetGet('name') ?>" /></td>
                        <td><?php echo $item->offsetGet('name') ?></td>
                        <td><?php echo $item->offsetGet('sku') ?></td>
                        <td><?php echo (float) $item->offsetGet('qty') ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
-->