<?php
$order = new Seahinet\Sales\Model\Order;

?>
<div class="main_article_content text-center">
    <div class="columns">
        <p>输入你的订单号和账单地址的电子邮箱来查找你的订单。</p>

        <form action="<?php echo $this->getBaseUrl() ?>sales_order/" id="orderStatusForm" method="get" novalidate="novalidate">
            <fieldset><label class="text-left" for="orderNumber">订单号:</label><br />
                <input class="required" data-required="true" id="orderNumber" name="orderNumber" type="text" />
                <div class="error hidden" data-form-error="true">请输入订单号。</div>
            </fieldset>

            <fieldset><label class="text-left" for="zipEmail">账单地址的电子邮箱 （支付宝订单请使用配送地址邮箱）:</label><br />
                <input class="required" data-required="true" id="zipEmail" name="zipEmail" type="text" /></fieldset>
            <button class="button-pink status-submit" type="submit">发送</button></form>
    </div>
</div>