<?php
$orders = $this->getOrders();
if (count($orders) != 0):
    ?>
    <table class="table address-list text-center">
        <thead style="border:1px solid #eee">
            <tr class="table_head line-height-30">
                <th  class="col-lg-6 col-md-6 text-center"><?php echo $this->translate('commodity') ?></th>
                <th  class="col-lg-1 col-md-1"><?php echo $this->translate('Amount of the transaction') ?></th>
                <th  class="col-lg-1 col-md-1 text-center"><?php echo $this->translate('quantity') ?></th>
                <th  class="col-lg-3 col-md-3 text-center"><?php echo $this->translate('trading status') ?></th>     
                <th class="col-lg-1 col-md-1"></th>
            </tr>
        </thead>
    </table> 
    <?php foreach ($orders as $order): ?>                      
        <table class="table table-no-border list_table">
            <caption>
                <div class="col-xs-6 store"><?php echo $order->getStore()['name'] ?> <a href=""><span class="fa fa-qq"></span> </a></div>
                <div class="col-xs-6 text-right list_right">
                    <span class="label"><?php echo $this->translate('Order ID') ?>:</span>
                    <span><?php echo $order['increment_id'] ?></span>
                    <span class="list_time"><?php echo date('Y-m-d', strtotime($order['created_at'])) ?></span>
                    
                </div>
            </caption>
            <tbody>      
                <?php
                $flag = true;
                foreach ($order->getItems() as $item):
                    $product = $item['product'];
                    $thumbnail = $product->getThumbnail();
                    ?>
                    <tr>
                        <td>
                            <a href=""><img class="Thumbnail" src="<?php echo $thumbnail ? $this->getResourceUrl('image/resized/100x/' . $thumbnail) : $this->getPubUrl('frontend/images/placeholder.png') ?>" alt="<?php echo $product['name'] ?>" /></a>

                        </td>
                        <td class="text-vtop">
                            <h4 class="product-name"><a href=""><?php echo $product['name'] ?></a></h4>
                            <?php
                            $options = json_decode($item['options'], true);
                            if ($item['product_id'] && count($options)):
                                ?>
                                <dl class="options">
                                    <?php
                                    foreach ($product->getOptions() as $option):
                                        if (isset($options[$option->getId()])):
                                            ?>
                                            <dt><?php echo $option['title'] ?></dt>
                                            <dd>
                                                <?php
                                                echo (in_array($option['input'], ['select', 'radio', 'checkbox', 'multiselect']) ?
                                                        $option->getValue($options[$option->getId()]) : $options[$option->getId()])
                                                ?>
                                            </dd>
                                            <?php
                                        endif;
                                    endforeach;
                                    ?>
                                </dl>
                            <?php endif ?>
                        </td>
                        <td class="text-center">
                            <div class="price-box text-right">
                                <?php if ($product->getFinalPrice($item['qty'], false) == $item['base_price']): ?>
                                    <span class="regular-price">
                                        <span class="label"><?php echo $this->translate('Price') ?></span>
                                        <span class="price"><?php echo $order->getCurrency()->format($item['price']) ?></span>
                                    </span>
                                <?php else: ?>
                                    <span class="old-price text-nowrap">
                                        <span class="label"><?php echo $this->translate('Old Price') ?></span>
                                        <span class="price"><?php echo $order->getCurrency()->convert($product->getFinalPrice($item['qty'], false), true) ?></span>
                                    </span>
                                    <span class="special-price">
                                        <span class="label"><?php echo $this->translate('Special Price') ?></span>
                                        <span class="price"><?php echo $order->getCurrency()->format($item['price']) ?></span>
                                    </span>
                                <?php endif; ?>
                            </div>
                        </td>
                        <td class="text-center">
                            <?php echo (float) $item['qty'] ?>
                        </td>
                        <td class="Arefund"> <a href=""  data-toggle="modal" data-target="#modal-reply">退货/退款</a></td>
                        <?php if ($flag): ?>
                            <td rowspan="<?php echo count($order->getItems()) ?>" class="text-center text-nowrap">
                                <span class="total"><?php echo $order->getCurrency()->format($order['total']) ?></span>
                                <span class="shipping"><?php echo $this->translate('(Including Shipping Fee: %s)', [$order->getCurrency()->format($order['shipping'])]) ?></span>
                            </td>
                            <td rowspan="<?php echo count($order->getItems()) ?>" class="text-nowrap">
                                <span class="status">
                                    <?php echo $this->translate($order->getStatus()['name']) ?>
                                </span>
                                <a href="<?php echo $this->getBaseUrl('sales/order/view/?id=' . $order->getId()) ?>"><?php echo $this->translate('Order Details') ?></a>
                                <?php if ($order->canRefund()): ?>
                                    <a href="<?php echo $this->getBaseUrl('sales/refund/?id=' . $order->getId()) ?>"><?php echo $this->translate('Refund Application') ?></a>
                                <?php endif ?>
                            </td>
                            <?php
                            $flag = false;
                        endif;
                        ?>
                    </tr>
                <?php endforeach ?>
            </tbody>  
        </table>
    <?php endforeach; ?>
<?php endif; ?>
<p><?php echo $this->getChild('pager')->setCollection($orders); ?></p>

 <div id="modal-reply" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="replyModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="replyModalLabel">售后详情</h4>
                </div>
            
                <div class="modal-body">
                	<div class="layer_table">
                		<table class="table details_layer">
	                    	<thead>
	                    		<tr class="details_thead"> 
	                    		<th>
	                    			<lable>申请服务：</lable>
	                    			
	                    				<select class="form-control select_xl">
										      <option value="1">仅退款</option>
										      <option value="2">退货退款</option>
										 </select>  
										 <span class="color-red">*</span><span class="span_txt">必选项</span>  
	                    			</th>
	                    		</tr>
	                    		</thead>
                    		</table>
                    	<div id="pop-up">
                    		<div id="Arefund_cont" class="">
                    			<div class="input-box">
					            	<label class="control-label"><i class="color-red">*</i>是否收到货：</label>
					            	<div class="cell">
						                <span class="male"> <input name="optionsRadios" id="optionsRadios1" value="option1" checked="" type="radio">未收到货</span>
						                <span class="female"><input name="optionsRadios" id="optionsRadios2" value="option2" checked="" type="radio">已收到货</span>
					           		 </div>
       							 </div>
	       						 <div class="input-box">
						            <label><i class="color-red">*</i><span>备注<span  class="font_color">(0/200字)</span>：</span></label>
						            <div class="cell input_width">
						                <textarea name="description" id="description" class="form-control" rows="4"></textarea>
						            </div>
						        </div>
						        <div class="input-box">
						            <label><i class="color-red">*</i><span>上传凭证：</span></label>
						            <div class="cell">
						               <button class="input_img">选择凭证照片</button>
						            </div>
						        </div>
                    		</div>
                    		
                    		<div id="goods" class="Arefund_hide" >
                    			<div class="input-box">
					            <label class="control-label"><i class="color-red">*</i>退货退款原因：</label>
					            <div class="cell">
					                <select class="form-control">
					                		<option >请选择退货退款原因</option>
										      <option >买错了重拍</option>
										      <option >不喜欢</option>
										      <option >尺码不合适</option>
									 </select> 
					            </div>
       						 </div>
       						 <div class="input-box">
					            <label><i class="color-red">*</i><span>订单退款金额：</span></label>
					            <div class="cell input_width">
					                <input type="txt" value="不超过订单金额"><lable>元<span>（最多58.00元,含发货邮费0.00元）</span></lable>
					            </div>
					        </div>
					        <div class="input-box">
					            <label><i class="color-red">*</i><span>备注<span  class="font_color">(0/200字)</span>：</span></label>
					            <div class="cell input_width">
					                <textarea name="description" id="description" class="form-control" rows="4"></textarea>
					            </div>
					        </div>
					        <div class="input-box">
					            <label><i class="color-red">*</i><span>上传凭证：</span></label>
					            <div class="cell">
					               <button class="input_img">选择凭证照片</button>
					            </div>
					        </div>
                    		</div>
					        
                    		</div>
                    		
                    		
                    		
                    		
					         <div class="input-box btn_sub" >
					           <input type="submit" value="提交申请" />
					           <button>取消并返回</button>
					        </div>
                    		
                		</div>
                    
                    
                    
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary">确认</button>
                </div>
            </div>
        </div>
    </div>
    
   <script type="text/javascript">
   $(function(){
	   $('select').change(function(){
	   var value=$(".select_xl").val();
	   if(value=='1'){
	   $('#Arefund_cont').removeClass('Arefund_hide');
	   $('#goods').addClass('Arefund_hide');
	   }
	   if(value=='2'){
	   $('#goods').removeClass('Arefund_hide');
	   $('#Arefund_cont').addClass('Arefund_hide');
	   }


	   });

	   });


	</script>
