<?php
$orders = $this->getOrders();
if ($orders):
    $flag = true;
// var_dump($orders->toArray());
    ?>
    <table class="table address-list text-center">
        <thead style="border:1px solid #eee">
            <tr class="table_head ">
                <th  class="col-md-4 text-center"><?php echo $this->translate('commodity') ?></th>
                <th  class="col-md-2 text-right"><?php echo $this->translate('Amount of the transaction') ?></th>
                <th  class="text-center"><?php echo $this->translate('quantity') ?></th>
                <th  class="text-center"><?php echo $this->translate('trading status') ?></th>     
                <th></th>
            </tr>
        </thead>
    </table>
    <?php if (count($orders)): ?>  
        <?php foreach ($orders as $order): ?>                      

            <table class="table table-no-border list_table">
                <caption>
                    <div class="col-xs-6 store"><?php echo $order->getStore()['name'] ?> <a href=""><span class="fa fa-qq"></span> </a></div>
                    <div class="col-xs-6 text-right list_right">
                        <span class="label"><?php echo $this->translate('Order ID') ?>:</span>
                        <span><?php echo $order['increment_id'] ?></span>
                        <span class="list_time"><?php echo date('Y-m-d', strtotime($order['created_at'])) ?></span>
                        <span class="list_delete"><a href=""><?php echo $this->translate('Delete') ?></a></span>
                    </div>
                </caption>
                <tbody>      
                    <?php
                    foreach ($order->getItems() as $item):
                        $product = $item['product'];
                        $thumbnail = $product->getThumbnail();
                        ?>
                        <tr>
                            <td>
                                <a href=""><img class="Thumbnail" src="<?php echo $thumbnail ? $this->getResourceUrl('image/resized/100x/' . $thumbnail) : $this->getPubUrl('frontend/images/placeholder.png') ?>" alt="<?php echo $product['name'] ?>" /></a>

                            </td>
                            <td class="text-vtop">
                                <h4 class="product-name"><a href=""><?php echo $product['name'] ?></a></h4>
                                <?php
                                $options = json_decode($item['options'], true);
                                if ($item['product_id'] && count($options)):
                                    ?>
                                    <dl class="options">
                                        <?php
                                        foreach ($product->getOptions() as $option):
                                            if (isset($options[$option->getId()])):
                                                ?>
                                                <dt><?php echo $option['title'] ?></dt>
                                                <dd>
                                                    <?php
                                                    echo (in_array($option['input'], ['select', 'radio', 'checkbox', 'multiselect']) ?
                                                            $option->getValue($options[$option->getId()]) : $options[$option->getId()])
                                                    ?>
                                                </dd>
                                                <?php
                                            endif;
                                        endforeach;
                                        ?>
                                    </dl>
                                <?php endif ?>
                            </td>
                            <td>
                                <div class="price-box text-right">
                                    <?php if ($product->getFinalPrice($item['qty'], false) == $item['base_price']): ?>
                                        <span class="regular-price">
                                            <span class="label"><?php echo $this->translate('Price') ?></span>
                                            <span class="price"><?php echo $order->getCurrency()->format($item['price']) ?></span>
                                        </span>
                                    <?php else: ?>
                                        <span class="old-price text-nowrap">
                                            <span class="label"><?php echo $this->translate('Old Price') ?></span>
                                            <span class="price"><?php echo $order->getCurrency()->convert($product->getFinalPrice($item['qty'], false), true) ?></span>
                                        </span>
                                        <span class="special-price">
                                            <span class="label"><?php echo $this->translate('Special Price') ?></span>
                                            <span class="price"><?php echo $order->getCurrency()->format($item['price']) ?></span>
                                        </span>
                                    <?php endif; ?>
                                </div>
                            </td>
                            <td>
                                <?php echo (float) $item['qty'] ?>
                            </td>
                            <?php if ($flag): ?>
                                <td rowspan="<?php echo count($order->getItems()) ?>" class="text-center text-nowrap">
                                    <span class="total"><?php echo $order->getCurrency()->format($order['total']) ?></span>
                                    <span class="shipping"><?php echo $this->translate('(Including Shipping Fee: %s)', [$order->getCurrency()->format($order['shipping'])]) ?></span>
                                </td>
                                <td rowspan="<?php echo count($order->getItems()) ?>" class="text-nowrap">
                                    <span class="status">
                                        <?php echo $this->translate($order->getStatus()['name']) ?>
                                    </span>
                                    <a href="<?php echo $this->getBaseUrl('sales/order/view/?id=' . $order->getId()) ?>"><?php echo $this->translate('Order Details') ?></a>
                                    <?php if ($order->canRefund()): ?>
                                        <a href="<?php echo $this->getBaseUrl('sales/refund/?id=' . $order->getId()) ?>"><?php echo $this->translate('Refund Application') ?></a>
                                    <?php endif ?>
                                </td>
                                <?php
                                $flag = false;
                            endif;
                            ?>
                        </tr>
                    <?php endforeach ?>
                </tbody>  
            </table>
        <?php endforeach; ?>
    <?php endif ?>
<?php endif; ?>
