<div class="modal fade" id="modal-edit-discount">
    <div class="modal-dialog">
        <div class="modal-content">
            <form action="<?php echo $this->getAdminUrl('sales_order/saveDiscount/') ?>" method="post" data-ajax="true">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title"><?php echo $this->translate('Discount') ?></h4>
                </div>
                <div class="modal-body">
                    <div class="input-box">
                        <label for="discount" class="control-label required">
                            <?php echo $this->translate('Discount') ?>
                        </label>
                        <div class="cell">
                            <div class="input-group">
                                <span class="input-group-addon"><?php echo $this->getConfig()['i18n/currency/base'] ?></span>
                                <input type="number" name="discount" id="discount" class="form-control number required" value="" />
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn" data-dismiss="modal"><?php echo $this->translate('Close') ?></button>
                    <button type="submit" class="btn btn-theme"><?php echo $this->translate('Save') ?></button>
                </div>
                <input type="hidden" name="csrf" value="<?php echo $this->getCsrfKey() ?>" />
                <input type="hidden" name="id" value="" />
            </form>
        </div>
    </div>
</div>
