<?php
$item = $this->getVariable('item');
$product = $item['product'];
$thumbnail = $product->getThumbnail();
$inventory = $item->getInventory();
?>
<tr class="product-list">
    <td></td>
    <td>
        <input type="checkbox" class="float-left checkbox-<?php echo $item['store_id'] ?>" name="item[]" value="<?php echo $item['id'] ?>">
        <a  class="float-left" href="<?php echo $item['product']->getUrl() ?>">
            <img src="<?php echo strpos($thumbnail, '://') === false ? $this->getBaseUrl('pub/resource/image/resized/88x/' . $thumbnail) : $thumbnail ?>" alt="" />
        </a>
    </td>
    <td>
        <a href="<?php echo $item['product']->getUrl() ?>">
            <?php echo $item['product_name'] ?>
        </a>
    </td>
    <td>
        <?php echo $this->getCurrency()->format($item['price']) ?>
    </td>
    <td class="qty">
        <label class="spin minus" for="qty-<?php echo $item['id'] ?>">-</label>
        <input type="number" name="qty[<?php echo $item['id'] ?>]" id="qty-<?php echo $item['id'] ?>"
               min="<?php echo (float) $inventory['min_qty'] ?>"
               max="<?php echo min((float) $inventory['max_qty'], (float) $inventory['qty']) ?>"
               step="<?php echo (float) $inventory['increment'] ?>"
               class="form-control required" value="<?php echo (float) $item['qty'] ?>" />
        <label class="spin plus" for="qty-<?php echo $item['id'] ?>">+</label>
    </td>
    <td>
        <span class="checkout-num"><?php echo $this->getCurrency()->format($item['price'] * $item['qty']) ?></span>
    </td>
    <td>
        <a href="<?php echo $this->getBaseUrl('checkout/cart/movetowishlist/?csrf='), $this->getCsrfKey(), '&id=', $item['id'] ?>">
            <span><?php echo $this->translate('Move to Wishlist') ?></span>
        </a>
        <a href="<?php echo $this->getBaseUrl('checkout/cart/remove/?csrf='), $this->getCsrfKey(), '&id=', $item['id'] ?>">
            <span><?php echo $this->translate('Delete') ?></span>
        </a>
    </td>
</tr>