<?php
$item = $this->getVariable('item');
$product = $item['product'];
$thumbnail = $product->getThumbnail();
$inventory = $item->getInventory();
?>
<tr class="product-list">
    <td>
        <input type="checkbox"<?php if ($item['status']): ?> checked="checked"<?php endif ?> class="checkbox-<?php echo $item['store_id'] ?>" name="item[]" value="<?php echo $item['id'] ?>" />
    </td>
    <td>
        <a href="<?php echo $item['product']->getUrl() ?>">
            <img src="<?php echo strpos($thumbnail, '//') === false ? $this->getResourceUrl('image/resized/88x/' . $thumbnail) : $thumbnail ?>" alt="" />
        </a>
    </td>
    <td class="product-name">
        <a href="<?php echo $item['product']->getUrl() ?>">
            <?php echo $item['product_name'] ?>
        </a>
        <?php
        $options = json_decode($item['options'], true);
        if ($item['product_id'] && count($options)):
            ?>
            <dl class="options">
                <?php
                foreach ($item['product']->getOptions() as $option):
                    if (isset($options[$option->getId()])):
                        ?>
                        <dt><?php echo $option['title'] ?></dt>
                        <dd>
                            <?php
                            echo (in_array($option['input'], ['select', 'radio', 'checkbox', 'multiselect']) ?
                                    $option->getValue($options[$option->getId()]) : $options[$option->getId()])
                            ?>
                        </dd>
                        <?php
                    endif;
                endforeach;
                ?>
            </dl>
        <?php endif; ?>
    </td>
    <td class="price" data-price="<?php echo $item['price'] ?>">
        <?php echo $this->getCurrency()->format($item['price']) ?>
    </td>
    <td class="qty">
        <div class="text-nowrap">
            <label class="spin minus" for="qty-<?php echo $item['id'] ?>">-</label>
            <input type="number" name="qty[<?php echo $item['id'] ?>]" id="qty-<?php echo $item['id'] ?>"
                   min="<?php echo (float) $inventory['min_qty'] ?>"
                   max="<?php echo min((float) $inventory['max_qty'], (float) $inventory['qty']) ?>"
                   step="<?php echo (float) $inventory['increment'] ?>"
                   class="form-control required" value="<?php echo (float) $item['qty'] ?>" />
            <label class="spin plus" for="qty-<?php echo $item['id'] ?>">+</label>
        </div>
    </td>
    <td class="subtotal">
        <?php echo $this->getCurrency()->format($item['price'] * $item['qty']) ?>
    </td>
    <td class="text-nowrap actions">
        <a href="<?php echo $this->getBaseUrl('checkout/cart/movetowishlist/') ?>?csrf=<?php echo $this->getCsrfKey() ?>&id=<?php echo $item->getId() ?>">
            <span><?php echo $this->translate('Move to Wishlist') ?></span>
        </a><br /> 
        <a href="<?php echo $this->getBaseUrl('checkout/cart/remove/') ?>" data-method="delete" data-params="csrf=<?php echo $this->getCsrfKey() ?>&item=<?php echo $item['id'] ?>">
            <span><?php echo $this->translate('Delete') ?></span>
        </a>
    </td>
</tr>