<?php
$item = $this->getVariable('item');
$product = $item['product'];
$thumbnail = $product->getThumbnail();
?>
<tr>
    <td><input type="checkbox" name="item[]" value="<?php echo $item['id'] ?>"></td>
    <td>
        <a href="<?php echo $item['product']->getUrl() ?>">
            <img src="<?php echo strpos($thumbnail, '://') === false ? $this->getBaseUrl('pub/resource/image/resized/88x/' . $thumbnail) : $thumbnail ?>" alt="" />
        </a>
    </td>
    <td>
        <a href="<?php echo $item['product']->getUrl() ?>">
            <?php echo $item['product_name'] ?>
        </a>
    </td>
    <td>
        <?php echo $this->getCurrency()->format($item['price']) ?>
    </td>
    <td>
        <input type="number" name="qty[<?php echo $item['id'] ?>]" class="form-control required" value="<?php echo (float) $item['qty'] ?>" />
    </td>
    <td>
        <?php echo $this->getCurrency()->format($item['price'] * $item['qty']) ?>
    </td>
    <td>
        <a href="<?php echo $this->getBaseUrl('checkout/cart/movetowishlist/?csrf='), $this->getCsrfKey(), '&id=', $item['id'] ?>">
            <span><?php echo $this->translate('Move to Wishlist') ?></span>
        </a>
        <a href="<?php echo $this->getBaseUrl('checkout/cart/remove/?csrf='), $this->getCsrfKey(), '&id=', $item['id'] ?>">
            <span><?php echo $this->translate('Delete') ?></span>
        </a>
    </td>
</tr>