
    <?php echo $this->translate('Select Qty') ?>
    <span class="checkout-num"><?php echo $this->getQty() ?></span>
    <?php echo $this->translate('Unit') ?>
    &nbsp;&nbsp;
    <?php
    if (!$this->getVariable('simplify')):
        if ((float) $this->getCart()['discount']):
            foreach (json_decode($this->getCart()['discount_detail'], true) as $type => $discount):
                ?>
                <?php echo $this->translate('Discount(%s)', [$type]) ?>
                <?php echo $this->getCurrency()->format($discount) ?>
                <?php
            endforeach;
        endif;
        ?>
        <?php
        if ($this->getCart()['shipping']):
            ?>
            <?php //echo $this->translate('Shipping') ?>
            <?php //echo $this->getCurrency()->format($this->getCart()['shipping']) ?>
            <?php
        endif;
    endif;
    ?>
    &nbsp;&nbsp;
    <?php echo $this->translate('Total') ?>:
    <span class="checkout-num"><?php echo $this->getCurrency()->format($this->getCart()['total']) ?></span>
