<?php
$item = $this->getVariable('item');
$key = $this->getVariable('key');
$parent = $this->getVariable('parent');
if ($item['type'] === 'hidden'):
    ?>
    <input type="hidden" name="<?php echo $key ?>" value="<?php echo isset($item['value']) ? $item['value'] : '' ?>" />
    <?php
else:
    ?>
    <div class="input-box">
        <?php if (isset($item['label'])): ?>
            <label for="<?php echo $key ?>" class="control-label<?php if (isset($item['required'])): ?> required<?php endif ?>">
                <?php echo $this->translate($item['label']) ?>
            </label>
        <?php endif ?>
        <div class="cell">
            <?php if ($item['type'] === 'select'): ?>
                <select name="<?php echo $key ?>" id="<?php echo $key ?>"<?php
                if (!isset($item['attrs']['class'])):
                    ?> class="form-control<?php if (isset($item['required'])): ?> required<?php endif ?> <?php
                            if (isset($item['class'])) {
                                echo $item['class'];
                            }
                            ?>"<?php endif ?> <?php if (isset($item['attrs'])) echo $parent->getAttrs($item['attrs']) ?>>
                            <?php if (!isset($item['required']) || !$item['required']): ?>
                        <option><?php echo $this->translate(isset($item['empty_string']) ? $item['empty_string'] : 'Please Select') ?></option>
                    <?php endif ?>
                    <?php
                    foreach ($item['options'] as $value => $label):
                        if (is_array($label)):
                            ?>
                            <optgroup label="<?php echo $value ?>">
                                <?php foreach ($label as $v => $l): ?>
                                    <option value="<?php echo $v ?>"<?php if (isset($item['value']) && (in_array($v, (array) $item['value']) || $v == $item['value'])): ?> selected="selected"<?php endif ?>><?php echo $l ?></option>
                                <?php endforeach; ?>
                            </optgroup>
                        <?php else: ?>
                            <option value="<?php echo $value ?>"<?php if (isset($item['value']) && $value == $item['value']): ?> selected="selected"<?php endif ?>><?php echo $label ?></option>
                        <?php endif ?>
                    <?php endforeach ?>
                </select>
            <?php elseif ($item['type'] === 'radio' || $item['type'] === 'checkbox'): ?>
                <?php foreach ($item['options'] as $value => $label): ?>
                    <input type="<?php echo $item['type'] ?>" name="<?php echo $key ?>" id="<?php echo $key, '-', $value ?>"<?php
                    if (!isset($item['attrs']['class'])):
                        ?> class="form-control<?php if (isset($item['required'])): ?> required<?php endif ?> <?php
                               if (isset($item['class'])) {
                                   echo $item['class'];
                               }
                               ?>"<?php endif ?> value="<?php echo $value ?>"<?php if (isset($item['value']) && $value == $item['value']): ?> checked="checked"<?php endif ?> <?php if (isset($item['attrs'])) echo $parent->getAttrs($item['attrs']) ?>/>
                    <label for="<?php echo $key, '-', $value ?>" class="control-label"><?php echo $label ?></label>
                <?php endforeach ?>
            <?php elseif ($item['type'] === 'textarea'): ?>
                <textarea name="<?php echo $key ?>" id="<?php echo $key ?>"<?php
                if (!isset($item['attrs']['class'])):
                    ?> class="form-control<?php if (isset($item['required'])): ?> required<?php endif ?> <?php
                              if (isset($item['class'])) {
                                  echo $item['class'];
                              }
                              ?>"<?php endif ?> <?php if (isset($item['attrs'])) echo $parent->getAttrs($item['attrs']) ?>><?php echo isset($item['value']) ? $item['value'] : '' ?></textarea>
                          <?php
                      elseif ($item['type'] === 'widget' && isset($item['widget'])):
                          echo $parent->{$item['widget']};
                      else:
                          ?>
                <input type="<?php echo $item['type'] ?>" name="<?php echo $key ?>" id="<?php echo $key ?>"<?php
                if (!isset($item['attrs']['class'])):
                    ?> class="form-control<?php if (isset($item['required'])): ?> required<?php endif ?> <?php
                           if (isset($item['class'])) {
                               echo $item['class'];
                           }
                           ?>"<?php endif ?> value="<?php echo isset($item['value']) ? $item['value'] : '' ?>" <?php if (isset($item['attrs'])) echo $parent->getAttrs($item['attrs']) ?>/>
                   <?php endif ?>
        </div>
    </div>
<?php endif; ?>
    