<?php
use Seahinet\Checkout\ViewModel\Cart\Item;

$item = $this->getVariable('item');
$product = $item['product'];
$thumbnail = $product->getThumbnail();
$item_model = new Item();
$options = $item_model->getOption($item);
?>
<tr class="product-list">
    <td class="td-img">
        <img src="<?php echo strpos($thumbnail, '://') === false ? $this->getBaseUrl('pub/resource/image/resized/88x/' . $thumbnail) : $thumbnail ?>" alt="" />
    </td>
    <td class="td-name">
        <?php echo $item['product_name'] ?>
        <?php 
            foreach ($options as $k=>$v){
                echo '<p><span>'. $k .'：'. $v .'</span></p>';
            }
        ?>
    </td>
    <td class="td-price">
        <?php echo $this->getCurrency()->format($item['price']) ?>
    </td>
    <td class="tb-stock td-qty">
        <?php echo (float) $item['qty'] ?>
    </td>
    <td class="td-subtotal">
        <span class="checkout-num"><?php echo $this->getCurrency()->format($item['price'] * $item['qty']) ?></span>
    </td>
    <?php if ($this->getVariable('rowspan')): ?>
        <td rowspan="<?php echo $this->getVariable('rowspan') ?>" class="td-method">
            <?php echo $this->getChild('shipping')->setVariable('store_id', $item['store_id']) ?>
        </td>
        <td rowspan="<?php echo $this->getVariable('rowspan') ?>" class="td-comment">
            <textarea name="comment[<?php echo $item['store_id'] ?>]" class="form-control"></textarea>
        </td>
    <?php endif ?>
</tr>