<?php
$item = $this->getVariable('item');
$product = $item['product'];
$thumbnail = $product->getThumbnail();
?>
<tr class="product-list">
    <td class="td-img">
        <img src="<?php echo strpos($thumbnail, '://') === false ? $this->getBaseUrl('pub/resource/image/resized/88x/' . $thumbnail) : $thumbnail ?>" alt="" />
    </td>
    <td class="td-name">
        <strong><?php echo $item['product_name'] ?></strong>
        <?php
        $options = json_decode($item['options'], true);
        if ($item['product_id'] && count($options)):
            ?>
            <dl class="options">
                <?php
                foreach ($item['product']->getOptions() as $option):
                    if (isset($options[$option->getId()])):
                        ?>
                        <dt><?php echo $option['title'] ?></dt>
                        <dd>
                            <?php
                            echo (in_array($option['input'], ['select', 'radio', 'checkbox', 'multiselect']) ?
                                    $option->getValue($options[$option->getId()]) : $options[$option->getId()])
                            ?>
                        </dd>
                        <?php
                    endif;
                endforeach;
                ?>
            </dl>
        <?php endif; ?>
    </td>
    <td class="td-price">
        <?php echo $this->getCurrency()->format($item['price']) ?>
    </td>
    <td class="tb-stock td-qty">
        <?php echo (float) $item['qty'] ?>
    </td>
    <td class="td-subtotal">
        <span class="checkout-num"><?php echo $this->getCurrency()->format($item['price'] * $item['qty']) ?></span>
    </td>
    <?php if ($this->getVariable('rowspan')): ?>
        <td rowspan="<?php echo $this->getVariable('rowspan') ?>" class="td-method">
            <?php echo $this->getChild('shipping')->setVariable('store_id', $item['store_id']) ?>
        </td>
        <td rowspan="<?php echo $this->getVariable('rowspan') ?>" class="td-comment">
            <textarea name="comment[<?php echo $item['store_id'] ?>]" class="form-control"></textarea>
        </td>
    <?php endif ?>
</tr>