<div class="modal fade" id="new-group" tabindex="-1" role="dialog" aria-labelledby="new-group-label">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form action="<?php echo $this->getSaveUrl() ?>" method="post" data-ajax="true">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="new-group-label"><?php echo $this->translate('Add New Attribute Group') ?></h4>
                </div>
                <div class="modal-body">
                    <input type="hidden" name="csrf" value="<?php echo $this->getCsrfKey() ?>" />
                    <div class="input-box">
                        <label for="group:name" class="control-label required"><?php echo $this->translate('Name') ?></label>
                        <input type="text" name="name" id="group:name" class="form-control required" />
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-theme"><?php echo $this->translate('Submit') ?></button>
                </div>
            </form>
        </div>
    </div>
</div>