<?php
$elements = $this->getVariable('elements');
if ($this->hasTitle()):
    ?>
    <div class="product-edit">
        <form action="<?php echo $this->getSaveUrl() ?>" method="post"<?php if ($this->hasUploadingFile()): ?> enctype="multipart/form-data"<?php endif ?>>
            <?php echo $this->getChild('tabs') ? $this->getChild('tabs')->setVariable('model', $this->getVariable('model')) : '' ?>
            <div class="page-content table tab-pane fade active in" id="main-tab">
                <?php
            endif;
            foreach ($elements as $key => $item) {
                echo $this->getInputBox($key, $item);
            }
            if ($this->hasTitle()):
                ?>
            </div>
            <div class="buttons-set">
                <button type="reset" class="btn btn-reset"><span><?php echo $this->translate('Reset') ?></span></button>
                <button type="button" class="btn btn-next"><span><?php echo $this->translate('Next') ?></span></button>
                <button type="submit" name="success_url" value="<?php echo $this->getQuery('id') ? $this->getUri() : $this->getBaseUrl('retailer/product/selling/') ?>" class="btn btn-submit"><span><?php echo $this->translate('Save and Return') ?></span></button>
                <button type="submit" class="btn btn-submit"><span><?php echo $this->translate('Save') ?></span></button>
                <?php if ($this->getDeleteUrl()): ?>
                    <a href="<?php echo $this->getDeleteUrl() ?>" class="btn btn-delete" data-method="delete" data-params="id=<?php echo $this->getVariable('model')->getId() ?>&csrf=<?php echo $this->getCsrfKey() ?>&success_url=<?php echo rawurlencode($this->getRequest()->getHeader('HTTP_REFERER')) ?>">
                        <span><?php echo $this->translate('Delete') ?></span>
                    </a>
                    <?php
                endif;
                echo $this->getAdditionalButtons();
                ?>
            </div>
        </form>
    </div>
<?php endif; ?>
