---
admin_email_template_list:
    - Are you sure to delete this record?
    - Are you sure to delete these records?
admin_email_template_edit:
    - Are you sure to delete this record?
    - Are you sure to delete these records?
admin_email_subscriber_list:
    - Are you sure to delete this record?
    - Are you sure to delete these records?
admin_email_queue_list:
    - Are you sure to delete this record?
    - Are you sure to delete these records?
    