---
admin_email_template_list:
    update: grid
    root:
        children:
            head:
                action:
                    -
                        method: setTitle
                        params: Email Template
            content:
                children:
                    breadcrumb:
                        action:
                            -
                                method: addCrumb
                                params: [{link:':ADMIN/email_template/',label:'Email Template'}]
                            -
                                method: addAdditional
                                params: [{link:':ADMIN/email_template/edit/',label:'Add New Template'}]
                    grid:
                        type: Seahinet\Admin\ViewModel\Email\Grid
            extra:
                children:
                    send:
                        type: Seahinet\Lib\ViewModel\Template
                        template: admin/email/send
admin_email_template_edit:
    update: edit
    root:
        children:
            content:
                children:
                    breadcrumb:
                        action:
                            -
                                method: addCrumb
                                params: [{link:':ADMIN/email_template/',label:'Template Management'}]
                            -
                                method: addCrumb
                                params: [{label:'Edit'}]
                    edit:
                        type: Seahinet\Admin\ViewModel\Email\Edit
            extra:
                children:
                    send:
                        type: Seahinet\Lib\ViewModel\Template
                        template: admin/email/send
admin_email_subscriber_list:
    update: grid
    root:
        children:
            head:
                action:
                    -
                        method: setTitle
                        params: Subscriber / Newsletter
            content:
                children:
                    breadcrumb:
                        action:
                            -
                                method: addCrumb
                                params: [{link:':ADMIN/email_subscriber/',label:'Newsletter Subscriber'}]
                    grid:
                        type: Seahinet\Admin\ViewModel\Email\Subscriber
admin_email_queue_list:
    update: grid
    root:
        children:
            head:
                action:
                    -
                        method: setTitle
                        params: Email Queue
            content:
                children:
                    breadcrumb:
                        action:
                            -
                                method: addCrumb
                                params: [{link:':ADMIN/email_queue/',label:'Email Queue'}]
                    grid:
                        type: Seahinet\Admin\ViewModel\Email\Queue
