---
checkout_cart:
    update: frontend
    root:
        children:
            head:
                action:
                    -
                        method: addScript
                        params: frontend/js/bttrlazyloading.js
                    -
                        method: addScript
                        params: [{src:'frontend/js/cart.js',defer:'defer',async:'async'}]
            content:
                children:
                    messages:
                        action:
                            -
                                method: addHandledSegment
                                params: checkout
                    cart:
                        type: Seahinet\Checkout\ViewModel\Cart
                        template: checkout/cart
                        children:
                            item:
                                type: Seahinet\Checkout\ViewModel\Cart\Item
                                template: checkout/cart/item
                            total:
                                type: Seahinet\Checkout\ViewModel\Cart
                                template: checkout/cart/total
                            method:
                                type: Seahinet\Lib\ViewModel\Template
                                template: checkout/cart/method
                            crosssell:
                                type: Seahinet\Checkout\ViewModel\Cart\Crosssell
                                template: catalog/product/link
                            logview:
                                type: Seahinet\Checkout\ViewModel\Cart\LogView
                                template: catalog/product/link
                            wishlist:
                                type: Seahinet\Checkout\ViewModel\Cart\Wishlist
                                template: catalog/product/link
checkout_cart_mini:
    update: frontend
    root:
        unset: [head]
        template: page/ajax
        children:
            content:
                children:
                    cart:
                        type: Seahinet\Checkout\ViewModel\Cart
                        template: checkout/cart/mini
                        children:
                            total:
                                type: Seahinet\Checkout\ViewModel\Cart
                                template: checkout/minicart/total
checkout_order:
    update: frontend
    root:
        children:
            head:
                action:
                    -
                        method: addScript
                        params: frontend/js/locate.js
                    -
                        method: addScript
                        params: frontend/js/checkout.js
            content:
                type: Seahinet\Lib\ViewModel\Template
                template: checkout/order
                children:
                    messages:
                        action:
                            -
                                method: addHandledSegment
                                params: checkout
                    address:
                        type: Seahinet\Checkout\ViewModel\Order\Address
                        template: checkout/order/address
                    payment:
                        type: Seahinet\Checkout\ViewModel\Order\Payment
                        template: checkout/order/payment
                    review:
                        type: Seahinet\Checkout\ViewModel\Order\Review
                        template: checkout/order/review
                        children:
                            item:
                                type: Seahinet\Checkout\ViewModel\Cart\Item
                                template: checkout/order/review/item
                            shipping:
                                type: Seahinet\Checkout\ViewModel\Order\Shipping
                                template: checkout/order/shipping
                            total:
                                type: Seahinet\Checkout\ViewModel\Cart
                                template: checkout/order/total
checkout_order_shipping:
    update: frontend
    root:
        unset: [head]
        template: page/ajax
        children:
            content:
                unset: [breadcrumb,messages]
                children:
                    shipping:
                        type: Seahinet\Checkout\ViewModel\Order\Shipping
                        template: checkout/order/shipping
checkout_order_payment:
    update: frontend
    root:
        unset: [head]
        template: page/ajax
        children:
            content:
                unset: [breadcrumb,messages]
                children:
                    payment:
                        type: Seahinet\Checkout\ViewModel\Order\Payment
                        template: checkout/order/payment
checkout_order_review:
    update: frontend
    root:
        unset: [head]
        template: page/ajax
        children:
            content:
                unset: [breadcrumb,messages]
                children:
                    review:
                        type: Seahinet\Checkout\ViewModel\Cart
                        template: checkout/order/total
checkout_order_success:
    update: frontend
    root:
        children:
            content:
                children:
                    success:
                        type: Seahinet\Checkout\ViewModel\Success
                        template: checkout/success
