---
checkout_cart:
    update: frontend
    root:
        children:
            content:
                children:
                    messages:
                        action:
                            -
                                method: addHandledSegment
                                params: checkout
                    cart:
                        type: Seahinet\Checkout\ViewModel\Cart
                        template: checkout/cart
                        children:
                            total:
                                type: Seahinet\Checkout\ViewModel\Cart
                                template: checkout/cart/total
                            method:
                                type: Seahinet\Lib\ViewModel\Template
                                template: checkout/cart/method
                            crosssell:
                                type: Seahinet\Checkout\ViewModel\Cart\Crosssell
                                template: catalog/product/link
checkout_cart_mini:
    update: frontend
    root:
        unset: [head]
        template: page/ajax
        children:
            content:
                children:
                    cart:
                        type: Seahinet\Checkout\ViewModel\Cart
                        template: checkout/cart/mini
                        children:
                            total:
                                type: Seahinet\Checkout\ViewModel\Cart
                                template: checkout/cart/total
checkout_order:
    update: frontend
    root:
        children:
            head:
                action:
                    -
                        method: addScript
                        params: frontend/js/locate.js
            content:
                type: Seahinet\Lib\ViewModel\Template
                template: checkout/order
                children:
                    messages:
                        action:
                            -
                                method: addHandledSegment
                                params: checkout
                    address:
                        type: Seahinet\Checkout\ViewModel\Order\Address
                        template: checkout/order/address
                    shipping:
                        type: Seahinet\Checkout\ViewModel\Order\Shipping
                        template: checkout/order/address
                    payment:
                        type: Seahinet\Checkout\ViewModel\Order\Payment
                        template: checkout/order/payment
                    review:
                        type: Seahinet\Checkout\ViewModel\Order\Review
                        template: checkout/order/review
checkout_order_shipping:
    update: frontend
    root:
        unset: [head]
        template: page/ajax
        children:
            content:
                children:
                    shipping:
                        type: Seahinet\Checkout\ViewModel\Order\Shipping
                        template: checkout/order/address
checkout_order_payment:
    update: frontend
    root:
        unset: [head]
        template: page/ajax
        children:
            content:
                children:
                    payment:
                        type: Seahinet\Checkout\ViewModel\Order\Payment
                        template: checkout/order/payment
checkout_order_review:
    update: frontend
    root:
        unset: [head]
        template: page/ajax
        children:
            content:
                children:
                    review:
                        type: Seahinet\Checkout\ViewModel\Order\Review
                        template: checkout/order/review
