---
permissions:
    children:
        -
            link: api_rest_role/
            title: REST - Role
            priority: 70
        -
            link: api_rest_attribute/
            title: REST - Attributes
            priority: 71