<?php
$order = $this->getOrder();
$currency = $this->getOrder()->getCurrency();
$back_url = $this->getRequest()->getHeader('HTTP_REFERER');
?>

<div class="view clearfix font-12">
    <form action="<?php echo $this->getBaseUrl('retailer/sales_shipment/save/') ?>" method="post" class="form-sales">
        <input type="hidden" name="csrf" value="<?php echo $this->getCsrfKey() ?>" />
        <input type="hidden" name="order_id" value="<?php echo $this->getQuery('id') ?>" />
        <input type="hidden" name="back_url" value="<?php echo $back_url; ?>" />
        <div class="panel wide">
            <ul class="col-xs-12 col-sm-12 title-nav name padding-5 font-12">
                <li class="col-xs-5 col-sm-5 text-left">
                    <?php
                    if ($store = $order->getStore()) {
                        echo $store->offsetGet('name');
                    }
                    ?>
                </li>
                <li class="col-xs-7 col-sm-7 text-right">
                    <?php echo $currency->format($order->offsetGet('total')) ?>
                    <span>(<?php echo $this->translate('Including Shipping Fee: %s', [$currency->format($order->offsetGet('shipping'))]) ?>)</span>
                </li>	
            </ul>
            <table class="table inline bt padding-5">
                <?php
                $items = $this->getCollection();
                $flag = TRUE;
                foreach ($items as $item):
                    $product = $item['product'];
                    $thumbnail = $product->getThumbnail();
                    $max = $this->getMaxQty($item);
                    if ($max):
                        ?>
                        <tr<?php if (isset($item['id'])): ?> data-id="<?php echo $item['id'] ?>"<?php endif ?>>
                            <td class="col-xs-2 col-sm-2">
                                <img src="<?php echo strpos($thumbnail, '//') === false ? $this->getResourceUrl('image/resized/100x/' . $thumbnail) : $thumbnail ?>" width="50" height="50" alt="<?php echo $product->offsetGet('name') ?>" />
                            </td>
                            <td class="col-xs-6 col-sm-6 text-left" title="<?php echo $product->offsetGet('name') ?>">
                                <h4 class="font-12"><?php echo $product->offsetGet('name') ?></h4>
                                <?php
                                $options = json_decode($item['options'], true);
                                if ($item['product_id'] && count($options)) {
                                    foreach ($item['product']->getOptions() as $option) {
                                        if (isset($options[$option->getId()])) {
                                            echo $option['title'], ': ', (in_array($option['input'], ['select', 'radio', 'checkbox', 'multiselect']) ?
                                                    $option->getValue($options[$option->getId()]) : $options[$option->getId()]), '<br />';
                                        }
                                    }
                                }
                                ?>
                            </td>
                            <td class="col-xs-1 col-sm-1 text-right">
                                <span class="price" data-price="<?php echo $item['price'] ?>"><?php echo $currency->format($item['price']) ?></span>
                                <input type="hidden" name="item_id[]" value="<?php echo $item['id'] ?>" />
                                <input type="number" name="qty[]" max="<?php echo $max ?>" min="0" value="<?php echo (float) $max ?>" />
                            </td>
                            <?php
                            if ($flag):
                                ?>
                                <td rowspan="<?php echo count($items) ?>" class="col-xs-3 col-sm-3 total border-left action text-center">
                                    <span class="color-blue"><?php echo $this->translate($this->getStatus()->offsetGet('name'), [], 'sales') ?></span>
                                </td>
                                <?php
                                $flag = FALSE;
                            endif;
                            ?>
                        </tr>
                        <?php
                    endif;
                endforeach;
                ?>
            </table>
        </div>
        <div class="panel">
            <div class="panel-heading">
                <h4 class="panel-title font-14"><?php echo $this->translate('Order Infomation', [], 'sales') ?></h4>
            </div>
            <div class="panel-body">
                <?php echo $this->translate('ID'), ': ', $order['increment_id'] ?><br />
                <?php echo $this->translate('Status'), ': ', $this->translate($this->getStatus()->offsetGet('name'), [], 'sales') ?><br />
                <?php
                if ($store = $order->getStore()) {
                    echo $this->translate('Store'), ': ', $store->offsetGet('name');
                }
                ?><br />
                <?php
                if ($language = $order->getLanguage()) {
                    echo $this->translate('Language'), ': ', $language->offsetGet('name');
                }
                ?>
            </div>
        </div>
        <div class="panel">
            <div class="panel-heading">
                <h4 class="panel-title font-14"><?php echo $this->translate('Customer Infomation', [], 'sales') ?></h4>
            </div>
            <div class="panel-body"><?php if ($customer = $this->getCustomer()): ?>
                    ID: <?php echo $customer->getId() ?><br />
                    <?php echo $this->translate('Username'), ': ', $customer['username'] ?>
                <?php endif ?></div>
        </div>
        <div class="panel">
            <div class="panel-heading">
                <h4 class="panel-title font-14"><?php echo $this->translate('Billing Address', [], 'sales') ?></h4>
            </div>
            <div class="panel-body">
                <?php echo $order->offsetGet('billing_address') ?>
            </div>
        </div>
        <div class="panel">
            <div class="panel-heading">
                <h4 class="panel-title font-14"><?php echo $this->translate('Shipping Address', [], 'sales') ?></h4>
            </div>
            <div class="panel-body">
                <?php echo $order->offsetGet('shipping_address') ?>
            </div>
        </div>
        <div class="panel">
            <div class="panel-heading">
                <h4 class="panel-title font-14"><?php echo $this->translate('Shipping Method', [], 'sales') ?></h4>
            </div>
            <div class="panel-body">
                <?php echo $this->translate($order->getShippingMethod()->getLabel()) ?>
            </div>
        </div>
        <div class="panel">
            <div class="panel-heading">
                <h4 class="panel-title font-14"><?php echo $this->translate('Payment Method', [], 'sales') ?></h4>
            </div>
            <div class="panel-body">
                <?php echo $this->translate($order->getPaymentMethod()->getLabel()), '<br />', $this->translate('Order was placed using %s', [$order->offsetGet('currency')], 'sales') ?>
            </div>
        </div>

        <div class="panel">
            <div class="panel-heading">
                <h4 class="panel-title font-14"><?php echo $this->translate('Tracking', [], 'sales') ?></h4>
            </div>
            <div class="panel-body carrier">
                <div class="input-box">
                    <label for="carrier-code" class="control-label"><?php echo $this->translate('Carrier', [], 'sales') ?></label>
                    <select name="tracking[carrier_code]" id="carrier-code" class="form-control">
                        <option value=""><?php echo $this->translate('Custom Carrier') ?></option>
                        <?php foreach ($this->getCarriers() as $code => $title): ?>
                            <option value="<?php echo $code ?>" title="<?php echo $title ?>"><?php echo $this->translate($title, [], 'shipping') ?></option>
                        <?php endforeach ?>
                    </select>
                </div>
                <div class="input-box">
                    <label for="carrier" class="control-label"><?php echo $this->translate('Title') ?></label>
                    <input type="text" name="tracking[carrier]" class="form-control" id="carrier" maxlength="32" />
                </div>
                <div class="input-box">
                    <label for="number" class="control-label"><?php echo $this->translate('Tracking Number', [], 'sales') ?></label>
                    <input type="text" class="form-control" name="tracking[number]" id="number" />
                </div>
            </div>
        </div>
        <div class="panel">
            <div class="panel-heading">
                <h4 class="panel-title"><?php echo $this->translate('Comment', [], 'sales') ?></h4>
            </div>
            <div class="panel-body">
                <div class="input-box">
                    <textarea class="form-control" name="comment"></textarea>
                </div>
                <div class="buttons-set text-right">
                    <a class="btn btn-reset" href="<?php echo $back_url; ?>" ><?php echo $this->translate('Back') ?></a>
                    <button type="submit" class="btn btn-submit">
                        <span><?php echo $this->translate('Submit') ?></span>
                    </button>
                </div>
            </div>
        </div>
    </form>
</div>

