---
product.price.calc:
    -
        listener: [\Seahinet\Catalog\Listeners\Price\Regular, calc]
        priority: 0
    -
        listener: [\Seahinet\Catalog\Listeners\Price\Special, calc]
        priority: 10
    -
        listener: [\Seahinet\Catalog\Listeners\Price\Tier, calc]
        priority: 20
    -
        listener: [\Seahinet\Catalog\Listeners\Price\Group, calc]
        priority: 30
cart.add.before:
    -
        listener: [\Seahinet\Catalog\Listeners\Inventory, check]
        priority: 10
order.place.after:
    -
        listener: [\Seahinet\Catalog\Listeners\Inventory, decrease]
        priority: 0
order.refund.after:
    -
        listener: [\Seahinet\Catalog\Listeners\Inventory, increase]
        priority: 0
order.cancel.after:
    -
        listener: [\Seahinet\Catalog\Listeners\Inventory, increase]
        priority: 0
