---
product.price.calc:
    -
        listener: [\Seahinet\Catalog\Listeners\Price\Regular, calc]
        priority: 0
    -
        listener: [\Seahinet\Catalog\Listeners\Price\Special, calc]
        priority: 10
cart.add.before:
    -
        listener: [\Seahinet\Catalog\Listeners\Inventory, check]
        priority: 0
cart.add.after:
    -
        listener: [\Seahinet\Catalog\Listeners\Inventory, decrease]
        priority: 0
cart.remove.after:
    -
        listener: [\Seahinet\Catalog\Listeners\Inventory, increase]
        priority: 0
