---
catalog:
    icon: tags
    title: Catalog
    priority: 15
    children:
        -
            link: product_manage/
            title: Product Management
            priority: 0
        -
            link: category_manage/
            title: Category Management
            priority: 10
system:
    children:
        -
            link: config/catalog/
            title: Catalog Configuration
            priority: 45
