---
catalog:
    label: Catalog Configuration
    children:
        review:
            label: Review
            scope: merchant
            children:
                status:
                    type: select
                    label: Default Status
                    required: required
                    options:
                        1: Approved
                        0: Not Approved
                    default: 1
                    priority: 0
                allow_guests:
                    type: select
                    label: Allow Guests to Write Reviews
                    required: required
                    options:
                        1: Yes
                        0: No
                    priority: 20
                    default: 1
                akismet:
                    type: text
                    label: Akismet API Key
                    comment: Sign up for API key from <a href="https://akismet.com/">Akismet</a>
                    priority: 30
