---
admin_oauth_consumer_list:
    update: grid
    root:
        children:
            head:
                action:
                    -
                        method: setTitle
                        params: OAuth Consumer
            content:
                children:
                    breadcrumb:
                        action:
                            -
                                method: addCrumb
                                params: [{link:':ADMIN/api_oauth_consumer/',label:'OAuth Consumer'}]
                            -
                                method: addAdditional
                                params: [{link:':ADMIN/api_oauth_consumer/edit/',label:'Add New Consumer'}]
                    grid:
                        type: Seahinet\Admin\ViewModel\Api\Grid\Consumer
admin_oauth_consumer_edit:
    update: edit
    root:
        children:
            content:
                children:
                    breadcrumb:
                        action:
                            -
                                method: addCrumb
                                params: [{link:':ADMIN/api_oauth_consumer/',label:'OAuth Consumer'}]
                            -
                                method: addCrumb
                                params: [{link:':ADMIN/api_oauth_consumer/edit/',label:'Edit'}]
                    edit:
                        type: Seahinet\Admin\ViewModel\Api\Edit\Consumer
admin_oauth_token_list:
    update: grid
    root:
        children:
            head:
                action:
                    -
                        method: setTitle
                        params: Authorized OAuth Tokens
            content:
                children:
                    breadcrumb:
                        action:
                            -
                                method: addCrumb
                                params: [{link:':ADMIN/api_oauth_token/',label:'Authorized OAuth Tokens'}]
                    grid:
                        type: Seahinet\Admin\ViewModel\Api\Grid\Token
    