---
oauth_login:
    update: default
    root:
        children:
            content:
                children:
                    form:
                        type: Seahinet\Oauth\ViewModel\Login
admin_oauth_consumer_list:
    update: grid
    root:
        children:
            head:
                action:
                    -
                        method: setTitle
                        params: OAuth Consumer
            content:
                children:
                    breadcrumb:
                        action:
                            -
                                method: addCrumb
                                params: [{link:':ADMIN/api_oauth_consumer/',label:'OAuth Consumer'}]
                            -
                                method: addAdditional
                                params: [{link:':ADMIN/api_oauth_consumer/edit/',label:'Add New Consumer'}]
                    grid:
                        type: Seahinet\Admin\ViewModel\Api\Grid\Consumer
admin_oauth_consumer_edit:
    update: edit
    root:
        children:
            content:
                children:
                    breadcrumb:
                        action:
                            -
                                method: addCrumb
                                params: [{link:':ADMIN/api_oauth_consumer/',label:'OAuth Consumer'}]
                            -
                                method: addCrumb
                                params: [{link:':ADMIN/api_oauth_consumer/edit/',label:'Edit'}]
                    edit:
                        type: Seahinet\Admin\ViewModel\Api\Edit\Consumer
admin_oauth_token_list:
    update: grid
    root:
        children:
            head:
                action:
                    -
                        method: setTitle
                        params: Authorized OAuth Tokens
            content:
                children:
                    breadcrumb:
                        action:
                            -
                                method: addCrumb
                                params: [{link:':ADMIN/api_oauth_token/',label:'Authorized OAuth Tokens'}]
                    grid:
                        type: Seahinet\Admin\ViewModel\Api\Grid\Token
admin_rest_role_list:
    update: grid
    root:
        children:
            head:
                action:
                    -
                        method: setTitle
                        params: REST Role
            content:
                children:
                    breadcrumb:
                        action:
                            -
                                method: addCrumb
                                params: [{link:':ADMIN/api_rest_role/',label:'REST Role'}]
                            -
                                method: addAdditional
                                params: [{link:':ADMIN/api_rest_role/edit/',label:'Add New Role'}]
                    grid:
                        type: Seahinet\Admin\ViewModel\Api\Grid\RestRole
admin_rest_role_edit:
    update: edit
    root:
        children:
            content:
                children:
                    breadcrumb:
                        action:
                            -
                                method: addCrumb
                                params: [{link:':ADMIN/api_rest_role/',label:'REST Role'}]
                            -
                                method: addCrumb
                                params: [{link:':ADMIN/api_rest_role/edit/',label:'Edit'}]
                    edit:
                        type: Seahinet\Admin\ViewModel\Api\Edit\RestRole
admin_rest_attribute_list:
    update: grid
    root:
        children:
            head:
                action:
                    -
                        method: setTitle
                        params: REST Attribute Rules
            content:
                children:
                    breadcrumb:
                        action:
                            -
                                method: addCrumb
                                params: [{link:':ADMIN/api_rest_attribute/',label:'REST Attribute Rules'}]
                    grid:
                        type: Seahinet\Admin\ViewModel\Api\Grid\Attribute
                        template: admin/grid-simple
admin_rest_attribute_edit:
    update: edit
    root:
        children:
            content:
                children:
                    breadcrumb:
                        action:
                            -
                                method: addCrumb
                                params: [{link:':ADMIN/api_rest_attribute/',label:'REST Attribute Rules'}]
                            -
                                method: addCrumb
                                params: [{link:':ADMIN/api_rest_attribute/edit/',label:'Edit'}]
                    edit:
                        type: Seahinet\Admin\ViewModel\Api\Edit\Attribute
                        children:
                            attribute:
                                type: Seahinet\Admin\ViewModel\Api\Edit\Widget\Attribute
                                template: admin/api/attribute
