---
oauth:
    label: OAuth Login
    children:
        wechat:
            label: Wechat
            priority: 0
            scope: merchant
            children:
                enable:
                    type: select
                    label: Enable
                    required: required
                    priority: 0
                    options:
                        - Disabled
                        - Enabled
                    default: 1
                model:
                    type: hidden
                    scope: merchant
                    default: Seahinet\Oauth\Model\Client\Wechat
                icon:
                    type: text
                    label: Icon
                    priority: 4
                    attrs:
                        data-base: '#wechat-enable'
                    default: 'fa-wechat'
                label:
                    type: text
                    label: Label
                    required: required
                    priority: 5
                    attrs:
                        data-base: '#wechat-enable'
                    default: 'WeChat Login'
                appid:
                    label: App ID
                    priority: 10
                    type: text
                    attrs:
                        data-base: '#wechat-enable'
                secret:
                    label: App Secret
                    priority: 25
                    type: text
                    attrs:
                        data-base: '#wechat-enable'
        facebook:
            label: Facebook
            priority: 50
            scope: merchant
            children:
                enable:
                    type: select
                    label: Enable
                    required: required
                    priority: 0
                    options:
                        - Disabled
                        - Enabled
                    default: 1
                model:
                    type: hidden
                    scope: merchant
                    default: Seahinet\Oauth\Model\Client\Facebook
                icon:
                    type: text
                    label: Icon
                    priority: 4
                    attrs:
                        data-base: '#facebook-enable'
                    default: 'fa-facebook-square'
                label:
                    type: text
                    label: Label
                    required: required
                    priority: 5
                    attrs:
                        data-base: '#facebook-enable'
                    default: 'Facebook Login'
                appid:
                    label: App ID
                    priority: 10
                    type: text
                    attrs:
                        data-base: '#facebook-enable'
                secret:
                    label: App Secret
                    priority: 25
                    type: text
                    attrs:
                        data-base: '#facebook-enable'
