<?php
$level = $this->getVariable('level');
$item = $this->getVariable('category');
?>
<option data-id="<?php echo $item['id'] ?>" value="<?php echo $item['id'] ?>">
    <span class="title"><?php echo $item['name'] ?></span>
</option>
    <option value="<?php echo $item['id'] ?>">
        <?php
        foreach ($this->getVariable('children') as $item) {
            echo $this->renderCategory($item, $level + 1);
        }
        ?>
    </ul>
