<?php
$item = $this->getVariable('item');
$key = $this->getVariable('key');
$id = trim(preg_replace('/\W+/', '-', $key), '-');
$parent = $this->getVariable('parent');
?>
<div class="input-box <?php echo $this->getVariable('boxClass') ?>">
    <?php if (isset($item['label'])): ?>
        <label for="<?php echo $id ?>" class="control-label<?php if (isset($item['required'])): ?> required<?php endif ?>">
            <?php echo $this->translate($item['label']) ?>
        </label>
    <?php endif ?>
    <div class="cell">
        <?php if (empty($item['value'])): ?>
            <input type="file" name="<?php echo $key ?>" accept="image/*" id="<?php echo $id ?>"<?php
            if (!isset($item['attrs']['class'])):
                ?> class="form-control<?php if (isset($item['required'])): ?> required<?php endif ?> <?php
                       if (isset($item['class'])) {
                           echo $item['class'];
                       }
                       ?>"<?php endif ?> <?php
                   if (isset($item['attrs'])) {
                       echo $parent->getAttrs($item['attrs']);
                   }
                   ?>/>
                   <?php if (isset($item['comment'])): ?>
                <div class="comment">
                    <?php echo nl2br($this->translate($item['comment'])) ?>
                </div>
            <?php endif ?>
        <?php else: ?>
            <label for="<?php echo $id ?>">
                <img src="<?php
                if (substr($item['value'], 0, 4) === 'http'):
                    echo $item['value'];
                else:
                    ?>data:image/png;base64, <?php
                         echo base64_encode($item['value']);
                     endif;
                     ?>" width="320" alt="" />
            </label>
            <input type="file" name="<?php echo $key ?>" accept="image/*" id="<?php echo $id ?>" hidden="hidden" onchange="var r = new FileReader();
                        r.readAsDataURL(this.files[0]);
                        r.onload = function () {
                            $('[for=<?php echo $id ?>]>img').attr('src', this.result);
                        };" />
               <?php endif ?>
    </div>
</div>