<?php
$item = $this->getVariable('item');
?>
<div class="input-box">
    <?php if (isset($item['label'])): ?>
        <label class="control-label">
            <?php echo $this->translate($item['label']) ?>
        </label>
    <?php endif ?>
    <div class="cell">
        <?php echo $this->translate(isset($item['content']) ? $item['content'] : (isset($item['value']) ? $item['value'] : '')) ?>
    </div>
</div>
