<?php
$item = $this->getVariable('item');
$key = $this->getVariable('key');
$id = trim(preg_replace('/\W+/', '-', $key), '-');
$parent = $this->getVariable('parent');
if (isset($item['value']) && is_string($item['value'])) {
    $value = json_decode($item['value']);
    if (!$value) {
        $value = explode(',', $item['value']);
    }
    $item['value'] = $value;
}
?>
<div class="input-box <?php echo $this->getVariable('boxClass') ?>">
    <?php if (isset($item['label'])): ?>
        <label for="<?php echo $id ?>" class="control-label<?php if (isset($item['required'])): ?> required<?php endif ?>">
            <?php echo $this->translate($item['label']) ?>
        </label>
    <?php endif ?>
    <div class="cell">
        <select name="<?php echo $key, strpos($key, '[') ? '' : '[]' ?>" multiple="multiple" id="<?php echo $id ?>"<?php if (!empty($item['value'])): ?> data-default-value='<?php echo json_encode($item['value']) ?>'<?php
        endif;
        if (!isset($item['attrs']['class'])):
            ?> class="form-control<?php if (isset($item['required'])): ?> required<?php endif ?> <?php
                    if (isset($item['class'])) {
                        echo $item['class'];
                    }
                    ?>"<?php endif ?> <?php
                if (isset($item['attrs'])) {
                    echo $parent->getAttrs($item['attrs']);
                }
                ?>>
                    <?php
                    foreach ($item['options'] as $value => $label):
                        if (is_array($label)):
                            ?>
                    <optgroup label="<?php echo $this->translate($value) ?>">
                        <?php foreach ($label as $v => $l): ?>
                            <option value="<?php echo $v ?>"<?php if (isset($item['value']) && $item['value'] !== '' && in_array($v, (array) $item['value'])): ?> selected="selected"<?php endif ?>><?php echo $this->translate($l) ?></option>
                        <?php endforeach; ?>
                    </optgroup>
                <?php else: ?>
                    <option value="<?php echo $value ?>"<?php if (isset($item['value']) && $item['value'] !== '' && in_array($value, (array) $item['value'])): ?> selected="selected"<?php endif ?>><?php echo $this->translate($label) ?></option>
                <?php endif ?>
            <?php endforeach ?>
        </select>
        <a href="javascript:void(0);" onclick="javascript:$('select#<?php echo $id ?>').val('');" class="clear"><?php echo $this->translate('Clear') ?></a>
        <?php if (isset($item['comment'])): ?>
            <div class="comment">
                <?php echo nl2br($this->translate($item['comment'])) ?>
            </div>
        <?php endif ?>
    </div>
</div>
