<?php
$item = $this->getVariable('item');
$key = $this->getVariable('key');
$id = trim(preg_replace('/\W+/', '-', $key), '-');
$parent = $this->getVariable('parent');
?>
<div class="input-box <?php echo $this->getVariable('boxClass') ?>">
    <?php if (isset($item['label'])): ?>
        <label for="<?php echo $id ?>" class="control-label<?php if (isset($item['required'])): ?> required<?php endif ?>">
            <?php echo $this->translate($item['label']) ?>
        </label>
    <?php endif ?>
    <div class="cell">
        <textarea name="<?php echo $key ?>" id="<?php echo $id ?>"<?php
        if (!isset($item['attrs']['class'])):
            ?> class="form-control htmleditor fullbar<?php if (isset($item['required'])): ?> required<?php endif ?> <?php
                      if (isset($item['class'])) {
                          echo $item['class'];
                      }
                      ?>"<?php endif ?> <?php
                  if (isset($item['attrs'])) {
                      echo $parent->getAttrs($item['attrs']);
                  }
                  ?>><?php echo $item['value'] ?? '' ?></textarea>
                  <?php if (isset($item['comment'])): ?>
            <div class="comment">
                <?php echo nl2br($this->translate($item['comment'])) ?>
            </div>
        <?php endif ?>
    </div>
</div>
