---
-
    time: '0 0 * * *'
    code: 'Seahinet\RewardPoints\Listeners\Cron::schedule'
-
    time: '0 0 * * *'
    code: 'Seahinet\RewardPoints\Listeners\Cron::expiration'
-
    time: '0 0 * * *'
    code: 'Seahinet\RewardPoints\Listeners\Cron::activation'