 <div class="container">
    <?php
    if (count($this->getItems())):
        ?>
        <div class="breadcrumb-m hidden-lg">
            <a href="javascript:void(0);" onclick="javascript:history.back(-1);" class="fa fa-chevron-left fa-2x breadcrumb-right col-xs-1 col-sm-1">
            </a>
            <div class="content-list col-xs-10 col-sm-10">
                <a href=""><?php echo $this->translate('Shopping Cart'); ?></a>
            </div>
            <a href="javascript:void(0);" class="fa fa-bars fa-2x col-xs-1 col-sm-1" role="button" data-toggle="collapse" href="#collapseExample" aria-expanded="false" aria-controls="collapseExample"></a>
        </div>
        <form action="<?php echo $this->getBaseUrl('checkout/cart/update/') ?>" method="post">
            <input type="hidden" name="csrf" value="<?php echo $this->getCsrfKey() ?>" />
            <div class="table" id="cart">
                <?php
                $stores = [];
                foreach ($this->getItems() as $item) {
                    if (!isset($stores[$item['store_id']])):
                        ?>
                       
                        <ul class="store clearfix">
                            <li class="col-xs-1 col-sm-1 store">
                                <input type="checkbox" checked class="selectall" value="<?php echo $item['store']['id'] ?>">
                            </li>
                            <li class="col-xs-11 col-sm-11">
                                <?php echo $item['store']['name'] ?>
                            </li>
                        </ul>
                        <?php
                        $stores[$item['store_id']] = 1;
                    else:
                        $stores[$item['store_id']] ++;
                    endif;
                    echo $this->getRow($item);
                }
                ?>
                <ul class="col-xs-12 col-sm-12 checkout">
                    <li class="col-xs-1 col-sm-1 selectall">
                        <input type="checkbox" checked="checked" id="foot-selectall" />
                    </li>
                    <li class="col-xs-1 col-sm-1 selectall">
                        <label for="foot-selectall">
                            <?php echo $this->translate('Select All') ?>
                        </label>
                    </li>
                    <li class="col-xs-10 col-sm-10">
                        <?php echo $this->getChild('total'), $this->getChild('method') ?>
                    </li>
                </ul>
            </div>
        </form>
    <?php else: ?>
    <h2 class="text-center"><?php echo $this->translate('Shopping Cart Is Empty') ?></h2>
    <p class="text-center"><?php echo $this->translate('You have no items in your shopping cart.<br />Click <a href="%s">here</a> to continue shopping.', [$this->getBaseUrl()]) ?></p>
    <?php endif; ?>
    <?php
    $countC = count($this->getChild('crosssell')->getProducts());
    $countL = count($this->getChild('viewed_product')->getProducts());
    $countW = count($this->getChild('wishlist')->getProducts());
    ?>
    <?php if ($countC + $countL + $countW): ?>
        <div class="additional hidden-xs">
            <ul class="nav nav-tabs" role="tablist">
                <?php if ($countC): ?>
                    <li role="presentation" class="active">
                        <a href="#crosssell" aria-controls="crosssell" role="tab" data-toggle="tab">
                            <?php echo $this->translate('You May Like') ?>
                        </a>
                    </li>
                <?php endif ?>
                <?php if ($countW): ?>
                    <li role="presentation" class="<?php echo $countC ? '' : 'active' ?>">
                        <a href="#wishlist" aria-controls="wishlist" role="tab" data-toggle="tab">
                            <?php echo $this->translate('My Wishlist') ?>
                        </a>
                    </li>
                <?php endif ?>
                <?php if ($countL): ?>
                    <li role="presentation" class="<?php echo $countC + $countW ? '' : 'active'; ?>">
                        <a href="#viewed" aria-controls="viewed" role="tab" data-toggle="tab">
                            <?php echo $this->translate('Recently Viewed') ?>
                        </a>
                    </li>
                <?php endif ?>
            </ul>
            <div class="tab-content">
                <div role="tabpanel" class="tab-pane active" id="crosssell">
                    <?php echo $this->getChild('crosssell')->setLimit(6)->setVariable('width', ['xs' => '362', 'sm' => '228', 'md' => '221', 'lg' => '173']) ?>
                </div>
                <div role="tabpanel" class="tab-pane<?php echo $countC ? '' : ' active' ?>" id="wishlist">
                    <?php echo $this->getChild('wishlist')->setVariable('width', ['xs' => '362', 'sm' => '228', 'md' => '221', 'lg' => '173']) ?>
                </div>
                <div role="tabpanel" class="tab-pane<?php echo $countC + $countW ? '' : ' active'; ?>" id="viewed">
                    <?php echo $this->getChild('viewed_product')->setVariable('width', ['xs' => '362', 'sm' => '228', 'md' => '221', 'lg' => '173']) ?>
                </div>
            </div>
        </div>
    <?php endif ?>
</div>
