<div class="container">
    <div class="breadcrumb-m hidden-lg">
        <a href="javascript:viod(0);" onclick="javascript:history.back(-1);" class="fa fa-chevron-left fa-2x breadcrumb-right col-xs-1 col-sm-1"></a>
        <div class="content-list col-xs-10 col-sm-10">
            <a href=""><?php echo $this->translate('Order Confirmation'); ?></a>
        </div>
        <a href="javascript:viod(0);" class="fa fa-bars fa-2x col-xs-1 col-sm-1" role="button" data-toggle="collapse" href="#collapseExample" aria-expanded="false" aria-controls="collapseExample"></a>
    </div>
    <?php echo $this->getChild('messages') ?>
    <div class="checkout-steps">
        <?php echo $this->getChild('address'), $this->getChild('shipping'),$this->getChild('review'), $this->getChild('payment') ?>
    </div>
</div>