---
admin:
    resources:
        icon: television
        title: Resources
        priority: 30
        children:
            -
                link: 'resources_Category/'
                title: 'Category'
                priority: 0
