<div class="grid">
    <table class="table table-hover table-striped table-no-border">
        <thead class="sort-by">
            <tr>
                <th><?php echo $this->translate('Merchant') ?></th>
                <th><?php echo $this->translate('Store') ?></th>
                <th><?php echo $this->translate('Language') ?></th>
            </tr>
        </thead>
        <tbody>
            <?php
            $merchant = [];
            $stores = [];
            $languages = [];
            foreach ($this->getVariable('collection') as $item) {
                $merchant[$item['merchant_id']] = $item['merchant'];
                $stores[$item['store_id']] = $item['store'];
                $languages[$item['language_id']] = $item['language'];
            }
            $countS = count($stores);
            $countL = count($languages);
            foreach ($this->getVariable('collection') as $item):
                ?>
                <tr>
                    <?php if (isset($merchant[$item['merchant_id']])): ?>
                        <td class="text-vmiddle" rowspan="<?php echo max($countS, $countL) ?>">
                            <a href="<?php echo $this->getAdminUrl('i18n_merchant/edit/?id=' . $item['merchant_id']) ?>">
                                <?php echo $this->translate($item['merchant'], [], 'language') ?>
                            </a>
                        </td>
                        <?php
                        unset($merchant[$item['merchant_id']]);
                    endif;
                    if (isset($stores[$item['store_id']])):
                        ?>
                        <td>
                            <a href="<?php echo $this->getAdminUrl('i18n_store/edit/?id=' . $item['store_id']) ?>">
                                <?php echo $this->translate($item['store'], [], 'language') ?>
                            </a>
                        </td>
                        <?php
                        unset($stores[$item['store_id']]);
                    else:
                        echo '<td></td>';
                    endif;
                    if (isset($languages[$item['language_id']])):
                        ?>
                        <td>
                            <a href="<?php echo $this->getAdminUrl('i18n_language/edit/?id=' . $item['language_id']) ?>">
                                <?php echo $this->translate($item['language'], [], 'language') ?>
                            </a>
                        </td>
                        <?php
                        unset($languages[$item['language_id']]);
                    else:
                        echo '<td></td>';
                    endif;
                    ?>
                </tr>
                <?php
            endforeach;
            ?>
        </tbody>
    </table>
</div>
