<div class="grid">
    <table class="table table-no-border">
        <thead class="sort-by">
            <tr>
                <th><?php echo $this->translate('Merchant') ?></th>
                <th><?php echo $this->translate('Store') ?></th>
                <th><?php echo $this->translate('Language') ?></th>
            </tr>
        </thead>
        <tbody>
            <?php
            $merchant = [];
            $stores = [];
            $languages = [];
            foreach ($this->getVariable('collection') as $item) {
                $merchant[$item['merchant_id']] = $item['merchant'];
                if (!isset($stores[$item['merchant_id']])) {
                    $stores[$item['merchant_id']] = [];
                }
                if (!isset($languages[$item['merchant_id']])) {
                    $languages[$item['merchant_id']] = [];
                }
                $stores[$item['merchant_id']][$item['store_id']] = $item['store'];
                $languages[$item['merchant_id']][$item['language_id']] = $item['language'];
            }
            foreach ($this->getVariable('collection') as $item):
                $max = max(count($stores[$item['merchant_id']]), count($languages[$item['merchant_id']]));
                ?>
                <tr>
                    <?php if (isset($merchant[$item['merchant_id']])): ?>
                        <td class="text-vmiddle" rowspan="<?php echo $max ?>">
                            <a href="<?php echo $this->getAdminUrl('i18n_merchant/edit/?id=' . $item['merchant_id']) ?>">
                                <?php echo $this->translate($item['merchant'], [], 'language') ?>
                            </a>
                        </td>
                        <?php
                        unset($merchant[$item['merchant_id']]);
                    endif;
                    if (isset($stores[$item['merchant_id']][$item['store_id']])):
                        ?>
                        <td>
                            <a href="<?php echo $this->getAdminUrl('i18n_store/edit/?id=' . $item['store_id']) ?>">
                                <?php echo $this->translate($item['store'], [], 'language') ?>
                            </a>
                        </td>
                        <?php
                        unset($stores[$item['merchant_id']][$item['store_id']]);
                    elseif (empty($stores[$item['merchant_id']])):
                        echo '<td></td>';
                    else:
                        $currentKey = array_keys($stores[$item['merchant_id']])[0];
                        $current = array_shift($stores[$item['merchant_id']]);
                        ?>
                        <td>
                            <a href="<?php echo $this->getAdminUrl('i18n_store/edit/?id=' . $currentKey) ?>">
                                <?php echo $this->translate($current, [], 'language') ?>
                            </a>
                        </td>
                    <?php
                    endif;
                    if (isset($languages[$item['merchant_id']][$item['language_id']])):
                        ?>
                        <td>
                            <a href="<?php echo $this->getAdminUrl('i18n_language/edit/?id=' . $item['language_id']) ?>">
                                <?php echo $this->translate($item['language'], [], 'language') ?>
                            </a>
                        </td>
                        <?php
                        unset($languages[$item['merchant_id']][$item['language_id']]);
                    else:
                        echo '<td></td>';
                    endif;
                    ?>
                </tr>
                <?php
                if (count($stores, 1) === 0 && count($languages, 1) === 0) {
                    break;
                }
            endforeach;
            ?>
        </tbody>
    </table>
</div>
