<div class="container">
    <?php
    if (count($this->getItems())):
        ?>
        <div class="checkout-flow hidden-xs clearfix">
            <div class="item col-sm-4 active"><?php echo $this->translate('Shopping Cart', [], 'checkout') ?></div>
            <div class="item col-sm-4"><?php echo $this->translate('Order Confirmation', [], 'checkout') ?></div>
            <div class="item col-sm-4"><?php echo $this->translate('Complate', [], 'checkout') ?></div>
        </div>
        <form action="<?php echo $this->getBaseUrl('checkout/cart/update/') ?>" method="post">
            <table class="table" id="cart">
                <colgroup>
                    <col width="1" />
                    <col width="1" />
                    <col />
                    <col width="1" />
                    <col width="1" />
                    <col width="1" />
                    <col width="1" />
                </colgroup>
                <thead>
                    <tr>
                        <th colspan="2" class="selectall">
                            <input type="checkbox" checked="checked" id="head-selectall" />
                            <label for="head-selectall">
                                <?php echo $this->translate('Select All') ?>
                            </label>
                        </th>
                        <th class="text-left text-nowrap">
                            <?php echo $this->translate('Product Infomation') ?>
                        </th>
                        <th class="text-nowrap text-center">
                            <?php echo $this->translate('Price', [], 'checkout') ?>
                        </th>
                        <th class="text-nowrap text-center">
                            <?php echo $this->translate('Qty') ?>
                        </th>
                        <th class="text-nowrap text-center">
                            <?php echo $this->translate('Subtotal') ?>
                        </th>
                        <th class="text-nowrap text-center">
                            <?php echo $this->translate('Action') ?>
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    $stores = [];
                    foreach ($this->getItems() as $item) {
                        if (!isset($stores[$item['store_id']])):
                            ?>
                            <tr class="store">
                                <th>
                                    <input type="checkbox" checked class="selectall" value="<?php echo $item['store']['id'] ?>">
                                </th>
                                <th colspan="6">
                                    <?php echo $item['store']['name'] ?>
                                </th>
                            </tr>
                            <?php
                            $stores[$item['store_id']] = 1;
                        else:
                            $stores[$item['store_id']] ++;
                        endif;
                        echo $this->getRow($item);
                    }
                    ?>
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="3" class="selectall">
                            <input type="checkbox" checked="checked" id="foot-selectall" />
                            <input type="hidden" name="csrf" value="<?php echo $this->getCsrfKey() ?>" />
                            <label for="foot-selectall">
                                <?php echo $this->translate('Select All') ?>
                            </label>
                            <a href="<?php echo $this->getBaseUrl('checkout/cart/remove/') ?>" data-method="delete" data-serialize="#cart input[name]">
                                <?php echo $this->translate('Delete Selected Item(s)') ?>
                            </a>
                            <a href="<?php echo $this->getBaseUrl('checkout/cart/movetowishlist/') ?>" data-method="post" data-serialize="#cart input[name]">
                                <?php echo $this->translate('Move to Wishlist') ?>
                            </a>
                        </td>
                        <td colspan="4" class="text-right">
                            <?php echo $this->getChild('total'), $this->getChild('method') ?>
                        </td>
                    </tr>
                </tfoot>
            </table>
        </form>
    <?php else: ?>
        <div class="empty_cart">
            <div class="cart_img">
                <img src="<?php echo $this->getBaseUrl() ?>pub/theme/default/frontend/images/shopping_cart.jpg">
            </div>
            <ul>
                <li><?php echo $this->translate('You have no items in your shopping cart.<br />Click <a href="%s">here</a> to continue shopping.', [$this->getBaseUrl()]) ?></li>
            </ul>
        </div>
    <?php endif; ?>
    <?php
    $countC = count($this->getChild('crosssell')->getProducts());
    $countL = count($this->getChild('viewed_product')->getProducts());
    $countW = count($this->getChild('wishlist')->getProducts());
    ?>
    <?php if ($countC + $countL + $countW): ?>
        <div class="additional hidden-xs">
            <ul class="nav nav-tabs" role="tablist">
                <?php if ($countC): ?>
                    <li role="presentation" class="active">
                        <a href="#crosssell" aria-controls="crosssell" role="tab" data-toggle="tab">
                            <?php echo $this->translate('You May Like') ?>
                        </a>
                    </li>
                <?php endif ?>
                <?php if ($countW): ?>
                    <li role="presentation" class="<?php echo $countC ? '' : 'active' ?>">
                        <a href="#wishlist" aria-controls="wishlist" role="tab" data-toggle="tab">
                            <?php echo $this->translate('My Wishlist') ?>
                        </a>
                    </li>
                <?php endif ?>
                <?php if ($countL): ?>
                    <li role="presentation" class="<?php echo $countC + $countW ? '' : 'active'; ?>">
                        <a href="#viewed" aria-controls="viewed" role="tab" data-toggle="tab">
                            <?php echo $this->translate('Recently Viewed') ?>
                        </a>
                    </li>
                <?php endif ?>
            </ul>
            <div class="tab-content">
                <div role="tabpanel" class="tab-pane active" id="crosssell">
                    <?php echo $this->getChild('crosssell')->setLimit(6)->setVariable('width', ['xs' => '362', 'sm' => '228', 'md' => '221', 'lg' => '173']) ?>
                </div>
                <div role="tabpanel" class="tab-pane<?php echo $countC ? '' : ' active' ?>" id="wishlist">
                    <?php echo $this->getChild('wishlist')->setVariable('width', ['xs' => '362', 'sm' => '228', 'md' => '221', 'lg' => '173']) ?>
                </div>
                <div role="tabpanel" class="tab-pane<?php echo $countC + $countW ? '' : ' active'; ?>" id="viewed">
                    <?php echo $this->getChild('viewed_product')->setVariable('width', ['xs' => '362', 'sm' => '228', 'md' => '221', 'lg' => '173']) ?>
                </div>
            </div>
        </div>
    <?php endif ?>
</div>
