<?php
$csrf = $this->getCsrfKey();
$items = $this->getItems();
?>
<div class="minicart dropdown">
    <a href="javascript:void(0);" class="dropdown-toggle">
        <span class="fa fa-shopping-cart" aria-hidden="true"></span>
        <span><?php echo $this->translate('Shopping Cart', [], 'checkout') ?></span>
        <span class="badge"><?php echo $this->getQty() ?></span>
    </a>
    <div class="dropdown-menu dropdown-menu-right">
        <ul class="items"><?php
            if ($items):
                ?>
                <li class="title"><?php echo $this->translate('Recently Added Products') ?></li>
                <?php
                foreach ($this->getItems() as $item):
                    $thumbnail = $item['product']->getThumbnail();
                    ?>
                    <li data-id="<?php echo $item['product_id'] ?>" class="clearfix">
                        <a href="<?php echo $item['product']->getUrl() ?>" class="product-image col-xs-2">
                            <img src="<?php echo strpos($thumbnail, '://') === false ? $this->getBaseUrl('pub/resource/image/resized/45x/' . $thumbnail) : $thumbnail ?>" alt="<?php echo $item['product']['name'] ?>" class="img-responsive" />
                        </a>
                        <h3 class="product-name col-xs-7">
                            <a href="<?php echo $item['product']->getUrl() ?>"><?php echo $item['product']['name'] ?></a>
                        </h3>
                        <div class="col-xs-3 action">
                            <div class="price"><?php echo $this->getCurrency()->format($item['product']->getFinalPrice($item['qty'])), 'x', (float) $item['qty'] ?></div>
                            <a href="<?php echo $this->getBaseUrl('checkout/cart/remove/') ?>" data-method="delete" data-params="id=<?php echo $item['product_id'] ?>&csrf=<?php echo $csrf ?>" title="<?php echo $this->translate('Delete') ?>">
                                <span><?php echo $this->translate('Delete') ?></span>
                            </a>
                        </div>
                    </li>
                    <?php
                endforeach;
            endif;
            ?></ul>
        <div class="total">
            <div class="col-xs-8">
                <?php echo $this->getChild('total') ?>
            </div>
            <div class="col-xs-4">
                <a href="<?php echo $this->getBaseUrl('checkout/cart/') ?>" class="btn btn-checkout">
                    <span><?php echo $this->translate('View Cart') ?></span>
                </a>
            </div>
        </div>
        <div class="empty">
            <div class="fa fa-shopping-basket col-xs-4" aria-hidden="true"></div>
            <div class="col-xs-7"><?php echo $this->translate('You have no items in your shopping cart.') ?></div>
        </div>
    </div>
    <template id="tmpl-minicart">
        <li data-id="{$id}" class="clearfix">
            <a href="{$url}" class="product-image col-xs-2">
                <img src="{$thumbnail}" alt="{$name}" />
            </a>
            <h3 class="product-name col-xs-7">
                <a href="{$url}">{$name}</a>
            </h3>
            <div class="col-xs-3 action">
                <div class="price">{$price}x{$qty}</div>
                <a href="<?php echo $this->getBaseUrl('checkout/cart/remove/') ?>" data-method="delete" data-params="id={$id}&csrf=<?php echo $csrf ?>" title="<?php echo $this->translate('Delete') ?>">
                    <span><?php echo $this->translate('Delete') ?></span>
                </a>
            </div>
        </li>
    </template>
</div>