<div class="container">
    <div class="checkout-flow hidden-xs clearfix">
        <div class="item col-sm-4 active"><?php echo $this->translate('Shopping Cart', [], 'checkout'); ?></div>
        <div class="item col-sm-4 active"><?php echo $this->translate('Order Confirmation', [], 'checkout'); ?></div>
        <div class="item col-sm-4 active"><?php echo $this->translate('Complate', [], 'checkout'); ?></div>
    </div>
    <div class="text-center">
        <div class="trading-success">
            <h3 class="title"><span class="fa fa-check"></span><?php echo $this->translate('Your order has been received.') ?></h3>
            <h4 class="sub-title"><?php echo $this->translate('We are appreciated that you can choose our products.') ?></h4>
            <ul class="list-inline">
                <li><a href="<?php echo $this->getBaseUrl(); ?>"><?php echo $this->translate('Continue Shopping'); ?></a></li>
                <?php if ($this->hasLoggedIn()): ?>
                    <li><a href="<?php echo $this->getBaseUrl('sales/order/list/'); ?>"><?php echo $this->translate('View Order'); ?></a></li>
                <?php else:?>
                    <li><?php echo $this->translate('Your order number'); ?>:</li>
                    <li><?php echo $this->translate('Click here to view order details'); ?>:<a href="<?php $this->getBaseUrl('sales/inquire/inquire/'); ?>"><?php echo $this->translate('Order Inquire'); ?></a></li>
                <?php endif;?>
            </ul>
        </div>
    </div>
</div>
