<header class="header">
    <h2 class="page-title"><span lang="en">SeaHiNet</span> <span><?php echo $this->translate('Admin Panel') ?></span></h2>
</header>
<div class="main-container">
    <div class="panel panel-login clearfix">
        <div class="panel-body">
            <form action="<?php echo $this->getAdminUrl('index/login/') ?>" method="post" class="form-inline">
                <input type="hidden" name="csrf" value="<?php echo $this->getCsrfKey() ?>" />
                <?php if ($url = $this->getQuery('success_url')): ?>
                    <input type="hidden" name="success_url" value="<?php echo $url ?>" />
                <?php endif ?>
                <div class="input-box">
                    <label for="login:username" class="control-label"><?php echo $this->translate('Username') ?>: </label>
                    <input type="text" name="username" class="form-control required" id="login:username" spellcheck="false" />
                </div>
                <div class="input-box">
                    <label for="login:password" class="control-label"><?php echo $this->translate('Password') ?>: </label>
                    <input type="password" name="password" class="form-control required" minlength="6" id="login:password" />
                </div>
                <div class="input-box">
                    <label for="login:captcha" class="control-label"><?php echo $this->translate('Captcha') ?>: </label>
                    <input type="text" name="captcha" class="form-control required captcha" maxlength="5" id="login:captcha" autocomplete="off" spellcheck="false" />
                    <img src="<?php echo $this->getAdminUrl('index/captcha/') ?>" alt="" class="captcha" height="26" width="70" />
                </div>
                <div class="additional">
                    <a href="<?php echo $this->getAdminUrl('index/forgot/') ?>" class="forgot-pwd"><?php echo $this->translate('Forgot Your Password?') ?></a><br />
                    <input type="checkbox" name="persistent" class="form-control" id="login:persistent" />
                    <label for="login:persistent" class="control-label"><?php echo $this->translate('Remember Me') ?></label>
                </div>
                <div class="buttons-set text-center">
                    <button type="submit" class="btn"><span><?php echo $this->translate('Submit') ?></span></button>
                </div>
            </form>
        </div>
    </div>
</div>
<footer class="footer">
    <address class="copyright" lang="en"><?php echo $this->getVariable('copyright') ?></address>
</footer>