<?php
$tabs = $this->getTabs();
if (count($tabs)):
    $flag = $this->getMainTabLabel();
    ?>
    <ul class="nav nav-tabs clearfix" role="tablist">
        <?php if ($flag): ?>
            <li role="presentation" class="active">
                <a href="#main-tab" aria-controls="main-tab" role="tab" data-toggle="tab">
                    <?php echo $this->translate($this->getMainTabLabel()) ?>
                </a>
            </li>
        <?php endif ?>
        <?php foreach ($this->getTabs() as $id => $tab): ?>
            <li role="presentation"<?php
            if (!$flag) {
                echo ' class="active"';
                $flag = true;
            }
            ?>>
                <a href="#tab-<?php echo $id ?>" aria-controls="<?php echo $id ?>" role="tab" data-toggle="tab">
                    <?php echo $this->translate($tab) ?>
                </a>
            </li>
        <?php endforeach ?>
    </ul>
    <?php
    if ($this->generateTabPane()):
        foreach ($this->getTabs() as $id => $tab):
            if ($this->hasTab($id)):
                ?>
                <div role="tabpanel" class="tab-pane table fade" id="tab-<?php echo $id ?>">
                    <?php echo $this->$id ?>
                </div>
                <?php
            endif;
        endforeach;
    endif;
endif;
?>
