<?php
$segment = new Seahinet\Lib\Session\Segment('customer');
if ($segment->get('hasLoggedIn')):
    ?>
    <section class="section rewardpoints" data-change-after="coupon">
        <p>
            <input type="checkbox" name="include_balance"  />
            <label for="include_balance"><?php echo $this->translate('Use Balance'); ?></label>
            <span class="price balance" data-price="<?php echo $this->getCurrency()->convert($segment->get('customer')->getBalance(), TRUE) ?>">：<?php echo $this->getCurrency()->convert($segment->get('customer')->getBalance(), TRUE) ?></span>
        </p>
    </section>
    <?php
endif;
?>