<?php
$methods = $this->getPaymentMethods();
$current = $this->getCurrentMethod();
//var_dump($this);die;
?>
<section class="section payment">
    <h4 class="title"><b><?php echo $this->translate('Payment Method') ?></b></h4>
    <?php if ($methods): ?>
        <ul class="list list-inline">
            <?php foreach ($methods as $code => $model): ?>
                <li>
                    <input type="radio" name="payment_method" id="payment-method-<?php echo $code ?>" value="<?php echo $code ?>"<?php if ($code === $current || count($methods) === 1): ?> checked="checked"<?php endif ?> />
                    <label for="payment-method-<?php echo $code ?>">
                        <?php echo $this->translate($model->getLabel()) ?>
                    </label>
                    <p class="payment-description"><?php echo $this->translate($model->getDescription()) ?></p>
                </li>
            <?php endforeach ?>
        </ul>
    <?php else: ?>
        <p><?php echo $this->translate('Sorry, no payment methods are available for this order at this time.') ?></p>
    <?php endif ?>
</section>
