<?php
$storeId = $this->getVariable('store_id');
$methods = $this->getShippingMethods($storeId);
$current = $this->getCurrentMethod();
if ($methods):
    ?>
    <select name="shipping_method[<?php echo $storeId ?>]" id="shipping-method-<?php echo $storeId ?>">
        <?php foreach ($methods as $code => $label): ?>
            <option value="<?php echo $code ?>"<?php if (isset($current[$storeId]) && $current[$storeId] === $code): ?> selected="selected"<?php endif ?>>
                <?php echo $this->translate($label) ?>
            </option>
        <?php endforeach ?>
    </select>
<?php else: ?>
    <p><?php echo $this->translate('Sorry, no shipping methods are available for this order at this time.') ?></p>
<?php endif; ?>