<?php
$item = $this->getVariable('item');
$product = $item['product'];
$thumbnail = $product->getThumbnail();
$inventory = $item->getInventory();
?>
<ul class="col-xs-12 col-sm-12 product-list">
    <li class="col-xs-1 col-sm-1">
        <input type="checkbox"<?php if ($item['status']): ?> checked="checked"<?php endif ?> class="checkbox-<?php echo $item['store_id'] ?>" name="item[]" value="<?php echo $item['id'] ?>" />
    </li>
    <li class="col-xs-8 col-xs-8">
        <div class="product-img">
            <a href="<?php echo $item['product']->getUrl() ?>">
                <img src="<?php echo strpos($thumbnail, '://') === false ? $this->getBaseUrl('pub/resource/image/resized/88x/' . $thumbnail) : $thumbnail ?>" alt="" width="90%" />
            </a>
        </div>
        <div class="product-name">
            <h4><a href="<?php echo $item['product']->getUrl() ?>"><?php echo $item['product_name'] ?></a></h4>
            <?php
            $options = json_decode($item['options'], true);
            if ($item['product_id'] && count($options)):
                ?>
                <dl class="options">
                    <?php
                    foreach ($item['product']->getOptions() as $option):
                        if (isset($options[$option->getId()])):
                            ?>
                            <dt><?php echo $option['title'] ?></dt>
                            <dd>
                                <?php
                                echo (in_array($option['input'], ['select', 'radio', 'checkbox', 'multiselect']) ?
                                        $option->getValue($options[$option->getId()]) : $options[$option->getId()])
                                ?>
                            </dd>
                            <?php
                        endif;
                    endforeach;
                    ?>
                </dl>
            <?php endif; ?> 
        </div>
    </li>
    <div class="price" data-price="<?php echo $item['price'] ?>">
        <?php echo $this->getCurrency()->format($item['price'] * $item['qty']) ?>   
    </div>
    <li class="col-xs-3 col-sm-2 qty">
        <div class="text-nowrap">
            <label class="spin minus" for="qty-<?php echo $item['id'] ?>">-</label>
            <input type="number" name="qty[<?php echo $item['id'] ?>]" id="qty-<?php echo $item['id'] ?>"
                   min="<?php echo (float) $inventory['min_qty'] ?>"
                   max="<?php echo min((float) $inventory['max_qty'], (float) $inventory['qty']) ?>"
                   step="<?php echo (float) $inventory['increment'] ?>"
                   class="form-control required" value="<?php echo (float) $item['qty'] ?>" />
            <label class="spin plus" for="qty-<?php echo $item['id'] ?>">+</label>
        </div>
        <p>
            <a href="<?php echo $this->getBaseUrl('checkout/cart/remove/?csrf='), $this->getCsrfKey(), '&id=', $item['id'] ?>">
                <span class="fa fa-trash-o fa-1"></span>
            </a>
        </p>
    </li>
</ul>