<form action="<?php echo $this->getWsUrl() ?>" class="chat-form">
    <input type="hidden" name="from" value="<?php echo $this->getSegment('livechat')->get('id') ?>" />
    <input type="hidden" name="to" value="{{$to}}" />
    <input type="hidden" name="type" value="text" />
    <div class="chat-history">
        <ul class="chat-list"></ul>
    </div>
    <div class="input-box">
        <input type="text" name="msg" class="form-control required" />
        <button type="submit" class="btn btn-send">
            <span class="fa fa-send" aria-hidden="true"></span>
            <span class="sr-only"><?php echo $this->translate('Send') ?></span>
        </button>
    </div>
</form>
