<?php
$sessions = $this->getSessions();
$current = $this->getVariable('current');
$retailer = new Seahinet\Retailer\Model\Retailer;
?>
<div class="container">
    <div class="sidebar-left col-lg-3 col-md-3">
        <div class="custom-info">
            <div class="custom-head">
                <img src="<?php echo $this->getPubUrl('frontend/images/placeholder.png'); ?>" width="90" height="90" />
                <p><?php echo $this->getSegment('customer')->get('customer')['username'] ?? ''; ?></p>
            </div>
        </div>
        <div class="custom-list text-center">
            <p class="text-center">
                <input type="text" class="form-control" id="inputSuccess2" aria-describedby="inputSuccess2Status">
                <span class="fa fa-search" aria-hidden="true"></span>
            </p>
            <div class="service-list text-center">
                <ul class="nav nav-pills text-right" role="tablist">
                    <?php
                    foreach ($sessions as $session):
                        if (!$current) {
                            $current = $session['id'];
                        }
                        ?>
                        <li role="presentation"<?php if ($current == $session['id']): ?> class="active"<?php endif ?>>
                            <a href="#<?php echo $session['id'] ?>" role="tab" data-toggle="tab">
                                <?php echo $this->getTarget($session['id']) ?>
                            </a>
                        </li>
                    <?php endforeach ?>
                </ul>
            </div>
        </div>
    </div>
    <div class="main-container col-lg-9 col-md-9">
        <ul class="store-head">
            <li class="col-lg-3 col-md-3 border text-center">
                <ul class="nav nav-pills text-center" role="tablist">
                    <?php
                    //foreach ($sessions as $session):
                    if (!$current):
                        $current = $session['id'];
                    endif;
                    ?>
                    <li role="presentation">
                        <a href="#<?php echo $session['id'] ?>" role="tab" data-toggle="tab">
                            <?php echo $this->getTarget($session['id']) ?>
                        </a>
                    </li>
                    <?php
                    //endforeach;
                    ?>
                </ul>
            </li>
            <li class="col-lg-4 col-md-4 text-center border">
                <h4><?php echo $this->translate('Store Score'); ?>:5.0</h4>
                <ul>
                    <li><?php echo $this->translate('Description Match'); ?>:5.0</li>
                    <li><?php echo $this->translate('Service Attitude'); ?>:5.0</li>
                    <li><?php echo $this->translate('Logistics Service'); ?>:5.0</li>
                </ul>
            </li>
            <li class="col-lg-5 col-md-5 text-right padding-15">
                <a type="submit" class="btn btn-them"><?php echo $this->translate('Contact Admin Service'); ?></a>&nbsp;&nbsp;
                <a href=" " class="btn btn-close"><?php echo $this->translate('Close Chat'); ?></a>
            </li>
        </ul>
        <div class="chat-content">
            <div id="livechat" class="col-lg-9 col-md-9">
                <form action="<?php echo $this->getWsUrl() ?>" id="chat-form">
                    <input type="hidden" name="sender" value="<?php echo $this->getSegment('customer')->get('customer')->getId() ?>" />
                    <div class="tab-content">
                        <?php foreach ($sessions as $session): ?>
                            <div role="tabpanel" class="tab-pane fade<?php if ($current == $session['id']): ?> active in<?php endif ?>" id="<?php echo $session['id'] ?>">
                                <?php
                                echo $this->getChild('chat')->setVariable('id', $session['id'])
                                ?>
                            </div>
                        <?php endforeach ?>
                    </div>
                </form>
            </div>
            <div class="prodcut-info col-lg-3 col-md-3">
                <img src="<?php echo $this->getPubUrl('frontend/images/placeholder.png'); ?>" width="190" height="190" />
            </div>
        </div>
    </div>
</div>