<?php
$orders = $this->getOrders();
$profile1 = new Seahinet\Customer\ViewModel\Dashboard\Profile;
$profile = $profile1->getPendingPayment();
$shipping = $profile1->getShipping();
$reviewing = $profile1->getReviewing();
?>
<div id="Has-sold" class="seller-tab">
    <ul id="myTab" class="nav nav-tabs col-xs-12 col-sm-12 font-12 text-center">
        <li class="col-xs-3 col-sm-3" <?php if (count($this->getQuery()) === 1): ?> class="active"<?php endif ?>>
            <a href="<?php echo $this->getBaseUrl('sales/order/list/') ?>">
                <?php echo $this->translate('All'); ?>(<span><?php echo count($orders); ?></span>)
            </a>
        </li>
        <li class="col-xs-3 col-sm-3" <?php if (count($profile1->getPendingPayment()) != 0) : ?> class="active"<?php endif; ?>>
            <a href="<?php echo $this->getBaseUrl('sales/order/list/?status=1') ?>">
                <?php echo $this->translate('Pending Payment'); ?>(<span><?php echo $profile1->getPendingPayment() ?></span>)
            </a>
        </li>
        <li class="col-xs-3 col-sm-3" id="payment">
            <a href="<?php echo $this->getBaseUrl('sales/order/list/?status=2') ?>">
                <?php echo $this->translate('Delivering'); ?>(<span><?php echo $profile1->getShipping() ?></span>)
            </a>
        </li>
        <li class="col-xs-3 col-sm-3" id="refund">
            <a href="<?php echo $this->getBaseUrl('sales/order/list/?status=3') ?>">
                <?php echo $this->translate('Reviewing'); ?>(<span><?php echo $profile1->getReviewing() ?></span>)
            </a>
        </li>
    </ul>	
    <div class="search col-xs-12 col-sm-12 padding-5">
        <form class="form-inline" action="" method="get" novalidate = "novalidate">
            <span class="fa fa-search" aria-hidden="true"></span>
            <input type="search" name="increment_id" value="" class="col-xs-10 col-sm-10" />
            <button type="submit" class="btn btn-default"><?php echo $this->translate('Search'); ?></button>
        </form>
    </div>
    <?php if (count($orders)): ?>
        <div id="Product-details" class="tab-content font-12">
            <div class="tab-pane fade in active" id="all">
                <?php
                foreach ($orders as $order):
                    ?>  
                    <div class="menu-ctn">
                        <ul  class="col-xs-12 col-sm-12 title-nav name  padding-5">
                            <li class="col-xs-5 col-sm-5 text-left"><?php echo $order->getStore()->offsetGet('name') ?></li>
                            <li class="col-xs-7 col-sm-7 text-right">
                                <?php echo $order->getCurrency()->format($order->offsetGet('total')) ?>
                                <span>(<?php echo $this->translate('Including Shipping Fee: %s', [$order->getCurrency()->format($order->offsetGet('shipping'))]) ?>)</span>
                            </li>	
                        </ul>
                        <table class="table inline bt padding-5">
                            <?php
                            $items = $order->getItems();
                            $flag = true;
                            foreach ($items as $item):
                                $product = $item['product'];
                                $thumbnail = $product->getThumbnail();
                                ?>
                                <tr>
                                    <td class="col-xs-2 col-sm-2">
                                        <a href="<?php echo $product->getUrl(); ?>"><img src="<?php echo strpos($thumbnail, '//') === false ? $this->getResourceUrl('image/resized/100x/' . $thumbnail) : $thumbnail ?>" width="50" height="50" alt="<?php echo $product->offsetGet('name') ?>" /></a>
                                    </td>
                                    <td class="col-xs-6 col-sm-6 text-left" title="<?php echo $product->offsetGet('name') ?>">
                                        <h4 class="font-12"><?php echo $product->offsetGet('name') ?></h4>
                                        <?php
                                        $options = json_decode($item['options'], true);
                                        if ($item['product_id'] && count($options)):
                                            ?>
                                            <dl class="options">
                                                <?php
                                                foreach ($product->getOptions() as $option):
                                                    if (isset($options[$option->getId()])):
                                                        ?>
                                                        <dt><?php echo $option['title'] ?></dt>
                                                        <dd>
                                                            <?php
                                                            echo (in_array($option['input'], ['select', 'radio', 'checkbox', 'multiselect']) ?
                                                                    $option->getValue($options[$option->getId()]) : $options[$option->getId()])
                                                            ?>
                                                        </dd>
                                                        <?php
                                                    endif;
                                                endforeach;
                                                ?>
                                            </dl>
                                        <?php endif; ?>
                                    </td>
                                    <td class="col-xs-1 col-sm-1 text-right">
                                        <span class="price"><?php echo $order->getCurrency()->format($item->offsetGet('price')) ?></span>
                                        <span><?php echo (float) $item->offsetGet('qty') ?></span>
                                    </td>
                                    <?php
                                    if ($flag):
                                        ?>
                                        <td rowspan="<?php echo count($items) ?>" class="col-xs-3 col-sm-3 border-left action text-center">
                                            <span class="color-blue"><?php echo $this->translate($order->getStatus()->offsetGet('name'), [], 'sales') ?></span>
                                        </td>
                                        <?php
                                        $flag = FALSE;
                                    endif;
                                    ?>
                                </tr>
                            <?php endforeach; ?>
                        </table>
                        <ul class="sale_status padding-5">
                            <li class="col-xs-12 col-sm-12 text-right">
                                <?php if ($order->canRefund()): ?>
                                    <a href="<?php echo $this->getBaseUrl('sales/refund/apply/?id=' . $order['id']) ?>" class="btn"><?php echo $this->translate('Refund Application') ?></a>
                                <?php endif ?>
                                <?php if ($order->canReview()): ?>
                                    <a href="<?php echo $this->getBaseUrl('sales/order/review/?id=' . $order['id']) ?>" class="btn"><?php echo $this->translate('Add Review') ?></a>
                                <?php endif ?>
                                <a href="<?php echo $this->getBaseUrl('sales/order/view/?id=' . $order['id']) ?>" class="btn"><?php echo $this->translate('View Details') ?></a>
                            </li>
                        </ul>
                    </div>
                <?php endforeach; ?>
            </div>
            <div class="tab-pane fade " id="delivery">
                2
            </div>
            <div class="tab-pane fade" id="payment">
                3
            </div>
            <div class="tab-pane fade " id="refund">
                4
            </div>
        </div>
    <?php else: ?>
        <div>
            <p class="text-center"><?php echo $this->translate('You have placed no orders.') ?></p>
        </div>
    <?php endif; ?>
</div>