<?php
$customer = $this->getCustomer();
?>
<div class="profile clearfix">
    <a href="javascript:void(0);" class="photo col-xs-12 col-sm-2">
        <img alt="<?php echo $customer->offsetGet('username') ?>" class="img-responsive" width="100" src="<?php echo $this->getPubUrl('frontend/images/placeholder.png') ?>" />
    </a>
    <div class="info col-xs-12 col-sm-10">
        <div class="name">
            <span><?php echo $customer->offsetGet('username') ?></span>
            <span class="level"><?php echo $customer->getLevel() ?></span>
        </div>
        <div class="balance">
            <span class="label"><?php echo $this->translate('My Account') ?>:</span>
            <span><?php echo $this->translate('Balance') ?><span class="count"><?php echo $this->getCurrency()->convert($customer->getBalance(), true) ?></span></span>
        </div>
        <div class="transaction">
            <span class="label"><?php echo $this->translate('My Orders') ?>:</span>
            <span><?php echo $this->translate('Pending Payment') ?><span class="count">(<?php echo $this->getPendingPayment() ?>)</span></span>
            <span><?php echo $this->translate('Shipping', [], 'customer') ?><span class="count">(<?php echo $this->getShipping() ?>)</span></span>
            <span><?php echo $this->translate('Reviewing', [], 'customer') ?><span class="count">(<?php echo $this->getReviewing() ?>)</span></span>
        </div>
    </div>
</div>
