<?php
$customer = $this->getCustomer();
$avatar = $customer['avatar'];
?>
<div class="profile clearfix">
    <div class="head_pic">
        <a href="<?php echo $this->getBaseUrl('customer/account/edit/') ?>" class="photo col-xs-12 col-sm-2">
            <img alt="<?php echo $customer->offsetGet('username') ?>" class="img-responsive" width="100" src="<?php echo $avatar ? 'data:image/png;base64, ' . $avatar : $this->getPubUrl('frontend/images/placeholder.png') ?>" />
        </a>
    </div>
    <div class="info col-xs-12 col-sm-10">
        <div class="name">
            <span><?php echo $customer->offsetGet('username') ?></span>
            <span class="level"><?php echo $customer->getLevel() ?></span>
        </div>
        <div class="balance">
            <span class="label"><?php echo $this->translate('My Account') ?>:</span>
            <span><?php echo $this->translate('Balance') ?><span class="count"><?php echo $this->getCurrency()->convert($customer->getBalance(), true) ?></span></span>
            <span><?php echo $this->translate($this->getConfig()['rewardpoints/general/title']) ?><a href="<?php echo $this->getBaseUrl('customer/account/rewardpoints/'); ?>"><span class="count"><?php echo (int) $customer['rewardpoints'] ?></span></a></span>
        </div>
        <div class="transaction">
            <span class="label"><?php echo $this->translate('My Orders') ?>:</span>
            <a href="<?php echo $this->getBaseUrl('sales/order/list/?status=1') ?>"><?php echo $this->translate('Pending Payment') ?><span class="count">(<?php echo $this->getPendingPayment() ?>)</span></a>
            <a href="<?php echo $this->getBaseUrl('sales/order/list/?status=2') ?>"><?php echo $this->translate('Delivering', [], 'customer') ?><span class="count">(<?php echo $this->getShipping() ?>)</span></a>
            <a href="<?php echo $this->getBaseUrl('sales/order/list/?status=3') ?>"><?php echo $this->translate('Reviewing', [], 'customer') ?><span class="count">(<?php echo $this->getReviewing() ?>)</span></a>
        </div>
    </div>
</div>
