<?php
$cards = $this->getCards();
?>
<ul>
    <?php foreach ($cards as $card): ?>
        <li>
            <input type="radio" id="cc-<?php echo $card->getId() ?>" name="payment[data][cc]" hidden="hidden" value="<?php echo $card->getId() ?>" />
            <label for="cc-<?php echo $card->getId() ?>"><?php echo preg_replace('/^(.{4}).+(.{4})$/', '$1 **** **** $2', $card->offsetGet('number')) ?></label>
        </li>
    <?php endforeach ?>
</ul>
<div class="fieldset<?php if (count($cards) === 0): ?> hidden<?php endif ?>">
    <label for="cc-name" class="control-label"><?php echo $this->translate('Name on Card') ?></label>
    <input type="text" id="cc-name" name="payment[data][cc_name]" class="form-control required" autocomplete="off" spellcheck="false" />
    <label for="cc-type" class="control-label"><?php echo $this->translate('Credit Card Type') ?></label>
    <select id="cc-type" name="payment[data][cc_type]" class="form-control required" autocomplete="off">
        <option value=""><?php echo $this->translate('Please Select') ?></option>
        <?php foreach ($this->getTypes() as $value => $label): ?>
            <option value="<?php echo $value ?>"><?php echo $this->translate($label, [], 'payment') ?></option>
        <?php endforeach ?>
    </select>
    <label for="cc-number" class="control-label"><?php echo $this->translate('Credit Card Number') ?></label>
    <input type="text" id="cc-number" name="payment[data][cc_number]" class="form-control required" autocomplete="off" />
    <label class="control-label"><?php echo $this->translate('Expiration Date') ?></label>
    <select name="payment[data][exp_month]" class="form-control required">
        <option value=""><?php echo $this->translate('Month') ?></option>
        <?php for ($month = 1; $month <= 12; $month++): ?>
            <option value="<?php echo $month ?>"><?php printf('%2d - %s', $month, $this->getMonth($month)) ?></option>
        <?php endfor ?>
    </select>
    <select name="payment[data][exp_year]" class="form-control required">
        <option value=""><?php echo $this->translate('Year') ?></option>
        <?php for ($year = $this->getYear(), $i = 0; $i < 10; $i++): ?>
            <option value="<?php echo $year + $i ?>"><?php echo $year + $i ?></option>
        <?php endfor ?>
    </select>
    <label for="cc-verification" class="control-label dropdown">
        <?php echo $this->translate('Card Verification Number') ?>
        <a href="#" data-toggle="dropdown">
            <span class="fa fa-info-circle" aria-hidden="true"></span>
            <span class="sr-only"><?php echo $this->translate('What is it?') ?></span>
        </a>
        <div class="dropdown-menu">
            <img src="<?php echo $this->getPubUrl('frontend/images/cvv.gif') ?>" alt="" />
        </div>
    </label>
    <input type="tel" id="cc-verification" name="payment[data][cc_verification]" class="form-control required" autocomplete="off" />
</div>
