<!--[if lt IE 9]>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" class="no-js" lang="<?php echo $this->getLang() ?>"><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<![endif]-->
<!--[if (gte IE 9)|(!IE)]><!-->
<!DOCTYPE html>
<html class="no-js" lang="<?php echo $this->getLang() ?>">
    <head>
        <meta charset="UTF-8" />
        <!--<![endif]-->
        <?php echo $this->head ?>
    </head>
    <body class="<?php echo $this->getBodyClass() ?>">
        <?php echo $this->globalNotice ?>
        <?php echo $this->content ?>
        <?php echo $this->extra ?>
    </body>
</html>