<?php
$languages = $this->getLanguage();
if (count($languages)):
    ?>
    <div class="dropdown language">
        <a href="javascript:void(0);" title="<?php echo $this->translate('Language') ?>" class="dropdown-toggle" data-toggle="dropdown">
            <span class="fa fa-language" aria-hidden="true"></span>
            <span class="current"><?php echo $this->getCurrentLanguage() ?></span>
        </a>
        <ul class="dropdown-menu">
            <?php foreach ($languages as $language): ?>
                <li lang="<?php echo $language['code'] ?>">
                    <a href="<?php echo $this->getUrl($language) ?>">
                        <?php echo $language['name'] ?>
                    </a>
                </li>
            <?php endforeach ?>
        </ul>
    </div>
<?php endif; ?>
