<?php

namespace Seahinet\Lib\Source;

class LanguageCode implements SourceInterface
{

    protected $code = [
        'af_ZA' => 'Afrikaans (Suid-Afrika)',
        'az_AZ' => 'Azərbaycan (Azərbaycan)',
        'id_ID' => 'Bahasa Indonesia (Indonesia)',
        'ms_MY' => 'Bahasa Melayu (Malaysia)',
        'bs_BA' => 'Bosanski (Bosna i Hercegovina)',
        'ca_ES' => 'Català (Espanya)',
        'cy_GB' => 'Cymraeg (Y Deyrnas Unedig)',
        'da_DK' => 'Dansk (Danmark)',
        'de_DE' => 'Deutsch (Deutschland)',
        'de_CH' => 'Deutsch (Schweiz)',
        'de_AT' => 'Deutsch (Österreich)',
        'et_EE' => 'Eesti (Eesti)',
        'en_AU' => 'English (Australia)',
        'en_CA' => 'English (Canada)',
        'en_IE' => 'English (Ireland)',
        'en_NZ' => 'English (New Zealand)',
        'en_GB' => 'English (United Kingdom)',
        'en_US' => 'English (United States)',
        'es_AR' => 'Español (Argentina)',
        'es_CL' => 'Español (Chile)',
        'es_CO' => 'Español (Colombia)',
        'es_CR' => 'Español (Costa Rica)',
        'es_ES' => 'Español (España)',
        'es_MX' => 'Español (México)',
        'es_PA' => 'Español (Panamá)',
        'es_PE' => 'Español (Perú)',
        'es_VE' => 'Español (Venezuela)',
        'fil_PH' => 'Filipino (Pilipinas)',
        'fr_CA' => 'Français (Canada)',
        'fr_FR' => 'Français (France)',
        'gl_ES' => 'Galego (España)',
        'hr_HR' => 'Hrvatski (Hrvatska)',
        'it_IT' => 'Italiano (Italia)',
        'it_CH' => 'Italiano (Svizzera)',
        'sw_KE' => 'Kiswahili (Kenya)',
        'lv_LV' => 'Latviešu (Latvija)',
        'lt_LT' => 'Lietuvių (Lietuva)',
        'hu_HU' => 'Magyar (Magyarország)',
        'nl_NL' => 'Nederlands (Nederland)',
        'nb_NO' => 'Norsk Bokmål (Norge)',
        'nn_NO' => 'Nynorsk (Noreg)',
        'pl_PL' => 'Polski (Polska)',
        'pt_BR' => 'Português (Brasil)',
        'pt_PT' => 'Português (Portugal)',
        'ro_RO' => 'Română (România)',
        'sq_AL' => 'Shqip (Shqipëri)',
        'sk_SK' => 'Slovenčina (Slovensko)',
        'sl_SI' => 'Slovenščina (Slovenija)',
        'sr_RS' => 'Srpski (Srbija)',
        'fi_FI' => 'Suomi (Suomi)',
        'sv_SE' => 'Svenska (Sverige)',
        'vi_VN' => 'Tiếng Việt (Việt Nam)',
        'tr_TR' => 'Türkçe (Türkiye)',
        'is_IS' => 'íslenska (Ísland)',
        'cs_CZ' => 'čeština (Česká republika)',
        'el_GR' => 'Ελληνικά (Ελλάδα)',
        'be_BY' => 'беларуская (Беларусь)',
        'bg_BG' => 'български (България)',
        'mk_MK' => 'македонски (Македонија)',
        'mn_MN' => 'монгол (Монгол)',
        'ru_RU' => 'русский (Россия)',
        'uk_UA' => 'українська (Україна)',
        'he_IL' => 'עברית (ישראל)',
        'ar_DZ' => 'العربية (الجزائر)',
        'ar_KW' => 'العربية (الكويت)',
        'ar_MA' => 'العربية (المغرب)',
        'ar_SA' => 'العربية (المملكة العربية السعودية)',
        'ar_EG' => 'العربية (مصر)',
        'fa_IR' => 'فارسی (ایران)',
        'hi_IN' => 'हिंदी (भारत)',
        'bn_BD' => 'বাংলা (বাংলাদেশ)',
        'gu_IN' => 'ગુજરાતી (ભારત)',
        'th_TH' => 'ไทย (ไทย)',
        'lo_LA' => 'ລາວ (ລາວ)',
        'ka_GE' => 'ქართული (საქართველო)',
        'km_KH' => 'ខ្មែរ (កម្ពុជា)',
        'zh_CN' => '中文 (中国)',
        'zh_HK' => '中文 (中華人民共和國香港特別行政區)',
        'zh_TW' => '中文 (台灣)',
        'ja_JP' => '日本語 (日本)',
        'ko_KR' => '한국어 (대한민국)'
    ];

    public function getSourceArray($code = null)
    {
        return is_null($code) ? $this->code : (isset($this->code[$code]) ? $this->code[$code] : null);
    }

}
