<?php
$order = $this->getVariable('order');
?>
<tr class="tr-height"></tr>
<tr>
    <th colspan="9" class="description">
        <div class="clearfix">
            <div class="col-xs-6 text-left"><?php echo $this->translate('Recipient') ?>: <?php echo $order['recipient'] ?></div>
            <div class="col-xs-3 text-right"><?php echo $this->translate('Order ID') ?>: <?php echo $order['increment_id'] ?></div>
            <div class="col-xs-3 text-right"><?php echo $this->translate('Placed at') ?>: <?php echo $order['created_at'] ?></div>
        </div>
    </th>
</tr>
<?php
$flag = true;
$items = $order->getItems();
$currency = $order->getCurrency();
$count = count($items);
foreach ($items as $item):
    $product = $item['product'];
    $thumbnail = $product->getThumbnail();
    ?>
    <tr>
        <td>
            <img src="<?php echo strpos($thumbnail, '//') === false ? $this->getResourceUrl('image/resized/50x/' . $thumbnail) : $thumbnail ?>" alt="<?php echo $product['name'] ?>" width="65" />
        </td>
        <td class="col-md-3 col-xs-3 col-sm-3">
            <h4 class="product-name"><?php echo $product['name'] ?></h4>
            <?php
            $options = json_decode($item['options'], true);
            if ($item['product_id'] && count($options)):
                ?>
                <dl class="options">
                    <?php
                    foreach ($item['product']->getOptions() as $option):
                        if (isset($options[$option->getId()])):
                            ?>
                            <dt><?php echo $option['title'] ?></dt>
                            <dd>
                                <?php
                                echo (in_array($option['input'], ['select', 'radio', 'checkbox', 'multiselect']) ?
                                        $option->getValue($options[$option->getId()]) : $options[$option->getId()])
                                ?>
                            </dd>
                            <?php
                        endif;
                    endforeach;
                    ?>
                </dl>
            <?php endif; ?>
        </td>
        <td class="text-center"><?php echo $currency->format($item['price']) ?></td>
        <td class="text-center"><?php echo (float) $item['qty'] ?></td>
        <td class="text-center"></td>
        <?php if ($flag): ?>
            <td rowspan="<?php echo $count ?>" class="status text-center">
                <?php if ($application = $order->getRefundApplication()): ?>
                    <a href="<?php echo $this->getBaseUrl('retailer/refund/view/?id=' . $application['id']) ?>"><?php echo $this->translate('Refund Details') ?></a>
                <?php endif ?>
            </td>
            <td rowspan="<?php echo $count ?>" class="status text-center">
                <?php echo $this->translate($order->getStatus()['name']) ?>
                <a href="<?php echo $this->getBaseUrl('retailer/sales_order/view/?id=' . $order->getId()) ?>"><?php echo $this->translate('View Details') ?></a>
            </td>
            <td rowspan="<?php echo $count ?>" class="grand-total text-center text-nowrap">
                <?php echo $currency->format($item['total']) ?>
                <span class="shipping">(<?php echo $this->translate('Including Shipping Fee: %s', [$currency->format($item['shipping'])]) ?>)</span>
            </td>
            <td rowspan="<?php echo $count ?>" class="actions text-center">
                <?php if ($order->canCancel()): ?>
                    <a href="<?php echo $this->getBaseUrl('retailer/sales_order/cancel/?id=' . $order->getId()) ?>">
                        <?php echo $this->translate('Cancel', [], 'sales') ?>
                    </a>
                    <?php
                endif;
                if ($order->canHold()) :
                    ?>
                    <a href="<?php echo $this->getBaseUrl('retailer/sales_order/hold/?id=' . $order->getId()) ?>">
                        <?php echo $this->translate('Hold', [], 'sales') ?>
                    </a>
                    <?php
                endif;
                if ($order->canUnhold()) :
                    ?>
                    <a href="<?php echo $this->getBaseUrl('retailer/sales_order/unhold/?id=' . $order->getId()) ?>">
                        <?php echo $this->translate('Unhold', [], 'sales') ?>
                    </a>
                    <?php
                endif;
                if ($order->canInvoice()) :
                    ?>
                    <a class="invoice" href="<?php echo $this->getBaseUrl('retailer/sales_order/invoice/?id=' . $order->getId()) ?>">
                        <?php echo $this->translate('Invoice', [], 'sales') ?>
                    </a>
                    <?php
                endif;
                if ($order->canShip()) :
                    ?>
                <a class="ship" href="<?php echo $this->getBaseUrl('retailer/sales_order/ship/?id=' . $order->getId()) ?>">
                        <?php echo $this->translate('Ship', [], 'sales') ?>
                    </a>
                    <?php
                endif;
                if ($order->canRefund()) :
                    ?>
                <a class="refund" href="<?php echo $this->getBaseUrl('retailer/sales_order/refund/?id=' . $order->getId()) ?>">
                        <?php echo $this->translate('Refund', [], 'sales') ?>
                    </a>
                <?php endif; ?>
                <a href="<?php echo $this->getBaseUrl('retailer/sales_order/print/?id=' . $order->getId()) ?>">
                    <?php echo $this->translate('Print', [], 'sales') ?>
                </a>
            </td>
            <?php
            $flag = false;
        endif;
        ?>
    </tr>
<?php endforeach ?>

