<?php
$collection = $this->getCollection();
$filters = $this->getFilters();
?>
<div class="filters">
    <form action="<?php echo $this->getUri()->withQuery('')->withFragment('') ?>" method="get" class="form-inline">
        <div class="fieldset clearfix">
            <?php
            foreach ($filters as $key => $filter) {
                echo $this->getInputBox($key, $filter)->setVariable('boxClass', 'col-md-4 col-xs-6');
            }
            ?>
            <div class="buttons-set col-md-4 col-xs-6">
                <button type="submit" class="btn btn-theme"><?php echo $this->translate('Search') ?></button>
                <a href="<?php echo $this->getUri()->withQuery('')->withFragment('') ?>" class="btn btn-theme"><?php echo $this->translate('Reset') ?></a>
            </div>
        </div>
    </form>
</div>
<table class="table orders-list">
    <tbody>
        <?php
        foreach ($collection as $order) {
            echo $this->renderItem($order);
        }
        ?>
    </tbody>
    <thead>
        <tr class="text-center text-nowrap">
            <th class="text-nowrap"><?php echo $this->translate('Product Infomation') ?></th>
            <th></th>
            <th class="text-center text-nowrap"><?php echo $this->translate('Price') ?></th>
            <th class="text-center text-nowrap"><?php echo $this->translate('Qty') ?></th>
            <th></th>
            <th class="text-center text-nowrap"><?php echo $this->translate('After Sales') ?></th>
            <th class="text-center text-nowrap"><?php echo $this->translate('Order Status') ?></th>
            <th class="text-center text-nowrap"><?php echo $this->translate('Grand Total') ?></th>
            <th class="text-center text-nowrap"><?php echo $this->translate('Action') ?></th>
        </tr>
    </thead>
    <tfoot>
        <tr class="visible-empty">
            <td colspan="8"><?php echo $this->translate('There are no orders in your store with the condition.') ?></td>
        </tr>
        <tr class="hidden-empty">
            <td colspan="8">
                <?php echo count($collection) ? $this->getChild('pager')->setCollection($collection) : '' ?>
            </td>
        </tr>
    </tfoot>
</table>
