<?php
$addresses = $this->getAddress();
$attributes = $this->getAddressAttribute();
?>
<button type="button" class="btn btn-theme btn-add" data-info="{}" data-toggle="modal" data-target="#modal-address">
    <span class="fa fa-plus fa-button" aria-hidden="true"></span>
    <span><?php echo $this->translate('Add New Address') ?></span>
</button>
<table class="table address-list text-center">
    <thead>
        <tr class="table_head ">
            <th class="text-center"><?php echo $this->translate('Receiver') ?></th>
            <th class="text-center"><?php echo $this->translate('Telephone / Cell phone') ?></th>
            <th class="text-center"><?php echo $this->translate('Address') ?></th>
            <th class="text-center"><?php echo $this->translate('Zip code') ?></th>
            <th class="text-center"><?php echo $this->translate('Action') ?></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($addresses as $address): ?>
            <tr class="add-address">
                <td><?php echo $address['name'] ?></td>
                <td><?php echo $address['tel'] ?></td>
                <td><?php echo $address['address'] ?></td>
                <td><?php echo $address['postcode'] ?></td>
                <td class="modify_book">
                    <a href="javascript:void(0);" data-info='<?php echo json_encode($address) ?>' data-toggle="modal" data-target="#modal-address">
                        <?php echo $this->translate('Modify') ?>
                    </a>
                    /
                    <a href="<?php echo $this->getBaseUrl('customer/account/deleteAddress/') ?>" data-method="delete" data-params="id=<?php echo $address->getId() ?>&csrf=<?php echo $this->getCsrfKey() ?>">
                        <?php echo $this->translate('Delete') ?>
                    </a>
                </td>
                <td class="default_book">
                    <?php if (!$address->offsetGet('is_default')): ?>
                        <a href="<?php echo $this->getBaseUrl('customer/account/defaultAddress/?id='), $address->getId() ?>"><?php echo $this->translate('Set as Default') ?></a>
                    <?php else: ?>
                        <span class="btn-Address"><?php echo $this->translate('Default Address') ?></span>
                    <?php endif ?>
                </td>
            </tr>
        <?php endforeach ?>
    </tbody>
    <?php if (count($addresses)): ?>
        <tfoot>
            <tr>
                <td colspan="6">
                    <?php echo $this->getChild('pager')->setCollection($addresses) ?>
                </td>
            </tr>
        </tfoot>
    <?php endif ?>
</table>
