---
wsdl:
    message:
        customerValid:
            sessionId: string
            username: string
            password: string
        customerValidResponse:
            customerId: int
        customerInfo:
            sessionId: string
            customerId: int
        customerInfoResponse:
            customer: customer
        customerCreate:
            sessionId: string
            data: customer
        customerCreateResponse:
            customerId: int
        customerSave:
            sessionId: string
            customerId: int
            data: customer
        customerSaveResponse:
            result: int
        customerSearch:
            sessionId: string
            customerId: int
            keywords: string
            lastId: int
            limit: int
        customerSearchResponse:
            customers: customer[]
        addressList:
            sessionId: string
            customerId: int
        addressListResponse:
            address: address[]
        addressInfo:
            sessionId: string
            customerId: int
            addressId: int
        addressInfoResponse:
            address: address
        addressSave:
            sessionId: string
            customerId: int
            data: address
        addressSaveResponse:
            result: bool
        addressDelete:
            sessionId: string
            customerId: int
            addressId: int
        addressDeleteResponse:
            result: bool
    port:
        -
            name: customerValid
            input: tns:customerValid
            output: tns:customerValidResponse
            documentation: Valid customer username and password
        -
            name: customerInfo
            input: tns:customerInfo
            output: tns:customerInfoResponse
            documentation: Get customer info by id
        -
            name: customerCreate
            input: tns:customerCreate
            output: tns:customerCreateResponse
            documentation: Create a new customer
        -
            name: customerSave
            input: tns:customerSave
            output: tns:customerSaveResponse
            documentation: Modify customer's infomation
        -
            name: customerSearch
            input: tns:customerSearch
            output: tns:customerSearchResponse
            documentation: Get customer list
        -
            name: addressList
            input: tns:addressList
            output: tns:addressListResponse
            documentation: Get customer address list
        -
            name: addressInfo
            input: tns:addressInfo
            output: tns:addressInfoResponse
            documentation: Get customer address infomation
        -
            name: addressSave
            input: tns:addressSave
            output: tns:addressSaveResponse
            documentation: Update or create a customer address
        -
            name: addressDelete
            input: tns:addressDelete
            output: tns:addressDeleteResponse
            documentation: Delete a customer address
soap:
    customerValid: \Seahinet\Customer\Model\Api\Soap\Customer
    customerInfo: \Seahinet\Customer\Model\Api\Soap\Customer
    customerCreate: \Seahinet\Customer\Model\Api\Soap\Customer
    customerSearch: \Seahinet\Customer\Model\Api\Soap\Customer
    addressList: \Seahinet\Customer\Model\Api\Soap\Address
    addressInfo: \Seahinet\Customer\Model\Api\Soap\Address
    addressSave: \Seahinet\Customer\Model\Api\Soap\Address
    addressDelete: \Seahinet\Customer\Model\Api\Soap\Address
rest:
    customer: \Seahinet\Customer\Model\Api\Rest\Customer
    address: \Seahinet\Customer\Model\Api\Rest\Address
