---
Seahinet\Customer\Model\Customer.model.save.before:
    -
        listener: [\Seahinet\Customer\Listeners\Increment, generate]
        priority: 10
dispatch.before:
    -
        listener: [\Seahinet\Customer\Listeners\Persistent, validate]
        priority: 10
cart.add.after:
    -
        listener: [\Seahinet\Customer\Listeners\Wishlist, afterAddToCart]
        priority: 10
    