---
Seahinet\Customer\Model\Customer.model.save.before:
    -
        listener: [\Seahinet\Customer\Listeners\Increment, generate]
        priority: 10
dispatch.before:
    -
        listener: [\Seahinet\Customer\Listeners\Persistent, validate]
        priority: 10
cart.add.after:
    -
        listener: [\Seahinet\Customer\Listeners\Wishlist, afterAddToCart]
        priority: 10
customer.level.calc:
    -
        listener: [\Seahinet\Customer\Listeners\Level, calc]
        priority: 10
Seahinet\Customer\Model\Level.model.save.after:
    -
        listener: [\Seahinet\Customer\Listeners\Level, collate]
        priority: 10
customer.balance.calc:
    -
        listener: [\Seahinet\Customer\Listeners\Balance, calc]
        priority: 10
customer.balance.save: 
    -
        listener: [\Seahinet\Customer\Listeners\Balance, save]
        priority: 10
customer.balance.save.after:
    -
        listener: [\Seahinet\Customer\Listeners\Balance, afterSaveRecharge]
        priority: 10
frontend.customer.balance.save.before:
    -
        listener: [\Seahinet\Customer\Listeners\Balance,beforeSaveRecharge]
        priority: 10
frontend.customer.balance.save.after:
    -
        listener: [\Seahinet\Customer\Listeners\Balance,afterSaveRecharge]
        priority: 10
backend.customer.save.after:
    -
        listener: [\Seahinet\Customer\Listeners\Balance, afterSaveBackendCustomer]
        priority: 10