---
customer:
    icon: users
    title: Customer Management
    priority: 20
    children:
        -
            link: customer_manage/
            title: Customer Management
            priority: 0
        -
            link: customer_attribute/
            title: Attribute Management
            priority: 10
        -
            link: customer_attribute_set/
            title: Attribute Set Management
            priority: 11
        -
            link: customer_group/
            title: Customer Group
            priority: 20
        -
            link: customer_level/
            title: Customer Level
            priority: 30
        -
            link: customer_attribute_address/
            title: Address Attribute Management
            priority: 40
        -
            link: customer_media/
            title: Social Media Management
            priority: 41
system:
    children:
        -
            link: config/customer/
            title: Customer Configuration
            priority: 50
