<div class="container">

    <div class="col-left col-xs-3 col-sm-3 col-md-2">
        <?php echo $this->getChild('nav') ?>
    </div>
    <main class="col-main col-xs-9 col-sm-9 col-md-10">
        <?php if ($title = $this->getVariable('title')): ?>
            <h2 class="page-title"><span><?php echo $this->translate($title) ?></span></h2>
        <?php endif ?>
        <?php echo $this->getChild('messages') ?>
        <div class="page-content">
      
		 <?php echo $this->getChild('main') ?>
            
        </div>
     
    </main>
</div>