<div class="container">
    <?php if ($this->getSegment('customer')->get('hasLoggedIn')): ?>
        <div class="col-left col-xs-3 col-sm-3 col-md-2">
            <?php echo $this->getChild('nav') ?>
        </div>
        <main class="col-main col-xs-9 col-sm-9 col-md-10">
        <?php else: ?>
            <main class="col-main col-xs-12">
            <?php endif ?>
            <?php echo $this->getChild('messages'), $this->getChild('main') ?>
        </main>
</div>