<form action="<?php echo $this->getBaseUrl('customer/account/createpost/') ?>" method="post">
    <input type="hidden" name="csrf" value="<?php echo $this->getCsrfKey() ?>" />
    <fieldset>
        <legend><?php echo $this->translate('Create New Customer Account') ?></legend>
        <div class="input-box">
            <label class="control-label required" for="reg:username"><?php echo $this->translate('Username') ?></label>
            <div class="cell">
                <input type="text" name="username" id="reg:username" class="form-control required" spellcheck="false" />
            </div>
        </div>
        <div class="input-box">
            <label class="control-label required" for="reg:email"><?php echo $this->translate('Email') ?></label>
            <div class="cell">
                <input type="email" name="email" id="reg:email" class="form-control required email" />
            </div>
        </div>
        <div class="input-box">
            <label class="control-label required" for="reg:password"><?php echo $this->translate('Password') ?></label>
            <div class="cell">
                <input type="password" name="password" id="reg:password" class="form-control required" minlength="6" />
            </div>
        </div>
        <div class="input-box">
            <label class="control-label required" for="reg:cpassword"><?php echo $this->translate('Confirm Password') ?></label>
            <div class="cell">
                <input type="password" name="cpassword" id="reg:cpassword" class="form-control required" data-rule-equalto="#reg\:password" />
            </div>
        </div>
        <?php if (in_array('register', $this->getConfig()['customer/captcha/form'])): ?>
            <div class="input-box">
                <label for="reg:captcha" class="control-label required"><?php echo $this->translate('Captcha') ?>: </label>
                <div class="cell">
                    <input type="text" name="captcha" class="form-control required captcha" maxlength="5" autocomplete="off" spellcheck="false" id="reg:captcha" />
                    <img src="<?php echo $this->getBaseUrl('customer/account/captcha/') ?>" alt="" class="captcha" height="26" width="70" />
                </div>
            </div>
        <?php endif ?>
        <div class="buttons-set">
            <button type="submit" class="btn btn-submit"><span><?php echo $this->translate('Submit') ?></span></button>
        </div>
    </fieldset>
</form>