<div class="container header-logo">
    <h1>
        <a href="">
            <!--[if (gte IE 9)|(!IE)]><!-->
            <img src="<?php echo $this->getBaseUrl('/pub/theme/default/frontend/images/logo.svg') ?>" height="50" alt="">
            <!--<![endif]-->
            <!--[if lt IE 9]>
            <img src="<?php echo $this->getBaseUrl('/pub/theme/default/frontend/images/logo.png') ?>" height="50" alt="" />
            <![endif]-->
        </a> 
        <strong class="sr-only">Seahinet</strong>
        <span class="text-logo"><?php echo $this->translate('Welcome - Register')?></span>
    </h1>
</div>
<hr />
<div class="container container-create">
	<div class="row">
		<div class="col-xs-12 col-sm-6 create">
			<form action="<?php echo $this->getBaseUrl('customer/account/createpost/') ?>" method="post" id="create">
                <input type="hidden" name="csrf" value="<?php echo $this->getCsrfKey() ?>" />
                
                <div class="create2"> 
                	<div class="visible-xs ckb-create2">
            			<span class="text-create-login"><?php echo $this->translate('Already Registered,')?></span>  
    					<span>&nbsp;<a href="<?php echo $this->getBaseUrl('customer/account/login/') ?>" class="create-login-a"><?php echo $this->translate('Login Now')?></a></span>
    		    	</div>              
                    <div class="input-box input-bottom-30">
                        <div class="input-group">
                            <div class="input-group-addon input-addon-create"><?php echo $this->translate('Username') ?> </div>
                           	<input type="text" name="username" id="reg:username" class="form-control required input-create" spellcheck="false" />                            
                        </div>                
                    </div>
                    
                    <div class="input-box input-bottom-30">
                        <div class="input-group">
                        	<div class="input-group-addon input-addon-create"><?php echo $this->translate('Password') ?>   </div>
                            <input type="password" name="password" id="reg:password" class="form-control required input-create" minlength="6" />
                        </div>
                    </div>
                    <div class="input-box input-bottom-30">
                        <div class="input-group">
                        	<div class="input-group-addon input-addon-create"> <?php echo $this->translate('Confirm Password')?>  </div>
                            <input type="password" name="cpassword" id="reg:cpassword" class="form-control required input-create" data-rule-equalto="#reg\:password" />
                        </div>
                    </div>
                    
                    <div class="input-box input-bottom-30">
                        <div class="input-group">
                        	<div class="input-group-addon input-addon-create"><?php echo $this->translate('Email') ?> </div>
                            <input type="email" name="email" id="reg:email" class="form-control required email input-create " />
                        </div>
                    </div>
                    
                    <div class="input-box ckb-create">
                      	<div class="input-group">
                    		<input type="checkbox" name="chekc" id="reg:check" class="required">
                    		<span class="create-agree1"><?php echo $this->translate('I have read and agreed to ')?></span>
                    		<span class="create-agree2"><a href=""><?php echo $this->translate('the Seahi Service Agreement')?></a></span>       
                		</div>          	
                    </div>               
                    
                    <?php if (in_array('register', $this->getConfig()['customer/captcha/form'])): ?>
                        <div class="input-box">
                            <label for="reg:captcha" class="control-label required"><?php echo $this->translate('Captcha') ?>: </label>
                            <div class="cell">
                                <input type="text" name="captcha" class="form-control required captcha" maxlength="5" autocomplete="off" spellcheck="false" id="reg:captcha" />
                                <img src="<?php echo $this->getBaseUrl('customer/account/captcha/') ?>" alt="" class="captcha" height="26" width="70" />
                            </div>
                        </div>
                    <?php endif ?>
                    <div class="buttons-set">
                        <button type="submit" class="btn btn-submit submit-create"><span><?php echo $this->translate('Sign Up Now') ?></span></button>
                    </div>
                </div>
            </form>		
		</div>
		
		<div class="create-login hidden-xs col-sm-6">
			<div class="create-login2">
    			<span class="text-create-login"><?php echo $this->translate('Already Registered,')?></span>  
    			<span>&nbsp;<a href="<?php echo $this->getBaseUrl('customer/account/login/') ?>" class="create-login-a"><?php echo $this->translate('Login Now')?></a></span>
    			<div class="create-img">
    				<img src="<?php echo $this->getBaseUrl('pub/theme/default/frontend/images/create.png') ?>" />
    		    </div>
		    </div>
		</div>
		
	</div>
	
</div>








