<header class="header">
    <div class="container">
        <h1 class="logo">
            <a href="<?php echo $this->getBaseUrl() ?>">
                <!--[if (gte IE 9)|(!IE)]><!-->
                <img src="<?php echo $this->getPubUrl('frontend/images/logo.svg') ?>" height="50" alt="">
                <!--<![endif]-->
                <!--[if lt IE 9]>
                <img src="<?php echo $this->getPubUrl('frontend/images/logo.png') ?>" height="50" alt="" />
                <![endif]-->
            </a> 
            <strong><?php echo $this->translate('Welcome - Register') ?></strong>
        </h1>
    </div>
</header>
<div class="main-container">
    <div class="col-main container">
        <div class="col-xs-12 col-sm-6">
            <form action="<?php echo $this->getBaseUrl('customer/account/createpost/') ?>" method="post">
                <input type="hidden" name="csrf" value="<?php echo $this->getCsrfKey() ?>" />
                <div class="fieldset"> 
                    <div class="login visible-xs-block">
                        <p>
                            <?php echo $this->translate('Already Registered,') ?> 
                            <a href="<?php echo $this->getBaseUrl('customer/account/login/') ?>"><?php echo $this->translate('Login Now') ?></a>
                        </p>
                    </div>        
                    <div class="table">
                        <div class="input-box">
                            <label for="reg:username" class="control-label required"><?php echo $this->translate('Username') ?></label>
                            <div class="cell">
                                <input type="text" name="username" id="reg:username" class="form-control required" spellcheck="false" />  
                            </div>
                        </div>
                        <div class="input-box">
                            <label for="reg:password" class="control-label required"><?php echo $this->translate('Password') ?></label>
                            <div class="cell">
                                <input type="password" name="password" id="reg:password" class="form-control required" minlength="6" />
                            </div>
                        </div>
                        <div class="input-box">
                            <label for="reg:cpassword" class="control-label required"><?php echo $this->translate('Confirm Password') ?></label>
                            <div class="cell">
                                <input type="password" name="cpassword" id="reg:cpassword" class="form-control required" data-rule-equalto="#reg\:password" />
                            </div>
                        </div>
                        <div class="input-box">
                            <label for="reg:email" class="control-label required"><?php echo $this->translate('Email') ?></label>
                            <div class="cell">
                                <input type="email" name="email" id="reg:email" class="form-control required email" />
                            </div>
                        </div>
                        <?php if (in_array('register', $this->getConfig()['customer/captcha/form'])): ?>
                            <div class="input-box">
                                <label for="reg:captcha" class="control-label required"><?php echo $this->translate('Captcha') ?>: </label>
                                <div class="cell">
                                    <input type="text" name="captcha" class="form-control required captcha" maxlength="5" autocomplete="off" spellcheck="false" id="reg:captcha" />
                                    <img src="<?php echo $this->getBaseUrl('customer/account/captcha/') ?>" alt="" class="captcha" height="26" width="70" />
                                </div>
                            </div>
                        <?php endif ?>
                    </div>
                    <div class="additional">
                        <div class="input-box">
                            <input type="checkbox" id="reg:agreement" name="agreement" class="required" value="1">
                            <label for="reg:agreement">
                                <?php echo $this->translate('I have read and agreed to the') ?>
                                <a href=""><?php echo $this->translate('Service Agreement') ?></a>
                            </label>
                        </div>
                        <div class="input-box">
                            <input type="checkbox" id="reg:subscribe" name="subscribe" value="1">
                            <label for="reg:subscribe">
                                <?php echo $this->translate('Sign up for Newsletter') ?>
                            </label>
                        </div>
                    </div>
                    <div class="buttons-set">
                        <button type="submit" class="btn btn-submit"><span><?php echo $this->translate('Sign up Now') ?></span></button>
                    </div>
                </div>
            </form>		
        </div>
        <div class="hidden-xs col-sm-6 login text-center">
            <div class="text-left">
                <p>
                    <?php echo $this->translate('Already Registered,') ?>
                    <a href="<?php echo $this->getBaseUrl('customer/account/login/') ?>"><?php echo $this->translate('Login Now') ?></a>
                </p>
                <img src="<?php echo $this->getPubUrl('frontend/images/create.jpg') ?>" alt="" />
            </div>
        </div>
    </div>
</div>
<div class="footer">
    <?php echo $this->getChild('footer') ?>
</div>
