<form action="<?php echo $this->getBaseUrl('customer/account/loginpost/') ?>" method="post">
    <input type="hidden" name="csrf" value="<?php echo $this->getCsrfKey() ?>" />
    <fieldset>
        <legend><?php echo $this->translate('Customer Login') ?></legend>
        <div class="input-box">
            <label class="control-label required" for="login:username"><?php echo $this->translate('Username') ?></label>
            <div class="cell">
                <input type="text" name="username" id="login:username" class="form-control required" spellcheck="false" />
            </div>
        </div>
        <div class="input-box">
            <label class="control-label required" for="login:password"><?php echo $this->translate('Password') ?></label>
            <div class="cell">
                <input type="password" name="password" id="login:password" class="form-control required" minlength="6" />
            </div>
        </div>
        <?php
        if (in_array('login', explode(',', $this->getConfig()['customer/captcha/form'])) && ($this->getConfig()['customer/captcha/mode'] == 0 || $this->getConfig()['customer/captcha/attempt'] <= (new \Seahinet\Lib\Session\Segment('customer'))->get('fail2login'))):
            ?>
            <div class="input-box">
                <label for="login:captcha" class="control-label required"><?php echo $this->translate('Captcha') ?>: </label>
                <div class="cell">
                    <input type="text" name="captcha" class="form-control required captcha" maxlength="5" autocomplete="off" spellcheck="false" id="login:captcha" />
                    <img src="<?php echo $this->getBaseUrl('customer/account/captcha/') ?>" alt="" class="captcha" height="26" width="70" />
                </div>
            </div>
        <?php endif ?>
        <div class="buttons-set">
            <button type="submit" class="btn btn-submit"><span><?php echo $this->translate('Login') ?></span></button>
        </div>
    </fieldset>
</form>