<?php
$products = $this->getProducts();
?>
<div class="col-xs-9 col-sm-9 col-md-10 track">
    <h3><?php echo $this->translate('My Tracks'); ?></h3>
    <dl>
        <?php
        if (count($products)) :
            $class = $this->getVariable('class', 'col-xs-6 col-sm-4 col-md-3 col-lg-2');
            $width = $this->getVariable('width');
            $datas = [];
            foreach ($products as $product) :
                if (!isset($datas[$product['product_id']])) :
                    ?>
                    <dt>
                        <span class="fa fa-circle-o" aria-hidden="true"></span>
                        <?php echo date('Y-m-d', strtotime($product['created_at'])) ?>
                        <span class="browse"><?php echo $this->translate('Total %d item(s)', [count($products)]); ?></span>
                    </dt>
                    <?php
                    $datas[$product['product_id']] = 1;
                else :
                    $datas[$product['product_id']] ++;
                endif;
                $thumbnail = $product->getThumbnail();
                ?>
                <dd class="item <?php echo $class ?>">
                    <ul>
                        <li>
                            <a href="<?php echo $product->getUrl() ?>" title="<?php echo $product['name'] ?>" class="product-image">
                                <?php
                                if (strpos($thumbnail, 'http') !== false):
                                    ?>
                                    <img src="<?php echo $thumbnail ?>" alt="<?php echo $product['name'] ?>" />
                                <?php elseif ($width): ?>
                                    <img class="bttrlazyloading"<?php foreach ($width as $key => $value): ?> data-bttrlazyloading-<?php echo $key ?>-src="<?php echo $this->getBaseUrl('pub/resource/image/resized/' . $value . 'x/' . $thumbnail) ?>"<?php endforeach ?> alt="<?php echo $product['name'] ?>" />
                                <?php else: ?>
                                    <img src="<?php echo $this->getBaseUrl('pub/resource/image/resized/131x/' . $thumbnail) ?>" alt="<?php echo $product['name'] ?>" />
                                <?php endif ?>
                            </a>
                            <p><?php echo $product['name']; ?></p>
                            <div class="price-box">
                                <?php echo $this->getPriceBox($product) ?>
                            </div>
                            <div class="action">
                                <a href="<?php
                                echo $this->getBaseUrl('checkout/cart/add/?product_id=' . $product['id'] .
                                        '&qty=1&csrf=' . $this->getCsrfKey())
                                ?>" class="add2cart">
                                </a>
                            </div>
                        </li>
                    </ul>
                </dd>
                <?php
            endforeach;
        endif;
        ?>
    </dl>
</div>