<nav>
    <dl class="nav" role="menu">
        <?php foreach ($this->getLinks() as $link): ?>
            <dt>
                <?php echo $link['group'] ?>
            </dt>
            <dd class="item" role="presentation">
                <a href="<?php echo $this->getBaseUrl($link['link']) ?>" role="menuitem">
                    <span><?php echo $link['label'] ?></span>
                </a>
            </dd>
        <?php endforeach ?>
    </dl>
</nav>