<?php $customer = $this->getVariable('customer'); ?>
<div class="personinfo">
    <h3><?php echo $this->translate('Personal Info');?></h3>
    <form action="<?php echo $this->getBaseUrl('customer/account/editPersonalInfo/') ?>" method="post">
        <input type="hidden" name="csrf" value="<?php echo $this->getCsrfKey() ?>" />
        <input type="hidden" name="id" value="<?php echo $customer->id ?>">
        <div class="fieldset"> 
            <dl>
                <dt><label><?php echo $this->translate('Username') ?> :</label></dt>
                <dd><strong><?php echo $customer->username ?></strong></dd>
            </dl>
            <dl>
                <dt><label for="edit:oldpassword" class="control-label"><?php echo $this->translate('Old Password'); ?> :</label></dt>
                <dd><input type="password" name="crpassword" id="edit:oldpassword" class="required password" class="form-control required" minlength="6"/></dd>
            </dl>
            <dl>
                <dt><label for="edit:newpassword" class="control-label"><?php echo $this->translate('New Password') ?> :</label></dt> 
                <dd><input type="password" name="password" id="edit:newpassword" class="required password" minlength="6" /></dd>
            </dl>
            <dl>
                <dt><label for="edit:crpassword" class="control-label"><?php echo $this->translate('Confirm password') ?> :</label></dt> 
                <dd><input type="password" name="cpassword" id="edit:crpassword" class="required crpassword" /></dd>
            </dl>
            <div>
                <button type="submit"><span><?php echo $this->translate('Submit') ?></span></button>
            </div>
        </div>	
    </form>		
</div>