<?php
$logview = $this->getVariable('track');
?>
<div class="col-xs-9 col-sm-9 col-md-10 track">
    <h3><?php echo $this->translate('My Tracks');?></h3>
    <dl>
        <dt>
            <span class="fa fa-circle-o" aria-hidden="true"></span>
                <?php echo date('Y-m-d');?>
            <span class="browse"><?php echo $this->translate('A total of 1 items of goods');?></span>
        </dt>
        <dd>
        </dd>
        <dd>
        </dd>
    </ul>
</div>