<?php
$order = $this->getVariable('order');
$invoices = $this->getVariable('invoice');
$shipments = $this->getVariable('shipment');
$creditmemos = $this->getVariable('creditmemo');
?>

<div class="col-xs-9 col-sm-9 col-md-10 wishlist">
    <h3></span><?php echo $this->translate('Order Infomation',[],'sales'); ?></h3>
    <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active">
        	<a href="#orders" aria-controls="description" role="tab" data-toggle="tab">
        		<?php echo $this->translate('Orders') ?>
        	</a>
    	</li>
    	<?php 
    	   if (!empty($invoices)):
    	       foreach ($invoices as $key=>$invoice):
    	?>
            <li role="presentation">
                <a href="#invoices<?php echo count($invoices) !== 1 ? $key+1 : '' ?>" aria-controls="review" role="tab" data-toggle="tab">
                	<?php echo $this->translate('Invoices'),count($invoices) !== 1 ? $key+1 : '' ?>
                </a>
            </li>
        <?php 
                endforeach;
            endif;
            if (!empty($shipments)):
                foreach ($shipments as $key=>$shipment):
        ?>
            <li role="presentation">
                <a href="#shipments<?php echo count($shipments) !== 1 ? $key+1 : '' ?>" aria-controls="review" role="tab" data-toggle="tab">
                	<?php echo $this->translate('Shipments'),count($shipments) !== 1 ? $key+1 : '' ?>
                </a>
            </li>
        <?php
                endforeach;
            endif;
            if (!empty($creditmemos)):
                foreach ($creditmemos as $key=>$creditmemo):
            ?>
            <li role="presentation">
                <a href="#creditMemos<?php echo count($creditmemos) !== 1 ? $key+1 : '' ?>" aria-controls="review" role="tab" data-toggle="tab">
                	<?php echo $this->translate('Credit Memos'),count($creditmemos) !== 1 ? $key+1 : '' ?>
                </a>
            </li>
        <?php 
                endforeach;
            endif;
        ?>
    </ul>
    <div class="tab-content">
        <?php 
            echo $this->getChild('order_info')->setVariable('order',$order);
            foreach ($invoices as $key=>$invoice){
                if (!empty($invoice)){
                    echo $this->getChild('invoice_info')->setVariable('invoice',$invoice)
                                                        ->setVariable('key',count($invoices) !== 1 ? $key+1 : null)
                                                        ->setVariable('order',$order);
                }
            }
            foreach ($shipments as $key=>$shipment){
                if (!empty($shipment)){
                    echo $this->getChild('shipment_info')->setVariable('shipment',$shipment)
                                                        ->setVariable('key',count($shipments) !== 1 ? $key+1 : null)
                                                        ->setVariable('order',$order);
                }
            }
            foreach ($creditmemos as $key=>$creditmemo){
                if (!empty($creditmemo)){
                    echo $this->getChild('creditmemo_info')->setVariable('creditmemo',$creditmemo)
                                                        ->setVariable('key',count($creditmemos) !== 1 ? $key+1 : null)
                                                        ->setVariable('order',$order);
                }
            }
        ?>
    </div>
</div>



