<?php
$customer = $this->getCustomer();
?>
<div class="welcome col-xs-12 col-sm-4">
    <?php if ($customer === false): ?>
        <p><?php echo $this->translate($this->getConfig()['theme/frontend/welcome']) ?></p>
        <ul class="list-inline">
            <li class="login"><a href="<?php echo $this->getBaseUrl('customer/account/login/') ?>"><?php echo $this->translate('Log in') ?></a></li>
            <li class="register"><a href="<?php echo $this->getBaseUrl('customer/account/create/') ?>"><?php echo $this->translate('Sign up') ?></a></li>
        </ul>
    <?php else: ?>
        <p><?php echo $this->translate($this->getConfig()['theme/frontend/welcome_loggedin'], ['<a href="' . $this->getBaseUrl('customer/account/') . '">' . $customer['username'] . '</a>']) ?></p>
        <ul class="list-inline">
            <li class="logout"><a href="<?php echo $this->getBaseUrl('customer/account/logout/') ?>"><?php echo $this->translate('Log out') ?></a></li>
        </ul>
    <?php endif ?>
</div>